import { loadChapter } from '../../load.ts';

const here = import.meta.dirname;

export default loadChapter(here, {
  id: 'web-browser-apis',
  title: "Browser APIs",
  summary: "URL and URLSearchParams, a minimal router, storage with expiry, events and delegation, AbortController in the UI.",
  lessons: [
    {
      id: 'web-url-building',
      title: 'Building URLs with URL and URLSearchParams',
      kind: 'js',
      xp: 75,
      why: 'Concatenated URLs break on the first id with a slash or a search with an ampersand, and `new URL(path, base)` quietly drops your API prefix.',
      tags: ['url', 'encoding', 'query-string'],
      hints: [
        'Start from `const url = new URL(base)` and modify it; never build the string by hand.',
        'Resolution is the trap: append to the base path instead. `url.pathname.replace(/\\/+$/, \'\') + \'/\' + encoded.join(\'/\')` keeps the prefix whether or not it ends with `/`.',
        'Encode each segment with `encodeURIComponent(String(segment))`, but check for `\'\'`, `\'.\'` and `\'..\'` first: encoding leaves dots alone and the URL parser resolves them.',
        'For the query, `url.searchParams.append(key, String(item))` for each item of `Array.isArray(value) ? value : [value]`, skipping `null` and `undefined` (not falsy values).',
        'In `withQuery`, `url.searchParams.delete(key)` then append handles arrays and removal; `url.searchParams.set(key, String(value))` handles a single value. Return `url.href`.',
      ],
    },
    {
      id: 'web-route-matcher',
      title: 'A route matcher where the most specific route wins',
      kind: 'js',
      xp: 90,
      why: 'Every SPA router answers "which route is this URL?" A first-match router sends `/products/new` to the product page the day someone reorders the list.',
      tags: ['routing', 'url', 'spa'],
      hints: [
        'Compile each route once into a list of segments: `{ type: STATIC, value }`, `{ type: PARAM, name }` or `{ type: SPLAT }`. Strip leading and trailing slashes before splitting.',
        'Rank segments static 0, param 1, splat 2, and sort the routes once with a comparator that returns the difference at the first position where the ranks differ. `Array.prototype.sort` is stable, which keeps declaration order for ties.',
        'Treat a position past the end of a shorter pattern as rank 0: it can only be competing with a `*` there, and an exact end should win.',
        'Wrap the decoding of one route in `try/catch` and return `null` from the catch: `decodeURIComponent(\'100%\')` throws a `URIError`.',
        'In `href`, use `encodeURIComponent(String(value))` for each param and for each `/`-separated part of the splat, and throw when a param is `undefined`, `null` or `\'\'`.',
      ],
    },
    {
      id: 'web-events-quiz',
      title: 'Event phases, targets and listeners that leak',
      kind: 'quiz',
      xp: 60,
      why: 'Delegated handlers, dropdowns that close themselves and listeners that never go away all come from the event model, not from the framework.',
      tags: ['events', 'dom', 'delegation'],
      quiz: [
        {
          q: 'A list has one click listener on the `<ul>` and each `<li>` holds `<button data-id="7"><svg>…</svg> Delete</button>`. Clicking the icon does nothing: the handler reads `event.target.dataset.id` and gets `undefined`. What is the fix?',
          options: [
            'Use `event.currentTarget.dataset.id`',
            'Use `event.target.closest(\'button[data-id]\')`, check it is inside the list, and read its `dataset.id`',
            'Add `pointer-events: none` to the `<ul>`',
            'Listen in the capture phase so the button is the target',
          ],
          answer: [1],
          explain: '`target` is the innermost element clicked — the `<svg>` or its `<path>`. `currentTarget` is the `<ul>`, which has no `data-id`. `closest` walks up from the target to the element you care about. (`pointer-events: none` on the **icon** also works, but only until someone adds another nested element.) The capture phase does not change the target.',
        },
        {
          q: 'A dropdown opens on a button click and closes on `document.addEventListener(\'click\', close)`, registered in the button\'s click handler. The dropdown never appears. Why?',
          options: [
            'The `document` listener is added during the same click\'s dispatch and runs when the event bubbles up to `document`, closing the dropdown immediately',
            'Listeners added during dispatch are always ignored',
            '`document` does not receive click events; only `window` does',
            'The button needs `event.preventDefault()`',
          ],
          answer: [0],
          explain: 'The event is still travelling: after the button\'s listener it bubbles to `document`, where the brand-new listener fires. Fixes: register the outside-click listener on the next tick, or check `menu.contains(event.target)` / use `event.composedPath()` in `close`. `stopPropagation` on the button also "works" and breaks every other delegated listener, including analytics.',
        },
        {
          q: 'Which of these remove the listener? Select all that apply. (The listener was added with `el.addEventListener(\'scroll\', onScroll, { capture: true })`.)',
          options: [
            '`el.removeEventListener(\'scroll\', onScroll)`',
            '`el.removeEventListener(\'scroll\', onScroll, { capture: true })`',
            '`el.removeEventListener(\'scroll\', onScroll, true)`',
            '`el.removeEventListener(\'scroll\', () => onScroll())`',
          ],
          answer: [1, 2],
          explain: 'A listener is identified by type, function **and** the capture flag; `once` and `passive` do not matter for removal. Omitting `capture` looks for a bubble-phase listener and silently removes nothing. A new arrow function is a different function. The robust pattern is `{ signal: controller.signal }` on the `addEventListener` and one `controller.abort()`.',
        },
        {
          q: 'A form has `<input>`s, and you want one listener on the `<form>` to validate a field when the user leaves it. Which event do you listen for?',
          options: [
            '`blur`, because it bubbles from the input to the form',
            '`focusout`, because unlike `blur` it bubbles',
            '`change`, because it fires whenever focus moves',
            '`blur` with `{ passive: true }`',
          ],
          answer: [1],
          explain: '`focus` and `blur` do not bubble; `focusin` and `focusout` are their bubbling twins, made for delegation. (`addEventListener(\'blur\', fn, true)` also works, via the capture phase.) `change` fires on commit only if the value changed, so an untouched required field is never validated.',
        },
        {
          q: 'An `async` click handler does `await saveDraft(); event.currentTarget.classList.add(\'saved\')` and throws "Cannot read properties of null". Why?',
          options: [
            '`saveDraft` removed the element from the DOM',
            '`event` objects are recycled after 100 ms',
            '`currentTarget` is only set while the listener is being dispatched; after the `await` the dispatch is over and it is `null`',
            'Async functions cannot be event listeners',
          ],
          answer: [2],
          explain: 'By the time the promise resolves, the event has finished dispatching and `currentTarget` has been reset to `null`. Read what you need **before** the first `await` (`const button = event.currentTarget`). The same applies to `preventDefault()`: calling it after an `await` is too late to stop a form submission or navigation.',
        },
        {
          q: 'A `touchstart` listener on the page calls `preventDefault()` to build a custom swipe, and scrolling on mobile feels janky. Chrome also logs a warning. What is going on?',
          options: [
            'Touch listeners on `window` and `document` default to `passive: true`, so `preventDefault()` is ignored; and any non-passive touch listener forces the browser to wait for your JS before scrolling',
            '`preventDefault()` is not allowed on touch events',
            'The listener must be registered with `{ once: true }`',
            '`touchstart` does not fire on mobile; use `click`',
          ],
          answer: [0],
          explain: 'A browser cannot start scrolling until it knows whether a touch or wheel listener will cancel it, so non-passive listeners block scrolling on the main thread. That is why `touchstart`/`touchmove`/`wheel` listeners on `window`, `document` and `body` are passive by default. If you truly need to cancel, register `{ passive: false }` on the smallest element possible — or use CSS `touch-action` instead.',
        },
      ],
    },
    {
      id: 'web-link-interception',
      title: 'SPA navigation with one delegated click listener',
      kind: 'react',
      xp: 90,
      why: 'An SPA that swallows Ctrl-click, `target="_blank"` and `#anchor` links is the most visible way a router can be wrong.',
      tags: ['events', 'delegation', 'history', 'routing'],
      hints: [
        'One listener on `root`: `const link = event.target instanceof Element ? event.target.closest(\'a[href]\') : null`, then `if (!link || !root.contains(link)) return`.',
        'Check the cheap exits first: `event.defaultPrevented`, `event.button !== 0` and the four modifier keys.',
        'Read the target with `(link.getAttribute(\'target\') ?? \'\').toLowerCase()` and check `link.hasAttribute(\'download\')`. For the origin, `new URL(link.href).origin !== location.origin` covers other sites, ports, `mailto:` and `tel:`.',
        'In-page anchor: `url.hash && url.pathname === location.pathname && url.search === location.search`. Return without `preventDefault` so the browser scrolls.',
        'In `navigate`, compare the new location to `location.pathname + location.search + location.hash`: equal (or `replace`) → `history.replaceState(null, \'\', next)`, else `pushState`. Keep the listener functions in variables so `stop()` can remove them.',
      ],
    },
    {
      id: 'web-storage-quiz',
      title: 'Where to keep data in the browser',
      kind: 'quiz',
      xp: 60,
      why: 'Choosing the wrong storage gets you tokens stolen by XSS, carts that vanish, or a main thread blocked by megabytes of JSON.',
      tags: ['storage', 'security', 'cookies'],
      quiz: [
        {
          q: 'Where should a web app keep the session for a logged-in user, to limit what an XSS bug can do with it?',
          options: [
            'A JWT in `localStorage`, sent in an `Authorization` header',
            'A JWT in `sessionStorage`, so it disappears when the tab closes',
            'An `HttpOnly; Secure; SameSite=Lax` cookie',
            'A JWT in a JavaScript variable, refreshed from `localStorage` on load',
          ],
          answer: [2],
          explain: 'Anything JavaScript can read, an injected script can read and send elsewhere — both Web Storage APIs included. An `HttpOnly` cookie cannot be read by script at all. XSS can still make requests **as** the user while the page is open, but it cannot walk away with a credential that works for days. `SameSite` and CSRF protection cover the cookie\'s own weakness.',
        },
        {
          q: 'A user opens a second tab of your app. What does each tab see? Select all that apply.',
          options: [
            'The same `localStorage`',
            'The same `sessionStorage`',
            'A `storage` event in the **other** tab when one tab writes to `localStorage`',
            'A `storage` event in the tab that did the write',
          ],
          answer: [0, 2],
          explain: '`localStorage` is per origin; `sessionStorage` is per origin **per tab** (a tab opened with "Duplicate" starts with a copy, which then diverges). The `storage` event fires in every **other** same-origin document, never in the one that wrote — so it is a cheap cross-tab channel (logout everywhere), and it cannot be used to react to your own writes.',
        },
        {
          q: 'The app caches a 4 MB product catalogue in `localStorage` and parses it on start-up. On low-end phones the first interaction is delayed by almost a second. What is the best change?',
          options: [
            'Compress the JSON before storing it',
            'Move it to `sessionStorage`',
            'Move it to IndexedDB (or Cache Storage for the raw response), which is asynchronous and stores structured data without a giant `JSON.parse`',
            'Split it across 40 `localStorage` keys',
          ],
          answer: [2],
          explain: 'Web Storage is synchronous: reading 4 MB and parsing it blocks the main thread, and it is capped around 5 MB per origin anyway. IndexedDB is asynchronous, stores structured-cloneable values and has a far larger quota. Compressing makes the string shorter but adds decompression on the same thread; `sessionStorage` has the same API and limits.',
        },
        {
          q: 'Which of these can make data in `localStorage` disappear without your code removing it? Select all that apply.',
          options: [
            'The user clears site data',
            'A private/incognito window is closed',
            'Safari\'s tracking prevention, after 7 days of browser use without a visit to the site',
            'A new deploy of your app',
          ],
          answer: [0, 1, 2],
          explain: 'Treat Web Storage as a cache, never as the only copy of anything that matters: private windows start empty and are wiped on close, and Safari caps script-writable storage for sites the user has not interacted with recently. A deploy does not touch it — which is its own bug: data written by the old version is still there, in the old shape.',
        },
        {
          q: 'A "remember filters" feature does `localStorage.setItem(\'filters\', JSON.stringify(filters))` on every change. In production some users see an uncaught `QuotaExceededError`, and the filter panel stops working. What should the write do?',
          options: [
            'Nothing different: quota errors cannot happen below 5 MB',
            'Catch the error, free space it owns (expired entries under its own key prefix) and retry once, and otherwise carry on without persisting',
            'Call `localStorage.clear()` and retry',
            'Switch to cookies, which have no quota',
          ],
          answer: [1],
          explain: 'The quota is shared by everything on the origin, can be much smaller in some browsers or modes, and `setItem` throws when it is hit. Persistence is a nice-to-have here, so the write must never break the feature. `clear()` deletes other features\' data — and other teams\' — on the same origin. Cookies are limited to about 4 KB each and are sent with every request.',
        },
      ],
    },
    {
      id: 'web-storage-expiry',
      title: 'localStorage with expiry, bad data and a full disk',
      kind: 'js',
      xp: 85,
      why: 'Every app ends up with a localStorage wrapper; the naive one crashes at startup on a corrupt value and loses drafts when the quota is full.',
      tags: ['storage', 'errors', 'caching'],
      hints: [
        'Store an envelope such as `JSON.stringify({ v: value, e: expiresAt })`, with `e: null` when there is no ttl, under `prefix + key`.',
        'Write one `decode(raw)` that returns the envelope or `undefined`: `JSON.parse` in a `try`, then check the result is an object with the fields you expect (`JSON.parse(\'null\')` succeeds).',
        'An entry is live when `e === null || now() < e`. In `get`, anything not live is removed and `null` is returned.',
        'In `clearExpired`, first collect every `storage.key(i)` that starts with the prefix into an array, then decode and remove. Removing inside the index loop skips neighbours.',
        'In `set`: `try { setItem; return true } catch (e) { if not a quota error, throw }`, then `clearExpired()`, then one more `try`, returning `false` on a second quota error.',
      ],
    },
    {
      id: 'web-document-cookie',
      title: 'Reading and writing document.cookie correctly',
      kind: 'js',
      xp: 75,
      why: 'Cookie helpers look trivial, and their bugs are silent: truncated tokens, cookies the browser drops, and "logout" that deletes nothing.',
      tags: ['cookies', 'encoding', 'security'],
      hints: [
        'Parse with `indexOf(\'=\')` and two `slice`s, not `split(\'=\')`: values often contain `=`.',
        'Wrap `decodeURIComponent` in a helper that returns the raw value from its `catch`. Use `Object.hasOwn(cookies, name)` to keep the first duplicate.',
        'Validate the name with one anchored regex, `^[…]+$`, whose character class lists `0-9A-Za-z` plus the symbols from the brief (escape the `-`). Test it before anything else.',
        'Build an array of parts and `join(\'; \')`. Map `sameSite` through `{ strict: \'Strict\', lax: \'Lax\', none: \'None\' }[String(sameSite).toLowerCase()]` and throw when the result is `undefined`.',
        '`deleteCookie` is `serializeCookie(name, \'\', { maxAge: 0, path, domain, secure })`, where `secure` is true for `__Secure-` and `__Host-` names.',
      ],
    },
    {
      id: 'web-typeahead-abort',
      title: 'A typeahead that debounces, aborts and never shows stale results',
      kind: 'js',
      xp: 95,
      why: 'Search-as-you-type is in every product, and out-of-order responses make it show results for what the user typed a second ago.',
      tags: ['abort', 'debounce', 'race-conditions', 'async'],
      hints: [
        'Keep four pieces of state: the current query, the pending timer id, the latest `AbortController`, and the results currently shown.',
        '`input`: always `clearTimeout` first. Then trim, compare with the current query, handle `\'\'` immediately, and otherwise `setTimeout(() => start(query), delayMs)` with the injected timer.',
        'In `start`: abort the previous controller, create a new one and remember it as the latest, render loading with the results currently shown, then `await search(query, { signal })`.',
        'After the `await` (in both the success and the error path), render only if `controller === mine && !mine.signal.aborted`. That one check drops stale responses **and** AbortErrors.',
        '`dispose` sets a flag, clears the timer and aborts; make your render helper return early when the flag is set.',
      ],
    },
    {
      id: 'web-url-state-boss',
      title: 'BOSS: filters in the URL, with history that behaves',
      kind: 'react',
      xp: 230,
      boss: true,
      why: 'Shareable, bookmarkable, Back-button-friendly filters are a standard mid-level feature, and they combine URL parsing, history and request races.',
      tags: ['url', 'history', 'abort', 'state'],
      hints: [
        'Write `parseState` and `toSearch` first and make them pure. `new URLSearchParams(search)` accepts a leading `?`; `[...new Set(tags)].sort()` de-duplicates and orders the tags.',
        'Page: `/^\\d+$/.test(raw) && Number(raw) >= 1 ? Number(raw) : 1`. `Number(\'\')` is `0` and `Number(\' 4\')` is `4`, so test the string, not the number.',
        'In `update`, normalise first: `const next = parseState(toSearch({ ...state, ...patch }))`, then compare `next.q`, `next.tags` and `next.sort` with the current state to decide the page reset.',
        'Before writing history, `if (toSearch(next) === location.search) return`. On start, `history.replaceState(history.state, \'\', location.pathname + canonical + location.hash)` when the search is not canonical.',
        'One `load(state)` does everything request-related: abort the previous controller, render loading, await `fetchPage`, and render only if it is still the latest and not aborted. `update`, start and `popstate` all call it.',
      ],
    },
  ],
});
