import { loadChapter } from '../../load.ts';

const here = import.meta.dirname;

export default loadChapter(here, {
  id: 'js-modules-runtime',
  title: "Modules & the Runtime",
  summary: "ESM vs CJS, dynamic import, structuredClone, timers and microtasks in anger.",
  lessons: [
    {
      id: 'js-esm-cjs-quiz',
      title: 'Quiz: ESM and CommonJS in the same codebase',
      kind: 'quiz',
      xp: 60,
      why: 'Every Node codebase is somewhere in the ESM migration, and its errors are unreadable until you know the rules underneath.',
      tags: ['modules', 'esm', 'commonjs'],
      quiz: [
        {
          q: 'An ESM file does `import { helper } from \'legacy-lib\'` and Node fails with *Named export \'helper\' not found. The requested module is a CommonJS module*. `legacy-lib` ends with `module.exports = createApi();`. What is the fix that keeps working?',
          options: [
            'Add `"type": "module"` to your own `package.json`',
            '`import * as lib from \'legacy-lib\'` and use `lib.helper`, which is always populated',
            'Rename your file to `.cjs` and keep the named import',
            '`import lib from \'legacy-lib\'; const { helper } = lib;` — the default import is always `module.exports`',
          ],
          answer: [3],
          explain: 'Node finds a CommonJS module\'s named exports by **statically scanning** its source for patterns like `exports.helper = …` or `module.exports = { helper }`. A computed `module.exports = createApi()` cannot be scanned, so no named exports exist; only `default` (the whole `module.exports`) is guaranteed. A namespace import has the same detected names plus `default`, so `lib.helper` is `undefined` too.',
        },
        {
          q: 'What does `main.mjs` log?\n\n```js\n// counter.mjs\nexport let count = 0;\nexport function increment() { count++; }\n\n// main.mjs\nimport { count, increment } from \'./counter.mjs\';\nincrement();\nconsole.log(count);\n```',
          options: [
            '`1`, because an ES import is a live binding to the exporter\'s variable',
            '`0`, because `count` was copied when it was imported',
            'It throws, because imported bindings are read-only and `increment` writes to one',
            '`undefined`, because `let` exports are not initialised until first use',
          ],
          answer: [0],
          explain: 'ES imports are **live bindings**: `count` in `main.mjs` is a read-only view of the variable in `counter.mjs`, so it sees the increment. Only the *importer* cannot assign to it; the exporting module can. The CommonJS equivalent, `const { count, increment } = require(\'./counter\')`, copies the value at require time and logs `0`, which is why "it worked before the migration" code can change behaviour.',
        },
        {
          q: 'After moving to ESM, `readFileSync(path.join(__dirname, \'schema.sql\'))` throws `__dirname is not defined in ES module scope`. Which replacements are correct on every OS and in any folder? Select all that apply.',
          options: [
            '`path.join(import.meta.dirname, \'schema.sql\')` (Node 20.11+)',
            '`fileURLToPath(new URL(\'./schema.sql\', import.meta.url))`',
            '`path.join(process.cwd(), \'schema.sql\')`',
            '`new URL(\'./schema.sql\', import.meta.url).pathname`',
          ],
          answer: [0, 1],
          explain: '`import.meta.dirname` is the direct replacement, and `fileURLToPath` over a URL relative to `import.meta.url` works on older versions. `process.cwd()` is wherever the process was started from, not where the file lives. `.pathname` keeps URL encoding (`%20` for spaces) and on Windows gives `/C:/…`, so it breaks on exactly the machines you do not test on. (`new URL(…)` is fine here because the file name has no `#` or `?`.)',
        },
        {
          q: '`config.mjs` does `export const config = await loadSecrets();` (top-level await). What happens? Select all that apply.',
          options: [
            'Modules that import `config.mjs` do not start evaluating until `loadSecrets()` settles, so they always see a loaded `config`',
            'The await runs in the background and importers see `config` as `undefined` until it resolves',
            'A CommonJS file that does `require(\'./config.mjs\')` fails with `ERR_REQUIRE_ASYNC_MODULE`',
            'If `loadSecrets()` rejects, every module that imports `config.mjs` fails to load',
          ],
          answer: [0, 2, 3],
          explain: 'Top-level await makes the module **asynchronous to evaluate**: its importers wait for it, and a rejection fails the whole import graph that depends on it (which, for secrets, is what you want at boot). `require()` is synchronous; recent Node versions can `require()` an ES module, but not one that uses top-level await. There is no state where an importer observes a half-initialised binding.',
        },
        {
          q: 'A library ships both a CommonJS build and an ESM build. Your app `import`s it, while one of your dependencies `require`s it. The library keeps a module-level registry of plugins, and `lib.register()` from your code has no effect on what the dependency sees. Why?',
          options: [
            'ESM modules are re-evaluated on every import, so the registry is reset each time',
            'Module-level state is frozen in ESM and silently ignores writes',
            'The "dual package hazard": the CJS and ESM builds are two separate modules, each with its own module-level state',
            'The dependency has an older version of the library pinned',
          ],
          answer: [2],
          explain: 'Each module is evaluated once **per resolved file**. `require` loads the `.cjs` build, `import` loads the `.mjs` build: two files, two evaluations, two registries, two copies of every class (so `instanceof` also fails across them). Libraries avoid it by keeping state in one build and re-exporting it from the other, or by shipping only one format. A pinned older version would be a similar symptom, but that is a different cause.',
        },
        {
          q: '`a.mjs` imports `b.mjs`, and `b.mjs` imports `a.mjs` and, at its top level, reads `DEFAULTS`, which `a.mjs` declares as `export const DEFAULTS = { … }`. `a.mjs` is the entry point. What happens?',
          options: [
            '`b.mjs` gets `undefined` for `DEFAULTS`, as it would with CommonJS',
            'Node detects the cycle and evaluates `a.mjs` first, so it works',
            '`ReferenceError: Cannot access \'DEFAULTS\' before initialization` — `b.mjs` runs first and `DEFAULTS` is still in its temporal dead zone',
            'A `SyntaxError` at link time: circular imports are not allowed in ESM',
          ],
          answer: [2],
          explain: 'Evaluation is depth-first: `a` imports `b`, so `b` runs to completion before `a`\'s body. The binding `DEFAULTS` already exists (linking happened), but its `const` has not been initialised, so reading it throws. CommonJS would hand `b` a half-filled `exports` object and a silent `undefined`. Cycles are legal in both; the fixes are to read the value lazily (inside a function) or to move the shared constant into a third module that both import.',
        },
      ],
    },
    {
      id: 'js-import-meta-paths',
      title: '__dirname is gone: paths from import.meta.url',
      kind: 'js',
      xp: 70,
      why: 'Loading a template, a migration or a fixture next to your code is daily work, and the naive ESM version breaks on Windows and in folders with spaces.',
      tags: ['modules', 'esm', 'paths'],
      hints: [
        '`fileURLToPath(metaUrl)` from `node:url` is the whole of `moduleFile`: it decodes `%20` and handles Windows drive letters. `path.dirname` of that is `moduleDir`.',
        'Do not resolve with `new URL(relative, metaUrl)`: in a URL, `#` starts a fragment and `?` starts a query. `path.resolve(moduleDir(metaUrl), relativePath)` treats them as ordinary characters.',
        '`toImportSpecifier` is `pathToFileURL(filePath).href`, which encodes everything that needs it.',
        'For `isEntrypoint`, bail out on a missing argv1, `path.resolve(argv1)` it, and compare with `moduleFile(metaUrl)` both as is and with its extension removed (`self.slice(0, -path.extname(self).length)`). Compare whole paths, never `startsWith`.',
      ],
    },
    {
      id: 'js-dynamic-import',
      title: 'import() for plugins and lazy chunks',
      kind: 'js',
      xp: 85,
      why: 'Code splitting, optional dependencies and plugin systems all run on `import()`, and its failure modes (wrong export shape, cached failures) reach users.',
      tags: ['modules', 'dynamic import', 'promises'],
      hints: [
        '`class PluginLoadError extends Error { constructor(specifier, message, options) { super(message, options); … } }` passes `{ cause }` through to `Error`.',
        'Write a `loadOne(specifier)` that awaits the import, wraps a failure in `PluginLoadError`, picks `mod.default !== undefined ? mod.default : mod`, and validates it. Then map every specifier to `loadOne` before awaiting anything.',
        '`Promise.allSettled` waits for everything and keeps the results in input order. Walk them in order: the first `rejected` one is the error to throw; track names in a `Set` for duplicates.',
        'For `lazy`, keep `let pending = null`. On a call with no pending promise, set `pending = new Promise((resolve) => resolve(loader()))` (a synchronous throw becomes a rejection) and attach `pending.catch(() => { pending = null; })` so a failure is forgotten.',
      ],
    },
    {
      id: 'js-json-codec',
      title: 'A JSON codec that keeps Dates, Maps and BigInts',
      kind: 'js',
      xp: 90,
      why: 'Every boundary your data crosses as JSON (APIs, queues, SSR props, storage) silently turns Dates into strings and Maps into `{}` unless you encode them on purpose.',
      tags: ['serialization', 'json', 'structuredClone'],
      hints: [
        'Write a recursive `toWire(value)` that returns JSON-safe data, then `JSON.stringify(toWire(value))`. Walking the value yourself means you see the `Date` itself, not the string `toJSON` made of it.',
        'Check the special cases before the generic object case: `undefined`, `bigint`, non-finite numbers, then `Date`, `Map`, `Set`, arrays, objects with `toJSON`. Each special value becomes `{ $type: \'Date\', value: … }` and so on; for a `Map`, the value is an array of `[toWire(key), toWire(value)]` pairs.',
        'Escaping: when a plain object has an own `$type` key, return `{ $type: \'Object\', value: <its encoded members> }`, and have the decoder turn that back into a plain object without looking for tags on the wrapped object itself.',
        'Decode with `JSON.parse(text)` and **no reviver**, then walk the result with a `fromWire`. Build objects with `Object.defineProperty` (or `Object.fromEntries`) so a `"__proto__"` key stays an own key.',
      ],
    },
    {
      id: 'js-runtime-quiz',
      title: 'Quiz: runtime behaviour that bites in production',
      kind: 'quiz',
      xp: 60,
      why: 'Cloning, timers, unhandled rejections and clocks all behave differently from what the code appears to say, and the difference is an incident.',
      tags: ['runtime', 'timers', 'promises'],
      quiz: [
        {
          q: '`const copy = structuredClone(state)` where `state` holds a `Date`, a `Map`, a `Cart` class instance with a `total()` method, and a reference back to itself (a cycle). What is true of `copy`? Select all that apply.',
          options: [
            '`copy.createdAt` is a real `Date` and `copy.byId` a real `Map`',
            '`copy.cart.total()` works, because the prototype is cloned too',
            'The cycle is preserved: `copy.self === copy`',
            '`copy.cart` is a plain object with the instance\'s own data properties; `copy.cart instanceof Cart` is false',
          ],
          answer: [0, 2, 3],
          explain: '`structuredClone` understands `Date`, `Map`, `Set`, typed arrays, `Error`s and cycles, which is why it beats `JSON.parse(JSON.stringify(x))`. It does **not** clone prototypes: a class instance comes back as a plain object with its own fields, so methods are gone. A function anywhere in the value makes it throw a `DataCloneError`. The same algorithm is used by `postMessage`, so the same rules apply to data you send to a worker.',
        },
        {
          q: 'A session service schedules a token refresh 30 days ahead: `setTimeout(refresh, 30 * 24 * 60 * 60 * 1000)`. What happens?',
          options: [
            'It fires after 30 days, as long as the process stays up',
            'It throws a `RangeError` at the call',
            'It is silently clamped to 24.8 days',
            '`refresh` runs almost immediately: delays above 2^31 − 1 ms (about 24.8 days) overflow and are treated as 1 ms, with a `TimeoutOverflowWarning`',
          ],
          answer: [3],
          explain: 'Timer delays are stored as a signed 32-bit integer. Anything larger than 2,147,483,647 ms overflows; Node warns and uses 1 ms, and browsers fire immediately too. A refresh loop built on it hammers the auth server. Long waits belong in a scheduler or a database row with a due date, checked periodically; if you must use a timer, chain shorter ones.',
        },
        {
          q: 'A CLI tool starts a metrics flusher with `setInterval(flush, 10_000)` in a shared module. The command finishes its work, but the process never exits. What is the targeted fix?',
          options: [
            'Call `.unref()` on the interval, so it does not keep the event loop alive on its own (and flush once explicitly before exiting)',
            'Call `process.exit(0)` at the end of `main()`',
            'Switch to `setTimeout` chained recursively',
            'Wrap the interval in a `Promise` so it resolves when the work is done',
          ],
          answer: [0],
          explain: 'Node exits when nothing *ref\'d* is left in the event loop: an active interval is something. `timer.unref()` says "do not keep the process alive just for me", which is what background housekeeping wants. `process.exit()` works but skips pending writes (a half-flushed stdout, an unsent log batch) and hides the real cause. A chained `setTimeout` is just as ref\'d.',
        },
        {
          q: '```js\nconst userP = fetchUser(id);\nconst ordersP = fetchOrders(id);\nconst user = await userP;\nconst orders = await ordersP;\n```\n\n`fetchOrders` rejects 50 ms in, while `fetchUser` takes 300 ms. On Node 15+ with default settings, what happens?',
          options: [
            'Nothing unusual: the rejection is caught by `await ordersP` at 300 ms',
            'The rejection is swallowed and `orders` is `undefined`',
            'The process crashes with an unhandled rejection: when `ordersP` rejected, nothing was handling it yet',
            '`await userP` throws the orders error instead',
          ],
          answer: [2],
          explain: 'A rejection is "unhandled" if no handler is attached by the time the microtask queue drains after it. At 50 ms nothing is awaiting `ordersP`, so Node fires `unhandledRejection`, and since Node 15 the default is to crash. `await Promise.all([fetchUser(id), fetchOrders(id)])` attaches handlers to both immediately and is the fix. (It also fails fast, instead of waiting for the slower call.)',
        },
        {
          q: 'You log request durations as `Date.now() - start`. Some log lines show negative durations, others show a request "taking" 40 seconds when the client saw 200 ms. What is going on?',
          options: [
            '`Date.now()` has only 1-second resolution in Node',
            'The wall clock was adjusted (NTP sync, VM migration, a manual change) mid-request; durations need a monotonic clock like `performance.now()` or `process.hrtime.bigint()`',
            'The event loop was blocked for 40 seconds',
            'Integer overflow in the subtraction',
          ],
          answer: [1],
          explain: '`Date.now()` reads the **wall clock**, which may jump backwards or forwards whenever the system time is corrected. That is right for timestamps ("when did this happen") and wrong for intervals ("how long did it take"). `performance.now()` is monotonic: it never goes backwards, and it has sub-millisecond precision. A blocked event loop would make real durations long, but never negative.',
        },
        {
          q: 'A service keeps `const cache = new Map()` at module level, keyed by request URL, with no eviction. Memory grows steadily until the pod is OOM-killed every two days. Which fixes are sound? Select all that apply.',
          options: [
            'Bound it: an LRU with a maximum size, or entries with a TTL that are evicted',
            'Switch to a `WeakMap` keyed by the URL string',
            'Move it to a shared cache (Redis) with expiry if it must be shared across instances',
            'Call `global.gc()` periodically',
          ],
          answer: [0, 2],
          explain: 'A module-level `Map` lives as long as the process, so every distinct key stays forever. The fix is a policy: a size bound (LRU) or a time bound (TTL), or an external cache with expiry. A `WeakMap` cannot take string keys at all (it throws), and it only helps when the key is an object whose lifetime you want to follow. Forcing GC reclaims nothing that is still referenced.',
        },
      ],
    },
    {
      id: 'js-yield-event-loop',
      title: 'Long loops without freezing the server',
      kind: 'js',
      xp: 80,
      why: 'One synchronous loop over a big array stalls every request on the instance; chunking and yielding with the right kind of task is the fix.',
      tags: ['event loop', 'performance', 'AbortSignal'],
      hints: [
        'Structure: an `async` function with a `while (index < items.length)` loop. Inside, an inner `for` runs one chunk synchronously, then `onProgress?.(index, items.length)`.',
        'Yield between chunks with `await new Promise((resolve) => setImmediate(resolve))`. `await null` or `await Promise.resolve()` is a microtask and lets no timer or request in.',
        'Only yield when there is another chunk to do, and call `signal?.throwIfAborted()` once before the loop and again before each chunk; it throws `signal.reason`.',
        'You do not need a `try/catch` around `fn`: a throw inside the `async` function rejects the returned promise, and the loop stops there.',
      ],
    },
    {
      id: 'js-repeat-no-overlap',
      title: 'Repeating async work without setInterval',
      kind: 'js',
      xp: 80,
      why: 'Pollers, syncs and cleanup jobs on `setInterval` overlap when they are slow, and cannot be shut down cleanly.',
      tags: ['timers', 'async', 'shutdown'],
      hints: [
        'Keep `timer`, `running` (the promise of the run in progress) and `stopped` in the closure, plus one `AbortController` whose `signal` every run receives.',
        '`run()` wraps the task in an `async` IIFE with `try { await task({ signal }) } catch (e) { try { onError?.(e) } catch {} }`. That promise never rejects, and a sync throw is caught too.',
        'Only after `running` settles do you call `schedule()`, which does nothing once `stopped` is set. That is what makes it fixed-delay, and what stops the loop after `stop()`.',
        '`stop()`: set `stopped`, `timers.clearTimeout(timer)`, `controller.abort()`, and return `running ?? Promise.resolve()`.',
      ],
    },
    {
      id: 'js-event-once',
      title: 'Awaiting one event without leaking listeners',
      kind: 'js',
      xp: 85,
      why: 'Promise-wrapping an event is everywhere (servers, workers, sockets), and the leaky version shows up as MaxListenersExceededWarning and slow memory growth.',
      tags: ['events', 'AbortSignal', 'memory leaks'],
      hints: [
        'Pick the API once: `typeof target.addEventListener === \'function\'` means EventTarget, otherwise use `on`/`off`. Keep a `listen(name, fn)` and an `unlisten(name, fn)` so the rest of the code does not care.',
        'Check `signal?.aborted` first and reject with `signal.reason` before adding anything.',
        'Name your handlers (`onEvent`, `onError`, `onAbort`) so you can remove exactly those functions, and write one `cleanup()` that removes all three. Call it on every path before resolving or rejecting.',
        'In `onEvent`, the payload is `args[0]` for an EventTarget and `args` for an emitter. Run `filter` inside a `try/catch`; if it returns falsy, just return and keep listening.',
      ],
    },
    {
      id: 'js-fake-clock',
      title: 'BOSS: build fake timers',
      kind: 'js',
      xp: 240,
      boss: true,
      why: 'Fake timers are in every serious test suite; knowing how they work is how you debug the test that never advances.',
      tags: ['timers', 'testing', 'event loop'],
      hints: [
        'State: `now`, `nextId`, and a `Map` of id to `{ due, order, fn, args, interval }`. `order` is a counter you bump every time a timer is scheduled or rescheduled; it breaks ties between equal due times.',
        'Write `nextDue(limit)`: the timer with the smallest `(due, order)` among those with `due <= limit`. `tick` loops `for (let t = nextDue(target); t; t = nextDue(target))`, so timers added or cleared by callbacks are picked up naturally.',
        'Firing: set `now = timer.due`; for a timeout delete it; for an interval do `timer.due += timer.interval` (and bump `order`) *before* calling `fn(...args)`. If `fn` throws, you have not yet set `now = target`, which is exactly the required behaviour.',
        '`tickAsync` is the same loop with `await new Promise((r) => realSetImmediate(r))` before the loop and after each timer, where `realSetImmediate = globalThis.setImmediate` is captured at module load.',
        '`runAll`: `while (timers.size)`, throw once you have run 1000 callbacks, otherwise fire `nextDue(Infinity)`.',
      ],
    },
  ],
});
