import { loadChapter } from '../../load.ts';

const here = import.meta.dirname;

export default loadChapter(here, {
  id: 'ts-type-level-2',
  title: "Type-Level Programming II",
  summary: "Recursive types, dotted key paths, deep partial/required, tuple manipulation, parsing strings in types.",
  lessons: [
    {
      id: 'ts-deep-partial',
      title: 'DeepPartial, DeepReadonly, DeepRequired',
      kind: 'typecheck',
      xp: 80,
      why: 'Config overrides, test fixtures and frozen state all need "this, but at every depth" — and the naive recursive type breaks every function and Date it touches.',
      tags: ['recursive types', 'mapped types', 'immutability'],
      hints: [
        'Recursion is just a type alias that mentions itself inside a mapped type: `{ [K in keyof T]?: DeepPartial<T[K]> }`. The work is deciding what NOT to recurse into.',
        'Put the stop conditions first, in one conditional chain: `T extends ((...args: never[]) => unknown) | Date ? T : …`.',
        'For `DeepPartial` and `DeepRequired`, the next question is `T extends readonly unknown[] ? T : …` — arrays pass through whole.',
        '`DeepReadonly` does not need an array branch: a homomorphic mapped type over an array or tuple type — `{ readonly [K in keyof T]: DeepReadonly<T[K]> }` — already produces a readonly array or tuple.',
        '`DeepRequired` uses the `-?` modifier: `{ [K in keyof T]-?: DeepRequired<T[K]> }`, which also strips the `undefined` that `?` added.',
      ],
    },
    {
      id: 'ts-jsonify',
      title: 'Jsonify: what actually crosses the wire',
      kind: 'typecheck',
      xp: 85,
      why: 'Sharing a server type with the client is a lie the moment it holds a Date or a method; a derived wire type makes the compiler tell the truth.',
      tags: ['recursive types', 'conditional types', 'mapped types', 'json'],
      hints: [
        '`Json` can refer to itself: `string | number | boolean | null | Json[] | { [key: string]: Json }`.',
        'Write `Jsonify` as one chain of conditionals. The first question is `T extends { toJSON(): infer R } ? Jsonify<R> : …` — before anything asks whether `T` is an object.',
        'Name the droppable things once: `type Dropped = undefined | symbol | ((...args: never[]) => unknown)`. Array elements use a helper: `E extends Dropped ? null : Jsonify<E>`, and arrays match `T extends readonly (infer E)[]`.',
        'For objects, filter keys with an `as` clause: `{ [K in keyof T as K extends symbol ? never : T[K] extends Dropped ? never : K]: Jsonify<T[K]> }`. Mapping over `keyof T` keeps the `?` modifiers for free.',
        'An optional `note?: string` has value type `string | undefined`; `Jsonify` distributes, so it becomes `string | never` = `string`, and the key stays optional. That only works if a bare `undefined` gives `never`.',
      ],
    },
    {
      id: 'ts-key-paths',
      title: 'Dotted key paths and the value at a path',
      kind: 'typecheck',
      xp: 90,
      why: 'Every form library, i18n helper and `get(obj, "a.b.c")` in your codebase is either typed like this or is a string-typed hole.',
      tags: ['recursive types', 'template literals', 'mapped types'],
      hints: [
        'Build `Paths` with the "map each key, then index with `[keyof T]`" trick: each key K maps to the union of `K` and the template literal `${K}.${Paths<T[K]>}` (written with backticks in your code), and indexing collapses the object into a union.',
        'Iterate `keyof T & string` so number and symbol keys do not break the template literal, and descend into `NonNullable<T[K]>` so optional objects still yield their child paths.',
        'Stop early: `T extends ((...args: never[]) => unknown) | Date | readonly unknown[] ? never : …`. For a key whose `NonNullable<T[K]>` is a function, map it to `never`. Add `-?` to the mapped type, or an optional key contributes `undefined` to the union.',
        '`PathValue` peels one segment at a time: match `P` against the template `${infer Head}.${infer Rest}`; on a match recurse with `PathValue<T[Head], Rest>` (guarding `Head extends keyof T`), otherwise `P extends keyof T ? T[P] : never`.',
        'For optional parents, start `PathValue` with `T extends null | undefined ? undefined : …`. Because `T` is a bare type parameter, it distributes: `{ email: boolean } | undefined` becomes `PathValue<{ email: boolean }, …> | undefined`.',
      ],
    },
    {
      id: 'ts-tuple-args',
      title: 'Parameter lists are tuples',
      kind: 'typecheck',
      xp: 85,
      why: 'Wrappers that pre-fill or bind arguments are everywhere in service code; typed with variadic tuples they keep every signature instead of erasing it to `any`.',
      tags: ['variadic tuples', 'infer', 'generics'],
      hints: [
        '`DropFirst` is one `infer`: match `T` against `readonly [unknown, ...infer Rest]`. Without `readonly` in the pattern, a readonly tuple does not match.',
        'A generic rest parameter infers a tuple: in `function f<H extends unknown[]>(...head: H)`, calling `f("a", 1)` infers `H = [string, number]`.',
        'For `partial`, declare `Head` and `Tail` (both `extends unknown[]`) and `R`, and type `fn` as `(...args: [...Head, ...Tail]) => R`. The compiler infers `Head` from the arguments you pass and works out `Tail` as whatever is left.',
        'The body is one line — `return (...tail) => fn(...head, ...tail);` — and the return type is `(...tail: Tail) => R`.',
        '`Bound` maps each key and infers around the first parameter: `H[K] extends (ctx: never, ...args: infer A) => infer R ? (...args: A) => R : never`. `never` in the pattern accepts any context type.',
      ],
    },
    {
      id: 'ts-format-params',
      title: 'Parsing placeholders out of strings',
      kind: 'typecheck',
      xp: 90,
      why: 'Translation catalogues and log templates hide their parameters inside strings; parsing them at the type level turns "undefined unread messages" into a compile error.',
      tags: ['template literals', 'recursive types', 'i18n'],
      hints: [
        'First collect the raw text of every placeholder as a union: match `S` against the template `${string}{${infer Body}}${infer Rest}` and return `Body | Placeholders<Rest>`, else `never`.',
        'Split one placeholder with a second template match, against `${infer Name}:${infer Kind}`, which gives both parts; with no colon, the name is `B` itself and the type is `string`.',
        'Build the object with key remapping over the union: `{ [B in Placeholders<S> as NameOf<B>]: TypeOf<B> }`. Two identical placeholders are one union member, so they become one key.',
        'Map the kind with a small chain: `Kind extends "string" ? string : Kind extends "number" ? number : Kind extends "date" ? Date : never`.',
        '`FormatArgs<S> = [Placeholders<S>] extends [never] ? [] : [params: FormatParams<S>]` — the tuple wrapping stops `never` from swallowing the whole conditional.',
      ],
    },
    {
      id: 'ts-camel-keys',
      title: 'snake_case rows, camelCase objects',
      kind: 'typecheck',
      xp: 85,
      why: 'The database speaks snake_case and your code speaks camelCase; deriving one type from the other removes a whole class of drift between row types and domain types.',
      tags: ['template literals', 'recursive types', 'key remapping'],
      hints: [
        '`CamelCase` splits at the first underscore and recurses on the tail: match the template `${infer Head}_${infer Tail}` and produce `${Head}` followed by `CamelCase<Capitalize<Tail>>`.',
        '`SnakeCase` walks one character at a time with the template `${infer C}${infer Rest}`. A character is uppercase when `C extends Lowercase<C>` is false — that test leaves digits alone, unlike `C extends Uppercase<C>`.',
        'Key renaming is an `as` clause: `{ [K in keyof T as K extends string ? CamelCase<K> : K]: CamelKeys<T[K]> }`. It keeps `?` because it still iterates `keyof T`.',
        'Order the branches: `Date` or function → unchanged; `T extends (infer E)[]` → `CamelKeys<E>[]`; `T extends readonly (infer E)[]` → `readonly CamelKeys<E>[]`; then objects; then primitives.',
      ],
    },
    {
      id: 'ts-deep-merge',
      title: 'A deep merge that does not bite',
      kind: 'ts',
      xp: 90,
      why: 'Config and options merging is in every codebase, and the naive version shares state between requests and is a textbook prototype-pollution hole.',
      tags: ['recursion', 'immutability', 'security', 'objects'],
      hints: [
        'Split the job in two: a `cloneDeep` that copies arrays and plain objects (and returns anything else as-is), and a `mergeValue(base, override)` that decides what wins.',
        '`isPlainObject`: `typeof v === "object" && v !== null`, then compare `Object.getPrototypeOf(v)` with `Object.prototype` and `null`. That one check rules out arrays, Dates, Maps and class instances.',
        'In `mergeValue`: if the override is `undefined`, return a clone of the base. If both are plain objects, start from a clone of the base and assign `mergeValue(base[key], override[key])` for each key of the override. Otherwise return a clone of the override.',
        'Keep a `Set` of `__proto__`, `constructor` and `prototype`, and `continue` past them in both the clone loop and the merge loop. Assigning to `out.__proto__` on a normal object changes its prototype — it never creates a key.',
      ],
    },
    {
      id: 'ts-mapped-tuples',
      title: 'Mapped types over tuples: a typed Promise.all',
      kind: 'typecheck',
      xp: 80,
      why: 'Parallel-fetch helpers are in every loader and service; typed as `unknown[]` they force casts that silently go stale when the tasks are reordered.',
      tags: ['mapped types', 'variadic tuples', 'async'],
      hints: [
        'A homomorphic mapped type, `{ [K in keyof T]: … }`, over a tuple type gives back a tuple of the same length. You do not need a separate tuple branch.',
        '`AwaitedValues<T>` is one line: `{ [K in keyof T]: Awaited<T[K]> }`. `SettledValues` is the same with `Settled<Awaited<T[K]>>`.',
        'For `TaskResults`, unwrap each function with a conditional: `T[K] extends () => infer R ? Awaited<R> : never`, and add `-readonly` before the brackets so a readonly input tuple gives a mutable result.',
        '`runAll<T extends readonly (() => unknown)[]>(tasks: readonly [...T]): Promise<TaskResults<T>>`. The `[...T]` is what makes the compiler infer a tuple; the body needs one cast, because `Promise.all` over `tasks.map(...)` only knows it has an array.',
      ],
    },
    {
      id: 'ts-typed-form',
      title: 'BOSS: a typed form, paths and all',
      kind: 'typecheck',
      xp: 220,
      boss: true,
      why: 'Every form library you will use at work is typed like this; building it once makes their error messages readable and your own form helpers safe to refactor.',
      tags: ['recursive types', 'template literals', 'mapped types', 'forms'],
      hints: [
        'Start from the `Paths` type of the key-paths lesson and change one branch: instead of stopping at arrays, an array of `E` gives the template `${number}` plus `${number}.` followed by `FieldPath<E>` (both written with backticks).',
        'Check leaves first, then arrays, then objects: `T extends Leaf ? never : T extends readonly (infer E)[] ? … : { [K in keyof T & string]: K | … }[keyof T & string]`.',
        'For `FieldValue`, write a one-step helper `Step<T, S>`: an array with a segment matching the template `${number}` gives its element, an object gives `T[S]` when `S extends keyof T`, anything else `never`. Then `FieldValue` splits `P` at the first dot and recurses with `Step`.',
        '`FormErrors` is the same three-way split: leaf → `string`, array → `(FormErrors<E> | undefined)[]`, object → `{ [K in keyof T]?: FormErrors<T[K]> }`.',
        '`watch<Ps extends readonly FieldPath<T>[]>(...paths: Ps): { -readonly [I in keyof Ps]: FieldValue<T, Ps[I] & string> }`. In `createForm`, `get` needs `as FieldValue<T, typeof path>` and `watch` needs a cast too: the checker cannot follow a `map` into a mapped tuple.',
      ],
    },
  ],
});
