import { loadChapter } from '../../load.ts';

const here = import.meta.dirname;

export default loadChapter(here, {
  id: 'node-api-design',
  title: "API Design in Practice",
  summary: "Filtering and sorting parsers, cursor pagination, idempotency keys, versioning, bulk operations, merge patch.",
  lessons: [
    {
      id: 'node-list-query-parser',
      title: 'Filtering and sorting from the query string',
      kind: 'node',
      xp: 85,
      why: 'Every list endpoint grows filters and sorts; an allowlist parser is what stops `?sort=password_hash` and silently ignored duplicates.',
      tags: ['api design', 'validation', 'query strings'],
      hints: [
        'Iterate `params` (a `URLSearchParams` is iterable as `[key, value]` pairs) rather than calling `get()` per field — `get()` hides repeats and unknown keys, which are exactly the cases you must report.',
        'Count keys first (`for (const key of params.keys())`), then walk the pairs once, skipping a key you have already handled. A count above 1 is the "repeated" error.',
        'Split a key with a regex like `/^([A-Za-z_][A-Za-z0-9_]*)(?:\\[([a-z]+)\\])?$/`: group 1 is the field, group 2 the op (default `eq`). Look the field up with `Object.hasOwn(schema.filters, field)`, or `?constructor=1` finds `Object.prototype.constructor`.',
        'Write one `convert(type, raw)` that returns `{ ok, value }` or `{ ok: false, error }`, and use it for both a single value and every item of an `in` list. For integers, test `/^-?\\d+$/` on the whole string, then `Number.isSafeInteger`.',
        'After the loop: throw `new QueryError(details)` if it has any keys; otherwise fall back to `defaultSort`, and push `{ field: \'id\', dir: \'asc\' }` unless some sort entry already has `field === \'id\'`.',
      ],
    },
    {
      id: 'node-cursor-pagination',
      title: 'Opaque cursors that survive inserts and deletes',
      kind: 'node',
      xp: 90,
      why: 'Offset pagination repeats and skips rows on any table that is being written to. Keyset cursors are how every serious public API pages.',
      tags: ['api design', 'pagination', 'keyset'],
      hints: [
        'Sort a copy (`[...rows].sort(cmp)`) with one comparator that walks the sort fields in order and flips the sign for `desc`. Write it over arrays of key values, so the same function compares a row to a cursor.',
        'The cursor is the last item\'s sort-key values: `sort.map((s) => row[s.field])`. The next page is every row whose key compares **greater than** the cursor key under your comparator — no index anywhere.',
        'Take `limit + 1` rows. If you got more than `limit`, there is a next page: return the first `limit` and a cursor from the last of those. Otherwise `nextCursor` is `null`.',
        'Encode `{ s: signature, k: values }` with `Buffer.from(JSON.stringify(payload)).toString(\'base64url\')`, where `signature` is something like `price:desc,id:asc`. On decode, reject a mismatched `s`.',
        'Put the base64 decode and `JSON.parse` in one `try` that throws `new CursorError()`, then check the shape: an object, `s` matches, `k` is an array of the right length. `JSON.parse(\'null\')` succeeds, so check for `null` too.',
      ],
    },
    {
      id: 'node-idempotency-keys',
      title: 'Idempotency keys: retries that do not charge twice',
      kind: 'node',
      xp: 100,
      why: 'Networks drop responses, clients retry, and without idempotency keys a retried POST is a second payment. Every payments or orders API needs this.',
      tags: ['api design', 'idempotency', 'concurrency', 'http'],
      hints: [
        'Keep one `Map` from key to a record. A record is either `{ fingerprint, state: \'running\' }` or `{ fingerprint, state: \'done\', status, body, storedAt }`.',
        'The fingerprint only has to tell requests apart: `JSON.stringify([req.method, req.url, rawBody])` works; hashing it with `createHash(\'sha256\')` keeps the map small.',
        'Order the checks: expire a stale `done` record first; then a record with a different fingerprint is 422; a `running` one is 409; a `done` one is a replay.',
        'Claim the key with `records.set(key, { fingerprint, state: \'running\' })` **before** awaiting the handler, with no `await` between the `get` and that `set`. Otherwise two simultaneous first requests both see an empty map.',
        'Run the handler inside `try/catch`: a throw becomes `{ status: 500, body: … }`. Afterwards, `status < 500` → store the `done` record with `storedAt: now()`; otherwise `records.delete(key)`.',
      ],
    },
    {
      id: 'node-conditional-updates',
      title: 'ETags and If-Match: no more lost updates',
      kind: 'node',
      xp: 90,
      why: 'Two people editing the same record silently overwrite each other until the API makes writes conditional. `If-Match` is the HTTP-native fix.',
      tags: ['api design', 'http', 'concurrency', 'caching'],
      hints: [
        'The ETag is just `` `"${doc.version}"` `` — the quotes are part of the value. Send it on every `GET` and after every successful `PUT`.',
        'Write one `matches(header, etag, { weak })`: split on `,`, trim each tag, return true for `*`; a tag starting with `W/` matches only when `weak` is true and `tag.slice(2) === etag`; otherwise compare exactly.',
        '`If-None-Match` on `GET` uses weak comparison and answers `304` with `res.writeHead(304, { etag }); res.end()` — no JSON body. `If-Match` on `PUT` uses strong comparison.',
        'In `PUT`, `await` the body **first**. Then, with no `await` in between, do: 404 check, 428 check, 412 check (with the current `etag` header), `store.set(id, { version: doc.version + 1, data })`.',
      ],
    },
    {
      id: 'node-merge-patch',
      title: 'PATCH done right: JSON Merge Patch',
      kind: 'node',
      xp: 85,
      why: '`Object.assign(record, body)` loses nested fields, cannot delete, and mutates before validating. Merge Patch is the standard that fixes all three.',
      tags: ['api design', 'http', 'immutability', 'validation'],
      hints: [
        'The whole RFC is a short recursive function: if `patch` is not a plain object, return it; otherwise start from a **copy** of `target` (or `{}`), and for each key either delete it (`null`) or set it to `applyMergePatch(result[key], value)`.',
        'Always recurse, even when the target has no such key: `applyMergePatch(undefined, { k: null, v: 1 })` merges into `{}` and drops the `null`. Assigning the patch value directly would store it.',
        'Arrays are not plain objects: `Array.isArray(v)` must make your `isPlainObject` false, so an array in the patch replaces the target value.',
        'In the handler, compare the media type with `(header ?? \'\').split(\';\')[0].trim().toLowerCase()`. Then JSON, then plain object, then `load`, then readonly keys, then merge and validate.',
        'Only `save` touches storage. Because `applyMergePatch` copies, a failed validation leaves the stored object exactly as it was.',
      ],
    },
    {
      id: 'node-bulk-operations',
      title: 'Bulk endpoints with per-item results',
      kind: 'node',
      xp: 95,
      why: 'Imports and sync jobs send hundreds of items at once; a bulk endpoint must say exactly which ones worked, without melting the database.',
      tags: ['api design', 'concurrency', 'errors', 'http'],
      hints: [
        'Split the work in two passes. Pass one is synchronous: validate every item and detect duplicates, writing 422/409 results into `results[index]` and collecting the indexes that should be created.',
        'Only add a key to the `seen` set when the item is valid and not a duplicate, so an invalid item never blocks a later valid one.',
        'Bounded concurrency without a library: start `concurrency` async "lanes", each looping `while (next < jobs.length) { const job = jobs[next++]; await work(job); }`. Wait for all lanes with `Promise.all`.',
        'Write each outcome into `results[index]` (a pre-sized array), never `push` — that is what keeps index order when creates finish out of order. Wrap `await create(item)` in `try/catch`, which also catches a synchronous throw.',
        'Status: `201` only if every result is `201`, else `207`. The summary is counts over `results`.',
      ],
    },
    {
      id: 'node-api-versioning',
      title: 'Date-based API versioning without forking handlers',
      kind: 'node',
      xp: 100,
      why: 'Renaming a field breaks every client that will never update. Version transforms let the handlers move on while old clients keep working.',
      tags: ['api design', 'versioning', 'compatibility', 'http'],
      hints: [
        'Sort a copy of `changes` by `version` once, when `versioned` is called. The changes that apply to a client are exactly those with `change.version > clientVersion` — ISO dates compare correctly as strings.',
        'Upgrading is a fold, oldest first: `pending.reduce((data, change) => change.up(data), data)`. Downgrading is the same fold the other way: `reduceRight` with `change.down`.',
        'Only downgrade when `status` is 2xx and `body.data` is an object or array; build a new body with `{ ...body, data: … }` rather than assigning into the handler\'s object.',
        'In each transform, return the input untouched when its field is absent (`if (!(\'balance\' in r)) return r`), otherwise copy it, delete the old key from the copy, and add the new one. `Math.round(balance * 100)` fixes `0.29 * 100`.',
        'For `name`, use `indexOf(\' \')`: no space gives `lastName: \'\'`; otherwise slice either side of the **first** space. Joining back: `[firstName, lastName].filter(Boolean).join(\' \')`.',
      ],
    },
    {
      id: 'node-api-design-judgement',
      title: 'API design calls you cannot take back',
      kind: 'quiz',
      xp: 60,
      why: 'Once a partner depends on your API, status codes, method semantics and field shapes are a contract. These are the calls reviewers expect a mid-level engineer to get right.',
      tags: ['api design', 'http', 'compatibility'],
      hints: [
        'Idempotency is about the effect on server state, not about getting the same response twice.',
        'A change is breaking if a client written against the old contract can stop working without changing any of its code.',
      ],
      quiz: [
        {
          q: 'A client sends `PUT /users/7` with the body `{ "email": "new@x.io" }` — no `name`. Under PUT semantics, what should happen to the user\'s name?',
          options: [
            'It is kept: the server only updates the fields that were sent.',
            'The body is the complete new representation, so `name` is cleared — or, since `name` is required, the request is rejected as invalid.',
            'It depends on whether the client sent `If-Match`.',
            'The server should answer 405: updates must use PATCH.',
          ],
          answer: [1],
          explain: '`PUT` means "replace the resource with this". Treating it as a partial update is the most common REST bug: a client that PUTs what it thinks is a full object (but is missing a field it did not know about) silently wipes that field — or, as implemented by many teams, silently does not, and nobody knows which. Partial updates are what `PATCH` (e.g. JSON Merge Patch) is for. `If-Match` guards against concurrent writers; it does not change what the body means.',
        },
        {
          q: 'Your API is used by mobile apps you cannot force to update. Which of these changes are **breaking**? Select all that apply.',
          options: [
            'Adding a new optional field to a response object.',
            'Making a previously optional request field required.',
            'Renaming `total` to `totalCents` in responses.',
            'Accepting a new optional query parameter.',
            'Changing `id` in responses from a number to a string.',
          ],
          answer: [1, 2, 4],
          explain: 'Old clients never send the newly required field, so every one of their requests starts failing. A rename is a removal plus an addition: old clients read `total`, get `undefined`, and show "NaN". A type change breaks every client that does arithmetic or strict comparison on `id`. Adding optional response fields and optional parameters is safe **provided** clients ignore unknown fields — which is why you should tell them to, from day one. Breaking changes go behind a new version, not into the current one.',
        },
        {
          q: '`POST /users` arrives with well-formed JSON and a valid-looking email, but that email already belongs to another account. Which status fits best?',
          options: [
            '400 Bad Request',
            '422 Unprocessable Content',
            '409 Conflict',
            '500 Internal Server Error',
          ],
          answer: [2],
          explain: 'The request itself is fine; it conflicts with the **current state** of the server, which is what 409 is for (the same request would succeed against a different database). 400 is for a request the server cannot parse or that is structurally wrong; 422 for a well-formed request whose content is invalid on its own (an email with no `@`). A 500 here — usually an unhandled unique-constraint violation — tells the client to retry something that will never succeed, and pages your on-call.',
        },
        {
          q: 'Generating a customer\'s annual statement takes two to five minutes. How should `POST /statements` respond?',
          options: [
            '`202 Accepted` with a `Location` pointing at a status resource the client can poll (and optionally a webhook when it finishes).',
            'Hold the connection open until the statement is ready, then `201 Created`.',
            '`201 Created` immediately, with an empty statement that fills in later.',
            '`503 Service Unavailable` with `Retry-After: 300`.',
          ],
          answer: [0],
          explain: 'Proxies, load balancers and mobile networks kill connections long before five minutes, and the client then retries a job that is already running. `202` says "accepted, not done", and the status resource (`/statements/jobs/123` → `pending` / `done` with a link / `failed`) makes progress observable and retries safe. A 201 for something that does not exist yet lies to the client; a 503 says the server is broken when it is working as designed.',
        },
        {
          q: 'A partner runs a nightly export of your 5-million-row `events` table through `GET /events`, which is being inserted into constantly. Which pagination should the API offer for this?',
          options: [
            '`?page=N&pageSize=100` — it is the easiest for partners to parallelise.',
            '`?offset=N&limit=1000` — standard, and the database handles it.',
            'No pagination: stream all 5 million rows in one response.',
            'A keyset cursor over a stable sort ending in a unique column, e.g. `(created_at, id)`.',
          ],
          answer: [3],
          explain: 'Page and offset are the same thing: row N shifts every time a row is inserted before it, so a long export duplicates and skips rows, and `OFFSET 4000000` makes the database walk and discard four million rows per request. A keyset cursor ("after `(created_at, id)` = …") is stable under inserts and costs the same on page 1 and page 5000. One unbounded response is fragile: any network blip restarts the whole export.',
        },
        {
          q: 'A client retries `DELETE /orders/7` after a timeout. The first attempt had in fact succeeded, so the retry gets `404`. Is `DELETE` still idempotent?',
          options: [
            'No: an idempotent operation must return the same response every time, so the second call should also return 204.',
            'Yes: idempotency means repeating the request leaves the server in the same state as doing it once. The response may differ.',
            'Only if the client sent an `Idempotency-Key` header.',
            'No: DELETE is idempotent only when the resource never existed.',
          ],
          answer: [1],
          explain: 'HTTP defines idempotency by effect: after one DELETE or ten, order 7 is gone. Whether the retry answers 204 or 404 is a design choice (both are common; 404 is more honest), and clients should treat "404 on a retried delete" as success. `Idempotency-Key` exists for `POST`, which is **not** idempotent by definition — two POSTs create two orders unless you add that machinery.',
        },
      ],
    },
    {
      id: 'node-orders-api-boss',
      title: 'BOSS: a public orders API',
      kind: 'node',
      xp: 240,
      boss: true,
      why: 'Filters, cursors, idempotent creates and conditional updates all have to hold at once in a real public API. This is that API, end to end.',
      tags: ['api design', 'http', 'pagination', 'idempotency', 'concurrency'],
      hints: [
        'Structure first: a `route(req)` that returns `{ status, body, headers }` or throws an `HttpError(status, code, message, { details, headers })`, and one wrapper that sends either. Each endpoint becomes a small function.',
        'Store `{ order, version, seq }` per id, where `seq` is the creation number. `seq` is your tiebreaker: a position is `[...sort.map((s) => order[s.field]), seq]`, and the comparator falls back to `a.seq - b.seq`.',
        'For the list, count keys first (repeats are errors), then `switch` on the raw key: `status`, `status[in]`, `totalCents[gte]`, `totalCents[lte]`, `sort`, `limit`, `cursor`, default → unknown. Push filter predicates; collect errors into `details` and throw once.',
        'The cursor is `base64url(JSON.stringify({ s: \'totalCents:desc\', k: position }))`. Decoding: `try` the parse, then check it is an object, `s` matches the current sort signature, and `k` has `sort.length + 1` entries. Fetch `limit + 1` to decide on `nextCursor`.',
        'For POST: key format → stored-key lookup (compare the **raw** body string) → parse → validate → create; only store the response after a successful create, including its `location` and `etag` headers, and add `idempotent-replayed: true` on replay.',
        'For PATCH: `await readBody` right after the media-type check, and do every other check against `records.get(id)` read **after** that await. Build the patched order with a copying merge, validate it, then `records.set(id, { ...record, order: next, version: record.version + 1 })`.',
      ],
    },
  ],
});
