import { loadChapter } from '../../load.ts';

const here = import.meta.dirname;

export default loadChapter(here, {
  id: 'testing-unit',
  title: "Unit Tests That Pay",
  summary: "Pure functions, parsers, state machines, table-driven tests, boundaries — you write the tests.",
  lessons: [
    {
      id: 'test-unit-boundaries',
      title: 'Test on the boundary, not in the middle',
      kind: 'mutation',
      xp: 70,
      minTests: 6,
      why: 'Off-by-one bugs live on thresholds. A test in the middle of a band passes whether the code says `<` or `<=`.',
      tags: ['boundaries', 'unit tests', 'table-driven'],
      mutants: [
        { slug: 'first-band-exclusive', label: 'Charges the 501–2000 g rate for a parcel of exactly 500 g' },
        { slug: 'rounds-weight', label: 'Rounds the weight to the nearest 100 g before pricing it' },
        { slug: 'floors-started-kg', label: 'Counts only whole kilograms over 10 kg, not started ones' },
        { slug: 'extra-kg-on-exact', label: 'Charges an extra kilogram when the weight is exactly a whole kilogram over 10 kg' },
        { slug: 'accepts-zero', label: 'Prices a 0 g parcel instead of throwing a RangeError' },
        { slug: 'accepts-fractions', label: 'Prices a fractional weight such as 1.5 g instead of throwing' },
      ],
      hints: [
        'List the thresholds from the table: 500, 2000, 10000. Each one needs two tests.',
        'For each threshold test the value on it and one gram past it: 500 and 501, 2000 and 2001, 10000 and 10001.',
        'Over 10 kg, "started kilogram" has its own edges: 10001 g and 11000 g both cost `1395`, and 11001 g costs `1495`.',
        'The rejections: `0`, a negative number and `1.5` must each `toThrow(RangeError)`. One weight like 501 g also catches the rounding bug.',
      ],
    },
    {
      id: 'test-unit-table-driven',
      title: 'Table-driven tests for a parser',
      kind: 'mutation',
      xp: 75,
      minTests: 8,
      why: 'Parsers see dozens of input shapes. A table of cases makes the missing ones visible in review and costs one line per case.',
      tags: ['table-driven', 'parsing', 'unit tests'],
      mutants: [
        { slug: 'no-ms-unit', label: 'Cannot parse the `ms` unit, so `250ms` is null' },
        { slug: 'case-sensitive', label: 'Rejects upper-case units such as `1H30M`' },
        { slug: 'allows-repeats', label: 'Accepts the same unit twice (`1h1h`)' },
        { slug: 'allows-any-order', label: 'Accepts units out of order (`30m1h`)' },
        { slug: 'empty-is-zero', label: 'Returns 0 for an empty or blank string instead of null' },
        { slug: 'ignores-trailing-junk', label: 'Stops at the first bad character and returns the total so far' },
        { slug: 'accepts-decimals', label: 'Accepts fractions such as `1.5h`' },
      ],
      hints: [
        'Make two arrays: inputs that parse (with their milliseconds) and inputs that must return `null`. Loop over each and register one `it` per row.',
        'The valid table needs every unit on its own, including `ms`, a multi-part value, upper-case units and surrounding whitespace.',
        'The null table matters more: `""`, `"   "`, `"10"`, `"10s!"`, `"1.5h"`, `"-5s"`, `"1h1h"`, `"30m1h"`.',
        'Assert `toBe(null)`, not `toBeFalsy()`: the empty-string bug returns `0`, and `0` is falsy.',
      ],
    },
    {
      id: 'test-unit-errors',
      title: 'Assert the error callers catch',
      kind: 'mutation',
      xp: 80,
      minTests: 7,
      why: 'Callers catch a class and branch on a code. `toThrow()` with no argument passes when the code crashes with the wrong error entirely.',
      tags: ['errors', 'unit tests', 'parsing'],
      mutants: [
        { slug: 'crashes-on-garbage', label: 'Crashes with a TypeError on unparsable input instead of throwing a PriceError' },
        { slug: 'precision-as-format', label: 'Reports three decimals as FORMAT instead of PRECISION' },
        { slug: 'rounds-extra-decimals', label: 'Rounds extra decimals away instead of rejecting them' },
        { slug: 'negative-as-format', label: 'Reports a negative price as FORMAT instead of NEGATIVE' },
        { slug: 'one-decimal-is-pence', label: 'Reads `12.5` as 12 pounds and 5 pence' },
        { slug: 'loose-separators', label: 'Accepts commas anywhere, such as `1,23.45`' },
        { slug: 'coerces-numbers', label: 'Accepts a number argument instead of throwing a TypeError' },
      ],
      hints: [
        'Every rejection test needs two facts: the class (`toThrow(solution.PriceError)`) and the code (`toThrow({ code: \'FORMAT\' })`). A tiny helper that asserts both keeps the table short.',
        'Give each code at least one row: `""` is EMPTY, `"-5"` is NEGATIVE, `"12.345"` is PRECISION, `"abc"` and `"12."` are FORMAT.',
        'Separators have a rule too: `"1,234.56"` parses and `"1,23.45"` is FORMAT. And `"12.5"` must be `1250`, not `1205`.',
        'A non-string is a programming error: `parsePrice(12.5)` must throw a `TypeError`, and `.not.toThrow(solution.PriceError)` pins that it is not treated as user input.',
      ],
    },
    {
      id: 'test-unit-dates',
      title: 'Date arithmetic on fixed dates',
      kind: 'mutation',
      xp: 75,
      minTests: 6,
      why: 'Date bugs hide on Fridays, weekends, holidays and year ends. A test that uses today\'s date passes or fails depending on the day it runs.',
      tags: ['dates', 'unit tests', 'boundaries'],
      mutants: [
        { slug: 'sunday-is-business', label: 'Counts Sunday as a business day' },
        { slug: 'ignores-holidays', label: 'Ignores the holidays list' },
        { slug: 'negative-goes-forward', label: 'Counts forwards when n is negative' },
        { slug: 'counts-start-day', label: 'Counts the start date as the first business day' },
        { slug: 'zero-rolls-forward', label: 'Moves a weekend date to Monday when n is 0' },
      ],
      hints: [
        'Use the fixed dates from the brief. `2024-03-01` is a Friday, so Friday + 1 must be `2024-03-04`.',
        'Start on the days where rules apply: Friday + 1, Saturday + 1, Monday − 1 (the Friday before), and a date with n = 0 on a weekend.',
        'Holidays: `addBusinessDays(\'2024-12-24\', 1, { holidays: [\'2024-12-25\', \'2024-12-26\'] })` should skip both days to `2024-12-27`.',
        'For the Sunday bug, start on a Saturday and add 1: the answer is Monday `2024-03-04`, not Sunday.',
      ],
    },
    {
      id: 'test-unit-state-machine',
      title: 'Test the moves a state machine forbids',
      kind: 'mutation',
      xp: 90,
      minTests: 7,
      why: 'A state machine usually breaks when someone adds a move that should not exist. Only a test of the forbidden moves can see that.',
      tags: ['state machines', 'generated cases', 'unit tests'],
      mutants: [
        { slug: 'shipped-cancellable', label: 'Lets a shipped order be cancelled' },
        { slug: 'refund-before-delivery', label: 'Lets a paid order be refunded before it is delivered' },
        { slug: 'failed-payment-cancels', label: 'A failed payment cancels the order instead of returning it to the cart' },
        { slug: 'invalid-keeps-status', label: 'Returns the current status for an illegal move instead of throwing' },
        { slug: 'inherited-keys', label: 'Treats inherited names such as `toString` as legal events' },
        { slug: 'unsorted-events', label: '`allowedEvents` returns events in table order, not alphabetically' },
        { slug: 'error-fields-swapped', label: 'InvalidTransition has `from` and `event` swapped' },
      ],
      hints: [
        'Write the legal moves once, as an array of `[from, event, to]`. Test each one, then use the same array to generate the forbidden ones.',
        'Loop over every status (including the terminal ones) and every event. Skip the pairs in the legal list and expect each of the rest to `toThrow(solution.InvalidTransition)`.',
        'Pin the error fields too: `toThrow({ from, event })` catches a swap. Add unknown names such as `[\'cart\', \'toString\']`.',
        'For `allowedEvents`, spell out one expected list by hand, e.g. `pending_payment` gives `[\'cancel\', \'pay\', \'payment_failed\']`, so the test does not only agree with itself.',
      ],
    },
    {
      id: 'test-unit-no-side-effects',
      title: 'Test what a function must not change',
      kind: 'mutation',
      xp: 80,
      minTests: 6,
      why: 'A function that sorts or edits its argument in place breaks code far away from it, and a test of its return value cannot see that.',
      tags: ['immutability', 'sorting', 'unit tests'],
      mutants: [
        { slug: 'sorts-in-place', label: '`prioritise` sorts the caller\'s array in place' },
        { slug: 'tags-input-tasks', label: '`prioritise` writes a `rank` field onto the caller\'s task objects' },
        { slug: 'ties-by-title', label: 'Breaks full ties alphabetically by title instead of keeping input order' },
        { slug: 'undated-first', label: 'Puts tasks with no due date before dated ones' },
        { slug: 'done-not-last', label: 'Ignores `done` when ordering' },
        { slug: 'complete-mutates', label: '`completeTask` sets `done` on the caller\'s task object' },
      ],
      hints: [
        'After each call, look at the input as well as the result. `structuredClone(tasks)` before the call gives you something to compare against.',
        'Deep-freeze instead: `Object.freeze(tasks.map((t) => Object.freeze({ ...t })))`. In strict mode any write to it throws, so the test fails on the exact line that mutates.',
        'For ordering, let one rule decide each test: a done `high` task against an open `low` one; three `high` tasks with different due dates and one undated.',
        'Ties: three tasks with the same priority and due date and titles out of alphabetical order (`Zebra`, `Apple`, `Mango`) must come back in input order.',
      ],
    },
    {
      id: 'test-unit-invariants',
      title: 'Invariants over generated inputs',
      kind: 'mutation',
      xp: 90,
      minTests: 6,
      why: 'Examples check the cases you thought of. An invariant checked over hundreds of inputs finds the lost cent that none of your examples produced.',
      tags: ['property-based testing', 'invariants', 'money'],
      mutants: [
        { slug: 'loses-remainder', label: 'Drops the leftover cents, so the parts no longer add up to the total' },
        { slug: 'leftover-by-index', label: 'Gives the leftover cents to the first parts instead of the largest remainders' },
        { slug: 'rounds-each', label: 'Rounds each share instead of flooring and handing out the leftover' },
        { slug: 'ties-to-later', label: 'On a remainder tie, the later part gets the spare cent' },
        { slug: 'all-zero-nan', label: 'Returns NaN shares instead of throwing when every ratio is zero' },
        { slug: 'negative-total', label: 'Accepts a negative total' },
      ],
      hints: [
        'Build a set of inputs in plain loops: totals such as 0 to 1001, and ratio lists such as `[1, 1, 1]`, `[1, 2]`, `[50, 30, 20]`, `[3, 0, 7]`.',
        'Invariant one: the shares always sum to the total. Invariant two: each share is a whole number within 1 of `total * ratio / sum`.',
        'The spare-cent policy needs examples with known answers: `allocate(100, [1, 2])` is `[33, 67]`, and `allocate(100, [1, 1, 1])` is `[34, 33, 33]`.',
        'Rejections: a negative total, `10.5`, `[]` and `[0, 0]` each `toThrow(RangeError)`.',
      ],
    },
    {
      id: 'test-unit-design-quiz',
      title: 'Reviewing unit tests',
      kind: 'quiz',
      xp: 60,
      why: 'Most bad tests pass code review. Knowing what a test would catch, and what would break it for no reason, is the reviewer\'s job.',
      tags: ['test design', 'code review', 'unit tests'],
      quiz: [
        {
          q: 'A test reads `expect(vat(200)).toBe(200 * VAT_RATE)`, importing `VAT_RATE` from the module under test. What is the problem?',
          options: [
            'Nothing. Reusing the constant keeps the test in sync when the rate changes.',
            'It should use `toEqual`, because the result is a number that came from a calculation.',
            'The expected value comes from the code under test, so a wrong `VAT_RATE` (or a wrong formula that uses it the same way) still passes.',
            'Constants cannot be imported into test files.',
          ],
          answer: [2],
          explain: 'A test that derives its expected value from the implementation agrees with the implementation, whatever it does. Write the known answer: `expect(vat(200)).toBe(40)`. When the rate changes, the test should fail, and someone should decide that the new numbers are right.',
        },
        {
          q: '`formatInvoice(invoice)` is a pure function that calls `formatMoney` from the same module. How should its unit test treat `formatMoney`?',
          options: [
            'Mock it, so the test covers only `formatInvoice`.',
            'Let it run. It is pure and local, so mocking it only couples the test to how `formatInvoice` is built.',
            'Spy on it and assert it was called once per line.',
          ],
          answer: [1],
          explain: 'Mock at boundaries you do not control or cannot run quickly: the network, the clock, randomness, a paid API. Mocking a pure helper in the same module means an inlining refactor breaks the test while a real formatting bug in the helper goes unseen.',
        },
        {
          q: 'Which test name is most useful when it fails in CI?',
          options: [
            '`works`',
            '`shippingCost test 3`',
            '`calls Math.ceil once`',
            '`charges the 501–2000 g rate from 501 g`',
          ],
          answer: [3],
          explain: 'A failing test name is the first line of a bug report. It should state the behaviour and the input, so the reader knows what broke without opening the file. A name about an implementation detail (`Math.ceil`) describes something no user depends on.',
        },
        {
          q: 'Which of these belong in **one** test? Select all that apply.',
          options: [
            'Several assertions on the fields of one returned object, which describe a single outcome.',
            'Asserting both the return value and that the input was not mutated, for one call.',
            'Checking five unrelated rules of a function in sequence, each with its own setup.',
            'A loop over table rows where one failing row stops the rest from running.',
          ],
          answer: [0, 1],
          explain: '"One behaviour per test" is the rule, not "one `expect` per test". Several assertions about one call are fine. Unrelated rules in one test hide each other: when the first fails, the others never run. A table should register one `it` per row, so every row reports on its own.',
        },
        {
          q: 'A test of `isWeekendSurcharge()` passes Monday to Friday and fails every Saturday. What is the fix?',
          options: [
            'Mark it as flaky and retry it up to 3 times in CI.',
            'Skip it on weekends.',
            'Make the function take the date (or a clock) as a parameter, and test fixed dates chosen for each case.',
            'Mock `Date` globally for the whole test suite.',
          ],
          answer: [2],
          explain: 'The test depends on when it runs. Pass the date in (or inject a clock) and write one test per interesting day with a fixed date. Retries hide the problem, and a global `Date` mock leaks into unrelated tests.',
        },
        {
          q: 'A module has 100% line coverage, but a mutation-testing run shows that half its mutants survive. What does that mean?',
          options: [
            'The coverage tool is broken.',
            'The tests execute every line but many of them do not assert the results, or assert too little to tell right from wrong.',
            'Mutation testing is unreliable for pure functions.',
            'The code needs more branches so coverage can measure it properly.',
          ],
          answer: [1],
          explain: 'Coverage measures what ran, not what was checked. A test that calls a function and asserts `toBeDefined()` gets full coverage. A surviving mutant is a concrete bug your suite would ship: each one points to an assertion you are missing.',
        },
      ],
    },
    {
      id: 'test-unit-boss',
      title: 'BOSS: the checkout pricing suite',
      kind: 'mutation',
      xp: 220,
      boss: true,
      minTests: 10,
      why: 'Pricing bugs cost real money and hide on thresholds and in rule interactions. This is the suite a checkout team should have had before the free-shipping incident.',
      tags: ['boundaries', 'errors', 'money', 'immutability'],
      mutants: [
        { slug: 'threshold-before-discount', label: 'Checks free shipping against the subtotal before the discount' },
        { slug: 'threshold-exclusive', label: 'Charges shipping on a basket of exactly 5000' },
        { slug: 'min-spend-exclusive', label: 'Rejects a coupon whose minSpend is met exactly' },
        { slug: 'fixed-not-capped', label: 'A fixed coupon larger than the basket makes the total negative' },
        { slug: 'percent-floors', label: 'Rounds percent discounts down instead of to the nearest cent' },
        { slug: 'accepts-zero-qty', label: 'Accepts a line with qty 0' },
        { slug: 'writes-to-lines', label: 'Writes a `lineCents` field onto the caller\'s line objects' },
        { slug: 'empty-cart-priced', label: 'Prices an empty cart as shipping only instead of throwing EMPTY' },
      ],
      hints: [
        'Go through the brief rule by rule and ask for each: where is its threshold, and what is just past it? Write those pairs as rows in a table.',
        'Shipping: baskets of 4999, 5000 and 5001. Then one basket where the discount moves the total across the line: `[line(5500)]` with a fixed coupon of 1000 must pay `495` shipping.',
        'Coupons: 10% of 1995 is `200` (not 199); a fixed 2000 on a 1500 basket gives a discount of `1500` and a total of `495`; `minSpend: 3000` on a 3000 basket applies, on 2999 throws `MIN_SPEND`.',
        'Errors: assert the class and the code, e.g. `toThrow(solution.OrderError)` and `toThrow({ code: \'EMPTY\' })` for `[]`, and `BAD_LINE` for `qty: 0`.',
        'Side effects: `structuredClone(lines)` before the call and `expect(lines).toEqual(before)` after, or deep-freeze the cart so any write throws.',
      ],
    },
  ],
});
