import { loadChapter } from '../../load.ts';

const here = import.meta.dirname;

export default loadChapter(here, {
  id: 'sql-querying-2',
  title: "Querying II",
  summary: "LATERAL, GROUPING SETS and ROLLUP, DISTINCT ON, semi and anti joins, gap filling, percentiles.",
  lessons: [
    {
      id: 'sql-semi-anti-joins',
      title: 'Semi and anti joins: EXISTS, and why NOT IN lies',
      kind: 'sql',
      xp: 75,
      why: 'One NULL in a suppression list makes `NOT IN` return nobody; "has any" and "has none" are the two questions you ask most, and each has a classic wrong answer.',
      tags: ['exists', 'anti-join', 'nulls'],
      hints: [
        'A join returns a customer once per matching order. The question "has at least one" is `where exists (select 1 from orders o where o.customer_id = c.id and ...)`.',
        '`x not in (subquery)` is never true once the subquery yields a NULL, because `x <> NULL` is unknown. Use `not exists` for both "has no paid order" and "is not suppressed".',
        'Case-insensitive matching goes inside the subquery: `where lower(s.email) = lower(c.email)`.',
        'Statement 2 is `where c.marketing_opt_in and not exists (... o.status = \'paid\') and not exists (... suppressions ...)`, ordered by `c.id`.',
      ],
    },
    {
      id: 'sql-distinct-on',
      title: 'The latest row per group with DISTINCT ON',
      kind: 'sql',
      xp: 75,
      why: '"Latest status per shipment" is asked of every event table, and `max()` plus a join-back returns duplicates the first time two events share a timestamp.',
      tags: ['distinct on', 'greatest-n-per-group', 'ordering'],
      hints: [
        '`select distinct on (s.id) ... order by s.id, e.happened_at desc, e.id desc` keeps the first row per shipment under that ordering.',
        'Start from `shipments` and `left join shipment_events`, or shipment 5 (no events) disappears. Put `nulls last` on `happened_at desc` inside so a real event beats the null row.',
        'The `distinct on` expressions must lead the `order by`, so the output is ordered by shipment. Wrap the query in a subquery to order it differently.',
        'Outside: `select latest.* from (...) latest order by latest.happened_at desc nulls last, latest.shipment_id;`',
      ],
    },
    {
      id: 'sql-lateral-as-of',
      title: 'As-of joins with LATERAL',
      kind: 'sql',
      xp: 85,
      why: 'Exchange rates, prices and tax rules change at irregular times; "the value in effect at that moment" is an as-of join, and `LATERAL` is how Postgres says it.',
      tags: ['lateral', 'as-of join', 'money'],
      hints: [
        'You want, per order, the newest rate with `effective_at <= placed_at` for the same currency: a subquery with `order by r.effective_at desc limit 1`.',
        'Put that subquery in `FROM` with `left join lateral (...) rate on true`, so it can refer to `o` and still keep orders it finds nothing for.',
        '`cross join lateral` (or an inner `join lateral`) drops the USD order placed before any USD rate. The GBP orders need no rate: handle them with a `case`.',
        '`amount_cents * rate_micros` overflows `int`. Write `round(o.amount_cents::numeric * rate.rate_micros / 1000000)::int`.',
      ],
    },
    {
      id: 'sql-rollup-subtotals',
      title: 'Subtotals and grand totals with ROLLUP',
      kind: 'sql',
      xp: 85,
      why: 'Finance exports always want subtotals; `ROLLUP` does it in one pass, and `grouping()` is the only honest way to tell a subtotal row from a real NULL.',
      tags: ['rollup', 'grouping sets', 'reporting'],
      hints: [
        '`group by rollup (s.region, s.product)` gives detail rows, a subtotal per region and one grand total.',
        'A subtotal row has `product` NULL, and so does nothing in this data; but a sale with no region has `region` NULL just like the grand total. `grouping(s.region)` is 1 only on the grand total.',
        'Label with `case when grouping(s.region) = 1 then \'All regions\' else coalesce(s.region, \'unknown\') end`, and the same shape for product.',
        'Order by the grouping flags and the raw columns: `order by grouping(s.region), coalesce(s.region, \'unknown\'), grouping(s.product), s.product`.',
      ],
    },
    {
      id: 'sql-percentiles',
      title: 'Latency percentiles, not averages',
      kind: 'sql',
      xp: 80,
      why: 'An average hides exactly the slow requests users complain about; p50 and p95 are how latency is reported and alerted on.',
      tags: ['percentiles', 'ordered-set aggregates', 'observability'],
      hints: [
        'Ordered-set aggregates: `percentile_cont(0.5) within group (order by r.duration_ms)` for the median.',
        '`percentile_disc(0.95)` returns an observed value; `percentile_cont` interpolates. Both return double precision, and `round(x, 1)` needs `numeric`: cast the aggregate first.',
        'Only endpoints with at least 5 requests: that is a `having count(*) >= 5`, not a `where`.',
        '`count(*) filter (where r.status >= 500)` is an integer; `* 1.0 / count(*)` makes it a fraction, then `round(..., 3)`.',
      ],
    },
    {
      id: 'sql-relational-division',
      title: '"Completed every required training": relational division',
      kind: 'sql',
      xp: 90,
      why: 'Questions about "all" (every required skill, every mandatory field, every approval) have no keyword in SQL, and the counting version miscounts retakes and extras.',
      tags: ['relational division', 'exists', 'reporting'],
      hints: [
        'Start from `employees`, so the designer with no requirements still appears. Join requirements with a left join or a lateral subquery.',
        'Per employee, count the required trainings, and separately count how many of *those* have at least one completion.',
        'Counting completions directly counts retakes twice and optional courses at all. `count(distinct rr.training_id) filter (where exists (select 1 from completions c where c.employee_id = e.id and c.training_id = rr.training_id))` counts each required one once.',
        '`missing` is required minus done; `compliant` is `missing = 0`. Order by `compliant, missing desc, name` (false sorts before true).',
      ],
    },
    {
      id: 'sql-gap-fill',
      title: 'Gap filling and carrying the last value forward',
      kind: 'sql',
      xp: 90,
      why: 'Charts need a point for every day, and data only exists where something happened; starting from the data instead of the calendar draws the wrong line.',
      tags: ['generate_series', 'lateral', 'time series'],
      hints: [
        'Build the grid first: `products p cross join generate_series(\'2024-03-01\'::date, \'2024-03-07\'::date, interval \'1 day\') as d`.',
        'For each cell you want the most recent count on or before that day, however long before the range. Do not filter counts to the range.',
        '`left join lateral (select sc.quantity, sc.counted_on from stock_counts sc where sc.product_id = p.id and sc.counted_on <= d order by sc.counted_on desc limit 1) latest on true`.',
        '`is_filled` must be true when there is no count at all: `latest.counted_on is distinct from d::date` handles the null case. Format the day with `to_char(d, \'YYYY-MM-DD\')`.',
      ],
    },
    {
      id: 'sql-islands-streaks',
      title: 'Streaks: gaps and islands',
      kind: 'sql',
      xp: 95,
      why: 'Streaks, uptime runs and consecutive-month subscriptions are all "gaps and islands", and the row-number trick solves them in one pass instead of a loop over millions of rows.',
      tags: ['window functions', 'gaps and islands', 'dates'],
      hints: [
        'First reduce to one row per user per UTC day: `select distinct user_id, (happened_at at time zone \'UTC\')::date as day from activity`.',
        'Number each user\'s days: `row_number() over (partition by user_id order by day)`.',
        'Within a run of consecutive days, `day - row_number` is the same date (a `date` minus an `int` is a date). That value identifies the island.',
        'Group by `user_id` and the island: `min(day)`, `max(day)` and `count(*)::int`, then `order by name, min(day)`.',
      ],
    },
    {
      id: 'sql-sla-report-boss',
      title: 'Boss: the weekly SLA report in one query',
      kind: 'sql',
      xp: 240,
      boss: true,
      why: 'Operational reports are where the chapter\'s techniques meet: latest-per-group, first-per-group, a fixed "now", percentiles, and a total row that is not a sum of the rows above it.',
      tags: ['reporting', 'lateral', 'rollup', 'percentiles'],
      hints: [
        'Build a per-ticket CTE first: first agent reply (`min(happened_at)` over `agent_reply` events), deadline (`created_at + first_response_minutes * interval \'1 minute\'`) and current status.',
        'The current status is the latest `status_change` by `happened_at desc, id desc`: a `left join lateral (... limit 1)` with `coalesce(status, \'open\')`.',
        'Breached is `coalesce(first_response_at, \'2024-04-01 12:00:00+00\'::timestamptz) > deadline`. A strict `>` makes a reply exactly on the deadline on time.',
        'Aggregate from `teams` left joined to the per-ticket rows, so Onboarding appears. Count `c.id` (not `*`), and use `filter` for the conditional counts.',
        '`group by rollup (tm.name)` adds the total row; label it with `grouping(tm.name)` and `order by grouping(tm.name), tm.name`. `percentile_cont` skips NULLs, so unanswered tickets drop out of the median by themselves.',
      ],
    },
  ],
});
