import { loadChapter } from '../../load.ts';

const here = import.meta.dirname;

export default loadChapter(here, {
  id: 'design-domain',
  title: "Domain Modelling",
  summary: "Value objects, invariants in aggregates, a Money type, event-sourcing-lite, specifications.",
  lessons: [
    {
      id: 'design-value-objects',
      title: 'Value objects: valid, immutable, equal by value',
      kind: 'js',
      xp: 75,
      why: 'Emails and date ranges passed around as raw strings get validated in some places, compared wrongly in others and mutated by accident; a value object closes all three holes at once.',
      tags: ['value-objects', 'domain-modelling', 'immutability', 'dates'],
      hints: [
        'Use a class with private fields (`#value`) set in the constructor, getters to read them, and a `static parse` / `static of` factory that validates before calling `new`.',
        'For `equals`, check the type first: `other instanceof EmailAddress && other.value === this.value`. That is what makes a plain string or look-alike object unequal.',
        'Parse dates with `/^(\\d{4})-(\\d{2})-(\\d{2})$/`, build `Date.UTC(y, m - 1, d)`, then confirm `getUTCFullYear()`, `getUTCMonth()` and `getUTCDate()` match what you parsed.',
        '`nights` is `(utc(end) - utc(start)) / 86_400_000`. `contains(date)` is `date >= start && date < end`; `overlaps(o)` is `start < o.end && o.start < end` — all plain string comparisons.',
      ],
    },
    {
      id: 'design-money',
      title: 'Money: integer minor units and honest rounding',
      kind: 'js',
      xp: 85,
      why: 'Float prices, mixed currencies and `Math.round` on refunds produce penny errors that finance teams spend days reconciling; a Money type prevents them by construction.',
      tags: ['money', 'value-objects', 'rounding', 'domain-modelling'],
      hints: [
        'Same shape as the previous lesson: private `#amountMinor` and `#currency`, getters, `Object.freeze(this)`, and a validating `static of`. Normalise `-0` in the constructor with `amount === 0 ? 0 : amount`.',
        'A private `#same(other)` that throws `CurrencyMismatchError` keeps `add`, `subtract` and `compare` one line each.',
        'For `parse`, match `/^(-)?(\\d+)(?:\\.(\\d+))?$/`, reject a fraction longer than `CURRENCIES[currency]`, then `Number(whole + fraction.padEnd(exponent, \'0\'))`.',
        'Half away from zero with integers: `q = Math.trunc(n / d)`, `r = n - q * d`, and if `Math.abs(r) * 2 >= d` add `Math.sign(n)` to `q`. Use it with `n = amount * basisPoints`, `d = 10_000`.',
        'For `toDecimalString`, pad `String(Math.abs(amount))` to `exponent + 1` digits, split off the last `exponent` digits as the fraction, and add the `-` back in front.',
      ],
    },
    {
      id: 'design-money-allocation',
      title: 'Allocating money without losing a penny',
      kind: 'js',
      xp: 85,
      why: 'Splitting bills, spreading discounts across lines and pro-rating refunds all have to add up exactly; rounding each part independently never does.',
      tags: ['money', 'allocation', 'rounding', 'invariants'],
      hints: [
        'For each ratio compute `numerator = total * ratio`, then `base = Math.floor(numerator / ratioSum)` and `remainder = numerator % ratioSum` — both exact integers.',
        'The leftover is `total - sum(bases)`. It is always smaller than the number of parts, so each part gets at most one extra unit.',
        'Sort a copy of the parts by `remainder` descending, then by `index` ascending, and add 1 to the first `leftover` of them. Return the bases in the original order.',
        'For a negative total, allocate `Math.abs(total)` and multiply each part by -1 at the end, turning `-0` back into `0`.',
        '`distributeDiscount` is `allocate(discount, lines.map((l) => l.amountMinor))` plus the range checks and a special case for a zero discount (all-zero ratios would otherwise throw).',
      ],
    },
    {
      id: 'design-order-aggregate',
      title: 'An aggregate that enforces its own invariants',
      kind: 'js',
      xp: 90,
      why: 'When five services edit an order object directly, its rules are enforced nowhere; an aggregate root makes every change go through one place that checks them.',
      tags: ['aggregates', 'invariants', 'domain-modelling', 'encapsulation'],
      hints: [
        'Keep lines in a private `Map` from SKU to line object (a `Map` iterates in insertion order), plus private `#status`, `#coupon` and `#placedAt`.',
        'Write every command as "all checks, then all changes". For a merge: check the price, check `existing.quantity + quantity <= MAX_QUANTITY`, and only then add.',
        'Never store a discount. `totals()` computes the subtotal from the lines, the raw discount from the coupon, and `Math.min(raw, subtotal)`.',
        'After `changeQuantity` changes the lines, drop the coupon if `subtotal < coupon.minSubtotalMinor`.',
        '`snapshot()` builds fresh objects: `[...lines.values()].map((l) => ({ ...l }))`, `coupon ? { ...coupon } : null`, then spread `this.totals()` in.',
      ],
    },
    {
      id: 'design-event-sourcing',
      title: 'Event-sourcing lite: a gift card that remembers',
      kind: 'js',
      xp: 100,
      why: 'Balances updated in place cannot explain themselves and can be double-spent; storing facts plus an expected version fixes both, and the decide/evolve split is useful far beyond event sourcing.',
      tags: ['event-sourcing', 'concurrency', 'domain-modelling', 'pure-functions'],
      hints: [
        'State after `CardIssued` can be `{ cardId, balanceMinor, frozen: false, orders: {} }`, where `orders[orderId]` is `{ redeemedMinor, refundedMinor }`. `evolve` is a `switch` on `event.type` returning spread copies.',
        '`rehydrate(events)` is `events.map(upcast).reduce(evolve, null)`, where `upcast` renames `amount` to `amountMinor` when `amountMinor` is missing.',
        'In `decide`, handle `Issue` first (the only command allowed on `null`), then throw `NOT_FOUND` for `null`, then `switch` on the command type, checking the rules in the order of the table.',
        'The store keeps a `Map` of arrays. `append` compares `current.length` with `expectedVersion` before writing, and both methods copy (`structuredClone`) on the way in and out.',
        '`handle` is a loop: `for (let attempt = 1; ; attempt++)` → load → rehydrate → decide → `try { append } catch (e) { if (e instanceof ConcurrencyError && attempt < maxAttempts) continue; throw e; }`.',
      ],
    },
    {
      id: 'design-specifications',
      title: 'Specifications: business rules that explain themselves',
      kind: 'js',
      xp: 80,
      why: 'Eligibility rules get copied between checkout, banners and admin tools, and nobody can say why a customer failed one; composable, named specifications fix both.',
      tags: ['specification', 'business-rules', 'composition', 'domain-modelling'],
      hints: [
        'Represent every specification by one function `explain(candidate) → { satisfied, failed }` plus a `name`. `isSatisfiedBy` is `explain(c).satisfied`; `select` filters with it.',
        'A leaf: `const satisfied = Boolean(predicate(c)); return { satisfied, failed: satisfied ? [] : [name] }`.',
        '`all(...specs)`: explain **every** child (`specs.map((s) => s.explain(c))`), then `satisfied = results.every(...)` and `failed = satisfied ? [] : results.flatMap((r) => r.failed)`. `any` is the same with `some`.',
        '`a.and(b)` can simply be `all(a, b)`, and `a.or(b)` is `any(a, b)`. Names: `specs.length === 1 ? specs[0].name : \'(\' + names.join(\' and \') + \')\'`.',
        '`freeDelivery = livesIn(\'GB\').and(isMember.or(hasOrderedAtLeast(3))).and(isFlagged.not())`.',
      ],
    },
    {
      id: 'design-typed-money',
      title: 'Currencies the compiler keeps apart',
      kind: 'typecheck',
      xp: 85,
      why: 'A currency mismatch caught at runtime is a failed refund job; the same check in the type system is a red squiggle in the pull request.',
      tags: ['typescript', 'money', 'generics', 'tuples'],
      hints: [
        'Give `Money` and `Rate` type parameters constrained to `Currency`, and use them for the `currency`, `from` and `to` fields. Mark every field `readonly`.',
        '`money<C extends Currency>(amountMinor: number, currency: C): Money<C>` infers the literal from the argument.',
        'For `add`, `sum` and `convert`, only one argument should decide the currency: `add<C extends Currency>(a: Money<C>, b: Money<NoInfer<C>>)`, `sum<C>(currency: C, items: readonly Money<NoInfer<C>>[])`, `convert<F, T>(m: Money<F>, r: Rate<NoInfer<F>, T>)`.',
        '`NonEmptyArray<T> = readonly [T, ...T[]]`.',
        '`allocate<C extends Currency, R extends NonEmptyArray<number>>(m: Money<C>, ratios: R): { -readonly [K in keyof R]: Money<C> }`, and cast the final `map(...)` to that type.',
      ],
    },
    {
      id: 'design-domain-judgement',
      title: 'Modelling calls: values, entities and boundaries',
      kind: 'quiz',
      xp: 60,
      why: 'Choosing what is a value, what owns a rule and where an aggregate ends decides whether a domain model protects its data or just describes it.',
      tags: ['domain-modelling', 'aggregates', 'judgement'],
      quiz: [
        {
          q: 'Which of these are best modelled as **value objects**? (Select all that apply.)',
          options: [
            'The shipping address copied onto an order.',
            'A customer account.',
            'An amount of money with its currency.',
            'A support ticket that moves through statuses.',
            'A date range for a hotel stay.',
          ],
          answer: [0, 2, 4],
          explain: 'A value object is defined entirely by its attributes: two £5 amounts, or two identical addresses, are interchangeable, so they are immutable and compared by value. An entity has an identity that persists while its attributes change: a customer who changes their email is the same customer, and a ticket is the same ticket as it moves from open to closed. The address on an order is a value — a snapshot of where it was sent — even if the customer\'s address book entry is an entity.',
        },
        {
          q: 'Where should the rule "an order may contain at most 10 of any item" be enforced?',
          options: [
            'In the order aggregate itself, in the method that adds or changes a line.',
            'In the React form, so users get immediate feedback.',
            'In each API handler that edits an order.',
            'In a nightly job that finds and fixes offending orders.',
          ],
          answer: [0],
          explain: 'An invariant belongs to the object that owns the data, so it holds whichever path changes it: the API, the admin tool, a script, next year\'s mobile backend. The form can *also* check for a better experience, but that is a courtesy, not the rule. Copying the check into every handler means the next handler forgets; a nightly fix-up means the invalid order already shipped.',
        },
        {
          q: 'A customer can have tens of thousands of orders. A colleague proposes a `Customer` aggregate that contains its `orders` array, so "a customer may have at most 3 unpaid orders" can be checked inside it. What is the better design?',
          options: [
            'Go ahead: loading all orders is fine if you add an index.',
            'Keep `Customer` and `Order` as separate aggregates that refer to each other by id; enforce the unpaid-orders rule when placing an order with a query (or a counter on the customer), accepting it is checked at that boundary.',
            'Make the orders array lazy-loaded so the aggregate stays small in memory.',
            'Put every change to either object in one serialisable database transaction.',
          ],
          answer: [1],
          explain: 'An aggregate is a consistency boundary, and it should be small: everything inside it is loaded and saved together, and concurrent edits to any part conflict. A customer-plus-all-orders aggregate makes every order change contend with every other. Reference other aggregates by id, and handle rules that span them deliberately — a check at the moment an order is placed, a counter the customer aggregate owns, or eventual consistency with a compensating action. Lazy loading hides the cost; it does not remove the contention.',
        },
        {
          q: 'Which of these are acceptable ways to **store** a price? (Select all that apply.)',
          options: [
            'A `double precision` column in pounds.',
            'An integer column of minor units, plus a currency code column.',
            'A `numeric(12, 2)` column, plus a currency code column.',
            'A text column holding the formatted string, like `£12.34`.',
          ],
          answer: [1, 2],
          explain: 'Both integer minor units and a fixed-point decimal are exact, and both need the currency stored next to them — an amount without a currency is not money. Integers are simplest to move through JSON and JavaScript without surprises (`numeric` usually arrives as a string). Floating point cannot represent most decimal fractions, so sums drift. A formatted string mixes display with data: it cannot be summed, sorted or re-formatted for another locale.',
        },
        {
          q: 'A bug recorded three days of `CardRedeemed` events with amounts ten times too large. The events are already in the store and projections have used them. What is the right fix?',
          options: [
            'Run an `UPDATE` on the events table to correct the amounts, then rebuild the projections.',
            'Delete the bad events and ask the affected customers to repeat their purchases.',
            'Fix the bug, then append correcting events (for example `RedemptionCorrected` with the difference) so the history shows both the mistake and the correction, and let projections apply them.',
            'Add a special case to `evolve` that divides amounts by ten for events between those dates.',
          ],
          answer: [2],
          explain: 'Events are facts about what the system did, and other things (projections, emails, integrations, auditors) may already have acted on them. Rewriting history makes the store disagree with everything downstream and destroys the evidence of the incident. A correcting event is the accounting approach — you never erase a ledger line, you post an adjustment — and it flows through every projection the normal way. A date-based special case in `evolve` works until someone forgets why it is there.',
        },
        {
          q: 'Every class in the domain folder is a bag of getters and setters, and the rules live in services: `OrderService.applyDiscount(order)` sets `order.discount`, `CheckoutService` sets `order.status`. What is the main risk of this "anemic" model?',
          options: [
            'Getters and setters are slower than methods.',
            'Nothing stops code from setting fields directly, so each rule is enforced only on the paths that remember to go through the right service.',
            'The objects cannot be serialised to JSON.',
            'It uses too many classes.',
          ],
          answer: [1],
          explain: 'When the data can be changed without its rules, the rules are optional. Sooner or later a new service, script or admin endpoint sets `order.status = \'shipped\'` directly and skips the check. Putting behaviour next to the data (`order.applyCoupon(…)`, `order.place()`) means the only way to change the state is the way that checks it. Services still have a job — orchestrating repositories, payments and emails — but not owning the order\'s invariants.',
        },
      ],
    },
    {
      id: 'design-refunds-boss',
      title: 'BOSS: partial refunds that always add up',
      kind: 'js',
      xp: 240,
      boss: true,
      why: 'Refunds against discounted, multi-line orders are where money quietly leaks; pricing every unit once and recording refunds as facts is how real commerce systems stay reconcilable.',
      tags: ['money', 'allocation', 'event-sourcing', 'aggregates'],
      hints: [
        'Split the work: `decide` validates and emits events that record only what was asked; `evolve` on `OrderPlaced` does the pricing and keeps it in the state; refunds read from that state.',
        'Pricing in `evolve`: `gross = lines.map(l => l.unitPriceMinor * l.quantity)`, `discounts = allocate(discountMinor, gross)`, then per line `net = gross[i] - discounts[i]` and `unitAmounts = allocate(net, Array(quantity).fill(1))`.',
        'A refund of `k` units takes `unitAmounts.slice(refunded, refunded + k)` and sums it. Track `refundedQuantity` per line and the items of each `refundId` so a retry can be recognised.',
        'For shipping, count the units left **after** this request: for each line, `quantity - refundedQuantity - (quantity in this request)`. If that is 0 across all lines and shipping has not been refunded, add it.',
        'Keep `evolve` pure with spread copies: `lines: state.lines.map((l) => l.sku in thisRefund ? { ...l, refundedQuantity: … } : l)`, and a new `refunds` object.',
      ],
    },
  ],
});
