import { loadChapter } from '../../load.ts';

const here = import.meta.dirname;

export default loadChapter(here, {
  id: 'ts-safety-patterns',
  title: "Type-Safety Patterns",
  summary: "Exhaustiveness, assertion functions, readonly and immutability, nominal types, safe records.",
  lessons: [
    {
      id: 'ts-exhaustive-match',
      title: 'Exhaustive matching as an expression',
      kind: 'typecheck',
      xp: 90,
      why: 'A `switch` with a fallback routes every new variant to the default forever; an exhaustive `match` makes each call site that forgot it a compile error.',
      tags: ['discriminated unions', 'exhaustiveness', 'generics', 'type predicates'],
      hints: [
        '`Handlers<T, R>` is a mapped type over the kinds: `{ [K in T[\'kind\']]: (value: Extract<T, { kind: K }>) => R }`.',
        'For `match`, make the handlers object its own type parameter so the result can be computed from it: `match<T extends Tagged, H extends Handlers<T, unknown>>(value: T, handlers: H): ReturnType<H[keyof H]>`.',
        'To reject extra keys, intersect the parameter with a type that maps every non-kind key to `never`: `handlers: H & Record<Exclude<keyof H, T[\'kind\']>, never>`.',
        '`matchOr<T extends Tagged, K extends T[\'kind\'], R>(value, handlers: { [P in K]: … }, otherwise: (value: Exclude<T, { kind: K }>) => R)`: `K` is inferred from the handler keys. Check `Object.hasOwn(handlers, value.kind)` at runtime.',
        '`isKind` returns a generic arrow with a predicate: `<T extends Tagged>(value: T): value is Extract<T, { kind: K }> => value.kind === kind`.',
      ],
    },
    {
      id: 'ts-assertion-functions',
      title: 'Assertion functions',
      kind: 'typecheck',
      xp: 80,
      why: 'Invariant checks and request validation should narrow what comes after them; without an assertion signature every caller re-checks or reaches for `!`.',
      tags: ['assertion functions', 'narrowing', 'validation'],
      hints: [
        'Change the return types: `assert(condition: unknown, message: string): asserts condition` and `assertDefined<T>(value: T, name: string): asserts value is NonNullable<T>`.',
        'Methods on an object literal only work as assertions if the object\'s type is written down. Declare an `interface Ensure { string(value: unknown, name: string): asserts value is string; … }` and write `export const ensure: Ensure = { … }`.',
        'For `oneOf`, give the method a `const` type parameter so the literals survive: `oneOf<const T extends readonly string[]>(value: unknown, allowed: T, name: string): asserts value is T[number]`.',
        '`Publishable = Draft & { title: string; publishAt: Date }`, and the method is `assertPublishable(): asserts this is Publishable`.',
      ],
    },
    {
      id: 'ts-non-empty',
      title: 'Non-empty arrays',
      kind: 'typecheck',
      xp: 80,
      why: '`reduce` without a seed, `Math.max()` of nothing and `lines[0].currency` all fail on an empty list; a non-empty type moves that check to the one place the data arrives.',
      tags: ['tuples', 'type predicates', 'generics'],
      hints: [
        'A variadic tuple with one required element: `type NonEmptyArray<T> = [T, ...T[]]`, and the same with `readonly` in front.',
        'The guard needs an explicit predicate: `isNonEmpty<T>(items: readonly T[]): items is ReadonlyNonEmptyArray<T>`. Narrowing a mutable `T[]` with it keeps it mutable.',
        'Take `ReadonlyNonEmptyArray<T>` in `first`, `last` and `maxBy`; then `items[0]` is a `T`, and `maxBy` can start from it.',
        '`mapNonEmpty`: destructure `const [head, ...tail] = items` and return `[fn(head, 0), ...tail.map((item, i) => fn(item, i + 1))]`. In `groupByKey`, a new group is created as `[item]`, which is already a `NonEmptyArray<T>`.',
      ],
    },
    {
      id: 'ts-exclusive-options',
      title: 'Exactly one, at least one',
      kind: 'typecheck',
      xp: 90,
      why: '"By id or by email", "one payment method" and "email or phone" are rules a plain union does not enforce; `?: never` makes the illegal combinations unrepresentable.',
      tags: ['unions', 'mapped types', 'never', 'api design'],
      hints: [
        'Start with a helper for "the keys only B has, forbidden": `type Without<A, B> = { [K in Exclude<keyof B, keyof A>]?: never }`. Then `XOR<A, B> = (A & Without<A, B>) | (B & Without<B, A>)`.',
        'For "one alternative per key", map over `K` and index the result with `[K]`: `{ [P in K]-?: … }[K]`. Each alternative makes key `P` required with `Required<Pick<T, P>>`.',
        '`RequireAtLeastOne<T, K>` = `Omit<T, K> & { [P in K]-?: Required<Pick<T, P>> & Partial<Pick<T, Exclude<K, P>>> }[K]`.',
        '`RequireExactlyOne` is the same, except the other keys are forbidden instead of optional: `{ [Q in Exclude<K, P>]?: never }`.',
      ],
    },
    {
      id: 'ts-immutable-types',
      title: 'Deeply immutable types',
      kind: 'typecheck',
      xp: 85,
      why: 'State that is mutated in place is behind stale renders, corrupted caches and "someone changed the config" bugs; `Readonly<T>` stops only the first level.',
      tags: ['immutability', 'conditional types', 'mapped types', 'readonly'],
      hints: [
        'Write `Immutable<T>` as a chain of conditional types, most specific first: functions, `Date`, maps, sets, arrays, other objects, then everything else.',
        'Maps and sets: `T extends ReadonlyMap<infer K, infer V> ? ReadonlyMap<Immutable<K>, Immutable<V>>`, and the same with `ReadonlySet<infer U>`. Test for them before the generic object case, or you will map over their methods.',
        'Arrays and tuples: `T extends readonly unknown[] ? { readonly [I in keyof T]: Immutable<T[I]> }`. A mapped type over an array or tuple type parameter keeps it an array or tuple.',
        '`deepFreeze`: if it is a non-null object, `Object.freeze` it and recurse over `Object.values`, then `return value as Immutable<T>`. `addLine` returns `{ ...cart, lines: [...cart.lines, line] }`.',
      ],
    },
    {
      id: 'ts-defensive-copies',
      title: 'Defensive copies',
      kind: 'ts',
      xp: 85,
      why: '`readonly Date[]` does not stop anyone calling `setHours`; value objects that share their arrays and Dates with callers change when the callers do.',
      tags: ['immutability', 'classes', 'dates', 'encapsulation'],
      hints: [
        'Keep the state in private `#` fields, and store the slots as numbers (`date.getTime()`), which cannot be mutated.',
        'In `create`, loop over the iterable, reject `NaN` times with a `RangeError`, then dedupe and sort: `[...new Set(times)].sort((a, b) => a - b)`.',
        'The `slots` getter builds new dates every time: `Object.freeze(this.#times.map((t) => new Date(t)))`. `next` also returns `new Date(t)`.',
        '`withSlot` can go back through `Schedule.create` with the old slots plus the new one; `withoutSlot` filters by `getTime()`. Give `name` a getter and no setter.',
      ],
    },
    {
      id: 'ts-safe-lookups',
      title: 'Objects are not dictionaries',
      kind: 'ts',
      xp: 85,
      why: 'Inherited keys like `toString` and the `__proto__` setter turn plain-object lookups, counters and path readers into bugs and security holes that `Record<string, T>` hides.',
      tags: ['records', 'maps', 'security', 'prototypes'],
      hints: [
        'Every fix in this lesson is one of two moves: check `Object.hasOwn(obj, key)` instead of `key in obj` or a bare `obj[key]`, or use a `Map`.',
        '`lookup`: `return Object.hasOwn(table, key) ? table[key] : undefined`.',
        '`countBy`: count in a `Map<string, number>`, then `return Object.fromEntries(counts)`. `fromEntries` defines `__proto__` as an ordinary own property; assigning `obj[\'__proto__\'] = n` would not.',
        '`getPath`: split on `.`, and for each segment return `undefined` unless the current value is a non-null object that has that segment as an own property.',
      ],
    },
    {
      id: 'ts-safety-quiz',
      title: 'Escape hatches and what they cost',
      kind: 'quiz',
      xp: 70,
      why: '`!`, `as`, `any` and a friendly `default` are each sometimes right; knowing exactly which check each one switches off is what keeps them rare.',
      tags: ['exhaustiveness', 'assertions', 'readonly', 'any'],
      quiz: [
        {
          q: '`Plan` gains a third variant, `{ kind: \'team\' }`. Which of these functions become compile errors? Select all that apply.\n\n```ts\n// (1)\nfunction a(p: Plan): number { switch (p.kind) { case \'free\': return 0; case \'pro\': return p.seats; default: return assertNever(p); } }\n// (2)\nfunction b(p: Plan): number { switch (p.kind) { case \'free\': return 0; case \'pro\': return p.seats; } }\n// (3)\nfunction c(p: Plan): number { switch (p.kind) { case \'free\': return 0; case \'pro\': return p.seats; default: throw new Error(\'unreachable\'); } }\n// (4)\nfunction d(p: Plan): number { switch (p.kind) { case \'free\': return 0; case \'pro\': return p.seats; default: return 0; } }\n```',
          options: ['(1)', '(2)', '(3)', '(4)'],
          answer: [0, 1],
          explain: '(1) passes `p` to a parameter of type `never`; once `team` exists, `p` is `{ kind: \'team\' }` there and the call fails. (2) has no default, and its declared return type is `number`: while every case returns, the end of the function is unreachable, but with a new variant control can fall off the end and TypeScript reports TS2366 ("Function lacks ending return statement"). (3) and (4) compile — a `throw` or a fallback value in `default` accepts anything, so the new variant fails at runtime or, worse, quietly gets the fallback. Only write a `default` when "everything else" really is a policy.',
        },
        {
          q: '`interface Config { port: number; host: string }`. Which of these report that `host` is missing? Select all that apply.',
          options: [
            '`const a: Config = { port: 80 };`',
            '`const b = { port: 80 } as Config;`',
            '`const c = { port: 80 } satisfies Config;`',
            '`const d = <Config>{ port: 80 };`',
          ],
          answer: [0, 2],
          explain: 'An annotation and `satisfies` both check the literal against `Config`, including missing and excess properties; `satisfies` additionally keeps the literal\'s own, narrower type. A type assertion (`as Config` or the older `<Config>` prefix) only requires the types to be *comparable* — one assignable to the other in either direction — and `{ port: number }` is a supertype of `Config`, so the assertion succeeds and `b.host` is `undefined` at runtime. Use `as` for facts the compiler cannot know, never to construct values.',
        },
        {
          q: 'What happens here?\n\n```ts\nfunction resetName(u: User) { u.name = \'\'; }\nconst current: Readonly<User> = loadUser();\nresetName(current);\n```',
          options: [
            'A compile error: a `Readonly<User>` is not assignable to a `User`',
            'A runtime `TypeError`, because `Readonly` freezes the object',
            'It compiles and mutates `current`',
            'It compiles, and `resetName` receives a copy',
          ],
          answer: [2],
          explain: '`readonly` properties are assignable to mutable ones — TypeScript deliberately does not treat them as different types, for compatibility — so passing a `Readonly<User>` where a `User` is expected is allowed, and the function mutates the caller\'s object. `Readonly` is also purely compile-time: nothing is frozen or copied. Mark parameters that do not mutate as `Readonly<…>`/`readonly T[]` yourself (so they accept both), and copy defensively at trust boundaries.',
        },
        {
          q: '```ts\nconst config = Object.freeze({ db: { url: \'postgres://prod\' }, port: 5432 });\nconfig.db.url = \'postgres://test\';\n```\n\nWhat happens?',
          options: [
            'A compile error, and a runtime `TypeError` in strict mode',
            'It compiles, and the assignment succeeds at runtime',
            'A compile error, but the assignment would succeed at runtime',
            'It compiles, and the assignment is silently ignored at runtime',
          ],
          answer: [1],
          explain: '`Object.freeze` is shallow at runtime and its type is shallow to match: `Readonly<{ db: { url: string }; port: number }>` makes `config.db` read-only, not `config.db.url`. Both the checker and the engine allow the nested write, and the "frozen" production config now points at the test database. Deep immutability needs a recursive freeze and a recursive type, as in the `Immutable<T>` lesson.',
        },
        {
          q: 'Which is the best way to handle this?\n\n```ts\nconst admin = users.find((u) => u.role === \'admin\')!;\nsendReport(admin.email);\n```',
          options: [
            'Fine as is: `!` documents that there is always an admin',
            'Replace `!` with `as User`, which is more explicit',
            'Check the result: `if (!admin) throw new Error(\'no admin user configured\')` (or an `assertDefined` helper), then use it',
            'Use optional chaining: `sendReport(admin?.email)`',
          ],
          answer: [2],
          explain: '`!` removes `undefined` from the type without checking anything, so the day there is no admin you get "Cannot read properties of undefined (reading \'email\')" somewhere far from the cause. `as User` is the same unchecked claim. Optional chaining passes `undefined` into `sendReport`, moving the failure further away. An explicit check (or an assertion function) narrows just as well and fails where the assumption breaks, with a message that names it.',
        },
        {
          q: 'A legacy helper returns `any`. What is the most effective way to stop that `any` spreading through your module?\n\n```ts\ndeclare function legacyParse(text: string): any;\n```',
          options: [
            'Annotate every variable that receives its result, for example `const order: Order = legacyParse(text)`',
            'Wrap it once, `function parseOrder(text: string): unknown { return legacyParse(text); }`, and validate the `unknown` into an `Order` in that wrapper',
            'Turn on `noImplicitAny`',
            'Cast at each call site: `legacyParse(text) as Order`',
          ],
          answer: [1],
          explain: '`any` is contagious: property reads, calls and arithmetic on it produce more `any`, and it is assignable to every type, so annotations at call sites (1) and casts (4) check nothing and have to be repeated everywhere. `noImplicitAny` only flags *implicit* `any`; an explicit `any` return type is untouched. Converting it to `unknown` once, at a single wrapper, forces the one place that knows the data to validate it, and the rest of the codebase gets a real type.',
        },
      ],
    },
    {
      id: 'ts-state-machine',
      title: 'BOSS: a type-safe state machine',
      kind: 'typecheck',
      xp: 240,
      boss: true,
      why: 'Checkout flows, uploads and order lifecycles are state machines; deriving every state, event and transition from one config literal turns typos and illegal transitions into compile errors.',
      tags: ['state machines', 'mapped types', 'inference', 'type predicates'],
      hints: [
        'Start with the unions: `StateName<States> = keyof States & string` and `EventsIn<States, S> = keyof States[S][\'on\'] & string`.',
        '`keyof` a union of `on` maps gives only the *shared* events. For all of them, map each state to its events and index: `{ [S in StateName<States>]: EventsIn<States, S> }[StateName<States>]`. `FinalState` uses the same shape with `[EventsIn<States, S>] extends [never] ? S : never`.',
        '`transition<S extends StateName<States>, E extends EventsIn<States, S>>(state: S, event: E): States[S][\'on\'][E]`. The literal targets survive because of the validation step below; the body needs one `as`.',
        'Validate targets by intersecting the parameter with a mapped version of itself: `states: States & { [S in keyof States]: { readonly on: Readonly<Record<string, keyof States & string>> } }`, and type `initial` as `StateName<States>`.',
        'Use `Object.hasOwn(states[state].on, event)` in `can` and `send`. `isFinal(state): state is FinalState<States>` checks for no own keys. In `start()`, expose `state` through a getter only, and declare `Service.state` as `readonly`.',
      ],
    },
  ],
});
