import { loadChapter } from '../../load.ts';

const here = import.meta.dirname;

export default loadChapter(here, {
  id: 'craft-communication',
  title: "Communication",
  summary: "Design docs, ADRs, estimation, postmortems, working with product, disagreeing well.",
  lessons: [
    {
      id: 'craft-design-docs',
      title: 'Design docs that save weeks',
      kind: 'quiz',
      xp: 70,
      why: 'A design doc moves the expensive arguments to before the code exists; mid-level engineers are expected to write them for anything hard to reverse.',
      tags: ['design docs', 'ADRs', 'planning'],
      quiz: [
        {
          q: 'Which pieces of work deserve a design doc before coding? (Select all that apply.)',
          options: [
            'Moving order confirmation emails out of the checkout request, onto a queue and a worker',
            'Adding a nullable column and showing it on an existing admin page',
            'Choosing between Postgres full-text search and a hosted search service for product search',
            'Fixing a crash that has a clear reproduction and a one-line cause',
            'Changing a public API response that two mobile apps depend on',
          ],
          answer: [0, 2, 4],
          explain: 'Write a doc when a change is **hard to reverse**, **crosses team boundaries**, or has **real alternatives** worth comparing: a new async architecture, a build-versus-buy choice, a contract other teams consume. A small, reversible change is fully explained by a good PR description. A doc there is ceremony, and ceremony teaches people to skip docs where they matter.',
        },
        {
          q: 'What is the **Non-goals** section for?',
          options: [
            'Listing the features that will come in a later phase, so product knows the roadmap',
            'Naming things a reasonable reader might expect this work to include, and saying explicitly that it does not, so the scope argument happens now instead of in week four',
            'Recording the options that were considered and rejected, with the reasons',
            'Nothing much: it is optional boilerplate that good docs usually leave empty',
          ],
          answer: [1],
          explain: 'Most scope creep is not malicious: someone reasonably assumed the email work "obviously" included the digest. Non-goals turn those assumptions into explicit decisions that reviewers can challenge **before** work starts. Rejected options belong in "Alternatives considered". An empty Non-goals section is usually a sign that nobody has thought about the edges yet.',
        },
        {
          q: 'Which goal is written well?',
          options: [
            'Make search better',
            'Use Elasticsearch for search',
            'Search is fast and relevant for users',
            'p95 search latency under 300 ms at current traffic, and a "no results" rate below 5 % for the top 500 queries (today: 1.4 s and 18 %)',
          ],
          answer: [3],
          explain: 'A goal should tell you when you are done and whether it worked: a measure, a target, and a baseline. "Better" and "fast and relevant" cannot be argued with, which is exactly the problem: nobody can check them. "Use Elasticsearch" is a **solution** dressed as a goal; it skips the question the doc exists to answer.',
        },
        {
          q: 'Why should a design doc include "Alternatives considered", with "do nothing" among them? (Select all that apply.)',
          options: [
            'Reviewers will ask "why not X?" anyway. Answering it in the doc, with the trade-offs, saves the round trip and shows the choice was made rather than defaulted to',
            'It makes the doc look thorough to leadership',
            '"Do nothing" forces you to state what the problem costs today, which is what justifies the cost of the fix',
            'It lets the reviewers vote on which option to build',
          ],
          answer: [0, 2],
          explain: 'Alternatives are where reviewers learn whether you understood the problem. If the only option on the page is the one you wanted, a reviewer cannot tell whether you rejected the simpler one or never saw it. "Do nothing" is the most useful alternative, because it makes you write down the cost of the status quo. Design is not decided by vote: the doc names a decision owner.',
        },
        {
          q: 'Your design doc has been in review for two weeks. It has 60 comments, and two reviewers disagree about the database. What should you do?',
          options: [
            'Keep replying to comments until everyone agrees',
            'Start building the version you prefer, and let the code settle it',
            'Set up a 30-minute call with the two reviewers and the decision owner, decide, then record the decision and its reasoning in the doc and close the review',
            'Rewrite the doc from scratch to address every comment',
          ],
          answer: [2],
          explain: 'Comment threads are good at finding problems and bad at resolving disagreements between two people. A short synchronous conversation with whoever owns the decision ends it. Then write the outcome **back into the doc**, so the next reader does not have to reconstruct it from sixty comments. Building your preferred version first turns a design disagreement into a sunk-cost argument.',
        },
        {
          q: 'Six months after launch, a new engineer asks why the service uses a queue instead of calling the email provider directly. Where should the answer be? (Select all that apply.)',
          options: [
            'In the design doc, marked with its final decision and date, and linked from the service\'s README',
            'In a short ADR (architecture decision record) in the repository: context, decision, consequences',
            'In the head of the engineer who built it',
            'In the Slack thread where it was discussed',
          ],
          answer: [0, 1],
          explain: 'Decisions outlive the people and the chat retention period. An ADR is a one-page record kept next to the code: the context at the time, the decision, and its consequences. When it is superseded, you add a new ADR that points back, rather than editing history. Together with the linked design doc, it answers "why is it like this?" without an archaeology project.',
        },
      ],
    },
    {
      id: 'craft-estimate-ranges',
      title: 'Estimates as ranges with confidence',
      kind: 'js',
      xp: 85,
      why: 'A single-number estimate is almost always wrong; a range with a confidence level is something product can actually plan with.',
      tags: ['estimation', 'planning', 'statistics'],
      hints: [
        'Validate first: a non-empty array, and for every task three finite numbers with `0 <= best <= likely <= worst`.',
        'Loop once, adding `(best + 4 * likely + worst) / 6` to a running mean and `((worst - best) / 6) ** 2` to a running variance.',
        'The project `sd` is `Math.sqrt(variance)`. Then `p85 = roundUp(mean + 1.04 * sd)` and `p95 = roundUp(mean + 1.645 * sd)`, using the exact `roundUp` from the brief.',
        '`spikes` is `tasks.filter((t) => t.worst > 3 * t.likely).map((t) => t.name)`. Build the summary sentence, and append the spike sentence only when the list is not empty.',
      ],
    },
    {
      id: 'craft-async-writing',
      title: 'Writing that gets acted on',
      kind: 'quiz',
      xp: 65,
      why: 'On a distributed team, a message that needs a follow-up question costs a day; writing that can be acted on without a reply is a promotion-level skill.',
      tags: ['writing', 'async', 'collaboration'],
      quiz: [
        {
          q: 'You are stuck on a failing integration test and want help in the team channel. Which message gets you unblocked fastest?',
          options: [
            '"Hi, is anyone around?"',
            '"Is anyone familiar with the orders tests?"',
            '"`orders.test.ts` fails on CI but not locally, with `ECONNREFUSED 127.0.0.1:5432` (log linked). I checked the Postgres service container starts, and tried running the tests serially. Does CI need a health check before the tests start? This blocks PR #812."',
            'A direct message to the most senior engineer, with the full stack trace',
          ],
          answer: [2],
          explain: 'The good message can be answered in one reply by whoever knows: it states the symptom, the evidence, what you already ruled out, a specific question, and why it matters. "Hi, is anyone around?" costs a round trip before the question even starts. Asking in the channel rather than a DM means more people can answer, and the answer is searchable for the next person who hits it.',
        },
        {
          q: 'Your weekly status update goes to your manager and the PM. Which shape is best?',
          options: [
            'Lead with the headline ("On track for the 14th; one risk"), then the risk and what you need, then brief progress, with details linked rather than pasted',
            'A diary of what you did each day, in order',
            'A list of every ticket you touched, with its status',
            'Nothing unless something is wrong: no news is good news',
          ],
          answer: [0],
          explain: 'Readers of a status update want to know one thing first: do I need to do anything? Putting the conclusion first (sometimes called BLUF, "bottom line up front") answers that in one line, and the risk plus the ask makes it actionable. Diaries and ticket lists make the reader do the synthesis. Silence is ambiguous: "fine" and "too busy to write" look the same.',
        },
        {
          q: 'You are blocked on another team\'s API change, which was due last week. Your own deadline is in ten days. What is the best first message, and to whom?',
          options: [
            'A post in your own team\'s channel saying the other team is late',
            'A message to their tech lead or their channel: what you need, why, the date it becomes a problem ("without it by the 20th we miss the launch"), and what would help, including an offer to send the PR yourself',
            'An escalation straight to both managers, so it gets priority',
            'Nothing yet: they know about it, and chasing looks pushy',
          ],
          answer: [1],
          explain: 'Go to the people who can fix it, first and directly, and make it easy to say yes: a concrete need, a concrete date, and an offer of help. Most "late" dependencies are simply lower on someone else\'s list, and a clear date moves them. Escalate if that does not work, and tell them you are doing so. Complaining in your own channel changes nothing, and waiting silently turns a ten-day problem into a launch slip.',
        },
        {
          q: 'A 90-message thread about the retry policy has reached a decision. Only four people followed it. What do you do? (Select all that apply.)',
          options: [
            'Post a short summary at the top level: the decision, the main reason, who decided, what changes, and a link to the thread',
            'Nothing: the thread is there for anyone who needs it',
            'Record the decision where it will be found later (the design doc, an ADR or the ticket), not only in chat',
            'Tag the whole team in the thread so they read all 90 messages',
          ],
          answer: [0, 2],
          explain: 'A decision that only four people know about has not really been made: everyone else will keep working to the old assumption. A five-line summary with a link costs one person five minutes and saves everyone else an hour. Chat is also where decisions go to be lost, so put it somewhere durable. Tagging everyone into 90 messages is the opposite of a summary.',
        },
        {
          q: 'You are going on holiday for two weeks in the middle of a migration. What does a good handover note contain? (Select all that apply.)',
          options: [
            'The current state: what is done, what is in flight, and what has not started, with links',
            'The next concrete step, and the decisions still open, with who can make each one',
            'Known risks, and how to roll back if something goes wrong',
            'Your personal phone number, so they can call you if anything comes up',
          ],
          answer: [0, 1, 2],
          explain: 'The test of a handover is whether the person picking it up can make progress **and** handle a bad day without you. State, next step, open decisions with owners, risks and rollback cover that. Leaving your phone number signals that the handover is not really complete, and it guarantees a call on the beach. If there must be an emergency route, it goes through your manager.',
        },
        {
          q: 'You file a bug for another team. Which report lets them fix it without asking you anything?',
          options: [
            '"Checkout is broken for some users, urgent!"',
            'A screen recording of the error page, with no text',
            '"Same as the bug last month, see Slack"',
            '"Checkout returns 500 for carts that contain a gift card and a discount code. Steps: …; expected: …; actual: 500, request id `req_9f2`, since deploy 4711 (Tuesday 14:05 UTC). About 40 users a day are affected; workaround: remove the discount."',
          ],
          answer: [3],
          explain: 'A good bug report is a reproduction plus the evidence to find it in the logs (a request id and a time), when it started (which often names the cause), and how bad it is, so it can be prioritised honestly. "Urgent" without impact gets triaged by volume. A recording shows the symptom but not the input. "See Slack" sends the reader on a search they may not have access to finish.',
        },
      ],
    },
    {
      id: 'craft-pr-description',
      title: 'A bot that reviews PR descriptions',
      kind: 'js',
      xp: 85,
      why: 'The PR description is the only design record most changes get; checking it automatically keeps the template from becoming decoration.',
      tags: ['pull requests', 'writing', 'automation'],
      hints: [
        'Start with `body.replace(/<!--[\\s\\S]*?-->/g, \'\')`. The lazy `*?` stops at the first `-->`, and `[\\s\\S]` crosses newlines. Run every other check on the result.',
        'Split into lines and walk them: a line matching `/^#{2,3} (.*)$/` starts a section (key: its name trimmed and lower-cased); any other line starting with `#` ends the current one. Join each section\'s lines and trim them.',
        'Content is empty when it is `\'\'` or matches `/^(todo|tbd|n\\/a)$/i`. Check `What`, `Why`, `How to test` in order: missing (no key) or empty.',
        'Migrations: `file.split(\'/\').slice(0, -1).includes(\'migrations\')`. Unchecked boxes: `/^\\s*- \\[ \\] (.*)$/` on each line, reporting the trimmed text.',
      ],
    },
    {
      id: 'craft-incident-updates',
      title: 'Incident updates people can plan around',
      kind: 'js',
      xp: 80,
      why: 'During an incident, predictable, plain-language updates stop the flood of pings and let support and leadership do their jobs.',
      tags: ['incidents', 'communication', 'time'],
      hints: [
        'Write two helpers first: `formatTime(ms, now)`, which slices `toISOString()` for the date and `HH:MM`, and `formatDuration(ms)`, which floors to whole minutes.',
        'In `formatTime`, compare `iso.slice(0, 10)` with the same slice of `now`, and put the date in front only when they differ.',
        'The cadence is `{ 1: 30, 2: 60, 3: 120 }` minutes. Round up with `Math.ceil((now + cadence) / FIVE_MIN) * FIVE_MIN`, where `FIVE_MIN` is `300000`.',
        'Resolved incidents take a different third line, measure the duration to `resolvedAt`, and return `nextUpdateAt: null`. Check `impact` before anything else.',
      ],
    },
    {
      id: 'craft-action-items',
      title: 'Action items that actually get done',
      kind: 'js',
      xp: 80,
      why: 'Retro and postmortem actions without an owner, a date and a checkable outcome quietly die; catching that before the meeting ends is cheap follow-through.',
      tags: ['meetings', 'parsing', 'dates'],
      hints: [
        'Match item lines with `/^\\s*- \\[( |x|X)\\] (.*)$/`: group 1 is the box, group 2 the text.',
        'Owner: `/@([A-Za-z0-9_-]+)/`. Due: `/\\(due (\\d{4}-\\d{2}-\\d{2})\\)|\\bdue (\\d{4}-\\d{2}-\\d{2})/i`, where the date is in whichever group matched. Remove each matched text from the item, then collapse spaces with `.replace(/\\s+/g, \' \').trim()`.',
        'A real date: build `new Date(Date.UTC(y, m - 1, d))` and check that `getUTCFullYear`, `getUTCMonth` and `getUTCDate` give back `y`, `m - 1` and `d`.',
        'Only open items get problems, in order: no-owner, then no-due-date / bad-due-date / overdue (`due < today` as strings), then vague (`/^(look into|investigate|think about|consider|discuss|follow up)\\b/i` on the cleaned text).',
      ],
    },
    {
      id: 'craft-design-review',
      title: 'Review a design doc',
      kind: 'quiz',
      xp: 90,
      why: 'A good design review finds the two things that will hurt in production and leaves the author\'s reasonable choices alone; that is how you earn a seat in design discussions.',
      tags: ['design docs', 'code review', 'queues'],
      quiz: [
        {
          q: 'Which of these statements from the doc are problems you should raise? Select every problem, and nothing that is fine.',
          options: [
            'Goal 1: "Make notifications faster and more reliable."',
            'Proposal: "The worker calls the provider\'s `send` API for each message it receives."',
            'Proposal: "Checkout writes the order and an `order.confirmed` row to an `outbox` table in the same transaction."',
            'Proposal: "We will use Amazon SQS, which the platform team already runs."',
            'Alternatives considered: "None. Queues are the industry standard for this."',
            'Proposal: "…with a dead-letter queue after 10 failed attempts."',
          ],
          answer: [0, 1, 4],
          explain: '**Goal 1** cannot be checked, so nobody will know whether the project worked. **The worker line** ignores the delivery guarantee two bullets up: at-least-once means some messages arrive twice, and each one becomes a second email. **"Alternatives: none"** hides whether simpler options (a background job in the same service, a retry with a timeout) were rejected or never considered.\n\nThe decoys are good choices. The **outbox** is exactly how you avoid the dual-write bug (order saved but message lost, or the reverse). **SQS run by the platform team** is boring, managed infrastructure. A **dead-letter queue** after a bounded number of retries is standard practice.',
        },
        {
          q: 'Which other parts of the doc should you raise? (Select all that apply.)',
          options: [
            'Moving every template into the repo and rebuilding it in MJML, "while we are here"',
            'Rollout: switching checkout over and turning on the worker on launch day',
            'Retrying a failed message for up to 24 hours',
            'Open question: whether SMS should go through the same worker next year',
          ],
          answer: [0, 1],
          explain: 'The **template rebuild** is unrelated to the problem, doubles the work and the risk, and the empty Non-goals section is where it should have been pushed out. The **launch-day switch** means the first real test of the new path is on all traffic at once, with no quick way back.\n\nThe others are fine. A confirmation email that arrives hours late during a long provider outage is better than none, and the DLQ catches the rest. Listing SMS as an **open question** is exactly right: it is noted, it is not in scope, and it does not drive the design.',
        },
        {
          q: 'Explain the problem with the worker calling `send` for every message it receives. What goes wrong, and what is the fix?',
          options: [
            'Nothing goes wrong: SQS standard queues deliver each message exactly once',
            'Messages can arrive out of order, so the worker must sort them by timestamp before sending',
            'Switch the queue to at-most-once delivery, so duplicates cannot happen',
            'A message can be delivered twice (for example, the worker crashes after sending but before deleting it), so customers get duplicate emails. Send an idempotency key such as `order-confirmed-<orderId>` to the provider, or record what was sent and skip repeats',
          ],
          answer: [3],
          explain: 'At-least-once delivery is the normal guarantee of SQS standard queues, Kafka consumers and most job systems: a message whose processing outcome is uncertain gets delivered again. So the consumer must be **idempotent**: processing the same message twice must have the same effect as processing it once. Most email and payment providers accept an idempotency key for exactly this reason. At-most-once "fixes" duplicates by losing emails, which is the problem the doc started with. Order does not matter for independent confirmations.',
        },
        {
          q: 'How should you phrase your comment on Goal 1?',
          options: [
            '"This goal is meaningless."',
            '"Can we make this measurable, so we know when we are done and whether it worked? For example: checkout p99 unaffected when the provider is down; 99.9 % of confirmations sent within 5 minutes; none lost to provider 5xx errors (today: about 40 a week)."',
            '"nit: wording"',
            'No comment: Goal 2 is specific enough, so Goal 1 does not matter',
          ],
          answer: [1],
          explain: 'The useful comment names the problem, says why it matters, and offers a concrete version the author can accept or adjust. Proposing numbers (with today\'s baseline) does half the work for them. "Meaningless" is accurate but makes the author defensive, and "nit" signals that it does not matter, when an unmeasurable goal is the reason projects never finish.',
        },
        {
          q: 'Why is the template migration a problem in this doc, even though versioned templates are a good idea?',
          options: [
            'It has nothing to do with the problem this doc exists to solve. It doubles the scope and the risk of the launch, and nothing in Non-goals pushes back. Suggest a separate doc or a later phase, and list it as a non-goal here',
            'MJML is the wrong tool for email templates',
            'Templates should never live in the repository',
            'It should be done first, before the queue work starts',
          ],
          answer: [0],
          explain: '"While we are here" is how a two-week project becomes a two-month one. If the queue launch goes wrong, you now cannot tell whether the cause is the queue or a rebuilt template. The idea itself is good, so the comment should protect it: give it its own doc and its own launch. The review is about scope, not about MJML.',
        },
        {
          q: 'What is a better rollout plan than switching over on launch day?',
          options: [
            'Launch on a Friday evening, when traffic is lowest',
            'Keep both paths on for everyone for a week, so nothing can be lost',
            'Ship the worker first in shadow mode (consume and log, but do not send). Then move checkout to the outbox behind a flag for 1 %, 10 % and 100 % of orders, watching "sent within 5 minutes" and duplicates, with the old path one flag flip away',
            'Test it thoroughly in staging, then switch; staging is realistic enough',
          ],
          answer: [2],
          explain: 'A staged rollout makes each step small and reversible, and it tells you what to watch at each step. Shadow mode proves the worker handles real traffic before any customer depends on it. Keeping both paths on sends every customer two emails. Friday evening means low traffic **and** nobody around when it breaks. Staging never has production\'s volume, data or provider behaviour.',
        },
      ],
    },
    {
      id: 'craft-disagreeing-well',
      title: 'Disagreeing well',
      kind: 'quiz',
      xp: 70,
      why: 'Mid-level engineers are expected to push back, and to do it in a way that makes decisions better rather than slower or more personal.',
      tags: ['collaboration', 'working with product', 'feedback'],
      quiz: [
        {
          q: 'In a design review, a staff engineer proposes a shared cache that you believe will cause stale-price bugs. You are the most junior person in the room. What do you do?',
          options: [
            'Stay quiet: they have more context than you',
            'Say it, as a concern about the outcome: "I\'m worried about stale prices after an update. How would invalidation work when a price changes?", and point to the incident or data behind the worry if you have one',
            'Wait, and raise it in code review once the PR exists',
            'Message your manager privately that the design is wrong',
          ],
          answer: [1],
          explain: 'A design review is the cheapest moment to raise a concern, and framing it as a question about a concrete scenario keeps it about the system, not the person. Either you are right, and you just saved weeks, or there is an answer, and you learned something. Waiting for the PR raises the cost of changing course. Going to your manager first skips the person who can actually answer.',
        },
        {
          q: 'Product wants to ship on the 14th and asks you to skip the tests to make it. What is the best response?',
          options: [
            '"No. We never skip tests."',
            '"OK", and skip them',
            'Offer options with their costs: ship on the 14th with a smaller scope; ship the full scope on the 18th; or ship on the 14th behind a flag to 5 % of users, with the tests landing that week. Say what risk each one carries',
            'Agree, then quietly write the tests anyway and ship late',
          ],
          answer: [2],
          explain: 'Product owns the trade-off between date, scope and risk; engineering owns making the costs visible. A flat "no" leaves them with no way forward, and a silent "OK" hides a risk they did not agree to take. Options turn a standoff into a decision that someone accountable can make with the facts. Quietly doing something other than what you agreed destroys trust faster than either.',
        },
        {
          q: 'The team chose the approach you argued against. What does "disagree and commit" mean in practice? (Select all that apply.)',
          options: [
            'You build the chosen approach as well as you would have built your own',
            'You tell people outside the team it was not your idea, so you are not blamed later',
            'If new evidence appears (a load test shows the problem you predicted, say), you raise it, with that evidence',
            'You re-open the decision at every stand-up until it changes',
          ],
          answer: [0, 2],
          explain: 'Committing means the decision gets your full effort, not a half-hearted implementation that proves you right. It does not mean pretending new evidence does not exist: facts that were not available at the time are a legitimate reason to revisit. Re-litigating the same arguments, or distancing yourself from the decision in public, makes every future decision slower and more political.',
        },
        {
          q: 'A disagreement in a PR thread has gone back and forth eight times and is getting sharp. What do you do?',
          options: [
            'Reply with a longer, more detailed argument',
            'Approve it to end the argument',
            'Ask a third person to vote in the thread',
            'Suggest a quick call, and afterwards post a summary in the thread of what was agreed and why',
          ],
          answer: [3],
          explain: 'Text strips out tone, so a long written argument tends to escalate. Ten minutes of talking usually resolves what eight comments could not, and it is much harder to be sharp with someone you can hear. Then write the outcome back into the thread, so the record matches what happened and the next reader understands the change. Approving to end it teaches both of you that persistence beats reasons.',
        },
        {
          q: 'Your tech lead has made a decision you think is wrong and costly, and a one-to-one conversation has not changed it. When is it right to take it to their manager, and how? (Select all that apply.)',
          options: [
            'When the cost is significant (security, data loss, weeks of wasted work), not for matters of preference',
            'Tell the tech lead first that you are going to, and why, so it is not behind their back',
            'Bring the decision, the risk and your evidence, not a complaint about the person',
            'Do it anonymously, to avoid friction',
          ],
          answer: [0, 1, 2],
          explain: 'Escalation is a normal tool, not a betrayal, as long as it is proportionate, transparent and about the decision. Saying "I still think this is risky enough that I\'d like Sam to weigh in" keeps the relationship intact, and often the tech lead would rather settle it that way too. Anonymous escalation turns a technical disagreement into a trust problem.',
        },
        {
          q: 'In a retro you realise that a bug you insisted was "not our problem" was in fact caused by your change. What is the best move?',
          options: [
            'Say so plainly: "I was wrong about this. It was my change. Here is what I missed, and what I would check next time."',
            'Say nothing: it is fixed now',
            'Point out that the reviewer approved it too',
            'Apologise at length, and offer to stop working on that area',
          ],
          answer: [0],
          explain: 'Owning a mistake quickly and specifically is one of the fastest ways to earn trust, because it makes everything else you say more credible. What you missed is the useful part for the team. Deflecting to the reviewer turns a learning moment into blame, and a long apology makes the room manage your feelings instead of the problem.',
        },
      ],
    },
    {
      id: 'craft-postmortem-boss',
      title: 'Boss: a postmortem that teaches something',
      kind: 'js',
      xp: 250,
      boss: true,
      why: 'Postmortems are how teams learn from incidents; an accurate timeline, honest numbers, blameless language and owned actions are what separate a learning document from a blame document.',
      tags: ['postmortems', 'incidents', 'writing', 'time'],
      hints: [
        'Clean the timeline first: parse each `at` once, sort by time (`Array#sort` is stable), then filter out exact duplicates with a `Set` of `JSON.stringify([ms, kind, text])`.',
        'Build a `Map` of the first time of each milestone from the **sorted** timeline. The start time is the first `start`, or the earliest event. The metrics come from those two.',
        'Problems, in order: missing milestones; event order (walk the milestones, comparing each present one with the last present one); blame phrases with `new RegExp(`\\\\b${phrase}\\\\b`, \'i\')` over the summary and event texts; missing owner/due per action; then the two action-type checks.',
        'Durations floor to minutes: `m < 60` gives `${m} min`, otherwise `${h} h` plus ` ${m % 60} min` when that is not 0. Offsets are `+` or `-` followed by the duration of the absolute difference.',
        'Assemble the sections as strings, `join(\'\\n\\n\')`, and add one final `\\n`. Sort actions by `[\'prevent\', \'detect\', \'mitigate\', \'process\'].indexOf(type)`, and write `|` as `\\|` inside the table.',
      ],
    },
  ],
});
