import { loadChapter } from '../../load.ts';

const here = import.meta.dirname;

export default loadChapter(here, {
  id: 'node-auth',
  title: "Authentication & Authorisation",
  summary: "Session stores, JWT verification pitfalls, RBAC and ABAC policies, reset tokens, PKCE.",
  lessons: [
    {
      id: 'node-session-store',
      title: 'A session store with real expiry',
      kind: 'node',
      xp: 85,
      why: 'Every cookie-session app needs server-side idle and absolute timeouts, id rotation and "log out everywhere"; the naive Map has none of them.',
      tags: ['security', 'sessions', 'authentication'],
      hints: [
        'Keep two maps: `sessions` (sid → `{ userId, data, createdAt, lastSeenAt }`) and `byUser` (userId → `Set` of sids). A `Map` also makes `\'__proto__\'` an ordinary missing key, which a plain object does not.',
        'Write one private `live(sid)` that returns the session or `undefined`, and deletes it (from both maps) when it finds it expired. Make every public method go through it.',
        'Expired is `now() - lastSeenAt >= idleMs || now() - createdAt >= absoluteMs`. `get` sets `lastSeenAt = now()` only after `live` said yes.',
        '`rotate`: remove the old sid from both maps, then store `{ ...session, lastSeenAt: now() }` under a new random id and index it. Copying `createdAt` is the whole point.',
        '`destroyAllForUser` iterates a copy (`[...byUser.get(userId) ?? []]`), skips `except`, counts only the ones `live()` accepts, and removes each one.',
      ],
    },
    {
      id: 'node-jwt-verify',
      title: 'Verifying a JWT without the classic holes',
      kind: 'node',
      xp: 95,
      why: 'alg:none, algorithm confusion, seconds-vs-milliseconds and substring audiences are the real-world JWT bypasses; you will review code that has one of them.',
      tags: ['security', 'jwt', 'crypto', 'authentication'],
      hints: [
        'Work strictly in the order of the brief, and write a small `fail(code)` that throws `new JwtError(code)` so each check is one line.',
        'Validate the shape before decoding anything: `parts.length === 3` and every part matches `/^[A-Za-z0-9_-]+$/`. `Buffer.from(x, \'base64url\')` never throws, so the regex is your only syntax check.',
        'Decide the algorithm yourself: `if (header.alg !== \'HS256\') fail(\'unsupported-alg\')`. Then compute `createHmac(\'sha256\', secret).update(h + \'.\' + p).digest(\'base64url\')` over the segments exactly as received.',
        'Constant-time compare: turn both strings into Buffers, return false if the lengths differ, else `crypto.timingSafeEqual(a, b)`. `timingSafeEqual` throws on unequal lengths, which would otherwise surface as a 500.',
        'Time: `const nowSec = now() / 1000`; expired is `nowSec >= exp + leewaySec`, not yet valid is `nowSec < nbf - leewaySec`. Audience: `aud === audience || (Array.isArray(aud) && aud.includes(audience))` — never `includes` on a string.',
      ],
    },
    {
      id: 'node-refresh-rotation',
      title: 'Refresh token rotation with reuse detection',
      kind: 'node',
      xp: 90,
      why: 'Long-lived refresh tokens are the credential attackers actually want; rotation with family revocation turns a silent, permanent compromise into a forced logout.',
      tags: ['security', 'tokens', 'authentication', 'sessions'],
      hints: [
        'Model three maps: `families` (familyId → `{ userId, createdAt, revoked }`), `refreshTokens` and `accessTokens` (token → `{ familyId, issuedAt, ... }`). Revoking a family is then one flag that every token consults.',
        'Look tokens up by `crypto.createHash(\'sha256\').update(token).digest(\'hex\')`, and guard `typeof token === \'string\'` first so junk is simply "not found".',
        'In `refresh`, follow the brief\'s order exactly: unknown or revoked family → `invalid`; `record.used` → revoke the family, then throw `reuse-detected`; then the two expiry checks; only then `record.used = true` and issue.',
        'Reuse is checked **before** expiry on purpose: an old, used token turning up is evidence of theft whether or not it has since expired.',
        '`familyTtlMs` is measured from the family\'s `createdAt` (set at `login`), never from the token being refreshed — that is what makes it absolute.',
      ],
    },
    {
      id: 'node-rbac',
      title: 'Role-based access control with inheritance',
      kind: 'node',
      xp: 85,
      why: 'Permissions-not-roles checks are how every admin panel stays maintainable past three roles, and resolving the role graph safely is a small, classic bit of engineering.',
      tags: ['security', 'authorization', 'rbac', 'graphs'],
      hints: [
        'Validate first: loop over `Object.entries(roles)` and throw if any `inherits` entry is not `Object.hasOwn(roles, parent)`. `parent in roles` is true for `\'toString\'`.',
        'Resolve with a depth-first function `resolve(name, path)` that memoises results in a `Map`. The cycle test is "is `name` already on the current `path`?", not "have I ever visited it?" — the latter reports diamonds as cycles.',
        'Check the memo before the cycle test: a role that is already fully resolved cannot be part of a cycle through the current chain.',
        'A granted `g` covers `p` when `g === p || g === \'*\' || (g.endsWith(\':*\') && p.startsWith(g.slice(0, -1)))`. `slice(0, -1)` keeps the colon, which is what stops `invoice:*` matching `invoices:read`.',
        'In `can`, return `false` unless `Array.isArray(user?.roles)`, and skip any role that is not an own key of `roles`. The middleware is three lines: 401, 403, `next()`.',
      ],
    },
    {
      id: 'node-abac-policy',
      title: 'Attribute-based policies: deny overrides, fail closed',
      kind: 'node',
      xp: 90,
      why: 'Ownership, tenancy, status and MFA rules outgrow roles fast; a tiny policy engine with deny-overrides and default-deny keeps them reviewable instead of scattered across handlers.',
      tags: ['security', 'authorization', 'abac', 'multi-tenancy'],
      hints: [
        'Loop over the rules once. Skip a rule unless `rule.actions.includes(request.action) || rule.actions.includes(\'*\')`.',
        'Wrap only the `rule.when(request)` call in try/catch, and treat a throw as `return { allowed: false, reason: \'error:\' + rule.id }` right there.',
        'A matching deny can return immediately. A matching allow must **not** return: remember the first one (`firstAllow ??= rule`) and keep looking for denies.',
        'Compare with `=== true`. After the loop: `firstAllow` → allowed, otherwise `default-deny`.',
        'For `shared-read`, guard the missing array: `Array.isArray(resource.sharedWith) && resource.sharedWith.includes(subject.id)`. For MFA, deny when `context.mfa !== true`.',
      ],
    },
    {
      id: 'node-reset-tokens',
      title: 'Password reset tokens done properly',
      kind: 'node',
      xp: 90,
      why: 'A reset link is a bearer credential for the whole account. Hashing it at rest, single use, expiry and no enumeration are what a security review will ask about.',
      tags: ['security', 'authentication', 'crypto', 'race conditions'],
      hints: [
        'Write `const hash = (t) => crypto.createHash(\'sha256\').update(t).digest(\'hex\')` and use it for both storing and looking up. The raw token only ever goes to the mailer.',
        'For an unknown email just `return { ok: true }` — the same object the happy path returns.',
        'A helper `forgetUser(userId)` that deletes every `tokens` entry whose `record.userId === userId` covers both "a new request replaces the old link" and "a reset consumes all links".',
        'In `resetPassword`: type check, `tokens.get(hash(token))`, expiry (`now() >= expiresAt` → delete and throw), then the password rule, then `forgetUser` — all synchronous — and only then the two `await`s.',
        'If the concurrency test fails, look for an `await` before the delete: every `await` is a point where the second call can run its own lookup and still find the record.',
      ],
    },
    {
      id: 'node-pkce',
      title: 'OAuth code exchange with PKCE',
      kind: 'node',
      xp: 100,
      why: 'Every SPA and mobile login goes through an authorization-code exchange; PKCE, exact redirect matching and one-shot codes are what stop an intercepted code becoming an account takeover.',
      tags: ['security', 'oauth', 'crypto', 'authentication'],
      hints: [
        '`challengeFor` is one line: `crypto.createHash(\'sha256\').update(verifier).digest(\'base64url\')`. The RFC 7636 test vector in the tests tells you immediately whether it is right.',
        'In `authorize`, check `Object.hasOwn(clients, clientId)` (not `clients[clientId]`), then `redirectUris.includes(redirectUri)` — a whole-string match, no `startsWith`, no URL normalising — then the method and the challenge regex.',
        'Keep three maps: `codes` (live code → grant), `spent` (code → the access token it produced, or `null`) and `tokens` (access token → `{ userId, clientId }`).',
        'In `exchange`: verifier format first (nothing consumed); then `if (spent.has(code))` revoke `spent.get(code)` from `tokens` and throw; then unknown/expired. Then `codes.delete(code); spent.set(code, null)` **before** comparing client, redirect URI and challenge.',
        'Compare the challenge with Buffers: equal lengths first, then `crypto.timingSafeEqual`. On success, `spent.set(code, accessToken)` so a later replay knows which token to revoke.',
      ],
    },
    {
      id: 'sec-auth-design',
      title: 'Auth design decisions',
      kind: 'quiz',
      xp: 70,
      why: 'Where tokens live, how revocation works and what a login error may say are decided in design review, long before anyone writes the code.',
      tags: ['security', 'authentication', 'architecture'],
      quiz: [
        {
          q: 'A React SPA talks to your own API on the same site. Where should it keep the long-lived refresh token?',
          options: [
            'In `localStorage`, so it survives a reload, and send it in an `Authorization` header',
            'In an `HttpOnly; Secure; SameSite=Strict` cookie scoped with `Path=/auth/refresh`',
            'In `sessionStorage`, because it is cleared when the tab closes',
            'In a JavaScript variable only, re-logging the user in on every reload',
          ],
          answer: [1],
          explain: 'Any script running on the page — an XSS, a compromised npm dependency, a browser extension — can read `localStorage` and `sessionStorage` and ship the token elsewhere, where it keeps working. An `HttpOnly` cookie cannot be read by JavaScript at all; `SameSite=Strict` and the narrow `Path` limit when the browser attaches it. Memory-only is safe but logs users out on every reload, which is fine for the short-lived access token and unusable for the refresh token.',
        },
        {
          q: 'Access tokens are 60-minute JWTs verified without a database lookup. An employee is fired at 10:00. What actually stops them using the API at 10:05?',
          options: [
            'Deleting their refresh tokens: they cannot get a new access token',
            'Rotating the JWT signing key',
            'Nothing short of a check on each request against a revocation list or the user\'s status — or waiting for `exp`',
            'Deleting the user row, since the JWT\'s `sub` no longer exists',
          ],
          answer: [2],
          explain: 'A self-contained token is valid until `exp` unless something on the request path says otherwise. Killing the refresh token stops *renewal*, not the hour already issued. Rotating the key logs **everyone** out. Deleting the row only helps if some code loads the user on each request — which is exactly the lookup JWTs were meant to avoid. The honest trade-off: short access-token lifetimes (5–15 min) and a small denylist (by `jti` or by user) checked on each request.',
        },
        {
          q: 'Your login endpoint returns 401 "invalid email or password" in both cases. Timing shows unknown emails answer in 2 ms and known ones in 80 ms. What is the fix?',
          options: [
            'When the user is not found, still run the password hash against a fixed dummy hash, so both paths do the same work',
            'Nothing: the messages are identical, so there is no enumeration',
            'Add a random 50–100 ms `setTimeout` before every response',
            'Return 200 with `{ ok: false }` instead of 401',
          ],
          answer: [0],
          explain: 'The 78 ms is the scrypt/bcrypt comparison that only runs for real accounts, so response time says who has an account. Random delay adds noise that averages away over repeated requests; the status code does not matter. Doing the same expensive work on both paths (verify against a precomputed dummy hash) removes the signal. Rate limiting the endpoint makes the remaining measurement expensive.',
        },
        {
          q: 'Why does changing the account email require the user to re-enter their password ("sudo mode") even though they are logged in?',
          options: [
            'Because the email change needs the plaintext password to re-hash it',
            'So a stolen session or an unlocked laptop cannot be turned into a permanent takeover by redirecting password resets to the attacker',
            'Because sessions older than 5 minutes are not trusted for anything',
            'It is a UX convention with no security value',
          ],
          answer: [1],
          explain: 'A hijacked session is bounded by its timeouts — unless the attacker can use it to change the email (and then reset the password), or the password, or MFA settings. Step-up authentication on those few actions means a session alone is not enough to make the compromise permanent. It also rotates the session id, since privileges changed.',
        },
        {
          q: 'In an OAuth authorization-code flow with PKCE, what is the `state` parameter still for?',
          options: [
            'Nothing — PKCE replaced it',
            'Carrying the access token back to the client',
            'Telling the auth server which scopes to grant',
            'Binding the callback to the browser session that started the flow, so an attacker cannot make the victim complete a login with the attacker\'s code (login CSRF)',
          ],
          answer: [3],
          explain: 'PKCE stops a *stolen* code being redeemed by someone else. `state` (a random value stored in the user\'s session and compared on the callback) stops the reverse: a victim\'s browser being fed the *attacker\'s* code, so the victim ends up signed in to the attacker\'s account and saves their card details there. Modern guidance says PKCE can cover CSRF when the client properly binds its verifier to the session, but checking `state` is cheap and many providers still require it.',
        },
        {
          q: 'A classic server-rendered web app with one backend. Which session design is the better default?',
          options: [
            'An opaque random session id in an `HttpOnly` cookie, with session data in a server-side store',
            'A JWT in a cookie holding the user\'s id and roles, so no store is needed',
            'A JWT in `localStorage`, sent as a bearer token',
            'The user id in a signed cookie, with no expiry so users stay logged in',
          ],
          answer: [0],
          explain: 'With one backend there is no cross-service verification problem for JWTs to solve, and server-side sessions give you what JWTs make hard: instant logout, "log out everywhere", role changes that apply on the next request, and idle timeouts. JWTs put stale roles in the client until `exp`. A never-expiring signed cookie cannot be revoked at all.',
        },
      ],
    },
    {
      id: 'node-auth-boss',
      title: 'BOSS: login, lockout, sudo mode and kill switches',
      kind: 'node',
      xp: 240,
      boss: true,
      why: 'Login, session hygiene, step-up auth and "disable this account now" are the auth surface of every product; this is the whole of it, end to end, with the bugs that make it into incident reports.',
      tags: ['security', 'authentication', 'sessions', 'http'],
      hints: [
        'Write the plumbing first: `send(res, status, body, headers)`, an `HttpError(status, code)` class, `readJson(req)` that throws `HttpError(400, \'bad-request\')` for anything but a JSON object, and one `try/catch` in the server that turns `HttpError` into its response and anything else into `500 internal`.',
        'Parse the cookie header by splitting on `;` and each part on its first `=`, and look sessions up in a `Map` so `sid=__proto__` is just "not found". Write one `authenticate(req)` that throws `HttpError(401, \'unauthorized\')` and touches `lastSeenAt`.',
        'Lockout is a `Map` from normalised email to `{ failures, lockedUntil }`. Check it **before** `verify` (throw 429 while `now() < lockedUntil`; delete the entry once it has passed), increment on every `null`, set `lockedUntil` when `failures` reaches `maxFailures`, and delete the entry on success.',
        'On login success, read the incoming `sid` and delete it from the map before creating the new session. `/sudo` re-verifies with the email stored in the session, then deletes the old id and stores the **same session object** (with `sudoUntil = now() + sudoMs`) under a new one.',
        'For the admin route: `permissions[role]` must only be read when `Object.hasOwn(permissions, role)` — `permissions.constructor` is a function. Check permission before sudo, and after `disable` resolves true, loop over the sessions map and delete every entry with that `userId`.',
      ],
    },
  ],
});
