import { loadChapter } from '../../load.ts';

const here = import.meta.dirname;

export default loadChapter(here, {
  id: 'design-modules-apis',
  title: "Designing Module APIs",
  summary: "Small surfaces, error design, configuration, plugin systems, layering and boundaries.",
  lessons: [
    {
      id: 'design-options-defaults',
      title: 'Options objects: defaults, typos and ownership',
      kind: 'js',
      xp: 75,
      why: 'Every module you write takes an options object; `||` defaults, ignored typos and shared nested objects are the bugs that ship with it.',
      tags: ['api-design', 'configuration', 'validation', 'immutability'],
      hints: [
        'Do the unknown-key check first, over `Object.keys(options)`, against `[\'baseUrl\', ...Object.keys(DEFAULTS)]`.',
        'A helper `const pick = (key) => options[key] === undefined ? DEFAULTS[key] : options[key]` handles "absent", "undefined" and "0/false/null are real" in one place.',
        'Validate each picked value with a precise check: `Number.isInteger(v) && v >= 0`, `typeof v === \'boolean\'`, `Array.isArray(v)`.',
        'Build headers as a new object: start from `{ ...DEFAULTS.headers }`, then loop over `Object.entries(options.headers ?? {})` assigning `headers[name.toLowerCase()] = value`.',
        'Return `Object.freeze({ …, retryOn: Object.freeze([...retryOn]), headers: Object.freeze(headers) })` — copy, then freeze each level.',
      ],
    },
    {
      id: 'design-waitlist-encapsulation',
      title: 'A small surface that keeps its promises',
      kind: 'js',
      xp: 80,
      why: 'A module can only guarantee its rules if nothing outside it can reach its state; leaked arrays and aliased inputs are how invariants quietly die.',
      tags: ['encapsulation', 'invariants', 'api-design', 'immutability'],
      hints: [
        'Keep `confirmed` and `waiting` as local arrays inside `createWaitlist` and put only functions (and a getter) on the returned object.',
        'Store a copy on the way in (`{ ...person }`) and hand out copies on the way out: `confirmed.map((p) => Object.freeze({ ...p }))`.',
        'Write one `promote()` helper that moves people from the front of `waiting` while `confirmed.length < capacity`, returning their ids. Both `leave` and `setCapacity` call it.',
        'For capacity, keep `capacity` as a closure variable, validate in `setCapacity` before assigning, and expose `get capacity() { return capacity; }` — a getter with no setter ignores (or, in strict code, rejects) assignment.',
      ],
    },
    {
      id: 'design-error-translation',
      title: 'Error design: answers, failures and bugs',
      kind: 'js',
      xp: 80,
      why: 'A module that returns `null` for an outage or wraps every failure in the same generic error forces every caller to guess; its errors are part of its API.',
      tags: ['errors', 'api-design', 'boundaries', 'databases'],
      hints: [
        'Only `db.findOne` resolving `undefined` means "absent". Convert that with `?? null`; never produce `null` from a `catch`.',
        'Write `translate(error)` returning a new error for the two recognised cases and the original `error` otherwise. Then `const run = async (op) => { try { return await op(); } catch (e) { throw translate(e); } }`.',
        'Pass the email into the translation (or build `EmailTakenError` where you know it) so the error can carry `email`. `super(message, { cause })` sets `cause` for you.',
        'The connection check: `typeof error?.code === \'string\' && (CODES.has(error.code) || error.code.startsWith(\'08\'))`. The guard is what lets a rejected string pass through untouched.',
        '`getById` is `findById` plus a `null` check that throws `UserNotFoundError`; `rename` throws it when `update` returns an empty array.',
      ],
    },
    {
      id: 'design-plugin-hooks',
      title: 'A plugin system: waterfall, bail and notify hooks',
      kind: 'js',
      xp: 95,
      why: 'Build tools, CMSs and linters all grow plugin systems; the calling rules of each hook decide whether one broken plugin takes the whole product down.',
      tags: ['plugins', 'extensibility', 'api-design', 'errors'],
      hints: [
        'Validate and order once, in `createPipeline`: `[...plugins].sort((a, b) => phase(a) - phase(b))` with `phase` mapping `pre` → 0, absent → 1, `post` → 2. The copy protects the caller; the stable sort keeps registration order.',
        'Precompute nothing per hook; `ordered.filter((p) => typeof p.transform === \'function\')` inside `run` is fine and skips plugins without that hook.',
        'Transform loop: `try { out = await plugin.transform(value, ctx); } catch (e) { throw new PluginError(plugin.name, \'transform\', e); }` then `if (out !== undefined) value = out;`.',
        'Validate loop: the same `try/catch` shape, then `if (typeof problem === \'string\') throw new ValidationError(problem, plugin.name);`.',
        'onComplete loop: wrap each call in `try/catch`, and wrap the `onPluginError(...)` call in its own `try/catch` so a broken reporter is swallowed too.',
      ],
    },
    {
      id: 'design-boundary-mapping',
      title: 'Boundaries: never pass the row through',
      kind: 'js',
      xp: 75,
      why: 'Returning rows and saving request bodies as-is couples clients to your schema and ships mass-assignment and data-leak bugs; explicit mappings are the layer that prevents both.',
      tags: ['layering', 'boundaries', 'security', 'api-design'],
      hints: [
        'Build the response by naming fields: `{ id: String(row.id), displayName: row.display_name, createdAt: row.created_at.toISOString() }`. Never start from `...row`.',
        'Work out `privileged` once: `viewer != null && (viewer.role === \'admin\' || String(viewer.id) === String(row.id))`, then return `privileged ? { ...base, email: row.email, role: row.role } : base`.',
        'For requests, start with a guard: `typeof body === \'object\' && body !== null && !Array.isArray(body)`. Then read only `body.email` and `body.displayName` into new variables.',
        'Collect problems in a `fields` object as you go and throw once at the end if it has any keys. For the update, add `displayName` to the patch only when `body.displayName !== undefined`, and throw `nothing to update` if the patch ends up empty.',
      ],
    },
    {
      id: 'design-deprecation',
      title: 'Deprecating an API without breaking anyone',
      kind: 'js',
      xp: 85,
      why: 'Shared modules outlive their first API; changing a signature safely (shim, warn once, fail in CI, remove later) is a routine mid-level task that goes wrong as a "small refactor".',
      tags: ['deprecation', 'api-design', 'backwards-compatibility'],
      hints: [
        'Split the work: a `normalise(args)` that turns any accepted calling style into one message object, then a single path that validates and delivers it.',
        'Detect the positional form with `typeof args[0] === \'string\' || Array.isArray(args[0])`, then destructure `const [to, subject, body, isHtml = false] = args` and build `{ to, subject, [isHtml ? \'html\' : \'text\']: body }`.',
        'Keep a `Set` of codes already warned inside `createMailer`. A `deprecate(code)` helper throws `DeprecationError` when `throwOnDeprecation` is set, otherwise warns only if the code is not in the set yet.',
        'For the object form, copy first (`{ ...args[0] }`) before replacing `body` with `text`. Build the envelope with `Array.isArray(v) ? [...v] : [v]` for `to` and `cc`, and add `text`/`html` only when they are not `undefined`.',
      ],
    },
    {
      id: 'design-typed-options',
      title: 'Option combinations the compiler refuses',
      kind: 'typecheck',
      xp: 90,
      why: 'A bag of optional fields pushes "which combination is valid?" onto every caller at runtime; a union with `never` keys makes the invalid ones red squiggles.',
      tags: ['typescript', 'api-design', 'discriminated-unions', 'overloads'],
      hints: [
        'Start with the three option types. Each lists its own trigger as required and every other trigger as `?: never`, e.g. `OnceOptions = Common & { at: Date; everyMs?: never; cron?: never; timezone?: never; jitterMs?: never }`.',
        '`retry?: false | RetryPolicy` — the literal type `false`, not `boolean`.',
        '`ExactlyOne<T> = { [K in keyof T]: Pick<T, K> & { [O in Exclude<keyof T, K>]?: never } }[keyof T]`.',
        'Three overload signatures above the implementation: `(job, options: OnceOptions): OneShotHandle`, `(job, options: IntervalOptions | CronOptions): RecurringHandle`, and `(job, options: ScheduleOptions): OneShotHandle | RecurringHandle` for the un-narrowed case.',
      ],
    },
    {
      id: 'design-lifecycle',
      title: 'Start, stop, roll back: a module with a lifecycle',
      kind: 'js',
      xp: 90,
      why: 'Services that leak a database pool when startup fails, or close it before the HTTP server drains, have no lifecycle design; the fix is a small, reusable API.',
      tags: ['lifecycle', 'resources', 'concurrency', 'api-design'],
      hints: [
        'Compute the start order first with a depth-first walk: for each registered name, visit its `dependsOn` entries, then push the name. Mark names as "visiting" to detect cycles and throw for names not in the map.',
        'Keep `started = []` and push a name only after its `start` resolves. Rolling back and stopping are then the same loop: `for (const name of [...started].reverse())`, each `stop` in its own `try/catch`.',
        'Wrap the failing component\'s error as `new StartupError(name, error)` after the rollback loop, and reset `started` so the next `start()` begins clean.',
        'For concurrency keep the in-flight promises: `if (starting) return starting;` in `start`, and in `stop`, `if (starting) return starting.catch(() => {}).then(() => lifecycle.stop());`.',
        'Set `state` at the edges: `\'starting\'` before the run, `\'started\'` or `\'stopped\'` when it settles; `\'stopping\'` before stopping and `\'stopped\'` in a `finally`.',
      ],
    },
    {
      id: 'design-api-judgement',
      title: 'Module APIs: what is a contract, and what is breaking',
      kind: 'quiz',
      xp: 60,
      why: 'Once another team depends on your module, its signature, errors and even accidental behaviour are a contract; review-time judgement decides how expensive that contract is.',
      tags: ['api-design', 'semver', 'code-review'],
      quiz: [
        {
          q: 'You maintain `createClient(options)`, used by twelve services. Which of these changes need a **major** version? (Select all that apply.)',
          options: [
            'Adding an optional `userAgent` option whose default reproduces the old behaviour.',
            'Making the previously optional `region` option required.',
            'Throwing `RateLimitError` instead of the generic `HttpError` it used to throw for a 429.',
            'Adding a `requestId` property to the objects it resolves with.',
            'No longer accepting numeric ids, only strings.',
          ],
          answer: [1, 2, 4],
          explain: 'Breaking means "code that worked yesterday stops working". Making an option required and narrowing accepted input both break existing callers outright. Changing the error class breaks every `catch (e) { if (e instanceof HttpError …) }` — errors are part of the contract. A new optional option with a backwards-compatible default, or an extra property on a result, is additive: existing callers never notice (unless they deep-equal whole results, which is their bet, not your contract).',
        },
        {
          q: 'A call site reads `renderInvoice(invoice, true, false)`. What is the best change to the API?',
          options: [
            'Keep the booleans and document them in JSDoc, so editors show the parameter names on hover.',
            'Take an options object (`renderInvoice(invoice, { includeTax: true, watermark: false })`), or split into two functions if a flag switches between two different behaviours.',
            'Replace the booleans with numeric flags combined with `|`, like a C API.',
            'Reorder the parameters so the one most callers pass comes first.',
          ],
          answer: [1],
          explain: 'Positional booleans are unreadable at the call site, which is where code is reviewed; a hover tooltip does not help in a diff. Named options read correctly, can be added to without breaking anyone, and can default independently. When a boolean selects between two genuinely different operations (`save(doc, true)` meaning "publish"), two well-named functions are clearer still.',
        },
        {
          q: 'A `utils` package exports 25 functions. Other teams use 3 of them. You want to rename and restructure the other 22 freely. What do you do?',
          options: [
            'Prefix the internal ones with an underscore; everyone knows that means private.',
            'Keep exporting all 25 so they can be unit-tested directly.',
            'Export only the 3 from the package entry point (and the `exports` field in `package.json`), and test the internals through them or with tests inside the package.',
            'Mark the 22 as `@internal` in their JSDoc and keep exporting them.',
          ],
          answer: [2],
          explain: 'Anything importable will be imported, whatever its name or comment says, and then renaming it is a breaking change (Hyrum\'s law). A small public surface is what buys you the freedom to refactor. Tests do not need a public export: they can live inside the package or go through the public functions, which also stops them pinning implementation details.',
        },
        {
          q: 'Placing an order can fail because stock ran out. The HTTP API should answer **409** in that case. Where does the 409 belong?',
          options: [
            'The service throws `new HttpError(409, \'out of stock\')` so the handler can pass it straight through.',
            'The repository checks stock and throws the 409, since it is the layer that knows the numbers.',
            'The service returns `{ status: 409 }` instead of an order.',
            'The service throws (or returns) a domain outcome such as `OutOfStockError` with the SKU and quantity available; the HTTP handler maps it to 409.',
          ],
          answer: [3],
          explain: 'Status codes are an HTTP concern. If the service speaks HTTP, it cannot be reused from a queue consumer, a CLI or a GraphQL resolver, and its tests have to know about 409. The service reports what happened in domain terms, with the data a caller needs; each delivery mechanism translates that outcome into its own vocabulary at its own boundary.',
        },
        {
          q: 'Which of these are sound rules for a plugin system? (Select all that apply.)',
          options: [
            'A failure in a notification-style hook (`onComplete`, "after save") is reported and isolated, so the Slack plugin being down does not stop publishing.',
            'A failure in a transform hook fails the run, with an error that names the plugin and hook.',
            'Plugins get direct access to the core\'s internal state, for maximum flexibility.',
            'Plugin order is deterministic and documented (e.g. `pre`, normal, `post`, then registration order).',
          ],
          answer: [0, 1, 3],
          explain: 'Each hook kind needs a failure rule: a broken transform produced no valid output, so the run cannot continue, and "[tagger] transform failed" saves an hour of bisecting; a broken notifier did not affect the result, so it should not undo it. Order must be predictable because transforms compose. Handing plugins internal state makes every internal change a breaking change for every plugin — the hook API **is** the plugin contract.',
        },
        {
          q: 'You have shipped the new `sendEmail({ … })` alongside the deprecated positional form, with a once-per-process warning. When is it reasonable to delete the old form?',
          options: [
            'In the next major version, once CI runs with deprecations as errors (or usage telemetry) shows no remaining callers you know of.',
            'Straight away: the warning has been logged, so callers have been told.',
            'Never: removing anything is a breaking change.',
            'In the next minor version, since the new API already exists.',
          ],
          answer: [0],
          explain: 'A warning in a log nobody reads is not notice. The honest sequence is: ship the replacement, warn, give teams a way to find their call sites (`--throw-deprecation`-style strict mode in CI), measure, and remove in a **major** release that says so in the changelog. Removing in a minor breaks semver; never removing means the shim and its drift live forever.',
        },
      ],
    },
    {
      id: 'design-flags-boss',
      title: 'BOSS: a feature-flag client forty services depend on',
      kind: 'js',
      xp: 230,
      boss: true,
      why: 'A module every service imports must never throw, never surprise and never break its callers; a flag client is where all of this chapter\'s API rules meet.',
      tags: ['api-design', 'errors', 'plugins', 'deprecation'],
      hints: [
        'Do all option handling up front in `createFlagClient`: unknown keys, the `fetchFlags` check, the `defaults`/`defaultValues` conflict and its warning, and `const defaults = { ...(options.defaults ?? options.defaultValues ?? {}) }`.',
        'Write `report(error)` once: `try { onError(error) } catch {}`. Every failure in the client goes through it instead of being thrown.',
        'Write `decide(key, user)` as a straight list of early returns in the order of the brief: overrides, not loaded, unknown (`!Object.hasOwn(definitions, key)`), disabled, allow list, rollout. `evaluate` calls it and then runs the `onEvaluate` hooks.',
        'For `ready()`: `if (definitions) return Promise.resolve(true); if (loading) return loading;` then `loading = (async () => { try { definitions = structuredClone(await fetchFlags()); return true; } catch (e) { report(new FlagLoadError(e)); return false; } })().finally(() => { loading = null; });`.',
        'The rollout test is strictly less than: `bucket(key, user.id) < rollout`, and `false` when `user?.id` is `undefined`. Deprecation warnings use a `Set` of codes already warned.',
      ],
    },
  ],
});
