import { loadChapter } from '../../load.ts';

const here = import.meta.dirname;

export default loadChapter(here, {
  id: 'js-numbers-text',
  title: "Numbers & Text Done Right",
  summary: "Floating point, money, BigInt, Intl.NumberFormat, Unicode normalisation, grapheme segmentation.",
  lessons: [
    {
      id: 'js-float-traps',
      title: 'Floating point in code review',
      kind: 'quiz',
      xp: 60,
      why: 'Binary floating point, unsafe integers and loose conversions produce off-by-a-cent totals and "0" for empty fields; spotting them in a diff is cheaper than reconciling the ledger.',
      tags: ['numbers', 'floating point', 'code review'],
      quiz: [
        {
          q: 'A cart sums `items.reduce((s, i) => s + i.price, 0)` with prices like `0.1` and `0.2` (in pounds), and a test asserts `total === 0.3`. It fails. What is the right fix?',
          options: [
            'Compare with a tolerance: `Math.abs(total - 0.3) < Number.EPSILON`',
            'Round the total with `Number(total.toFixed(2))` after every addition',
            'Store and add prices as integer pence (`10 + 20 === 30`), and format only for display',
            'Use `parseFloat` on each price before adding',
          ],
          answer: [2],
          explain: '`0.1` and `0.2` have no exact binary representation, so their sum is `0.30000000000000004`. Integers are exact up to 2⁵³, so money in minor units adds, compares and sums exactly. `Number.EPSILON` is the gap next to **1**, not a general tolerance — for totals in the thousands it is far too small — and rounding after every step hides the error without removing it (and `toFixed` itself rounds the binary value, see the next question).',
        },
        {
          q: 'What does `(1.005).toFixed(2)` return?',
          options: ['`"1.01"`', '`"1.00"`', '`"1.005"`', '`"1.0"`'],
          answer: [1],
          explain: 'The literal `1.005` is stored as the nearest double, `1.00499999999999989…`, and `toFixed` rounds **that** value correctly — down. The same thing happens to `Math.round(x * 100) / 100`. If the decimal digits matter, keep them as digits: integer minor units, or a string-based decimal, and round with an explicit rule.',
        },
        {
          q: 'An API returns `{"orderId": 9007199254740993}`. After `JSON.parse`, what is `body.orderId === 9007199254740992`?',
          options: [
            '`true`',
            '`false`',
            'It throws a `RangeError` for an unsafe integer',
            '`JSON.parse` returns the id as a BigInt, so the comparison is `false`',
          ],
          answer: [0],
          explain: 'Above `Number.MAX_SAFE_INTEGER` (2⁵³ − 1) doubles are spaced 2 apart, so `9007199254740993` cannot be represented and is silently rounded to `…992` — the id of a different order. Nothing throws and nothing warns. Use `Number.isSafeInteger` to detect it, and parse ids as strings or BigInts (the `JSON.parse` reviver\'s `context.source` gives you the original digits).',
        },
        {
          q: 'A form handler does `const qty = Number(input.value)`. Which of these produce `0` rather than `NaN`? (select all)',
          options: ['`Number("")`', '`parseFloat("")`', '`Number(null)`', '`Number(undefined)`'],
          answer: [0, 2],
          explain: '`Number` treats an empty or all-whitespace string as `0`, and `null` as `0`, so an empty field or a missing value becomes a valid-looking quantity of zero. `parseFloat("")` and `Number(undefined)` are `NaN`. Validate the text first (non-empty, the digits you expect) and only then convert.',
        },
        {
          q: 'Someone "truncates" a computed value with `parseInt(value)`. For `value = 0.0000005`, what is the result?',
          options: ['`0`', '`NaN`', '`5e-7`', '`5`'],
          answer: [3],
          explain: '`parseInt` takes a **string**: the number is converted with `String(0.0000005)`, which is `"5e-7"`, and `parseInt` reads digits until the first non-digit — `5`. Large numbers go wrong the same way (`"1e+21"` → `1`). To drop the fraction of a number, use `Math.trunc` (or `Math.floor` for negatives rounding down).',
        },
        {
          q: 'A validator must reject the string `"abc"` as "not a number". Which expression is `true` for `"abc"`?',
          options: [
            '`isNaN("abc")`',
            '`Number.isNaN("abc")`',
            '`"abc" === NaN`',
            '`Number.isFinite("abc")`',
          ],
          answer: [0],
          explain: 'The global `isNaN` converts its argument first, so it answers "would this become NaN?" — true here. `Number.isNaN` answers "is this value the NaN value?" and does not convert, so it is false for any string. `x === NaN` is false for every `x`, NaN included. Know which question you are asking; for input validation, converting explicitly and then calling `Number.isNaN` (or `Number.isFinite`) makes it obvious.',
        },
        {
          q: 'Which of these lines throw a `TypeError`? (select all)',
          options: ['`10n + 1`', '`10n / 3n`', '`Math.max(1n, 2n)`', '`1n < 2`'],
          answer: [0, 2],
          explain: 'BigInt refuses to mix with Number in arithmetic, because either conversion could lose information — `10n + 1` throws, and so does passing BigInts to `Math` functions. Comparisons are allowed across the two types (`1n < 2` is `true`). BigInt division truncates towards zero: `10n / 3n` is `3n`, which is exactly what makes it useful for exact rounding.',
        },
      ],
    },
    {
      id: 'js-parse-amount',
      title: 'Parse money input without floats',
      kind: 'js',
      xp: 80,
      why: '`parseFloat` turns "12abc" into 12 and "1,234.50" into 1, and `Number("")` is 0; money typed by a user must be validated as text and converted to integer minor units without ever becoming a float.',
      tags: ['numbers', 'money', 'validation', 'parsing'],
      hints: [
        'Validate the whole trimmed string with one anchored regex before converting anything: `^(-?)([0-9]+|[0-9]{1,3}(?:,[0-9]{3})+)(?:\\.([0-9]+))?$`. The `(?:,[0-9]{3})+` part is what rejects `1,23` and `1,2345`.',
        'Check the fraction length against `digits` yourself: more digits than the currency has is an error, not something to round.',
        'Build the integer from text, not arithmetic: remove the commas from the integer part, `padEnd(digits, "0")` the fraction, concatenate, then `Number(...)` once. Reject it if `!Number.isSafeInteger(result)`.',
        'Apply the sign last, and only when the magnitude is not zero, so `"-0"` gives `0`. `formatAmount` is the same trick backwards: `String(Math.abs(minor)).padStart(digits + 1, "0")`, then split off the last `digits` characters.',
      ],
    },
    {
      id: 'js-exact-rounding',
      title: 'Rates, rounding modes and BigInt',
      kind: 'js',
      xp: 90,
      why: 'Tax and commission are "amount × rate, rounded", and `Math.round` rounds a refund differently from the charge, cannot do banker\'s rounding, and silently loses exactness on large amounts.',
      tags: ['numbers', 'money', 'rounding', 'BigInt'],
      hints: [
        'Do the arithmetic in `BigInt`: `BigInt(amount) * BigInt(rateBps)` is exact at any size. BigInt `/` truncates towards zero and `%` gives the remainder with the sign of the dividend.',
        'Work on the magnitude: take `abs`, compute `q = abs / 10000n` and `r = abs % 10000n`. Every mode then reduces to one question: add 1 to `q` (move away from zero) or not? Put the sign back at the end.',
        'Compare `2n * r` with the divisor to classify the remainder: less is "below half", equal is "exactly half", greater is "above half" — no fractions, no floats.',
        'Away from zero when: `trunc` never; `floor` when negative (and `r > 0`); `ceil` when positive; `halfExpand` when `2r >= d`; `halfEven` when `2r > d`, or `2r === d` and `q` is odd. Convert with `Number(...)` and check `Number.isSafeInteger`.',
      ],
    },
    {
      id: 'js-allocate-cents',
      title: 'Split money without losing a cent',
      kind: 'js',
      xp: 85,
      why: 'Splitting a bill, spreading a discount over order lines or refunding part of a bundle with `Math.round` loses or invents a cent, and a ledger that does not balance is a finance ticket.',
      tags: ['numbers', 'money', 'allocation', 'BigInt'],
      hints: [
        'Two passes. First give each share its exact value rounded towards zero; then count how many units are left over (it is always fewer than the number of shares) and hand them out one each.',
        'With integers, share `i` is `amount * ratio / total` — so its rounded-down value is the integer quotient and what was dropped is the remainder `amount * ratio % total`. Compare remainders as integers, never as float fractions.',
        'Order the shares by remainder, largest first, breaking ties by index, and give `+1` to the first `leftover` of them. A zero ratio has remainder 0, so it never gets one.',
        'Do it on `abs(amount)` in `BigInt` (the product can pass `2**53`), then multiply each share by the sign and convert back with `Number(...)`. BigInt has no `-0`, so negatives come out clean.',
      ],
    },
    {
      id: 'js-bigint-json',
      title: '64-bit ids through JSON',
      kind: 'js',
      xp: 85,
      why: '`JSON.parse` silently rounds every id past 2⁵³, so the refund goes to the neighbouring transaction; and the usual `BigInt.prototype.toJSON` patch changes a global for every library in the process.',
      tags: ['numbers', 'BigInt', 'JSON', 'APIs'],
      hints: [
        'The reviver is called as `(key, value, context)`. For a primitive, `context.source` is the exact text it was parsed from — `"1283465098712340481"`, not the rounded Number.',
        'Only convert when all three hold: `typeof value === "number"`, `!Number.isSafeInteger(value)`, and the source matches `^-?[0-9]+$`. That leaves `1.5e300`, safe integers and strings alone.',
        'For stringify, pass a replacer: `(key, v) => typeof v === "bigint" ? JSON.rawJSON(v.toString()) : v`. `JSON.stringify` writes a raw-JSON value verbatim, so no quotes.',
        '`compareIds`: validate both with `^[0-9]+$` first, then compare `BigInt(a)` with `BigInt(b)` using `<` and `>`.',
      ],
    },
    {
      id: 'js-intl-numbers',
      title: 'Percentages, bytes and locale input',
      kind: 'js',
      xp: 85,
      why: 'Hand-rolled number formatting is English-only, shows "1000.0 KB", and `parseFloat("1.234,5")` turns a German user\'s order for 1 234 units into one.',
      tags: ['numbers', 'Intl', 'i18n', 'parsing'],
      hints: [
        '`formatPercent` is a single `Intl.NumberFormat` with `style: "percent"` (it multiplies by 100 for you), `maximumFractionDigits: digits`, and `signDisplay: "exceptZero"` when signed — that option already drops the sign on anything that rounds to zero.',
        '`formatBytes`: divide by 1000 while the value is at least 1000 and a bigger unit exists. Then check `Math.round(value * 10) / 10 >= 1000` — if so, divide once more. Format with `style: "unit"`.',
        '`new Intl.NumberFormat(locale).formatToParts(12345.6)` contains a `group` part and a `decimal` part: those are the separators to parse with. Escape them before putting them into a RegExp (`.` is a metacharacter).',
        'Build an anchored pattern: `^(-?)([0-9]+|[0-9]{1,3}(?:G[0-9]{3})+)(?:D([0-9]+))?$` with `G` the escaped group separator (or a class `[G ]` when it is a space character) and `D` the escaped decimal. Then drop every non-digit from the integer part, join with `.`, and call `Number`.',
      ],
    },
    {
      id: 'js-unicode-normalize',
      title: 'Unicode normalisation: slugs and usernames',
      kind: 'js',
      xp: 75,
      why: 'Two identical-looking strings compare unequal when one came from a Mac, and "ａｄｍｉｎ" passes a uniqueness check against "admin" — normalisation is how search, slugs and sign-up stop lying.',
      tags: ['unicode', 'strings', 'security', 'normalisation'],
      hints: [
        '`sameText` is one line: normalise both sides to `"NFC"` and compare. Normalising only one side is the classic half-fix.',
        '`slugify`: `"NFKD"` rather than `"NFD"` — the K also folds fullwidth letters, ligatures (`ﬁ`), `№` and superscripts. After that, `.replace(/\\p{M}/gu, "")` removes the combining accents that decomposition split off.',
        'Then lowercase, `.replace(/[^a-z0-9]+/g, "-")` to collapse every other run into one dash, and `.replace(/^-+|-+$/g, "")`. An empty result becomes `"untitled"`.',
        '`canonicalUsername`: `input.trim().normalize("NFKC").toLowerCase()`, then test it against `/^[a-z0-9_.-]{3,20}$/`. The allow-list is what rejects Cyrillic look-alikes and zero-width characters — normalisation cannot.',
      ],
    },
    {
      id: 'js-grapheme-truncate',
      title: 'Truncate text without breaking emoji',
      kind: 'js',
      xp: 80,
      why: '`slice(0, 20)` on a preview splits a family emoji into strangers and a flag into a boxed letter, and byte-limited columns and push payloads need the same care in UTF-8.',
      tags: ['unicode', 'strings', 'Intl', 'UTF-8'],
      hints: [
        '`new Intl.Segmenter(undefined, { granularity: "grapheme" }).segment(text)` is iterable; each item has a `.segment` string. `Array.from(it, (s) => s.segment)` gives you the clusters as an array.',
        '`truncate`: if the text has at most `max` clusters, return it as is. Otherwise `slice(0, max - graphemeLength(ellipsis))` of the clusters, `join("")`, `trimEnd()`, then add the ellipsis.',
        '`truncateBytes`: walk the clusters, measuring each with `new TextEncoder().encode(cluster).length`, and stop before the first one that would take the total over `maxBytes`.',
        '`countWords`: iterate `new Intl.Segmenter(locale, { granularity: "word" }).segment(text)` and count the items whose `isWordLike` is `true` — that skips spaces and punctuation, and handles Japanese and Thai.',
      ],
    },
    {
      id: 'js-invoice-totals',
      title: 'BOSS: invoice totals to the cent',
      kind: 'js',
      xp: 230,
      boss: true,
      why: 'An invoice is parsing, allocation, per-line rounding and formatting at once, and if the lines do not add up to the total to the cent, the accounting system rejects the whole batch.',
      tags: ['numbers', 'money', 'BigInt', 'Intl'],
      hints: [
        'Work in `BigInt` from the moment a price is parsed until the very end: parse to BigInt minor units, multiply by quantity, allocate, compute tax — then convert each output with a helper that throws a `RangeError` unless `Number.isSafeInteger(Number(x))`.',
        'Validate everything before computing: each line\'s price, quantity and rate (the error carries the line index), then the discount, then `discount <= subtotal`.',
        'Discount allocation is the largest-remainder allocator with the lines\' nets as weights: base `discount * net / subtotal`, remainder `discount * net % subtotal`, leftover units to the largest remainders, earlier line on a tie. Handle a zero discount (or zero subtotal) up front.',
        'Tax: `p = taxable * BigInt(bps)`, `q = p / 10000n`, `twice = 2n * (p % 10000n)`; add one when `twice > 10000n`, or when it is equal and `q` is odd. Group the tax summary with a `Map` keyed by rate and sort the result by rate.',
        'For `formatted`, turn minor units into an exact decimal string (`padStart(digits + 1, "0")`, then insert the point `digits` from the end) and pass that string to `Intl.NumberFormat.prototype.format`.',
      ],
    },
  ],
});
