import { loadChapter } from '../../load.ts';

const here = import.meta.dirname;

export default loadChapter(here, {
  id: 'node-streams-events',
  title: "Streams & Events II",
  summary: "Backpressure, pipeline, readline, CSV transforms, zlib, event emitter leaks.",
  lessons: [
    {
      id: 'node-stream-backpressure',
      title: 'Backpressure: respecting write() === false',
      kind: 'node',
      xp: 85,
      why: 'Exports and file writers that ignore backpressure buffer the whole dataset in memory and die at scale; ones that wait for drain naively hang on disk-full.',
      tags: ['streams', 'backpressure', 'memory'],
      testTimeoutMs: 20000,
      hints: [
        '`write()` returns a boolean. `false` does not mean the chunk was lost; it means "stop until I say `drain`".',
        'Inside `for await (const chunk of source)`, `if (!writable.write(chunk)) await once(writable, \'drain\')`. `once` from `node:events` rejects if `\'error\'` is emitted first.',
        'Wrap the loop in `try`/`catch`: on any error, `writable.destroy(error)` and rethrow. Breaking out of `for await` by throwing also calls the source\'s `return()`, closing it.',
        'After the loop, `writable.end()` then `await finished(writable)` from `node:stream/promises`, which waits for `\'finish\'` and rejects on `\'error\'`.',
      ],
    },
    {
      id: 'node-csv-parser',
      title: 'A streaming CSV parser that survives real exports',
      kind: 'node',
      xp: 100,
      why: 'Imports from spreadsheets and other systems are CSV, and split(\',\') breaks on the first quoted comma or multi-line note. Parsing it as a stream keeps large imports in bounded memory.',
      tags: ['streams', 'parsing', 'csv'],
      testTimeoutMs: 20000,
      hints: [
        'Splitting into lines first cannot work: a quoted field may contain `\\n`. Walk the text one character at a time and keep all state (current field, current record, "inside quotes") in variables that live across `transform` calls.',
        'Decode with a `StringDecoder` so a multi-byte character split across chunks is not mangled. Check for `\\uFEFF` only on the very first decoded text.',
        'Inside quotes, a `"` is ambiguous until you see the next character: `""` is a literal quote, anything else closes the field. Keep a `quotePending` flag so that decision can wait for the next chunk.',
        'Treat an unquoted `\\r` the same way: remember it, and only when the next character is not `\\n` add it to the field. In `flush`, an open quote is a `CsvError`; otherwise finish the last record if it has any content.',
        'On a finished record: `[\'\']` from an unquoted empty line is skipped; otherwise increment the record number, then store the header or `push(Object.fromEntries(names.map((n, i) => [n, fields[i]])))`. Return errors through `callback(error)`.',
      ],
    },
    {
      id: 'node-readline-log-report',
      title: 'Reading a huge log line by line',
      kind: 'node',
      xp: 80,
      why: 'Incident work means answering questions from multi-gigabyte logs. readline over a stream does it in constant memory, and a report on half a file is worse than none.',
      tags: ['streams', 'readline', 'logs'],
      testTimeoutMs: 20000,
      hints: [
        'Create the interface with `readline.createInterface({ input, crlfDelay: Infinity })` and consume it with `for await (const line of lines)` — that loop is also what makes an input error reject.',
        'Validate by splitting on `\' \'` and requiring exactly 5 parts, then test the status with `/^[1-5]\\d\\d$/` and the duration with `/^(\\d+)ms$/`. Empty lines `continue` before any of that.',
        'Strip the query with `rawPath.split(\'?\')[0]` and count in a `Map`. Start `statuses` with all four keys at `0`.',
        'Sort durations with `(a, b) => a - b` — the default sort compares strings, so `100` comes before `9`. Then `p95 = sorted[Math.ceil(0.95 * n) - 1]`.',
      ],
    },
    {
      id: 'node-zlib-limits',
      title: 'Compression without bombs or leftovers',
      kind: 'node',
      xp: 85,
      why: 'Accepting compressed uploads without an output limit is a one-request memory exhaustion; a failed compress that leaves an empty .gz behind corrupts the next job.',
      tags: ['streams', 'zlib', 'security'],
      testTimeoutMs: 20000,
      hints: [
        '`await pipeline(createReadStream(src), createGzip(), createWriteStream(dest))` does the streaming and the error propagation. Wrap it in try/catch for the cleanup.',
        'In the `catch`, `await rm(dest, { force: true })` — `force` makes a missing file a no-op — and then `throw error`, the original one.',
        'For the limit, count bytes **after** `createGunzip()`: add a third pipeline stage, `async function* (inflated) { for await (const chunk of inflated) { … } }`.',
        'Inside that stage, add `chunk.length` to a running total and `throw new TooLargeError(maxBytes)` the moment it passes `maxBytes`; `pipeline` then destroys the input and the gunzip. Collect chunks in an array and `Buffer.concat` at the end.',
      ],
    },
    {
      id: 'node-emitter-cleanup',
      title: 'Event listeners that always get removed',
      kind: 'node',
      xp: 95,
      why: 'Listener leaks are the most common Node memory leak: every exit path — break, error, abort, disconnect — must unsubscribe, and async iterators hide one of those exits.',
      tags: ['events', 'async iterators', 'memory'],
      testTimeoutMs: 20000,
      hints: [
        'Put the `emitter.on(...)` calls in `watchJob` itself, not inside an async generator body: that body does not run until the first `next()`.',
        'Buffer events in an array. `next()` takes from the front; if the array is empty, it awaits a promise whose `resolve` the listeners call when they push.',
        'Write one idempotent `finish()` that calls `emitter.off` for all three events and `signal.removeEventListener(\'abort\', onAbort)`, and call it on done, on error, on abort and from `return()`.',
        'Return a plain object: `{ [Symbol.asyncIterator]() { return this; }, async next() { … }, async return() { finish(); return { value: undefined, done: true }; } }`. `for await` calls `return()` on `break`.',
        'For the signal: if `signal.aborted` already, queue `{ error: signal.reason }` straight away; otherwise `addEventListener(\'abort\', onAbort, { once: true })` and queue the same thing when it fires.',
      ],
    },
    {
      id: 'node-stream-json-export',
      title: 'Streaming a large export over HTTP',
      kind: 'node',
      xp: 100,
      why: 'Export and report endpoints are where services run out of memory, leak database cursors to closed tabs, and return half the data with a 200.',
      tags: ['streams', 'http', 'backpressure'],
      testTimeoutMs: 20000,
      hints: [
        'Take the iterator yourself (`getRows()[Symbol.asyncIterator]()`) and `await rows.next()` once **before** writing headers. If that throws, you can still answer `500`.',
        'Write the body as an async generator: `yield \'[\'`, the first row, then `\',\' + JSON.stringify(row)` for each further row, then `yield \']\'`. Put `await rows.return?.()` in its `finally`.',
        '`await pipeline(Readable.from(body()), res)` waits for `drain`, and when the client disconnects or the generator throws it destroys the other side and calls the generator\'s `return()` — which runs your `finally`.',
        'Wrap the `pipeline` call in try/catch and swallow the error: by then the response has been destroyed, which is exactly the signal the client needs. Do not write `]` in a `catch`.',
      ],
    },
    {
      id: 'node-batch-writer',
      title: 'A batching Writable for bulk inserts',
      kind: 'node',
      xp: 75,
      why: 'Bulk imports batch rows into multi-row inserts. A writer that does not wait for each batch exhausts the pool and loses errors; one that forgets the tail loses data silently.',
      tags: ['streams', 'backpressure', 'databases'],
      testTimeoutMs: 20000,
      hints: [
        'The `write` callback is the whole trick: call it straight away while the batch is filling, and only after `flush` settles when it is full.',
        'Swap arrays instead of clearing: `const full = batch; batch = []; await flush(full);`.',
        'Bridge the promise to the callback with `flush(full).then(() => callback(), callback)` — a rejection reaches `callback(error)` and fails the stream.',
        'Add `final(callback)`: if `batch.length === 0` call back at once; otherwise flush the remainder the same way.',
      ],
    },
    {
      id: 'node-streams-events-quiz',
      title: 'Streams and emitters: the defaults that bite',
      kind: 'quiz',
      xp: 60,
      why: 'File-handle leaks, crashed workers and memory spikes in import jobs trace back to a handful of stream and emitter defaults every Node engineer is expected to know.',
      tags: ['streams', 'events', 'debugging'],
      quiz: [
        {
          q: 'An upload handler does `req.pipe(createGzip()).pipe(createWriteStream(dest))`. Clients sometimes disconnect mid-upload. What happens, and what is the fix?',
          options: [
            'Node destroys the whole chain automatically; nothing to fix.',
            'The gzip stream throws synchronously into the handler, which a try/catch around the line would catch.',
            '`.pipe()` does not forward errors or premature closes: the write stream is never closed, leaking a file descriptor and leaving a partial file. Use `pipeline(req, createGzip(), createWriteStream(dest))` and delete `dest` if it rejects.',
            'Set `highWaterMark: 0` on the write stream so nothing is buffered when the client leaves.',
          ],
          answer: [2],
          explain: '`.pipe()` handles backpressure but not failure: an error or early close on one stream leaves the others open. `pipeline` destroys every stage when any of them fails and reports the error once, which is also when you clean up the partial output. Stream errors are emitted asynchronously, so a try/catch around the `.pipe()` line never sees them.',
        },
        {
          q: 'A worker process uses a custom `EventEmitter` for job updates. One day an upstream bug makes it `emit(\'error\', err)` while nothing is listening for `\'error\'`. What happens?',
          options: [
            'The process throws `err` as an uncaught exception and, by default, crashes.',
            'The event is silently dropped, like any event with no listeners.',
            'Node logs a warning and continues.',
            'The error is queued until a listener is attached.',
          ],
          answer: [0],
          explain: '`\'error\'` is special: every other event with no listeners is a no-op, but an unhandled `\'error\'` is thrown from `emit()`. That is why every stream and emitter you create needs an error path (a listener, `pipeline`, or `once()`/`on()` from `node:events`, which reject on `\'error\'`).',
        },
        {
          q: 'Which statements about `emitter.emit(\'order.created\', order)` are true? Select all that apply.',
          options: [
            'Listeners run synchronously, in registration order, before `emit` returns.',
            'If a listener throws, the exception propagates out of `emit` to the caller, and later listeners do not run.',
            'Listeners run on the next tick, so a slow listener does not delay the code that emitted.',
            'An `async` listener that rejects produces an unhandled rejection rather than an exception at the `emit` call.',
          ],
          answer: [0, 1, 3],
          explain: '`emit` is a plain synchronous loop over the listeners. A throwing listener aborts it and surfaces in the emitter\'s caller — so a bug in an analytics listener can fail the request that created the order. An `async` listener returns a promise that `emit` ignores, so its rejection is unhandled (unless `captureRejections` is enabled). Deferring work is the listener\'s job (`setImmediate`, a queue), not something `emit` does.',
        },
        {
          q: 'An import uses `Readable.from(rows)` in object mode, where each row object holds about 2 MB of text, piped into a slow writer. Memory peaks far higher than "two or three rows". Why?',
          options: [
            'Object-mode streams ignore backpressure entirely.',
            'In object mode `highWaterMark` counts **objects** (default 16), not bytes, so each buffer may hold 16 rows — about 32 MB each side, before anything pushes back.',
            '`Readable.from` copies every object twice.',
            'The default `highWaterMark` in object mode is 16 KB, which 2 MB rows always exceed, so buffering is disabled.',
          ],
          answer: [1],
          explain: 'Backpressure still works in object mode, but its unit is "one object". With large objects, lower the `highWaterMark` (e.g. `{ highWaterMark: 2 }`) on the streams that hold them. Byte-mode streams default to 16 KB (64 KB for fs read streams), which is why the same pipeline over raw bytes stays small.',
        },
        {
          q: 'A script reads the header line of a CSV with `for await (const line of rl) { header = line; break; }` and then passes the same file stream to a function that reads the rest. The second function receives nothing. Why?',
          options: [
            'readline buffers the whole file on the first iteration.',
            'The stream is paused after `break` and needs `resume()`.',
            'Leaving a `for await` loop early calls the iterator\'s `return()`, which **destroys** the underlying stream. Read the header and the rows in one loop, or use a stage that treats the first line specially.',
            'CSV files must be opened twice: once for the header, once for the body.',
          ],
          answer: [2],
          explain: 'Async iteration over a stream owns the stream: `break`, `return` or a throw inside the loop destroys it (that is how cleanup is guaranteed). The same rule is what makes early exit safe in the rest of this chapter — and what makes "peek, then hand over" impossible with a plain loop. Branch on a `first` flag inside one loop instead.',
        },
        {
          q: 'Production logs show `MaxListenersExceededWarning: 11 close listeners added to [Socket]`. What is the right response?',
          options: [
            'Call `socket.setMaxListeners(0)` to remove the limit; the warning is noise.',
            'Raise the limit to 100, since sockets legitimately have many listeners.',
            'Ignore it: it is a warning, not an error.',
            'Treat it as a leak report: find the code adding a listener per request/operation to a long-lived emitter and make sure every path removes it (or use `once`, or an `AbortSignal` to scope it).',
          ],
          answer: [3],
          explain: 'The default limit of 10 exists to flag exactly this pattern: listeners added repeatedly and never removed, each pinning its closure in memory. Raising or removing the limit hides the symptom while memory keeps growing. Occasionally an emitter really has many listeners by design; that is a decision you make after finding out why, not the first fix.',
        },
      ],
    },
    {
      id: 'node-event-import-boss',
      title: 'Boss: the nightly event import',
      kind: 'node',
      xp: 240,
      boss: true,
      why: 'Batch imports from partners are a staple of mid-level backend work: streaming, validation, rejects files, batching and clean failure all at once.',
      tags: ['streams', 'zlib', 'backpressure', 'validation'],
      testTimeoutMs: 20000,
      hints: [
        'Shape it as `await pipeline(input, createGunzip(), splitLines, consume, { signal })`: `splitLines` is an `async function*` over decompressed chunks, and `consume` is an `async function` over the lines.',
        'In `splitLines`, decode with a `StringDecoder`, keep the unfinished tail in a string, yield each complete line with one trailing `\\r` removed, and after the loop yield the tail if it is non-empty.',
        'In `consume`, increment the line counter first (empty lines count), then `JSON.parse` in its own try/catch (`invalid json`), then check the shape (`invalid event`): non-null, not an array, non-empty strings, `Number.isInteger(ts)`.',
        'For rejects: `if (!rejects.write(text)) await once(rejects, \'drain\')`. For duplicates, a `Set` of ids seen so far.',
        'Batch like the batch-writer lesson: swap arrays, `await insert(full)` when full and once more after the loop if non-empty. Call `signal?.throwIfAborted()` before each insert; an error thrown from `consume` makes `pipeline` destroy `input`.',
      ],
    },
  ],
});
