import { loadChapter } from '../../load.ts';

const here = import.meta.dirname;

export default loadChapter(here, {
  id: 'craft-delivery',
  title: "Delivery",
  summary: "Git workflows, CI design, feature flags, releases and rollbacks, reviewing real diffs.",
  lessons: [
    {
      id: 'craft-flag-rollout',
      title: 'Feature flags with sticky percentage rollouts',
      kind: 'js',
      xp: 95,
      why: 'Every staged release goes through a flag evaluator; one that is not sticky, independent and monotonic flickers features and ruins experiments.',
      tags: ['feature flags', 'rollouts', 'hashing'],
      hints: [
        'Validate `rolloutPercent` first, then follow the table top to bottom, returning at the first row that applies.',
        'Treat missing lists as empty: `(flag.deny ?? []).includes(user.id)`. A rule matches when `user[rule.attribute] !== undefined && rule.in.includes(user[rule.attribute])`, and every rule must match.',
        'Handle `rolloutPercent === 100` before the anonymous check, so anonymous users get a fully rolled-out flag.',
        'The bucket is `fnv1a32(`${flag.key}:${user.id}`) % 10000`, and the user is in when `bucket < Math.round(flag.rolloutPercent * 100)`. The flag key in the hash is what makes two flags independent.',
      ],
    },
    {
      id: 'craft-semver-bump',
      title: 'Semantic versions from conventional commits',
      kind: 'js',
      xp: 85,
      why: 'The version number is a promise to every downstream consumer; getting the bump wrong breaks their builds on a routine install.',
      tags: ['semver', 'releases', 'parsing'],
      hints: [
        'Validate with an anchored regex: `^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$`. Then work out one bump per commit and keep the largest.',
        'Split each message on `\\n`. The header is the first line: `/^([a-z]+)(\\([^()]*\\))?(!)?: \\S/i` gives you the type and the `!`.',
        'A commit is breaking when the header has `!` or some **later** line matches `/^BREAKING[ -]CHANGE: /`. Check this only when the header matched.',
        'Rank the bumps (none < patch < minor < major). If the result is major and the current major is `0`, use minor. Then build the string, resetting everything to the right of the part you bumped.',
      ],
    },
    {
      id: 'craft-changelog',
      title: 'Release notes people actually read',
      kind: 'js',
      xp: 90,
      why: 'Support, mobile and downstream teams learn what changed from your release notes; a raw git log hides the one breaking change in forty chores.',
      tags: ['changelog', 'releases', 'communication'],
      hints: [
        'First remove cancelled pairs: collect the shas in a `Set`, and for every `revert` whose `reverts` is in it, drop both commits.',
        'Build each section from the remaining commits with `filter`, in the fixed order, and skip empty sections. Breaking changes filters on `breaking`, whatever the type.',
        'An entry is `- ` + (`**scope:** ` if there is a scope) + text + ` (` + (`#` + pr, or `sha.slice(0, 7)`) + `)`.',
        'Sort each section with a comparator that looks only at the scope: scoped before unscoped, then `a.scope < b.scope`. Return 0 for equal scopes so the stable sort keeps commit order.',
      ],
    },
    {
      id: 'craft-git-scenarios',
      title: 'Git in the weeks that go wrong',
      kind: 'quiz',
      xp: 75,
      why: 'Hotfixes, stacked branches, reverted merges and leaked secrets are where git knowledge stops being trivia and starts saving the release.',
      tags: ['git', 'releases', 'incident response'],
      quiz: [
        {
          q: 'A bug fix (`a1b2c3d`) was merged to `main` yesterday. Customers on the `release/2.3` branch need it today, and `main` also has six unreleased features since 2.3 was cut. What do you do?',
          options: [
            'Merge `main` into `release/2.3`',
            'Rebase `release/2.3` onto `main`',
            'On a branch from `release/2.3`, run `git cherry-pick -x a1b2c3d`, run the tests, and open a PR into the release branch',
            'Type the fix again by hand on the release branch, so the two histories stay separate',
          ],
          answer: [2],
          explain: 'Merging or rebasing brings all six unreleased features into a patch release. `cherry-pick` copies exactly one commit, and `-x` adds "(cherry picked from commit a1b2c3d)" to the message, so anyone can trace the release fix back to its original. Re-typing it by hand is how the two branches end up with slightly different fixes and no link between them. Going through a PR means the release branch\'s CI runs before customers get it.',
        },
        {
          q: 'You rebased your PR branch onto the latest `main`, and `git push` is rejected as non-fast-forward. A CI bot sometimes pushes formatting commits to PR branches. What do you run?',
          options: [
            '`git pull`, then `git push`',
            '`git push --force`',
            'Delete the remote branch and push it again under the same name',
            '`git push --force-with-lease`',
          ],
          answer: [3],
          explain: 'After a rebase the remote has the old commits and you have rewritten copies, so a force push is expected. `--force` overwrites whatever is there, including a bot commit you never saw. `--force-with-lease` refuses if the remote has moved since you last fetched, so you can fetch, look, and rebase again. (If your editor fetches in the background, add `--force-if-includes` too.) `git pull` merges the old, pre-rebase commits back in, so every commit appears twice. Deleting the branch closes the PR on most hosts and loses its review threads.',
        },
        {
          q: 'You branched `feature-b` from `feature-a` before `feature-a` was **squash-merged** into `main`. Now `git rebase main` on `feature-b` stops with conflicts in files you never touched, all from `feature-a`\'s commits. What is the clean fix?',
          options: [
            '`git rebase --onto main <last commit of feature-a> feature-b`, which replays only `feature-b`\'s own commits onto `main`',
            'Resolve each conflict by taking `main`\'s version, commit by commit',
            'Run `git rebase --skip` at every conflict until it finishes',
            'Squash-merge `feature-b` as well; squashing makes the conflicts go away',
          ],
          answer: [0],
          explain: 'A squash merge creates one **new** commit with a new hash. Git does not know that `feature-a`\'s original commits are already in `main`, so it tries to replay them on top of their own squashed copy. `--onto main X feature-b` means "take the commits after X up to feature-b and put them on main": only your work moves. `--skip` drops whole commits, and when one of your own commits also conflicts, it is silently lost. Resolving `feature-a`\'s conflicts by hand works, but it is slow and easy to get wrong.',
        },
        {
          q: 'PR #512 was merged into `main` as merge commit `m1` and broke checkout. It is 5 pm. Which statements are true? (Select all that apply.)',
          options: [
            '`git revert -m 1 m1` creates a commit that undoes the PR\'s changes, keeping `main`\'s side (the first parent)',
            '`git revert m1` without `-m` fails, because a merge has two parents and git will not guess which side to keep',
            'On Monday the author can fix the bug on the same branch and merge the PR again, and git will re-apply all of its changes',
            'To land it again later, revert the revert (or re-create the changes as new commits), then add the fix on top',
          ],
          answer: [0, 1, 3],
          explain: 'Reverting a merge needs `-m 1` to say "undo relative to the first parent", the branch that was merged into. The trap is afterwards. The revert undoes the **changes**, but the PR\'s commits are still in `main`\'s history, so git thinks they are already merged. Merging the branch again brings in only the new fix commits, not the original work. Revert the revert first ("Reapply PR #512"), or rebuild the changes as new commits, then add the fix.',
        },
        {
          q: 'During `git rebase main`, your commit that added a dependency conflicts with `main` in `package-lock.json`, because someone else added a different dependency. You have already resolved `package.json` to keep both. What next?',
          options: [
            'Edit the conflict markers in `package-lock.json` by hand, keeping both sides',
            'Take `main`\'s lockfile, run `npm install` so it adds your dependency from `package.json`, then `git add package-lock.json` and `git rebase --continue`',
            'Run `git checkout --ours package-lock.json` to keep your branch\'s version, since "ours" is your branch',
            'Delete `package-lock.json` and let `npm install` regenerate it from scratch',
          ],
          answer: [1],
          explain: 'A lockfile is generated output: hand-merging it produces something `npm ci` may reject, or worse, accept with inconsistent integrity hashes. Start from `main`\'s lockfile and let npm add your one dependency. Note that during a **rebase**, "ours" is the branch you are rebasing onto (`main`) and "theirs" is your commit, the reverse of a merge. So the third option does not do what its reasoning says, and skips `npm install` anyway. Deleting the lockfile re-resolves every transitive dependency, which turns a one-package PR into hundreds of silent upgrades.',
        },
        {
          q: 'Ten minutes ago you pushed a commit containing a live Stripe API key to a PR branch on a public repository. Which steps are necessary? (Select all that apply.)',
          options: [
            'Revoke and rotate the key in Stripe straight away',
            'Force-push the branch without that commit; once it is gone from the branch, the key is safe',
            'Move the key into the secret store, and turn on secret scanning or push protection so this cannot happen silently again',
            'Check Stripe\'s logs for any use of the key since it was pushed',
          ],
          answer: [0, 2, 3],
          explain: 'Bots scan public pushes within minutes, and the commit also lives on in forks, the PR\'s refs, CI logs and caches that a force push does not touch. A pushed secret is a leaked secret: **rotate it first**, then check whether it was used, then fix the process. Rewriting history afterwards is tidying, not remediation. Push protection (GitHub, GitLab) or a pre-commit scanner like gitleaks stops the next one before it leaves your machine.',
        },
      ],
    },
    {
      id: 'craft-ci-lint',
      title: 'Lint the CI config before it bites',
      kind: 'js',
      xp: 100,
      why: 'CI workflows hold production credentials and gate every deploy, yet nobody reviews them; the common failures are mechanical to detect.',
      tags: ['CI', 'security', 'graphs'],
      hints: [
        'Normalise first: `needs` to an array (a string becomes `[s]`, missing becomes `[]`), and `on` to a list of trigger names (a string, an array, or the object\'s keys).',
        'For cycles, build a `Map` from job id to its needs, and for each job walk the graph with a stack and a `seen` set. If you reach the starting job again, it is on a cycle. Skip names that are not jobs.',
        'Pinning: allow `./…` and `docker://…`; otherwise split at the last `@`. No `@` is unpinned. The owner is the text before the first `/`. `actions` and `github` pass with any ref; anyone else needs `/^[0-9a-f]{40}$/`.',
        'Untrusted input: find each `${{ … }}` in `run` with a global regex, and test its contents for `github.head_ref`, or `github.event.` followed by a path whose last segment is `title`, `body`, `message` or `ref`.',
      ],
    },
    {
      id: 'craft-affected-builds',
      title: 'Which packages does this PR affect?',
      kind: 'js',
      xp: 90,
      why: 'Monorepo CI only stays fast and correct if "affected" includes everything downstream of a change; getting the direction wrong ships untested code.',
      tags: ['CI', 'monorepo', 'graphs'],
      hints: [
        'Drop `.md` files first. If any remaining file matches a global entry (exact path, or a prefix when the entry ends in `/`), return every package name, sorted.',
        'The owner of a file is the package whose `dir + \'/\'` it starts with, preferring the longest `dir`.',
        'Build a reverse map, `dependents`: for each package and each of its `deps` that is a known package, record the package as a dependent of that dep.',
        'Put the owners in a `Set` and a queue, then walk: for each name taken off the queue, add every dependent that is not in the set yet, and queue it. The set stops cycles and removes duplicates.',
      ],
    },
    {
      id: 'craft-canary-verdict',
      title: 'Promote, wait or roll back a canary',
      kind: 'js',
      xp: 90,
      why: 'Automated canary analysis decides whether your release reaches every user; judging on too little data or the wrong comparison either ships bugs or blocks good releases.',
      tags: ['deployments', 'canary', 'monitoring'],
      hints: [
        'Write `judgeWindow(check, policy)` returning `healthy`, `unhealthy` (with reasons) or `insufficient`, and build `judgeCanary` on top of it.',
        'Order matters inside a window: the `abortAfterErrors` check comes before the sample-size check, and the sample-size check before the rate comparison.',
        'Compare `canary.errors / canary.requests - baseline.errors / baseline.requests` with `maxErrorRateIncrease` using `>`, and `canary.p99Ms` with `baseline.p99Ms * maxLatencyRatio` using `>`.',
        'Roll back if the latest window is unhealthy. Otherwise take `checks.slice(-healthyChecks)`: promote only if it has exactly `healthyChecks` windows and every one is `healthy`.',
      ],
    },
    {
      id: 'craft-review-deploy-diff',
      title: 'Review a risky deploy',
      kind: 'quiz',
      xp: 90,
      why: 'The PRs that cause outages are usually correct code shipped in the wrong order; spotting that in review is a core mid-level skill.',
      tags: ['code review', 'migrations', 'feature flags', 'CI'],
      quiz: [
        {
          q: 'Which lines of **`0042_pricing_v2.sql`** are defects that should block the merge? Select every defect and nothing that is fine.',
          options: [
            'line 2: `ALTER TABLE orders RENAME COLUMN total TO total_cents;`',
            'line 4: `ALTER TABLE orders ADD COLUMN currency text NOT NULL DEFAULT \'GBP\';`',
            'line 6: `ALTER TABLE orders ADD COLUMN discount_cents integer;`',
            'line 8: `CREATE INDEX orders_customer_created_idx ON orders (customer_id, created_at);`',
          ],
          answer: [0, 3],
          explain: '**Line 2** breaks the deploy itself. Migrations run first, and for the next ten minutes most of the 12 servers still run the old code, whose `UPDATE orders SET total = …` now fails on every quote. A rename is a breaking change for any code that is still running. **Line 8** builds an index on 40 million rows with a plain `CREATE INDEX`, which blocks every write to `orders` until it finishes: minutes of failed checkouts. Use `CREATE INDEX CONCURRENTLY`, outside a transaction.\n\nThe decoys are fine. Since Postgres 11, **line 4** (a constant default) is a metadata change with no table rewrite, and the old code simply ignores the new column. **Line 6** adds a nullable column, also instant. (Both still take a brief exclusive lock, so set a `lock_timeout` in case they queue behind a long query.)',
        },
        {
          q: 'Which lines of **`pricing.js`** and **`deploy.yml`** are defects? Select every defect and nothing that is fine.',
          options: [
            '`pricing.js:8`: `{ fallback: true }` on the flag check',
            '`pricing.js:9`: logging which pricing path served each quote',
            '`deploy.yml:15`: `needs: []` on the deploy job',
            '`deploy.yml:16`: `concurrency: production` on the deploy job',
          ],
          answer: [0, 2],
          explain: '**pricing.js:8** means that whenever the flag service is slow or down, every user gets v2 pricing: an outage of one system becomes an unplanned 100 % rollout of an untested pricing engine. **deploy.yml:15** lets a push to `main` deploy in parallel with its tests, so a red build still reaches production.\n\nThe decoys are good changes. **pricing.js:9** records which path served each order, which is exactly what you need when a customer disputes a price during the rollout. **deploy.yml:16** stops two deploys (and two migration runs) overlapping when two PRs merge a minute apart.',
        },
        {
          q: 'The fifth defect is in the PR description, not the code. What is wrong with "**Rollback:** revert this PR"?',
          options: [
            'Nothing: reverting is always the safest rollback',
            'A revert is slower than fixing forward, so the plan should say "fix forward" instead',
            'Reverting the code does not revert the migration. The old code would write to `total`, which no longer exists, so the "rollback" causes a second outage',
            'A revert also removes the feature flag, and flags should never be removed once added',
          ],
          answer: [2],
          explain: 'A rollback plan has to work with the database as the migration left it. Code can be reverted in minutes; a schema change cannot be undone by a revert, and the old code depends on the old schema. That is why every migration in a deploy should be **backward compatible**: the previous version of the code must run correctly against the new schema. Then rolling the code back is always safe, and the schema is cleaned up in a later deploy.',
        },
        {
          q: 'What is the safe way to ship the rename of `total` to `total_cents`?',
          options: [
            'Run the migration after the rolling restart instead of before it',
            'Take the site down for a maintenance window, so old and new code never run at the same time',
            'Keep one deploy, and make the new code catch "column does not exist" and retry with the old name',
            'Expand and contract over several deploys: add `total_cents`, write to both columns, backfill, switch reads to `total_cents`, stop writing `total`, and only then drop `total`',
          ],
          answer: [3],
          explain: 'Migrating afterwards just moves the outage to the new servers: they write `total_cents` before it exists. Expand and contract keeps every intermediate state compatible with both the version before and the version after, so each step can be deployed and rolled back on its own. It is more PRs, and that is the price of zero downtime. A maintenance window works, but it is downtime you did not need. Often the cheapest answer is not to rename at all: a comment or a view gives you the clear name without moving any data.',
        },
        {
          q: 'What should the flag check on `pricing.js:8` fall back to when the flag service cannot answer?',
          options: [
            '`true`, so customers get the better pricing even when the flag service is down',
            '`false`: when the flag service cannot answer, everyone gets the known-good legacy path, never an untested one at 100 %',
            'No fallback: let the error propagate, so that a flag outage is noticed',
            'Whatever the flag returned last time for that user, cached for ever',
          ],
          answer: [1],
          explain: 'The fallback is what happens during an incident, so it must be the safe, boring path. With `true`, a flag outage is an instant full rollout that skips every stage and every canary check. With no fallback, a flag outage becomes a checkout outage. Caching the last value is good practice, and most SDKs do it, but with a TTL. Cached "for ever", the kill switch stops working, and the kill switch is the reason the flag exists.',
        },
        {
          q: 'The author replies on `deploy.yml:15`: "The tests are flaky and block deploys twice a week." What is the best response?',
          options: [
            'Keep `needs: [test]`. Quarantine the flaky tests with a ticket and an owner and fix them, so the deploy is gated on tests that mean something',
            'Approve: the team can watch the dashboards after each deploy instead',
            'Approve, but add `continue-on-error: true` to the test job so failures are still visible',
            'Have the deploy job re-run the tests up to three times and deploy if any run passes',
          ],
          answer: [0],
          explain: 'Flaky tests are a real problem, and ungating the deploy "solves" it by removing the only automated check before production. `continue-on-error` does the same while looking responsible. "Deploy if any of three runs passes" hides real, intermittent bugs, which are exactly what flaky-looking failures sometimes are. Quarantine the specific flaky tests (visible, owned, time-boxed), keep the gate on the rest, and treat the flakiness as the bug.',
        },
      ],
    },
    {
      id: 'craft-rollout-boss',
      title: 'Boss: a staged rollout controller',
      kind: 'js',
      xp: 240,
      boss: true,
      why: 'Progressive delivery is how teams ship safely several times a day; the controller has to be correct in the unhappy paths, which are the only ones that matter during an incident.',
      tags: ['deployments', 'state machines', 'feature flags', 'reducers'],
      hints: [
        'Validate in `createRollout` and keep a copy of the plan in the state, with `stageIndex: -1` and `stageStartedAt: null`. Every return from `step` builds a new object: `{ ...state, … }`.',
        'Switch on `event.type`. Each case first checks the status it is allowed in, and throws `new Error(`cannot ${event.type} while ${state.status}`)` otherwise. `default` throws too.',
        'Write `enterStage(state, index, at)` (sets status `running`, the percent and `stageStartedAt: at`, and returns a `set-percent` action) and `rollBack(state, reason)`. `start`, `approve` and advancing all use `enterStage`.',
        'For `tick`: in `running`, `paused` or `awaiting-approval`, an unhealthy verdict rolls back first, whatever the status. Only a healthy tick in `running` can move forward.',
        'Moving forward: if `at - stageStartedAt < bakeMs`, nothing happens. Otherwise: last stage means `complete`; a next percent in `approvalBefore` means `awaiting-approval`; otherwise `enterStage(next)`. `resume` sets `stageStartedAt` to the resume time.',
      ],
    },
  ],
});
