import { loadChapter } from '../../load.ts';

const here = import.meta.dirname;

export default loadChapter(here, {
  id: 'sql-shaping-output',
  title: "Shaping Results for APIs",
  summary: "Arrays, jsonb aggregation, building nested API responses in one query, pivots.",
  lessons: [
    {
      id: 'sql-array-agg',
      title: 'Arrays of children without {NULL} or fan-out',
      kind: 'sql',
      xp: 70,
      why: 'A list endpoint with tags and counts is one query, not 1 + 2N, as long as the empty case and the second one-to-many are handled.',
      tags: ['array_agg', 'string_agg', 'fan-out'],
      hints: [
        'Joining both `post_tags` and `comments` to `posts` in one `FROM` multiplies them: 3 tags times 4 comments is 12 rows. Aggregate each relationship on its own.',
        'A correlated or `cross join lateral` subquery per relationship keeps them apart: one for the tags, one for `count(*)` of comments.',
        'Inside the tags subquery, join `post_tags` to `tags` with an inner join: zero rows then means "no tags", not a row of NULLs.',
        'An aggregate over zero rows is NULL: `coalesce(array_agg(tg.name order by tg.name), \'{}\')` and `coalesce(string_agg(tg.name, \', \' order by tg.name), \'\')`.',
      ],
    },
    {
      id: 'sql-jsonb-object-agg',
      title: 'Settings objects with jsonb_object_agg',
      kind: 'sql',
      xp: 75,
      why: 'Key-value tables (settings, feature flags, translations) are read as one object, and building it in SQL is one aggregate, if you know how it treats NULLs.',
      tags: ['jsonb', 'jsonb_object_agg', 'nulls'],
      hints: [
        'Drive the settings from `setting_defaults`, not from `user_settings`: every known key must appear, and retired keys must not.',
        'Per user, `setting_defaults d left join user_settings us on us.user_id = u.id and us.key = d.key`, inside a `cross join lateral` (or group by the user).',
        '`jsonb_object_agg(d.key, coalesce(us.value, d.value))` builds `settings`. JSON `null` is a jsonb value, not SQL NULL, so `coalesce` keeps it.',
        '`coalesce(jsonb_object_agg(us.key, us.value) filter (where us.key is not null), \'{}\')` builds `overrides`: the filter skips the NULL keys, the coalesce handles zero rows.',
      ],
    },
    {
      id: 'sql-unnest-ordinality',
      title: 'Batch lookups in request order with unnest WITH ORDINALITY',
      kind: 'sql',
      xp: 75,
      why: 'Batch loaders need one result per requested id, in order, with holes kept; `= any($1)` gets none of that, and the bug is a result on the wrong key.',
      tags: ['unnest', 'arrays', 'dataloader'],
      hints: [
        'Start from the array, not the table: `from unnest(p_ids) with ordinality as req(id, pos)` gives one row per element with its position.',
        '`left join products p on p.id = req.id` keeps ids with no product; `p.id is not null` is `found`.',
        'Return the requested id (`req.id`), not `p.id`, so a missing product still reports what was asked for. Order by `req.pos`.',
        '`with ordinality` produces a `bigint`; the function returns `pos int`, so cast: `req.pos::int`.',
      ],
    },
    {
      id: 'sql-pivot-filter',
      title: 'Pivots with FILTER',
      kind: 'sql',
      xp: 80,
      why: 'Month-by-column reports are asked for constantly, and pivoting in code or a spreadsheet is where regions with a missing month shift their numbers into the wrong column.',
      tags: ['pivot', 'filter', 'reporting'],
      hints: [
        'Start from `regions` and left join `sales`, so every region gets a row.',
        'Put the quarter in the join condition: `on s.region_code = r.code and s.sold_on >= \'2024-01-01\' and s.sold_on < \'2024-04-01\'`. In a `WHERE` it removes the regions with no sales.',
        'One column per month: `sum(s.amount_cents) filter (where s.sold_on >= \'2024-01-01\' and s.sold_on < \'2024-02-01\')`. `extract(month ...)` alone ignores the year.',
        'Wrap each sum in `coalesce(..., 0)::int`, count with `count(s.id)` (which skips the NULL row), and `order by q1_cents desc, r.name`.',
      ],
    },
    {
      id: 'sql-json-allow-list',
      title: 'Public JSON from an allow-list, never to_jsonb(row)',
      kind: 'sql',
      xp: 75,
      why: '`to_jsonb(row)` publishes every column, including the one a migration adds next year; an allow-list is the only shape that stays private by default.',
      tags: ['jsonb', 'security', 'api design'],
      hints: [
        'A deny-list (`to_jsonb(u) - \'password_hash\'`) is only as good as the next migration. Name the public fields instead.',
        '`jsonb_build_object(\'id\', u.id, \'handle\', u.handle, ...)` with exactly the six public keys.',
        '`jsonb_strip_nulls(...)` around it removes `bio` and `avatar_url` when they are NULL, and leaves `\'\'` alone.',
        'Filter `where u.deleted_at is null` and `order by u.id`.',
      ],
    },
    {
      id: 'sql-nested-order-json',
      title: 'Nested JSON documents: orders with their lines',
      kind: 'sql',
      xp: 85,
      why: 'Returning each order already shaped as the API document removes the 1 + 2N queries behind most slow list endpoints.',
      tags: ['jsonb', 'json aggregation', 'api design'],
      hints: [
        '`jsonb_build_object(\'id\', o.id, \'status\', o.status, \'placedOn\', o.placed_on, ...)` builds the outer object; a `date` becomes `"2024-05-01"`.',
        'The customer is a nested `jsonb_build_object(\'id\', c.id, \'name\', c.name)`; the lines are a `jsonb_agg` of objects in a `cross join lateral` subquery per order.',
        'Order inside the aggregate: `jsonb_agg(jsonb_build_object(...) order by oi.id)`. The outer `ORDER BY` does not reach it.',
        'Use `oi.unit_cents`, not `p.price_cents`, and `coalesce(jsonb_agg(...), \'[]\')` and `coalesce(sum(...), 0)` for an order with no lines.',
      ],
    },
    {
      id: 'sql-nested-three-levels',
      title: 'Three levels deep: customer, orders, items',
      kind: 'sql',
      xp: 90,
      why: 'Includes like `?include=orders.items` are where the naive query hits "aggregate function calls cannot be nested"; one correlated subquery per level is the pattern.',
      tags: ['jsonb', 'subqueries', 'api design'],
      hints: [
        'Write the function as `select jsonb_build_object(...) from customers c where c.id = p_customer_id`: no matching row means the function returns NULL.',
        'Each nested value is its own subquery: `\'orders\', (select jsonb_agg(...) from orders o ... where o.customer_id = c.id)`.',
        'Inside the orders subquery, `cross join lateral` a subquery that aggregates that order\'s items and sums its lines.',
        '`orderCount` and `lifetimeCents` are separate scalar subqueries; the latter joins items and filters `o.status = \'paid\'`. Every aggregate that can see zero rows needs a `coalesce`.',
      ],
    },
    {
      id: 'sql-shaping-judgement',
      title: 'Judgement: shaping JSON in the database',
      kind: 'quiz',
      xp: 70,
      why: 'JSON built in SQL moves serializer decisions (public fields, number precision, key order, array order) into queries, where they are easy to get wrong silently.',
      tags: ['jsonb', 'api design', 'judgement'],
      quiz: [
        {
          q: 'An endpoint returns `jsonb_build_object(\'id\', o.id, ...)` where `o.id` is a `bigint`. Ids have passed 2^53. What does a JavaScript client get?',
          options: [
            'The request fails: Postgres refuses to put a bigint larger than 2^53 into jsonb',
            'The id as a JSON string, because jsonb stores large integers as strings',
            'A JSON number that `JSON.parse` silently rounds to the nearest double, so some ids point at the wrong row',
            'The exact value, because modern JavaScript parses large JSON integers as BigInt',
          ],
          answer: [2],
          explain: 'jsonb stores numbers as `numeric`, so the database side is exact and the text is exact. `JSON.parse` turns every number into a double, and above 2^53 neighbouring integers collapse to the same value: no error, just the wrong id. Send such ids as strings (`o.id::text`), which is what most public APIs with 64-bit ids do.',
        },
        {
          q: 'A snapshot test compares the response text byte for byte. It breaks when `json_build_object` is changed to `jsonb_build_object`, though every value is the same. Why?',
          options: [
            'jsonb does not keep key order (it stores keys sorted, shorter keys first) and keeps only the last of duplicate keys; json keeps the text exactly as built',
            'jsonb escapes non-ASCII characters and json does not',
            'jsonb converts integers to floats, so `1` becomes `1.0`',
            'jsonb adds a trailing newline to every document',
          ],
          answer: [0],
          explain: '`json` is text that was checked to be valid; `jsonb` is a parsed binary form that normalises: key order is its own, duplicate keys collapse, whitespace goes. Clients should not depend on key order, and a snapshot test should compare parsed values, not text. Use jsonb when you will query or index it, and either when you only build output.',
        },
        {
          q: 'Which of these reliably returns an order\'s items as a JSON array in `order_items.id` order?',
          options: [
            '`select jsonb_agg(x) from (...) x` with an `order by oi.id` on the outer query',
            'An index on `order_items (order_id, id)`, so the rows are read in that order',
            '`jsonb_agg(x) from (select ... order by oi.id) x`: the subquery sorts before the aggregate sees the rows',
            '`jsonb_agg(x order by oi.id)`',
          ],
          answer: [3],
          explain: 'Only an `order by` inside the aggregate call is a guarantee. An outer `order by` sorts the result rows, not the elements inside one aggregate. A sorted subquery feeding the aggregate usually works today, but the planner is free to reorder (a parallel plan or a hash join will), and an index only describes one possible plan.',
        },
        {
          q: 'A new endpoint serves `select to_jsonb(u) - \'password_hash\' as body from users u`. What is the strongest review comment?',
          options: [
            'Use `row_to_json(u)` instead, which is faster',
            'Name the public fields with `jsonb_build_object`: a column added to `users` later is public the moment it exists, and nothing in this query changes to warn anyone',
            'Also remove `email`, and it is fine',
            'Move the query into a view so it can be reviewed separately',
          ],
          answer: [1],
          explain: 'A deny-list fails open: the dangerous change is a migration in another pull request, and this query, which is where the leak happens, does not change. An allow-list fails closed: a new column stays private until someone adds it here on purpose. Removing `email` fixes today and not next year; a view with the same expression leaks the same way.',
        },
        {
          q: 'A report returns `jsonb_build_object(\'total\', sum(amount))` where `amount` is `numeric(12,2)`. Which statements are true? (Select all that apply.)',
          options: [
            'The value is exact inside Postgres and in the JSON text',
            'Once a JavaScript client parses it, it is a binary double, and further arithmetic there can show errors like `0.30000000000000004`',
            'jsonb rounds `numeric` to 2 decimal places',
            'Sending integer cents, or the decimal as a string, keeps money exact end to end',
          ],
          answer: [0, 1, 3],
          explain: 'jsonb keeps `numeric` exactly and the JSON text is exact, but the client\'s parser decides the rest: in JavaScript every JSON number is a double. For money, integer cents stay exact up to 2^53 (about 90 trillion pounds), and a decimal string lets the client use a decimal library. jsonb does no rounding of its own.',
        },
        {
          q: 'What are real costs of building nested API responses in SQL rather than in the application? (Select all that apply.)',
          options: [
            'The work runs on the database, usually the hardest tier to scale out, so very large documents built on every request compete with every other query',
            'The response shape now lives in SQL, so changing it means changing a query or a function, and the team must be able to review and test SQL',
            'The result cannot be tested automatically',
            'Postgres cannot nest arrays more than two levels deep',
          ],
          answer: [0, 1],
          explain: 'Shaping in SQL removes round trips and N+1 queries, which is usually a large win; the costs are where the CPU is spent and who owns the shape. It is testable like any query (this chapter is graded by tests), and nesting depth is limited only by how many subqueries you write.',
        },
      ],
    },
    {
      id: 'sql-api-response-boss',
      title: 'Boss: a paginated API response in one function',
      kind: 'sql',
      xp: 240,
      boss: true,
      why: 'The busiest endpoints are paginated lists of nested documents; building one in a single round trip with correct paging and empty cases uses everything in this chapter.',
      tags: ['jsonb', 'pagination', 'api design', 'lateral'],
      hints: [
        'Clamp the limit first in a CTE: `least(greatest(coalesce(p_limit, 20), 1), 50)`.',
        'Select the candidate orders with `status <> \'draft\'`, `(p_before_id is null or o.id < p_before_id)`, `order by o.id desc`, and `limit n + 1`. The page is the first `n` of those.',
        '`nextBefore` is the smallest id on the page only when the candidates numbered more than `n`; otherwise JSON `null` (a `case` with no `else`).',
        'Per order, aggregate items and tags in two separate `cross join lateral` subqueries, each with `order by` inside the aggregate and a `coalesce(..., \'[]\')`.',
        'Wrap it in `select jsonb_build_object(\'customer\', ..., \'orders\', coalesce((select jsonb_agg(... order by s.id desc) ...), \'[]\'), \'page\', ...) from customers c where c.id = p_customer_id`, so an unknown customer returns NULL.',
      ],
    },
  ],
});
