import { loadChapter } from '../../load.ts';

const here = import.meta.dirname;

export default loadChapter(here, {
  id: 'js-async-patterns',
  title: "Async Patterns II",
  summary: "Semaphores, throttle and debounce, async iterators, composed aborts, deadlines, priority pools.",
  lessons: [
    {
      id: 'js-semaphore',
      title: 'A fair semaphore',
      kind: 'js',
      xp: 85,
      why: '"At most 5 connections to the payments API" is a process-wide limit, and a semaphore that leaks one permit per error deadlocks the service by lunchtime.',
      tags: ['async', 'concurrency', 'semaphore', 'cancellation'],
      hints: [
        'State is two things: a count of free permits and a FIFO array of waiters. Acquire takes a permit if one is free **and nobody is queued**; otherwise it pushes a waiter and returns a promise.',
        'Make the release function from a factory that closes over a `released` flag: `let released = false; return () => { if (released) return; released = true; handOff(); }`.',
        'Hand-off, not increment: on release, `shift()` the first waiter and resolve it with a fresh release function. Only when the queue is empty does `available` go up. That is what stops a newcomer barging past the queue.',
        'For abort, store the waiter entry, add an `abort` listener that splices that entry out and rejects with `signal.reason`, and remove the listener when the waiter is granted a permit.',
        '`use(fn)` is `const release = await this.acquire(); try { return await fn(); } finally { release(); }` — the `await` inside `try` is what catches a synchronous throw too.',
      ],
    },
    {
      id: 'js-debounce',
      title: 'Debounce with cancel and flush',
      kind: 'js',
      xp: 80,
      why: 'Every search box, autosave and resize handler needs one, and the copy-pasted version double-fires, loses `this`, and cannot be cancelled on unmount.',
      tags: ['async', 'timers', 'debounce', 'ui'],
      hints: [
        'Two pieces of state carry the whole thing: the current timer id (non-null means "a burst is in progress") and the pending `{ thisArg, args }` of the latest call not yet delivered.',
        'On every call: note whether this call starts a burst (`timer === null`), clear the old timer, and set a new one for `wait` ms. The timer callback ends the burst.',
        'Leading: if the call starts a burst and `leading` is on, call `fn.apply(this, args)` right away and leave `pending` empty. Otherwise store `pending = { thisArg: this, args }`. The trailing call then only happens if something is pending — which is exactly "the burst had more than one call".',
        'Write one `endBurst()` that sets `timer = null`, runs `fn.apply(pending.thisArg, pending.args)` if `trailing && pending`, clears `pending`, and returns the result. The timer calls it; `flush()` clears the timer and calls it too; `cancel()` clears the timer and both pieces of state.',
      ],
    },
    {
      id: 'js-throttle',
      title: 'A throttle that keeps the last call',
      kind: 'js',
      xp: 75,
      why: 'Scroll trackers, presence pings and progress bars need a steady rate, and the one-line throttle silently drops the final position.',
      tags: ['async', 'timers', 'throttle', 'ui'],
      hints: [
        'You do not need a clock at all. A window is "a timer is running": `timer !== null` means calls must wait.',
        'Idle call: run `fn.apply(this, args)` now and start a `wait`-ms timer. Call inside a window: overwrite a single `kept = { thisArg: this, args }` slot.',
        'When the timer fires: set `timer = null`; if something was kept, clear the slot, run it, and **start a new timer** — the trailing run is a run, so it opens its own window.',
        '`cancel()` clears the timer, sets it to `null`, and empties the kept slot.',
      ],
    },
    {
      id: 'js-latest-wins',
      title: 'Latest request wins',
      kind: 'js',
      xp: 85,
      why: 'Out-of-order responses are why a search box shows results for the wrong query; debouncing hides the race, it does not fix it.',
      tags: ['async', 'race conditions', 'cancellation', 'ui'],
      hints: [
        'Keep one piece of state: the call that is still allowed to deliver — its `AbortController` and its promise\'s `reject`.',
        'Return `new Promise((resolve, reject) => …)` yourself instead of returning `fn`\'s promise. That way you can reject it on your own schedule, before `fn` settles.',
        'To supersede: take the current entry, clear it, `controller.abort(reason)` and `reject(reason)` with the same `new SupersededError()`. `run.cancel` is exactly that function.',
        'When `fn`\'s promise settles, deliver only if the entry is still current: `if (current === entry) { current = null; resolve(value); }`. A superseded call\'s promise has already been rejected, and a second resolve/reject is ignored anyway.',
        'Call `fn` inside `try`/`catch` and convert a synchronous throw with `Promise.reject(error)` so it flows through the same path.',
      ],
    },
    {
      id: 'js-single-flight',
      title: 'Single-flight: coalesce concurrent calls',
      kind: 'js',
      xp: 80,
      why: 'A cache stampede turns one expired key into 400 identical database queries at peak traffic; coalescing in-flight calls is the standard fix.',
      tags: ['async', 'caching', 'deduplication', 'promises'],
      hints: [
        'A `Map` from key to the in-flight **promise** is the whole data structure. If the key is present, return that exact promise.',
        'Call `fn()` inside `try`/`catch` and wrap the result with `Promise.resolve(...)`; in the `catch`, use `Promise.reject(error)`. Store the promise before returning it.',
        'Cleanup must run on both outcomes without creating an orphan: `promise.then(cleanup, cleanup)` — the promise it returns always fulfils, unlike `promise.finally(cleanup)`.',
        'Inside `cleanup`, only delete if the entry is still yours: `if (map.get(key) === promise) map.delete(key)`. After `forget`, a newer promise may own the key.',
      ],
    },
    {
      id: 'js-async-channel',
      title: 'A push-to-pull async channel',
      kind: 'js',
      xp: 95,
      why: 'Turning sockets, watchers and callbacks into `for await` loops is everyday Node work, and the naive adapter loses values, hangs readers or leaks listeners.',
      tags: ['async iterators', 'backpressure', 'streams', 'cancellation'],
      hints: [
        'Two queues, never both non-empty at once: a buffer of values nobody has asked for yet, and a list of `{ resolve, reject }` for `next()` calls nobody has answered yet.',
        '`push`: if a waiter exists, `shift()` it and resolve `{ value, done: false }`; otherwise buffer. The return value is `buffer.length < highWaterMark` after that.',
        '`next`: buffered value first; then a stored failure (reject once, then forget it); then `done` if the channel is no longer open; otherwise push a waiter and return its promise.',
        'Track state as `open`, `closed` (producer ended — `close`/`fail`) and `cancelled` (consumer ended — `return`). `push` throws when `closed`, returns `false` when `cancelled`. `return` calls `onCancel` only when moving from `open`.',
        'When the channel closes, waiters can only exist if the buffer is empty — so settle them all at once: the first rejects with the failure if there is one, the rest resolve `{ value: undefined, done: true }`.',
      ],
    },
    {
      id: 'js-with-timeout',
      title: 'Timeouts that actually stop the work',
      kind: 'js',
      xp: 90,
      why: '`Promise.race` with a timer stops waiting but not working, leaks a timer per call, and ignores the caller\'s own cancellation.',
      tags: ['async', 'AbortSignal', 'timeouts', 'resource leaks'],
      hints: [
        'Return `new Promise((resolve, reject) => …)` and give yourself one `finish(settle, value)` helper guarded by a `settled` flag. Every path — result, error, timeout, parent abort — goes through it.',
        '`finish` does the cleanup before settling: `timers.clearTimeout(timer)` and `signal?.removeEventListener("abort", onParentAbort)`. Because the listener must be removable, it has to be a named function you keep a reference to — `{ once: true }` only removes a listener after it fires.',
        'The timer callback builds `new TimeoutError(`timed out after ${ms}ms`)`, calls `controller.abort(error)`, then `finish(reject, error)`. The parent listener does the same with `signal.reason`.',
        'Check `signal?.aborted` before anything else and return `Promise.reject(signal.reason)` without calling `fn`. Call `fn` in `try`/`catch` so a synchronous throw becomes `finish(reject, error)`.',
      ],
    },
    {
      id: 'js-async-pitfalls',
      title: 'Async code review',
      kind: 'quiz',
      xp: 60,
      why: 'These are the async bugs that pass review and fail under load; spotting them in a diff is a core mid-level skill.',
      tags: ['async', 'promises', 'code review'],
      quiz: [
        {
          q: 'What does this log?\n\n```js\nconst ids = [1, 2, 3];\nconst saved = [];\nids.forEach(async (id) => { await save(id); saved.push(id); });\nconsole.log(saved.length);\n```',
          options: ['3', '0', 'It depends on how fast `save` is', 'It throws: `forEach` does not accept async callbacks'],
          answer: [1],
          explain: '`forEach` calls each callback and ignores its return value — here a promise. All three `save` calls start, nothing waits for them, and the log runs synchronously before any `await` resumes, however fast `save` is. Use `for...of` with `await` (sequential) or `await Promise.all(ids.map(...))` (parallel). Errors are lost too: a rejection from a `forEach` callback is an unhandled rejection.',
        },
        {
          q: '`const user = await Promise.race([fetchUser(id), sleep(2000).then(() => { throw new TimeoutError(); })]);` — the fetch takes 30 s. What is true after the race rejects at 2 s? (select all)',
          options: [
            'The HTTP request is still in flight and will complete or fail on its own',
            'The HTTP request is cancelled, because its promise lost the race',
            'If `fetchUser` later rejects, nothing handles that rejection',
            'If `fetchUser` later rejects, `Promise.race` has already attached a handler, so it is not reported as unhandled',
          ],
          answer: [0, 3],
          explain: 'Promises are not cancellable: losing a race changes nothing about the work behind them — the socket, the query, the CPU all keep going. That is why the timeout has to abort a signal the work listens to. `Promise.race` does subscribe to every input, so a late rejection of the loser is handled (and ignored), not reported as unhandled.',
        },
        {
          q: 'A consumer does `for await (const msg of channel) { if (msg.type === "done") break; }`. What happens on `break`?',
          options: [
            'Nothing; the iterator stays open until it is garbage collected',
            'The loop drains every remaining value first, then exits',
            'The loop calls `channel.throw()` with a `BreakError`',
            'The loop calls `channel.return()`, giving the iterator a chance to clean up',
          ],
          answer: [3],
          explain: '`for...of` and `for await...of` call the iterator\'s `return()` method on `break`, on `return`, and when an exception escapes the loop body. For an `async function*` generator that runs its `finally` blocks, which is where you close the socket or remove the listener. A hand-written iterator without `return()` gets no such signal — and leaks.',
        },
        {
          q: 'Which is the right tool for each? A) Save a draft 1 s after the user stops typing. B) Report scroll position to analytics at most every 250 ms during a scroll. C) Two components request `/me` at mount.',
          options: [
            'A throttle, B debounce, C single-flight (coalesce)',
            'A debounce, B debounce, C cache the result forever',
            'A debounce, B throttle, C single-flight (coalesce)',
            'A throttle, B throttle, C latest-wins',
          ],
          answer: [2],
          explain: 'Debounce waits for quiet, which is what "after they stop typing" means; during a continuous scroll it would never fire, so B needs a throttle, which fires at a steady rate. Two identical concurrent requests should share one in-flight promise; caching forever would serve a stale user after a profile edit, and latest-wins would abort the first component\'s request.',
        },
        {
          q: 'Cleanup code in a promise helper:\n\n```js\nconst p = doWork();\np.finally(() => inFlight.delete(key));\nreturn p;\n```\n\nThe caller does `await helper().catch(handle)`. `doWork()` rejects. What happens?',
          options: [
            'Nothing unusual: the caller handles the rejection',
            'The caller handles it, but an unhandled rejection is still reported',
            '`finally` swallows the error, so the caller\'s `catch` never runs',
            'The key is never deleted because `finally` only runs on success',
          ],
          answer: [1],
          explain: '`p.finally(...)` returns a new promise that rejects with the same error, and nothing is attached to that new promise. The caller handled `p`, not the derived one, so Node reports an unhandled rejection (and by default, since Node 15, exits the process). Use `p.then(cleanup, cleanup)`, or return the `finally` chain itself so the caller\'s handler is attached to it.',
        },
        {
          q: 'A helper does `signal.addEventListener("abort", onAbort, { once: true })` and never removes it. Background jobs pass the server\'s long-lived shutdown signal. After a day of jobs that all finished normally, what is the state?',
          options: [
            'Every finished job left a listener, and its closure, on the shutdown signal',
            'Clean: `{ once: true }` removed each listener when its job finished',
            'The first job to finish aborted the shutdown signal',
            'Only the first listener was registered; later jobs ignore shutdown',
          ],
          answer: [0],
          explain: '`{ once: true }` removes a listener after it *fires*. On a signal that never aborts during normal operation, every listener — and everything its closure references — lives until the process exits. Node eventually warns with `MaxListenersExceededWarning`. Remove the listener explicitly when the work settles.',
        },
      ],
    },
    {
      id: 'js-priority-pool',
      title: 'BOSS: priority worker pool',
      kind: 'js',
      xp: 230,
      boss: true,
      why: 'Interactive work stuck behind 80,000 background jobs is a real outage; priority, cancellation and live resizing are what production job runners are made of.',
      tags: ['async', 'concurrency', 'priority queue', 'cancellation'],
      hints: [
        'Keep the queue **sorted** on insert, best first. Give every entry a sequence number from a counter so equal priorities keep their arrival order. Then starting a task is just `queue.shift()`.',
        'One `#drain()` loop does all the starting: `while (!paused && running < concurrency && queue.length)`. Call it from `run`, when a task settles, from `resume`, and from `setConcurrency` — which is all it takes for raising the limit to start work at once.',
        'Starting an entry: remove its abort listener, `running++`, call the task in `try`/`catch`, then `result.then(entry.resolve, entry.reject).then(() => { running--; drain(); checkIdle(); })`. The failure goes to that entry only.',
        'Per-task abort: the listener finds the entry in the queue; if it is still there, splice it out, remove the listener, reject with `signal.reason`, and check idle. If it has already started, it is not in the queue and nothing happens.',
        'Idle means `running === 0 && queue.length === 0`. Keep an array of waiting resolvers and flush it from a `#checkIdle()` called after every settle, every abort removal and every `clear`.',
      ],
    },
  ],
});
