import { loadChapter } from '../../load.ts';

const here = import.meta.dirname;

export default loadChapter(here, {
  id: 'react-forms-advanced',
  title: "Forms, Advanced",
  summary: "Multi-step wizards, field arrays, async validation, dirty tracking, unsaved-changes guards.",
  lessons: [
    {
      id: 'react-field-array',
      title: 'Field arrays: rows that come and go',
      kind: 'react',
      xp: 85,
      why: '"Add another" rows are in every admin form, and index keys plus forgotten focus make them quietly broken.',
      tags: ['forms', 'keys', 'focus', 'lists'],
      hints: [
        'Store rows as `{ id, name, email }`, with ids from a counter in a `useRef`, and render `key={row.id}`.',
        'The element to focus after Add does not exist yet in the click handler. Record the target in a ref and focus it in an effect that runs when the rows change.',
        'Keep the name inputs in a `Map` from row id to element, filled by ref callbacks.',
        'For Remove: `const remaining = rows.filter((_, i) => i !== index); const heir = remaining[index] ?? remaining[remaining.length - 1];`. No heir means focus the Add button.',
      ],
    },
    {
      id: 'react-uncontrolled-formdata',
      title: 'Uncontrolled forms with FormData',
      kind: 'react',
      xp: 75,
      why: 'Not every form needs state per field; reading the DOM once on submit is simpler, and it is how server actions work.',
      tags: ['forms', 'uncontrolled', 'formdata'],
      hints: [
        'Give every field a `name` and a `defaultValue` / `defaultChecked`. Do not pass `value`, or React takes control of it.',
        'Save `const form = event.currentTarget;` on the first line of the handler. After an `await`, `event.currentTarget` is `null`.',
        '`data.getAll(\'topics\')` for the checkbox group, `data.has(\'subscribe\')` for the single checkbox, and `Number(data.get(\'rating\'))` for the radio group.',
        'Wrap the call in `try { await onSubmit(...); form.reset(); } catch { setFailed(true); } finally { setSending(false); }`, and check `form.checkValidity()` before any of it.',
      ],
    },
    {
      id: 'react-money-input',
      title: 'A money input: text versus value',
      kind: 'react',
      xp: 90,
      why: 'Currency fields are where floating point costs real money and where controlled inputs fight the user\'s typing.',
      tags: ['forms', 'controlled inputs', 'parsing'],
      hints: [
        'Keep the text in state and derive the cents from it. The cents are what `onChange` reports; the text is what the input shows.',
        'Parse with a regex, `/^(\\d*)(?:\\.(\\d{0,2}))?$/`, and build cents from the two captured strings as integers: `units * 100 + Number(fraction.padEnd(2, \'0\'))`.',
        'To notice a new `valueCents` from outside, keep the last one you saw in state and compare during render. Replace the text only when the text does not already parse to the new value.',
        'Format on focus (no separators) and on blur (`toLocaleString(\'en-US\')` on the whole units), but only when the current text parses.',
      ],
    },
    {
      id: 'react-async-validation',
      title: 'Async validation without races',
      kind: 'react',
      xp: 95,
      why: '"Is this username taken?" touches debouncing, caching, stale responses and submit ordering at once; get one wrong and bad data reaches the server.',
      tags: ['forms', 'async', 'validation', 'race conditions'],
      hints: [
        'Keep a ref with the current input value, so code that runs after an `await` can ask "is this still the value I checked?".',
        'Two maps in refs: answers you already have (`name -> boolean`) and checks in flight (`name -> promise`). A failure is removed from the second and never added to the first.',
        'Write one `lookUp(value)` used by both blur and submit: known answer shows at once; otherwise show `Checking…`, await the (shared) check, and return `null` if the value has changed.',
        'Guard submit with a `busy` ref set before the first `await` and cleared in `finally`. State would not be updated yet for a second submit in the same tick.',
      ],
    },
    {
      id: 'react-dirty-tracking',
      title: 'Dirty tracking and partial saves',
      kind: 'react',
      xp: 85,
      why: 'Knowing exactly what changed decides what to send, what to warn about, and whether an edit made mid-save survives.',
      tags: ['forms', 'state', 'patch'],
      hints: [
        'Keep two states initialised from `profile`: the baseline and the current values. No effect copies the prop in later.',
        'Derive `changes` on every render by comparing each field with `Object.is`, and `dirty` from whether `changes` is empty.',
        'In submit, capture `const sent = values` before the `await`, and on success `setBaseline(sent)`, not the values on screen afterwards.',
        'The status is a small priority chain: `saving ? \'Saving…\' : dirty ? \'Unsaved changes\' : note`.',
      ],
    },
    {
      id: 'react-unsaved-guard',
      title: 'Guarding unsaved changes',
      kind: 'react',
      xp: 85,
      why: 'Losing ten minutes of typing to a stray click on Close is the kind of bug users remember.',
      tags: ['forms', 'hooks', 'events'],
      hints: [
        'Two jobs: an effect on `[when]` that adds the `beforeunload` listener only when `when` is true (and removes it in the cleanup), and a `guard` function.',
        'For a stable `guard`, keep `{ when, message, confirm }` in a ref updated after every render, and create `guard` once with `useCallback(…, [])` reading from the ref.',
        'The listener: `(event) => { event.preventDefault(); event.returnValue = \'\'; }`.',
        'In `NoteEditor`, keep `saved` in state, pass `text !== saved` as `when`, and after `await onSave(sent)` call `setSaved(sent)` inside a `try`.',
      ],
    },
    {
      id: 'react-form-wizard',
      title: 'A multi-step checkout',
      kind: 'react',
      xp: 100,
      why: 'Wizards split long forms, and they lose values, validate the wrong step and leave focus behind unless designed for it.',
      tags: ['forms', 'wizard', 'validation', 'focus'],
      hints: [
        'Hold all values in one state object in the wizard itself. Steps are just which fields are rendered.',
        'Describe the steps as data, `[{ title, fields: [...] }]`, so Next validates `STEPS[step].fields` and nothing else.',
        'Move focus to the heading in an effect on `[step]`, comparing against a ref that starts at the initial step (so the first render does not steal focus).',
        'One form, one `onSubmit`: on the last step it places the order, otherwise it validates and advances. Guard the order with a `placing` state and `disabled={placing}`.',
      ],
    },
    {
      id: 'react-form-ux',
      title: 'Form decisions that matter to users',
      kind: 'quiz',
      xp: 60,
      why: 'Validation timing, autofill and double submits are decided in code review, not by the framework.',
      tags: ['forms', 'ux', 'accessibility'],
      quiz: [
        {
          q: 'When should a field\'s validation message first appear?',
          options: [
            'On every keystroke, from the first character',
            'When the user leaves the field (or tries to submit), and after that update live as they fix it',
            'Only after submit, and only until the next submit',
            'Never: disable the submit button until the form is valid instead',
          ],
          answer: [1],
          explain: 'Errors on the first keystroke punish people for not having finished typing. Errors only on submit make them hunt, and do not tell them when they have fixed it. "Late to complain, quick to forgive" (validate on blur, then live) is the usual answer. A permanently disabled submit button explains nothing and cannot be focused, so keyboard and screen reader users do not even learn it exists.',
        },
        {
          q: 'Which statements about `disabled` and `readOnly` are true? Select all that apply.',
          options: [
            'A disabled input is left out of the submitted form data',
            'A readOnly input is submitted, and can still be focused and its text selected and copied',
            '`readOnly` works on checkboxes, radios and selects the same way it works on text inputs',
            'A disabled input stays in the Tab order so screen reader users can find it',
          ],
          answer: [0, 1],
          explain: 'Disabled controls are not submitted and not focusable, which surprises people who disable a field "to show it cannot be changed" and then find it missing on the server. `readOnly` keeps it in the submission and the Tab order, but only applies to text-like inputs and textareas: a readOnly checkbox can still be toggled.',
        },
        {
          q: 'A sign-up form has email, new password and one-time code fields. Which attributes help browsers and password managers fill it in correctly? Select all that apply.',
          options: [
            '`autocomplete="off"` on the password, for security',
            '`autocomplete="email"` on the email field',
            '`autocomplete="new-password"` on the password field',
            '`autocomplete="one-time-code"` on the code field',
          ],
          answer: [1, 2, 3],
          explain: '`new-password` tells password managers to suggest a strong password and save it; `current-password` is the sign-in equivalent. `one-time-code` lets phones offer the code from an SMS. `autocomplete="off"` on passwords is ignored by most browsers and, where honoured, pushes users to weaker, reused passwords.',
        },
        {
          q: 'How should you build a 6-digit verification code field?',
          options: [
            '`type="number"` so only digits can be typed',
            '`type="tel"`, since it shows a phone keypad',
            '`type="number"` with `min="0"` and `max="999999"`',
            '`type="text"` with `inputMode="numeric"`, `autocomplete="one-time-code"` and a `pattern` of six digits',
          ],
          answer: [3],
          explain: 'A code is a string of digits, not a number: `type="number"` drops leading zeros (`012345` becomes `12345`), accepts `e`, adds spinner buttons and changes the value on scroll. `inputMode="numeric"` gets the digit keypad without any of that, and `type="tel"` misstates what the field is to assistive technology.',
        },
        {
          q: 'Client validation passed, but the API answers `422` with `{ email: "already registered" }`. What should the form do?',
          options: [
            'Show a generic "Something went wrong" toast and clear the form',
            'Retry the request once, since 4xx responses are often transient',
            'Show the message on the email field with the same `aria-invalid`/`aria-describedby` wiring as client errors, keep every value, and focus the field',
            'Log it and let the user try again; the server validates anyway',
          ],
          answer: [2],
          explain: 'Server-side validation is the authority (uniqueness can only be checked there), so its errors deserve the same presentation as client errors: on the field, announced, focused. Clearing the form throws away the user\'s work, and retrying a 422 just gets the same answer.',
        },
        {
          q: 'Which of these actually prevent a duplicate order when a user double-clicks Pay or the network is slow? Select all that apply.',
          options: [
            'Ignoring submits while the first request is pending (a guard in the handler, and a disabled button)',
            'Sending an idempotency key generated once per checkout attempt, so the server can recognise a retry',
            'Debouncing the click handler by 300 ms',
            'Showing a spinner so the user knows to wait',
          ],
          answer: [0, 1],
          explain: 'The in-flight guard stops the double click. It cannot stop a retry after a timeout or a refresh, and only the server can recognise those, which is what an idempotency key is for. A debounce only narrows the window, and a spinner relies on the user noticing.',
        },
      ],
    },
    {
      id: 'react-invoice-editor',
      title: 'Boss: an invoice editor',
      kind: 'react',
      xp: 240,
      boss: true,
      why: 'Real forms combine field arrays, derived totals, validation timing and server errors, and the bugs live where they meet.',
      tags: ['forms', 'validation', 'field arrays', 'server errors'],
      hints: [
        'Lines are `{ id, description, quantity, unitPrice }` with raw text; totals and errors are derived on every render, never stored.',
        'An `attempted` flag, set on the first submit, turns client messages on. A field shows its client message if it has one, else a server message.',
        'Store server messages by `lineId:field`, never by index. At submit time capture `const idAtIndex = lines.map((l) => l.id)`, and translate `lines.<i>.<field>` through it when the promise rejects.',
        'After the `await`, the lines may have changed: read them from a ref kept up to date by an effect, and drop messages for ids that no longer exist.',
        'Focus the first invalid input by walking lines in order and fields in order, looking elements up in a `Map` of refs keyed the same way as the messages.',
      ],
    },
  ],
});
