import { loadChapter } from '../../load.ts';

const here = import.meta.dirname;

export default loadChapter(here, {
  id: 'ts-typing-real-code',
  title: "Typing Real Code",
  summary: "Event maps, reducers, API clients, function overloads, declaration files for untyped code.",
  lessons: [
    {
      id: 'ts-typed-reducer',
      title: 'Actions and reducers',
      kind: 'typecheck',
      xp: 85,
      why: 'Action creators that return `type: string` make every reducer take `any`; deriving the action union from the creators keeps reducers, dispatchers and exhaustive switches in sync.',
      tags: ['discriminated unions', 'reducers', 'as const'],
      hints: [
        'Hover over `cartActions.add` in the starter: `type` is `string`. Keep it literal with `type: \'cart/add\' as const` (or `as const` after the whole returned object).',
        '`ActionsOf<M>` is the union of the creators\' return types: index `M` with `keyof M` to get the union of creators, then take `ReturnType` of that. Constrain `M` to `Record<string, (...args: never[]) => { type: string }>`.',
        'Make `CartState` immutable with `readonly lines: readonly CartLine[]`, type the reducer\'s `action` as `CartAction`, and end the `switch` with `default: return assertNever(action)` where `assertNever(x: never): never` throws.',
        '`bindActions<M extends …>(creators: M, dispatch: (action: ActionsOf<M>) => void): { [K in keyof M]: (...args: Parameters<M[K]>) => void }`. Build the result in a loop over `Object.keys(creators) as (keyof M)[]`, asserting the accumulator\'s type and the created action `as ActionsOf<M>`.',
      ],
    },
    {
      id: 'ts-parallel-tasks',
      title: 'Typed parallel loading',
      kind: 'typecheck',
      xp: 80,
      why: 'Every page loader runs several requests at once; a keyed helper typed `Record<string, unknown>` puts a stale cast at every call site.',
      tags: ['mapped types', 'infer', 'promises', 'variadic tuples'],
      hints: [
        'Start with `ResultOf<F> = F extends () => Promise<infer V> ? V : never` (or `Awaited<ReturnType<F>>` behind a check that `F` is a task).',
        '`Results<T> = { [K in keyof T]: ResultOf<T[K]> }`. Because it maps over a type parameter, it preserves tuples as tuples as well as objects as objects.',
        'Constrain the inputs so non-tasks are errors: `parallel<T extends Record<string, Task>>(tasks: T): Promise<Results<T>>`, and `all<T extends Task[]>(...tasks: T): Promise<Results<T>>` — a rest parameter typed by a tuple parameter infers a tuple.',
        '`settle` returns `Promise<{ [K in keyof T]: Settled<ResultOf<T[K]>> }>`. In each body, the value built from `Object.fromEntries` (or `Promise.all`) needs one `as` to the declared return type.',
      ],
    },
    {
      id: 'ts-declare-module',
      title: 'Declaring untyped modules',
      kind: 'typecheck',
      xp: 90,
      why: 'Old internal packages, vendor SDKs, asset imports and bundler constants all need declarations; the one-line shorthand types them as `any` and the `any` spreads.',
      tags: ['declaration files', 'ambient modules', 'commonjs'],
      hints: [
        'Keep the file free of top-level `import`/`export`. Replace each shorthand with a block: `declare module \'feature-flags-client\' { export function createClient(options: ClientOptions): FlagClient; … }`.',
        'For the CommonJS package, declare a function and a namespace with the same name inside the module, then `export = slugify;`. The namespace holds `interface Options`, `const defaults: Required<Options>` and `function extend(charMap: Record<string, string>): void`.',
        'For `on`, map event names to argument tuples, `interface FlagEvents { ready: []; error: [error: Error]; update: [changedFlags: string[]] }`, then `on<E extends keyof FlagEvents>(event: E, listener: (...args: FlagEvents[E]) => void): () => void`. Three overloads also work.',
        'Wildcards: `declare module \'*.svg\' { const url: string; export default url; }` and, for CSS modules, a default export typed `{ readonly [className: string]: string }`. Globals: `declare const __APP_VERSION__: string;`.',
      ],
    },
    {
      id: 'ts-api-client-errors',
      title: 'An API client that returns its failures',
      kind: 'ts',
      xp: 90,
      why: 'Network errors, error statuses, HTML error pages and wrong-shaped JSON are four different failures; a client that throws or returns them as `T` hides all four from the type checker.',
      tags: ['fetch', 'discriminated unions', 'errors', 'boundaries'],
      hints: [
        'Structure `request` as four steps, each able to return early: call `fetch` in a try/catch, check `response.ok`, parse the text, run the parser.',
        'Join the URL by trimming: `baseUrl.replace(/\\/+$/, \'\')` and `path.replace(/^\\/+/, \'\')`, then join them with a single `/`.',
        'Read the body once with `await response.text()`. For an error status, that text is the `body`. For a success, `text === \'\' ? undefined : JSON.parse(text)` inside a try/catch.',
        'For the message, use `error instanceof Error ? error.message : String(error)`. Build headers as `{ accept: \'application/json\', ...options.headers }`, adding `\'content-type\': \'application/json\'` for `post`.',
      ],
    },
    {
      id: 'ts-typed-classes',
      title: 'Classes that enforce their rules',
      kind: 'typecheck',
      xp: 80,
      why: 'Abstract methods, protected state, private constructors and nominal fields turn a class\'s unwritten rules into compile errors instead of code-review comments.',
      tags: ['classes', 'abstract', 'access modifiers', 'nominal types'],
      hints: [
        'Mark the base `abstract class Repository<T extends Entity>` and declare `protected abstract validate(item: T): void;` with no body. Implement it as `protected validate(…)` in `UserRepository`.',
        'Make `items` `protected readonly`, and give `all()` the return type `readonly T[]`. With the constraint in place, `this.items.set(item.id, item)` needs no cast.',
        'For `Money`: `private constructor(cents: number)`, and a `#cents` private field with a `get cents()` accessor. The `#` field is what stops an object literal passing as a `Money`; a private constructor alone does not.',
        '`class FixedClock implements Clock` with `constructor(at: Date)` (required) and `now(): Date`.',
      ],
    },
    {
      id: 'ts-async-pagination',
      title: 'Lazy pagination with async generators',
      kind: 'ts',
      xp: 85,
      why: 'Helpers that load every page into an array download whole collections to show three rows, and never finish when an API repeats a cursor.',
      tags: ['async generators', 'pagination', 'iterators'],
      hints: [
        '`paginate` is an `async function*`: loop, `await fetchPage(cursor)`, `yield* page.items`, move to `page.nextCursor`, stop at `null`. Because it yields before fetching the next page, it is lazy for free.',
        'Keep a `Set` of every cursor seen. After yielding a page, if its `nextCursor` is already in the set, throw `new Error(\'cursor repeated: \' + cursor)`; otherwise add it.',
        'In `take`, return early for `n <= 0`, then `for await` over the source, push, and `break` as soon as you have `n`. `break` (or `return`) inside `for await` calls the iterator\'s `return()`, which runs the source\'s `finally`.',
        '`chunk` is another `async function*`: validate `size` with `Number.isInteger(size) && size >= 1`, collect into a batch, `yield` it when full and start a new one, then yield the leftover batch if it is not empty.',
      ],
    },
    {
      id: 'ts-column-defs',
      title: 'Per-column callback types',
      kind: 'typecheck',
      xp: 90,
      why: 'Table columns, form fields and CSV exports all pair a key with a callback; typing each callback from its own key is the difference between a checked config and a pile of casts.',
      tags: ['mapped types', 'discriminated unions', 'contextual typing', 'generics'],
      hints: [
        'Write the per-key object as a mapped type: `ColumnMap<Row> = { [K in keyof Row & string]: { key: K; header: string; align?: …; format?: (value: Row[K], row: Row) => string } }`.',
        'Index it to choose columns: `Column<Row, K extends keyof Row & string = keyof Row & string> = ColumnMap<Row>[K]`. With the default, that is the union of every column.',
        'Give `renderCell` its own key parameter: `renderCell<Row, K extends keyof Row & string>(row: Row, column: Column<Row, K>)`. Then `row[column.key]` is `Row[K]` and `column.format` accepts it.',
        '`defineColumns<Row>(columns: readonly Column<Row>[])` returns its argument; `renderRows` maps rows, then columns, through `renderCell`.',
      ],
    },
    {
      id: 'ts-real-code-quiz',
      title: 'Where everyday types lie',
      kind: 'quiz',
      xp: 70,
      why: 'Loose library types, `any` from `.json()`, and permissive callback types are where "it type-checks" and "it works" part ways.',
      tags: ['any', 'narrowing', 'callbacks', 'library types'],
      quiz: [
        {
          q: 'Why is `Object.keys(user)` typed `string[]` rather than `(keyof User)[]`?',
          options: [
            'A historical mistake kept for backward compatibility',
            'Because TypeScript cannot compute `keyof` for interfaces at compile time',
            'Because structural typing lets an object with extra properties be passed as a `User`, so the runtime keys can include ones `User` does not list',
            'Because `Object.keys` also returns symbol keys',
          ],
          answer: [2],
          explain: 'A value typed `User` may be a `{ id, name, passwordHash }` from the database: it is assignable to `User`, and `Object.keys` will return all three. Typing the result `(keyof User)[]` would let you index with a key the type does not describe. When you do know the object is exactly the shape (you built it yourself), a small helper with one cast is fine; when iterating over a known set of fields, loop over an explicit `const FIELDS = [\'id\', \'name\'] as const` instead. `Object.keys` never returns symbols.',
        },
        {
          q: 'Under TypeScript 5.5+, which of these is typed `number[]`?\n\n```ts\nconst values = [1, null, 2];\nconst a = values.filter((v) => v !== null);\nconst b = values.filter(Boolean);\n```',
          options: [
            'Both',
            'Only `a`',
            'Only `b`',
            'Neither: `filter` always returns the original element type',
          ],
          answer: [1],
          explain: 'Since 5.5 the compiler infers a type predicate for simple guard arrows like `(v) => v !== null`, so `a` is `number[]`. `Boolean` is a function declared as `(value?: unknown) => boolean`, not a predicate, so `b` stays `(number | null)[]` — and it would also drop `0`, which is a real bug when the array holds numbers. Prefer an explicit comparison; it is both correctly typed and correct.',
        },
        {
          q: 'This compiles. What is the problem, and the best fix?\n\n```ts\nasync function getUser(id: string): Promise<User> {\n  const res = await fetch(`/api/users/${id}`);\n  return res.json();\n}\n```',
          options: [
            'None; the return type annotation checks the value',
            '`res.json()` is `Promise<any>`, so nothing is checked. Annotate: `const data: User = await res.json()`',
            '`res.json()` is `Promise<any>`, so nothing is checked. Treat the body as `unknown` and validate it (a schema or a hand-written guard) before returning a `User`',
            'It must be `return await res.json()` so the type is unwrapped',
          ],
          answer: [2],
          explain: '`any` is assignable to everything, including `User`, so the annotation checks nothing — and neither does `const data: User = …`, which is the same unchecked claim written differently. An error page, a changed API or a `null` flows straight into code that trusts it. At the boundary, type the body as `unknown` (`const data: unknown = await res.json()`) and let a validator produce the `User`. It is also worth checking `res.ok` first: a 404 page is not a user either.',
        },
        {
          q: 'Which of these, passed as `onSave: (draft: Draft) => void`, compile? Select all that apply.',
          options: [
            '`() => setDirty(false)`',
            '`async (draft) => { await api.save(draft); }`',
            '`(draft: Draft, force: boolean) => {}`',
            '`(draft) => draft.title`',
          ],
          answer: [0, 1, 3],
          explain: 'A callback may take fewer parameters than it is offered (1), and a `void` return type in a function *type* means "the caller ignores the result", so returning a string (4) or a promise (2) is allowed. Requiring a parameter the caller never passes (3) is an error. The trap is (2): the caller ignores the promise, so a failed save is an unhandled rejection nobody awaits. If the caller should wait or handle errors, the type should say `(draft: Draft) => Promise<void>`; `@typescript-eslint/no-misused-promises` flags this case.',
        },
        {
          q: 'Under `strict`, what is the type of `err` here, and which line reads a message safely?\n\n```ts\ntry { await save(); } catch (err) { log(/* ? */); }\n```',
          options: [
            '`any`; `err.message` is fine',
            '`Error`; `err.message` is fine',
            '`unknown`; `(err as Error).message`',
            '`unknown`; `err instanceof Error ? err.message : String(err)`',
          ],
          answer: [3],
          explain: '`strict` includes `useUnknownInCatchVariables`, so `err` is `unknown`: JavaScript can throw anything — a string, `null`, a rejected fetch\'s `TypeError`, an object from a library. `(err as Error).message` compiles and gives `undefined` for a thrown string, or throws a new `TypeError` for `null` inside your error handler. Narrow with `instanceof Error` and fall back to `String(err)`.',
        },
        {
          q: 'Shared code runs in the browser and in Node, and stores a timer:\n\n```ts\nlet timer: number = setTimeout(flush, 100);\n```\n\nWith `@types/node` loaded this is an error. What is the portable fix?',
          options: [
            '`let timer: NodeJS.Timeout = setTimeout(flush, 100);`',
            '`let timer: ReturnType<typeof setTimeout> = setTimeout(flush, 100);`',
            '`let timer = setTimeout(flush, 100) as unknown as number;`',
            '`let timer: any = setTimeout(flush, 100);`',
          ],
          answer: [1],
          explain: 'Browsers return a `number`; Node returns a `Timeout` object (with `ref`/`unref`). `ReturnType<typeof setTimeout>` asks the environment you are compiling for and is right in both, and `clearTimeout` accepts it. `NodeJS.Timeout` breaks the browser build, and the casts make the compiler agree with something false in one of the two environments.',
        },
      ],
    },
    {
      id: 'ts-typed-store',
      title: 'BOSS: a typed state store',
      kind: 'typecheck',
      xp: 240,
      boss: true,
      why: 'A store typed once from its reducers checks every dispatch and every selector in the app with no annotations; typed as `any`, it turns every typo into a runtime bug.',
      tags: ['generics', 'infer', 'reducers', 'variadic tuples'],
      hints: [
        'Infer from the reducer\'s function type: `StateOf<R> = R extends (state: infer S, action: never) => unknown ? S : never`, and `ActionOf<R>` the same way on the second parameter (`infer A extends Action` keeps it an `Action`).',
        '`combineReducers<M extends Record<string, (state: never, action: never) => unknown>>(reducers: M): Reducer<{ [K in keyof M]: StateOf<M[K]> }, ActionOf<M[keyof M]>>`. `ActionOf` distributes over the union `M[keyof M]`, giving the union of actions.',
        '`createStore<S, A extends Action>(reducer: Reducer<S, A>, initial: S): Store<S, A>`. The reducer is the source of truth; `initial: NoInfer<S>` makes that explicit.',
        'For `createSelector`, infer the selectors as a tuple: `<Sel extends ((state: never) => unknown)[], R>(inputs: [...Sel], combine: (...values: SelectorResults<Sel>) => R)`, with `SelectorResults<Sel> = { [K in keyof Sel]: Sel[K] extends (state: never) => infer V ? V : never }`.',
        'The returned selector takes `Sel[number] extends (state: infer S) => unknown ? S : never`. Inferring from a parameter of a union of functions gives the intersection of their states, which is what "satisfies every input" means.',
      ],
    },
  ],
});
