import { loadChapter } from '../../load.ts';

const here = import.meta.dirname;

export default loadChapter(here, {
  id: 'sql-modelling-2',
  title: "Data Modelling II",
  summary: "Many-to-many, polymorphic associations, soft delete, audit trails, enums versus lookup tables, temporal data.",
  lessons: [
    {
      id: 'sql-junction-tables',
      title: 'Junction tables with a delete policy on each side',
      kind: 'sql',
      xp: 70,
      why: 'Every many-to-many relationship is a junction table, and its key, its two delete policies and its second index are decisions you make once and live with.',
      tags: ['many-to-many', 'foreign keys', 'indexes'],
      hints: [
        'The junction table needs no `id` of its own: `primary key (post_id, tag_id)` is its identity, and it makes a duplicate link a unique violation.',
        'The delete policies differ per side: `references posts(id) on delete cascade`, and `references tags(id) on delete restrict` (or the default, no action, which also refuses).',
        'A composite B-tree can only seek on its leading column. The primary key leads with `post_id`, so "posts with this tag" needs another index.',
        '`create index post_tags_tag_id_idx on post_tags (tag_id);` — Postgres never creates indexes for foreign keys on its own.',
      ],
    },
    {
      id: 'sql-exclusive-arc',
      title: 'Polymorphic associations with real foreign keys',
      kind: 'sql',
      xp: 85,
      why: 'The framework-default `commentable_type/commentable_id` pair cannot be foreign-keyed; an exclusive arc keeps integrity without giving up the polymorphic shape.',
      tags: ['polymorphic', 'check constraints', 'views'],
      hints: [
        'One nullable foreign key column per possible parent: `post_id int references posts(id) on delete cascade`, and the same for `photo_id`.',
        '"Exactly one" is a table-level check. `num_nonnulls(post_id, photo_id) = 1` says it directly and scales to a third parent type.',
        'Partial indexes suit these columns: `create index ... on comments (post_id) where post_id is not null`.',
        'In the view, left join both parents (an inner join to both returns nothing), then `coalesce(c.post_id, c.photo_id)` and `coalesce(p.title, ph.caption)`; `target_type` is a `case` on which column is set.',
      ],
    },
    {
      id: 'sql-soft-delete',
      title: 'Soft delete without breaking uniqueness',
      kind: 'sql',
      xp: 80,
      why: 'Adding `deleted_at` silently breaks every unique constraint on the table; a partial unique index is the fix most teams find only after the first support ticket.',
      tags: ['soft delete', 'partial indexes', 'migrations'],
      hints: [
        'A unique constraint cannot have a `where` clause, but a unique index can. Drop the constraint by name: `alter table users drop constraint users_email_key;`',
        'The index is on an expression: `create unique index users_live_email_idx on users (lower(email)) ...`',
        'Add the predicate: `... where deleted_at is null`. Deleted rows are then outside the index entirely, so they never collide.',
        'Restoring a user sets `deleted_at = null`, which puts the row back into the index, so a clash with a newer live user is caught with no extra code.',
        'The view is `create view live_users as select id, email, name from users where deleted_at is null;`',
      ],
    },
    {
      id: 'sql-audit-trigger',
      title: 'An audit trail nobody can forget to write',
      kind: 'sql',
      xp: 95,
      why: '"Who changed this and what was it before?" is asked in every incident and compliance review, and application-level logging always has a path that skips it.',
      tags: ['triggers', 'audit', 'plpgsql'],
      hints: [
        'The audit table has no `references accounts`: a cascade would erase history on delete, and without cascade the delete is refused.',
        'One function can serve all three operations: branch on `tg_op`, using `to_jsonb(new)` for inserts, both for updates, `to_jsonb(old)` for deletes (`old.id` is the account id on delete).',
        'Attach it with `after insert or update or delete on accounts for each row execute function audit_account()`. An AFTER trigger\'s return value is ignored, so `return null` is fine.',
        'To skip no-op updates, give the update trigger a condition: `when (old.* is distinct from new.*)`. That needs a separate `create trigger ... after update` from the insert/delete one.',
        'The actor is `current_setting(\'app.actor\', true)` — the second argument makes a missing setting return null instead of raising.',
      ],
    },
    {
      id: 'sql-state-transitions',
      title: 'State machines as lookup tables',
      kind: 'sql',
      xp: 90,
      why: 'Orders going from delivered back to pending is a data bug that a CHECK on values cannot catch; allowed transitions belong in a table the database enforces.',
      tags: ['lookup tables', 'triggers', 'state machines'],
      hints: [
        'Two tables: `order_statuses(code text primary key, is_terminal boolean not null)`, and `order_status_transitions` whose two columns both reference it, with `primary key (from_status, to_status)`.',
        'The existing column gets its foreign key with `alter table orders add constraint ... foreign key (status) references order_statuses(code)`.',
        'The trigger is `before update ... for each row`; inside, look the pair up with `not exists (select 1 from order_status_transitions t where t.from_status = old.status and t.to_status = new.status)`.',
        'Only check when the status really changes: `if new.status is distinct from old.status and not exists (...) then raise exception ...`, and always `return new`.',
      ],
    },
    {
      id: 'sql-tenant-composite-fk',
      title: 'Multi-tenant integrity with composite foreign keys',
      kind: 'sql',
      xp: 90,
      why: 'A missing tenant check in one handler leaks data across customers; putting tenant_id into the foreign key makes the leak impossible to write.',
      tags: ['multi-tenancy', 'foreign keys', 'security'],
      hints: [
        'A foreign key must reference columns covered by a unique constraint: `alter table projects add constraint projects_tenant_id_id_key unique (tenant_id, id);` and the same for users.',
        'Declare the references at table level: `foreign key (tenant_id, project_id) references projects (tenant_id, id) on delete cascade`.',
        'With the default MATCH SIMPLE, `(tenant_id, assignee_id)` is not checked while `assignee_id` is null — which is what makes "unassigned" legal.',
        'Plain `on delete set null` on a composite key nulls both columns, and `tenant_id` is not null. Name the column: `on delete set null (assignee_id)`.',
      ],
    },
    {
      id: 'sql-price-history',
      title: 'Temporal data: prices that were true at the time',
      kind: 'sql',
      xp: 90,
      why: 'Refunds, invoices and revenue reports need the price that applied then, not now; half-open validity periods are how you keep both.',
      tags: ['temporal data', 'history', 'functions'],
      hints: [
        'The check is `check (valid_to is null or valid_to > valid_from)`; the one-current-price rule is `create unique index ... on product_prices (product_id) where valid_to is null`.',
        'In `set_price`, close first: `update product_prices set valid_to = p_at where product_id = p_product_id and valid_to is null;` then insert the new open row.',
        'A change at or before the current start makes that UPDATE produce `valid_to <= valid_from`, so the check raises and the whole call fails. No extra `if` is needed.',
        'The view is a left join with half-open bounds: `o.placed_at >= pp.valid_from and (pp.valid_to is null or o.placed_at < pp.valid_to)`. `between` would match both prices at a changeover.',
      ],
    },
    {
      id: 'sql-modelling-judgement',
      title: 'Modelling judgement calls',
      kind: 'quiz',
      xp: 70,
      why: 'Enum or lookup table, UUID or bigint, JSONB or columns: cheap to decide in review, expensive to reverse after a year of data.',
      tags: ['data modelling', 'design review', 'trade-offs'],
      quiz: [
        {
          q: 'Order status will gain values over time, product wants a display label and an `is_terminal` flag per status, and ops want to add a status without a deploy. What do you model it as?',
          options: [
            'A native Postgres `enum` type',
            '`text` with a `CHECK (status in (...))` constraint',
            'A lookup table of statuses, with a foreign key from `orders.status`',
            'An `int` column with the meanings documented in the wiki',
          ],
          answer: [2],
          explain: 'A lookup table gives every status a row that can carry attributes (label, `is_terminal`, sort order), is changed with an `INSERT` rather than a migration, and is still enforced by a foreign key. An enum can gain values but cannot drop one and carries no attributes; a CHECK needs a migration for every new value; bare integers are unreadable in every query and enforce nothing.',
        },
        {
          q: 'Which statements about native Postgres enums (`CREATE TYPE ... AS ENUM`) are true? Select all that apply.',
          options: [
            'Values sort in declaration order, not alphabetically',
            'You can add a value with `ALTER TYPE ... ADD VALUE`',
            'You can remove a value with `ALTER TYPE ... DROP VALUE`',
            'Each value takes 4 bytes on disk, however long its label',
          ],
          answer: [0, 1, 3],
          explain: 'Enums sort by declaration order (useful for `low < normal < high`), are stored as 4-byte OIDs, and can gain values (`ADD VALUE ... BEFORE/AFTER`). There is no `DROP VALUE`: removing one means creating a new type and rewriting every column that uses it. That asymmetry is why enums suit small, stable sets.',
        },
        {
          q: 'What is the main cost of random UUIDv4 primary keys on a large, insert-heavy table?',
          options: [
            'Postgres cannot index `uuid` columns with a B-tree',
            'Each insert lands on a random leaf page of the primary-key index, so the working set is the whole index and writes cause page splits and extra WAL',
            'UUIDs are compared as 36-character strings, so every lookup is a string comparison',
            'Two servers can generate the same UUIDv4 at a realistic rate',
          ],
          answer: [1],
          explain: 'A `uuid` is a 16-byte binary value with a normal B-tree; the problem is locality. Sequential ids append to the right-most page, which stays in cache; random ids scatter writes over the whole index. Time-ordered UUIDv7 (or a `bigint` key with a separate random public id) keeps the benefits of UUIDs without the scatter. Collisions are not a practical concern.',
        },
        {
          q: 'A `users` table gets `deleted_at`, a partial unique index on live emails, and a `live_users` view. Which problems remain? Select all that apply.',
          options: [
            'New rows in other tables can still reference a soft-deleted user through their foreign keys',
            '`ON DELETE CASCADE` on child tables no longer fires, because nothing is deleted',
            'A legal erasure request is not satisfied by setting `deleted_at`',
            'Postgres refuses to `UPDATE` a row that has `deleted_at` set',
          ],
          answer: [0, 1, 2],
          explain: 'A foreign key checks that the row exists, and a soft-deleted row still exists; cascades never fire because no row is deleted, so children must be soft-deleted by your own code; and "right to erasure" means the personal data must actually go (or be anonymised). There is no rule stopping updates of soft-deleted rows — that is also on you.',
        },
        {
          q: 'A `settings jsonb` column on `users` holds UI preferences read as a whole, plus `plan`, which billing joins on, filters by, and which must be one of three values. What do you do?',
          options: [
            'Keep everything in the JSONB and add a GIN index',
            'Move `plan` to a real column with a constraint or foreign key; leave the UI preferences in JSONB',
            'Split every key into its own column so nothing is in JSONB',
            'Keep it in JSONB and validate `plan` in the application',
          ],
          answer: [1],
          explain: 'JSONB suits data read and written as a whole with no integrity rules. A value the database must join on, filter by and constrain wants to be a column: it gets a type, a constraint, statistics for the planner and a plain B-tree index. Splitting every UI preference into a column buys nothing; application-only validation is bypassed by the first backfill.',
        },
        {
          q: '`orders.total_cents` can be recomputed from `order_items`. When is storing it the right design?',
          options: [
            'Never: stored derived data always drifts',
            'Always, because summing items is slow',
            'When it records what the customer was actually charged — a fact that must not change when prices or discount rules change later',
            'Only if a nightly job recomputes it from the items',
          ],
          answer: [2],
          explain: 'The amount charged is not derived data, it is a historical fact: recomputing it from today\'s rules gives a different number from the one on the receipt and the card statement. Storing it is correct, and a nightly recompute would destroy it. For genuinely derived values (a cached count), the question is how staleness is detected and repaired.',
        },
      ],
    },
    {
      id: 'sql-bookings-boss',
      title: 'Boss: a room booking schema that cannot double-book',
      kind: 'sql',
      xp: 230,
      boss: true,
      why: 'Check-then-insert double-books under concurrency; ranges, an exclusion constraint and a trigger make the database the single source of truth.',
      tags: ['exclusion constraints', 'ranges', 'triggers', 'data modelling'],
      hints: [
        'Range shape checks are table-level: `check (not isempty(during))`, `check (not lower_inf(during) and not upper_inf(during))`, `check (lower_inc(during) and not upper_inc(during))`, `check (upper(during) - lower(during) <= interval \'4 hours\')`.',
        'The exclusion constraint is `exclude using gist (int4range(room_id, room_id, \'[]\') with =, during with &&)` — a one-element range stands in for `room_id with =`.',
        'Make it partial so cancelled bookings do not count: add `where (cancelled_at is null)` after the parenthesised list.',
        'Capacity spans two tables, so it is a `before insert or update of attendees, room_id` trigger that compares `new.attendees` with the room\'s capacity and raises with `using errcode = \'check_violation\'`.',
        '`free_rooms` is `select r.id, r.name, r.capacity from rooms r where r.capacity >= p_attendees and not exists (select 1 from bookings b where b.room_id = r.id and b.cancelled_at is null and b.during && p_during) order by r.capacity, r.id`.',
      ],
    },
  ],
});
