import { loadChapter } from '../../load.ts';

const here = import.meta.dirname;

export default loadChapter(here, {
  id: 'ts-runtime-boundaries',
  title: "Types at Runtime Boundaries",
  summary: "Parsing env and JSON, discriminated API responses, typed errors, unknown in catch.",
  lessons: [
    {
      id: 'ts-unknown-catch',
      title: 'unknown in catch: normalising what was thrown',
      kind: 'ts',
      xp: 70,
      why: '`(e as Error).message` is in every codebase that turned on strict, and it logs `undefined` exactly when something unusual broke.',
      tags: ['errors', 'unknown', 'narrowing'],
      hints: [
        'Handle the cases in order, most specific first: a real `Error`, then a string, then an object with a string `message`, then everything else.',
        '`value instanceof Error` narrows `unknown` straight to `Error`, so the first branch is `return value`.',
        'For the error-like object: `typeof value === "object" && value !== null && typeof (value as { message?: unknown }).message === "string"`. Put it in a type guard function so the branch reads cleanly.',
        'The description helper: `try { const json = JSON.stringify(value); if (json !== undefined) return json; } catch {}` and then `return String(value)`.',
        '`wrapError` passes the original `value` as the cause: `new Error(context + ": " + errorMessage(value), { cause: value })`.',
      ],
    },
    {
      id: 'ts-type-guards',
      title: 'Type predicates that compose',
      kind: 'typecheck',
      xp: 75,
      why: 'A check that returns `boolean` still needs a cast on the next line; predicates are how runtime checks and types stay the same thing.',
      tags: ['type guards', 'narrowing', 'generics', 'unknown'],
      hints: [
        'A predicate is a return type: `function isRecord(value: unknown): value is Record<string, unknown>`. Nothing else about the function changes.',
        'Give the key its own type parameter so the literal survives: `hasKey<K extends string>(value: unknown, key: K): value is Record<K, unknown>`.',
        'Inside `hasKeyOf`, once `hasKey(value, key)` is true the compiler knows `value[key]` exists, so `hasKey(value, key) && guard(value[key])` needs no cast.',
        'Guard factories return a function with a predicate of its own: `isArrayOf<T>(guard: Guard<T>): Guard<T[]> { return (value): value is T[] => Array.isArray(value) && value.every(guard); }`.',
        '`isOneOf<T extends string>(...allowed: T[]): Guard<T>` infers `T` as the union of the literals passed. `includes` wants a `T`, so compare through `(allowed as string[]).includes(value)`.',
      ],
    },
    {
      id: 'ts-parse-env',
      title: 'Parse the environment once, at startup',
      kind: 'ts',
      xp: 85,
      why: 'Misread env vars are a top cause of broken deploys, and every one of them compiles; a typed, fail-fast config turns them into one clear startup error.',
      tags: ['config', 'validation', 'boundaries', 'coercion'],
      hints: [
        'Push every problem onto one `errors` array and keep going (return the default for a bad value); throw once at the end if the array is not empty.',
        'Write a `read(key)` helper that turns `""` into `undefined`, so "unset" and "empty" share one path to the default.',
        'Integers: `/^\\d+$/.test(raw) ? Number(raw) : NaN`, then check the range. `Number("")` is 0 and `parseInt("80abc")` is 80, which is why neither is used alone.',
        'Booleans: compare against the four accepted strings explicitly. `Boolean("false")` is `true`.',
        'For the URL: `try { protocol = new URL(raw).protocol } catch {}` then compare with `"postgres:"` and `"postgresql:"`. Build the config object in table order so the errors come out in table order too, then `Object.freeze` it.',
      ],
    },
    {
      id: 'ts-query-params',
      title: 'Query strings are user input',
      kind: 'ts',
      xp: 85,
      why: 'List endpoints with `Number(params.get(...))` and `as SortField` are how `LIMIT NaN` 500s and table dumps reach production.',
      tags: ['validation', 'http', 'boundaries', 'urls'],
      hints: [
        'Normalise the input first: `typeof input === "string" ? new URLSearchParams(input) : input`. The constructor already strips a leading `?`.',
        'Write one `single(name)` helper around `params.getAll(name)`: more than one value is the "must be given once" error, `""` is absent, otherwise return the one value.',
        'For `status`, use `getAll("status").flatMap((s) => s.split(","))`, trim each, skip empties, and push only values that pass `STATUSES.includes` and are not already in the result.',
        'Collect errors in one array in parameter order; return `{ ok: false, errors }` if it is non-empty, otherwise the value with all five keys.',
        '`toQueryString`: `const p = new URLSearchParams()`, then `p.set` for each scalar that differs from its default, `p.append("status", s)` for each status, and `return p.toString()`.',
      ],
    },
    {
      id: 'ts-webhook-union',
      title: 'Webhooks: a discriminated union from untrusted JSON',
      kind: 'ts',
      xp: 90,
      why: 'Every payment, git and messaging integration delivers a union of event types you do not control; parsing it strictly but tolerantly is the difference between a robust integration and a 3 a.m. retry storm.',
      tags: ['discriminated unions', 'validation', 'webhooks', 'boundaries'],
      hints: [
        'Structure it as: is it a record? does it have a string `type`? is that type one we know? Then one small parser per event type.',
        'Unknown types are not errors: return `{ ok: true, event: { type: "unknown", originalType, id } }` so the caller can acknowledge and move on.',
        'Keep a `Map` (or an object checked with `Object.hasOwn`) from type string to parser. `payload.type in parsers` would accept `"toString"`.',
        'Every error is a path plus a reason; build each parser from small checks like `str(obj, "id", "data.id")` that push to the shared error list and return the value or `undefined`.',
        'Build the returned event from the checked fields only, never by spreading the input, so unexpected extra keys do not leak through.',
      ],
    },
    {
      id: 'ts-typed-errors',
      title: 'Typed errors: codes, causes and safe 500s',
      kind: 'ts',
      xp: 90,
      why: 'Leaked internal messages and wrapped 404s turning into 500s are two of the most common API bugs; an error vocabulary with codes fixes both.',
      tags: ['errors', 'api design', 'security', 'classes'],
      hints: [
        'In the constructor: `super(message, "cause" in options ? { cause: options.cause } : undefined)`, then set `name`, `code`, `status` (from `ERROR_CODES[code].status`) and `details`.',
        '`isAppError` is `value instanceof AppError && (code === undefined || value.code === code)`. `instanceof` narrows `unknown` for you.',
        '`findAppError`: keep a `Set` of visited errors; loop `while (current instanceof Error && !seen.has(current))`, return it if it is an `AppError`, otherwise add it to the set and move to `current.cause`.',
        'In `toProblem`, look up `ERROR_CODES[found.code]` and branch on `expose`. Build the slug with `code.toLowerCase().replaceAll("_", "-")`, spread `details` in only when present, and add `instance` last if it was passed.',
      ],
    },
    {
      id: 'ts-safe-fetch',
      title: 'A fetch wrapper with four named failures',
      kind: 'ts',
      xp: 90,
      why: '`(await res.json()) as T` hides offline, 5xx, HTML error pages and API drift behind one vague error; naming them is what lets the UI, the logs and the retry logic do the right thing.',
      tags: ['fetch', 'errors', 'http', 'boundaries'],
      hints: [
        'Wrap each step in its own `try`/`catch` so you know exactly which step failed: the `fetchFn` call, then `JSON.parse`, then `parse`.',
        'Remember that `fetch` resolves for 404 and 500. Check `res.ok` right after reading the text and before any JSON parsing.',
        '`HttpError` calls `super("http", method, url, message)`, keeps `body.slice(0, 200)`, and can compute `retryable` in a getter from `status`.',
        'In `describeFailure`, check `error instanceof ApiError` first, then `switch (error.kind)`; inside the `"http"` case, narrow with `error instanceof HttpError` to read `status`.',
      ],
    },
    {
      id: 'ts-response-matcher',
      title: 'Exhaustive handling of API responses',
      kind: 'typecheck',
      xp: 90,
      why: 'An `if (res.status === 201) … else …` quietly lumps every failure together; a typed matcher makes each status a separate, required branch, and a new status a compile error.',
      tags: ['discriminated unions', 'generics', 'inference', 'api design'],
      hints: [
        '`ResponseFor<R extends AnyResponse, S extends R["status"]> = Extract<R, { status: S }>`. The constraint on `S` is what rejects 404.',
        '`Handlers` maps over the status union: `{ [S in R["status"]]: (res: ResponseFor<R, S>) => Out }`.',
        'For `match`, use `<R extends AnyResponse, H extends Handlers<R, unknown>>(res: R, handlers: H): ReturnType<H[keyof H]>`. The body needs a cast: `handlers[res.status as keyof H]` is only known to be some handler.',
        '`matchOr<R extends AnyResponse, H extends Partial<Handlers<R, Out>>, Out>(res: R, handlers: H, fallback: (res: Exclude<R, { status: keyof H }>) => Out): Out`.',
        '`isStatus<R extends AnyResponse, S extends R["status"]>(res: R, ...statuses: S[]): res is ResponseFor<R, S>`. At runtime it is `(statuses as number[]).includes(res.status)`.',
      ],
    },
    {
      id: 'ts-boundary-handler',
      title: 'BOSS: the request boundary, end to end',
      kind: 'ts',
      xp: 230,
      boss: true,
      why: 'Wrong statuses, unbounded bodies and leaked internals are the classic API incidents; one well-built boundary factory prevents all of them for every route at once.',
      tags: ['http', 'validation', 'errors', 'boundaries'],
      hints: [
        'Split it in two: an inner `run()` that returns a `Res` for every outcome (never throws), and an outer part that adds `x-request-id`, computes the log level from the status and calls `log` once.',
        'Write one `problem(status, title, extras, headers)` helper that builds the `application/problem+json` response; every failure row in the table is then one line.',
        'Media type: `(req.headers["content-type"] ?? "").split(";")[0].trim().toLowerCase() === "application/json"`. Size: `Buffer.byteLength(req.body, "utf8")`.',
        'Put `options.parse`, `await options.handle(...)` and `JSON.stringify(result)` in ONE `try`. In the `catch`, a `ClientError` becomes its own status with `detail`; anything else becomes a 500 and you remember the message for the log.',
        'Keep the unexpected-error message in a variable outside `run()` (for example `let logError: string | undefined`), and add `error` to the log entry only when it is set.',
      ],
    },
  ],
});
