import { loadChapter } from '../../load.ts';

const here = import.meta.dirname;

export default loadChapter(here, {
  id: 'react-accessibility',
  title: "Accessible Components",
  summary: "Keyboard tabs, menu buttons, disclosures, live regions, focus traps, skip links.",
  lessons: [
    {
      id: 'react-disclosure',
      title: 'Disclosures: an accordion that says what it does',
      kind: 'react',
      xp: 70,
      why: 'A clickable div is the most common accessibility bug in React apps, and the accordion is where it usually lives.',
      tags: ['accessibility', 'aria', 'disclosure'],
      hints: [
        'Start from the markup in the brief: a `<button type="button">` inside an `<h3>`, and a panel `<div role="region">` right after it.',
        'Keep the panel rendered and toggle `hidden={!open}`. Conditional rendering would leave `aria-controls` pointing at nothing.',
        'Call `useId()` once per accordion and build both ids from it: `${prefix}-button-${item.id}` and `${prefix}-panel-${item.id}`.',
        'Hold a `Set` of open ids. Opening in single mode is `new Set([id])`; in multiple mode it is `new Set(current).add(id)`.',
      ],
    },
    {
      id: 'react-keyboard-tabs',
      title: 'Keyboard tabs with a roving tabindex',
      kind: 'react',
      xp: 90,
      why: 'Roving tabindex is how every composite widget (tabs, toolbars, grids, menus) becomes one Tab stop with arrow-key navigation.',
      tags: ['accessibility', 'keyboard', 'aria', 'tabs'],
      hints: [
        'Keep two pieces of state: which tab is **selected**, and which tab holds `tabIndex={0}`. In automatic mode they always move together; in manual mode they do not.',
        'Map the key to a target index: `{ ArrowRight: i === last ? 0 : i + 1, ArrowLeft: i === 0 ? last : i - 1, Home: 0, End: last }[event.key]`, and return early when it is `undefined`.',
        'Moving focus means calling `.focus()` on the tab element. Keep the buttons in a ref (a `Map` from tab id to element) and focus the target in the key handler.',
        'Render every panel with `hidden={tab.id !== selected}`, and build ids from `useId()` so `aria-controls` and `aria-labelledby` can point at each other.',
      ],
    },
    {
      id: 'react-menu-button',
      title: 'An actions menu that works from the keyboard',
      kind: 'react',
      xp: 100,
      why: 'Every row of every admin table has a "⋯" menu, and most of them trap or lose keyboard focus.',
      tags: ['accessibility', 'keyboard', 'focus', 'aria'],
      hints: [
        'One state value can hold everything: `null` while closed, otherwise the index of the focused item. A `useLayoutEffect` on it calls `.focus()` on that item.',
        'Put a single `onKeyDown` on the `<ul role="menu">`; key events from the focused item bubble to it. Handle the button\'s own ArrowDown/ArrowUp separately.',
        'For typeahead, loop `step` from 1 to `items.length` and look at `items[(active + step) % items.length]`, so the search starts after the current item and wraps.',
        'Close on outside clicks with a `mousedown` listener on `document`, added only while open and removed in the cleanup. Return early when the target is inside the menu **or** the button.',
      ],
    },
    {
      id: 'react-live-announcer',
      title: 'Live regions: saying what just happened',
      kind: 'react',
      xp: 85,
      why: 'Toasts, spinners and result counts are silent to screen readers unless something announces them.',
      tags: ['accessibility', 'aria-live', 'context'],
      hints: [
        'The provider renders both regions unconditionally, then `{children}`. The messages live in provider state; `announce` only calls setters.',
        'Store each message as `{ text, n }` with a counter, and render `<p key={n}>{text}</p>`: a new key is a new element, even for the same text.',
        'Wrap `announce` in `useCallback(…, [])` and use the setters\' functional form so it needs nothing from the render.',
        'In `AddToCart`, use `async` with `try { await onAdd(); announce(…) } catch { announce(…, \'assertive\') } finally { setPending(false) }`, and return early from the handler when already pending.',
      ],
    },
    {
      id: 'react-focus-trap',
      title: 'A focus trap for dialogs and drawers',
      kind: 'react',
      xp: 95,
      why: 'A modal that lets Tab walk out into the page behind it is broken for every keyboard and screen reader user.',
      tags: ['accessibility', 'focus', 'keyboard', 'dialogs'],
      hints: [
        'Write a `tabbables(container)` helper: `querySelectorAll` the candidates, then filter out `disabled`, `tabindex="-1"`, hidden inputs, and anything with `el.closest(\'[hidden]\')`.',
        'Activation and restoring are one effect on `[active]`: remember `document.activeElement`, focus the target, and return a cleanup that focuses the remembered element.',
        'Use `useEffect`, not `useLayoutEffect`: React restores the pre-commit focus after running layout-effect cleanups, which undoes your restore on deactivation.',
        'In `onKeyDown`, act only at the edges: Shift+Tab when `document.activeElement` is the first (or the container) focuses the last; Tab on the last (or the container) focuses the first. Call `preventDefault()` only in those cases.',
      ],
    },
    {
      id: 'react-route-focus',
      title: 'Skip links and focus on route change',
      kind: 'react',
      xp: 80,
      why: 'Client-side navigation is silent by default: no new title is read and focus is left on a link that may be gone.',
      tags: ['accessibility', 'focus', 'routing'],
      hints: [
        'Two effects: one on `[title, siteName]` that sets `document.title`, and one on `[routeKey]` that moves focus.',
        'Initialise a ref with the current route, `useRef(routeKey)`. In the effect, return early when `ref.current === routeKey`; otherwise update it and focus the heading.',
        'That comparison is what keeps the first render (and StrictMode\'s second run of it) from moving focus, and it ignores a `title` change on the same route.',
        'The skip link\'s handler is `event.preventDefault(); mainRef.current.focus();`. `<main>` and `<h1>` both need `tabIndex={-1}` for `.focus()` to work.',
      ],
    },
    {
      id: 'react-reorder-list',
      title: 'Reordering without dragging',
      kind: 'react',
      xp: 85,
      why: 'WCAG 2.2 requires a non-drag alternative for drag-and-drop, and the hard part is where focus goes after the move.',
      tags: ['accessibility', 'focus', 'wcag', 'lists'],
      hints: [
        'Build the new array with `items.slice()` and a swap, then call `onChange(next)`. Key the rows by `item.id`.',
        'The moved button only exists in its new place after the parent re-renders, so record which button to focus (for example `"b:up"`) in a ref, and focus it in an effect that runs when `items` changes.',
        'Keep button elements in a `Map` keyed by `${item.id}:up` / `${item.id}:down`, filled from ref callbacks.',
        'The item reached the end if `target === 0` when moving up, or `target === items.length - 1` when moving down. In that case record the other button.',
      ],
    },
    {
      id: 'react-accessible-names',
      title: 'Accessible names and native elements',
      kind: 'quiz',
      xp: 60,
      why: 'The accessible name is what screen readers say, what voice users say, and what your tests query; getting it wrong breaks all three.',
      tags: ['accessibility', 'aria', 'semantics'],
      quiz: [
        {
          q: 'An icon-only button renders `<button><svg>…</svg></button>`. What gives it a good accessible name?',
          options: [
            '`title="Delete"` on the SVG',
            '`aria-label="Delete draft"` on the button (or visually hidden text inside it), with `aria-hidden="true"` on the decorative SVG',
            '`role="img"` on the button',
            'Nothing: screen readers describe the icon',
          ],
          answer: [1],
          explain: 'A button\'s name comes from its content or from `aria-label`/`aria-labelledby`. An SVG contributes nothing useful on its own, and `title` support is inconsistent. Name the action, not the picture: "Delete draft" is better than "Trash can". Hiding the SVG stops some screen readers announcing "image" as well.',
        },
        {
          q: 'Why is `<div role="button" onClick={save}>Save</div>` worse than `<button type="button" onClick={save}>Save</button>`? Select all that apply.',
          options: [
            'The div is not in the Tab order unless you add `tabIndex={0}`',
            'The div does not fire `onClick` on Enter or Space; you must add a key handler yourself',
            'The div cannot be styled to look like a button',
            'The button is disabled with one attribute; the div needs `aria-disabled` plus your own guard in every handler',
          ],
          answer: [0, 1, 3],
          explain: 'The role only changes what a screen reader announces. Focusability, keyboard activation and disabling are behaviours the native element brings and the div does not. Styling is not the difference: a button can look like anything. The first rule of ARIA is not to use it when a native element does the job.',
        },
        {
          q: 'A text input has a visible "Email" label, and a hint below it: "We never share it." How should they be wired?',
          options: [
            '`aria-label="Email"` on the input, and the hint as a plain paragraph',
            '`placeholder="Email"` instead of a label, to save space',
            '`<label htmlFor={id}>Email</label>`, and `aria-describedby={hintId}` on the input pointing at the hint',
            '`aria-labelledby` pointing at both the label and the hint',
          ],
          answer: [2],
          explain: 'The label is the name, and the hint is the description: screen readers read the description after the name and role, and only the name is used by voice control ("click Email"). `aria-label` hides the visible label from assistive tech and can drift from it. A placeholder disappears as soon as you type and is not a reliable name. Putting the hint in the name makes the name long and harder to speak.',
        },
        {
          q: 'A page has three "Edit" buttons, one per address card. What is the problem, and a good fix?',
          options: [
            'None: the visual context makes it clear which is which',
            'Use `id="edit"` on each so they can be told apart',
            'Replace them with links, which screen readers list separately',
            'A screen reader\'s list of buttons shows "Edit, Edit, Edit". Give each a distinct name, for example `aria-label="Edit home address"`, or visible text plus visually hidden text',
          ],
          answer: [3],
          explain: 'Screen reader users often navigate by a list of buttons or links, with no surrounding context. The name must stand on its own. Repeated ids are invalid HTML and change nothing that is announced. Links are for navigation; choosing the element by how it is listed is the wrong reason.',
        },
        {
          q: 'Which of these are real uses of `aria-hidden="true"`? Select all that apply.',
          options: [
            'A decorative icon next to text that already says the same thing',
            'A visually duplicated element, such as a carousel\'s cloned slide used for looping',
            'A focusable button you want screen readers to skip',
            'An element you want hidden from sighted users too',
          ],
          answer: [0, 1],
          explain: '`aria-hidden` removes an element from the accessibility tree only; it stays visible and, crucially, stays focusable. A focusable element inside `aria-hidden` is a "ghost": keyboard users land on something a screen reader cannot describe. To hide something from everyone, use `hidden` or `display: none`, which do both.',
        },
        {
          q: 'A test does `getByRole(\'button\', { name: \'Save\' })` and fails to find a button that visibly reads "Save". Which could explain it? Select all that apply.',
          options: [
            'It has `aria-label="Submit form"`, which replaces the text as its name',
            'It is a `<div>` with an `onClick`, so it has no button role',
            'It is inside an element with `aria-hidden="true"`',
            'Its text comes from a CSS `::before` pseudo-element, which jsdom does not compute',
          ],
          answer: [0, 1, 2, 3],
          explain: 'All four happen. `aria-label` overrides content, a div has no role, `aria-hidden` removes it from the accessibility tree, and jsdom does not compute CSS-generated content (browsers do include it in the name). Queries by role and name fail for the same reasons assistive technology does, which is why they are worth writing.',
        },
      ],
    },
    {
      id: 'react-tree-view',
      title: 'Boss: an accessible tree view',
      kind: 'react',
      xp: 240,
      boss: true,
      why: 'The tree is the hardest common widget in the ARIA practices: nesting, visibility, roving focus and typeahead all at once.',
      tags: ['accessibility', 'keyboard', 'aria', 'focus'],
      hints: [
        'Most keys are about the **visible** nodes in order. Write `visibleNodes(nodes, expanded)` that walks the tree depth-first, descending only into expanded parents, and records each node\'s parent id.',
        'Keep three pieces of state: the expanded ids (a `Set`), the focused id and the selected id. The tab stop is the focused id if it is still visible, otherwise the first visible node.',
        'Put one `onKeyDown` on the `role="tree"` element and find the current node by the tab stop. Handlers on the nested `<li>`s would each receive the bubbling event.',
        'To move real focus after a render (the target may have just appeared), set a ref flag, and in a `useLayoutEffect` focus the element for the tab stop from a `Map` of ids to elements.',
        'In each item\'s `onClick`, call `event.stopPropagation()` first, then focus, select and (for a parent) toggle.',
      ],
    },
  ],
});
