import { loadChapter } from '../../load.ts';

const here = import.meta.dirname;

export default loadChapter(here, {
  id: 'testing-react',
  title: "Testing React",
  summary: "Forms, async UI, hooks and accessibility queries — you write the tests.",
  lessons: [
    {
      id: 'test-rtl-form-validation',
      title: 'Testing an accessible form',
      kind: 'mutation',
      subjectKind: 'react',
      xp: 95,
      minTests: 8,
      why: 'A form can show the right red text and still be unusable with a screen reader, or submit twice. Focus, ARIA links and the payload are all testable from the DOM.',
      tags: ['testing library', 'forms', 'accessibility', 'validation'],
      mutants: [
        { slug: 'no-focus', label: 'Leaves focus on the button instead of moving it to the first invalid field' },
        { slug: 'no-aria-invalid', label: 'Invalid fields are not marked `aria-invalid`' },
        { slug: 'error-not-linked', label: 'Error messages are not linked to their field with `aria-describedby`' },
        { slug: 'email-not-trimmed', label: 'Submits the email with the spaces the user typed around it' },
        { slug: 'password-off-by-one', label: 'Rejects a password of exactly 8 characters' },
        { slug: 'double-submit', label: 'The button stays enabled while saving, so a second click submits again' },
        { slug: 'terms-optional', label: 'Submits without the terms being accepted' },
        { slug: 'error-stays', label: 'An error stays on screen after the field is fixed, until the next submit' },
      ],
      hints: [
        'Write two helpers: `fill({ email, password, terms })` using `fireEvent.change` and `fireEvent.click` on `getByLabelText(...)`, and `describedBy(input)`, which returns the text of `document.getElementById(input.getAttribute(\'aria-describedby\'))`.',
        'Submit an empty form, then check each field\'s `aria-invalid` is `\'true\'` and `describedBy(field)` is its exact message. Check the callback was not called.',
        'Focus: a bad email with everything else valid puts `document.activeElement` on the Email input. A valid email with a short password puts it on Password.',
        'Boundaries and payload: 7 characters shows the password error; 8 submits. Type `\'  ada@example.com  \'` and expect `onSubmit` to get `\'ada@example.com\'`.',
        'Pending: make `onSubmit` return a promise you resolve later. After one click the button is `.disabled` and a second click adds no call. Settle it with `await act(async () => { d.resolve(); })`.',
      ],
    },
    {
      id: 'test-rtl-async-states',
      title: 'Loading, empty, error and the out-of-order response',
      kind: 'mutation',
      subjectKind: 'react',
      xp: 95,
      minTests: 7,
      why: 'Async UI bugs depend on timing: slow requests, failures, and responses that arrive in the wrong order. A mock that resolves at once can never show them.',
      tags: ['testing library', 'async', 'race conditions', 'data fetching'],
      mutants: [
        { slug: 'stale-results-win', label: 'An older search that resolves late replaces the newer results' },
        { slug: 'stale-error-wins', label: 'An older search that fails late shows its error over the newer results' },
        { slug: 'retry-uses-input', label: 'Retry searches the current field text instead of the query that failed' },
        { slug: 'loading-stays-on-error', label: 'The loading indicator stays up after an error' },
        { slug: 'no-empty-message', label: 'An empty result shows nothing instead of "No users match"' },
        { slug: 'searches-blank', label: 'A blank query still calls `search`' },
        { slug: 'sends-untrimmed', label: 'Searches for the text with its surrounding spaces' },
      ],
      hints: [
        'Make `search` push the query into `calls` and return a fresh deferred promise each time. Then you decide when, and in which order, each one settles.',
        'Check each state: `getByRole(\'status\')` while pending; the list items after resolving; `No users match "zed"` for `[]`; `getByRole(\'alert\')` after a rejection, with no status left.',
        'Retry: fail a search for `ann`, change the field to `bob` without submitting, click Retry, and expect `calls` to be `[\'ann\', \'ann\']`.',
        'The race: search `ann`, then `anna`. Resolve the second, then resolve the first, each in its own `await act(async () => { … })`. Only Anna\'s results may be on screen. Repeat with the first one rejecting: no alert.',
        'Input: `\'   \'` makes no call at all, and `\'  ann  \'` calls `search(\'ann\')`.',
      ],
    },
    {
      id: 'test-rtl-custom-hook',
      title: 'Testing a custom hook with renderHook',
      kind: 'mutation',
      subjectKind: 'react',
      xp: 90,
      minTests: 7,
      why: 'Shared hooks are APIs used by many components. Their bugs show up in sequences of calls, in updater functions and in unstable identities that re-run effects.',
      tags: ['testing library', 'hooks', 'renderHook', 'undo'],
      mutants: [
        { slug: 'set-keeps-redo', label: 'A new set after undo keeps the old redo steps' },
        { slug: 'same-value-recorded', label: 'Setting the current value again adds an undo step' },
        { slug: 'stale-updater', label: 'Two updaters in one act both see the value from the last render' },
        { slug: 'drops-newest', label: 'Over the limit, drops the newest undo steps instead of the oldest' },
        { slug: 'undo-past-start', label: 'Undo with nothing to undo sets the value to undefined' },
        { slug: 'unstable-functions', label: '`undo` is a new function on every render' },
        { slug: 'can-redo-wrong', label: '`canRedo` reports whether you can undo' },
        { slug: 'reset-keeps-history', label: '`reset` keeps the old value as an undo step' },
      ],
      hints: [
        'Wrap each call in its own `act(() => { result.current.x(); })`, then read `value`, `canUndo` and `canRedo` from `result.current` together in one `toEqual`.',
        'Walk a full sequence: set 1, set 2, undo, undo, redo, redo, checking all three fields after each step. Then undo and redo once more at each end: nothing may change.',
        'The redo branch: set 1, set 2, undo twice, set 5. Now `canRedo` is false and redo keeps 5.',
        'Updaters: `act(() => { set((n) => n + 1); set((n) => n * 2); })` from 10 must give 22. With `limit: 2`, after sets 1, 2, 3 you can only undo back to 1.',
        'Identity: keep `const first = result.current`, do some updates, call `rerender()`, and expect `result.current.undo` to `toBe(first.undo)`. Do the same for `set`, `redo` and `reset`.',
      ],
    },
    {
      id: 'test-rtl-tabs',
      title: 'Testing a keyboard-accessible widget',
      kind: 'mutation',
      subjectKind: 'react',
      xp: 90,
      minTests: 7,
      why: 'Keyboard and screen-reader support breaks without anyone noticing, because mouse-driven tests keep passing. The ARIA keyboard contract is precise enough to test directly.',
      tags: ['testing library', 'accessibility', 'keyboard', 'aria'],
      mutants: [
        { slug: 'no-wrap', label: 'ArrowRight on the last tab does not wrap to the first' },
        { slug: 'arrows-only-focus', label: 'Arrow keys move focus but do not select the tab' },
        { slug: 'every-tab-tabbable', label: 'Every tab has tabIndex 0, so Tab walks through all of them' },
        { slug: 'panel-unnamed', label: 'The tabpanel has no accessible name' },
        { slug: 'disabled-not-skipped', label: 'Arrow keys select the disabled tab' },
        { slug: 'no-home-end', label: 'Home and End do nothing' },
        { slug: 'onchange-on-reselect', label: 'Clicking the already-selected tab calls onChange' },
      ],
      hints: [
        'Write `selectedNames()`: the text of every tab whose `aria-selected` is `\'true\'`. It must always be a list of exactly one.',
        'Focus a tab with `tab(\'Profile\').focus()`, then `fireEvent.keyDown(document.activeElement, { key: \'ArrowRight\' })`. Assert both `selectedNames()` and `document.activeElement`.',
        'The data has a disabled `Team` between `Billing` and `Security`: ArrowRight from Billing must land on Security, and ArrowLeft from Security on Billing. Start on Security and press ArrowRight to test wrapping.',
        'Name the panel: `getByRole(\'tabpanel\', { name: \'Billing\' })`. Roving tabindex: map every tab to `[textContent, tabIndex]` after a click.',
        'onChange: click the selected tab (no call), click Billing twice (one call), then an arrow key (one more). Expect exactly `[\'billing\', \'security\']`.',
      ],
    },
    {
      id: 'test-rtl-context',
      title: 'Testing components that share a context',
      kind: 'mutation',
      subjectKind: 'react',
      xp: 90,
      minTests: 8,
      why: 'Components that talk through context break at the seams between them. Rendering them together in the real provider, with only storage faked, tests what users actually do.',
      tags: ['testing library', 'context', 'integration', 'test doubles'],
      mutants: [
        { slug: 'duplicate-lines', label: 'Adding a product that is already in the cart adds a second line' },
        { slug: 'counts-lines', label: 'The count shows the number of lines, not the total quantity' },
        { slug: 'always-plural', label: 'Shows `1 items`' },
        { slug: 'total-ignores-qty', label: 'The total ignores quantities' },
        { slug: 'threshold-exclusive', label: 'A cart of exactly £50 does not get free shipping' },
        { slug: 'removes-first-line', label: 'Remove deletes the first line, not the one clicked' },
        { slug: 'ignores-saved-cart', label: 'Ignores the cart saved in storage' },
        { slug: 'never-saves', label: 'Never writes the cart to storage' },
        { slug: 'silent-without-provider', label: '`useCart` outside a provider returns an empty cart instead of throwing' },
      ],
      hints: [
        'Render the page in miniature: one `CartProvider` around two `AddToCartButton`s and a `CartSummary`. Click the buttons by their names and read the `data-testid`s.',
        'Add the same product twice: there must be exactly one `Remove Mug` button, the count is `2 items`, and the total is `£25.00`. Then add a pen three times and check `4 items`.',
        'The threshold: two £25.00 items total exactly `£50.00` and show `Free shipping!`. Three £12.50 mugs show `Spend £12.50 more for free shipping`.',
        'Storage both ways: a fake with `cart` already set to `JSON.stringify([{ ...PEN, qty: 2 }])` must show `2 items` on first render; after clicks, `JSON.parse(fake.data.get(\'cart\'))` must equal the lines.',
        'Outside a provider: `expect(() => renderHook(() => solution.useCart())).toThrow(Error)`. Silence `console.error` around it, and restore it in a `finally`.',
      ],
    },
    {
      id: 'test-rtl-timers',
      title: 'Timers you control: testing toasts',
      kind: 'mutation',
      subjectKind: 'react',
      xp: 95,
      minTests: 7,
      why: 'Auto-dismissing UI hides timing bugs and timer leaks. An injected scheduler makes them visible and testable without waiting for real time.',
      tags: ['testing library', 'timers', 'test doubles', 'cleanup'],
      mutants: [
        { slug: 'errors-auto-dismiss', label: 'Error toasts disappear on their own' },
        { slug: 'wrong-delay', label: 'Info toasts are scheduled for 500 ms instead of 5000' },
        { slug: 'hover-no-pause', label: 'Hovering does not pause the timer' },
        { slug: 'leave-no-restart', label: 'After the pointer leaves, the toast never goes away' },
        { slug: 'dismiss-leaves-timer', label: 'Dismiss removes the toast but leaves its timer running' },
        { slug: 'no-limit', label: 'Shows more than 3 toasts' },
        { slug: 'drops-newest', label: 'Over the limit, the new toast is dropped instead of the oldest' },
        { slug: 'unmount-leaks-timers', label: 'Unmounting the provider leaves timers running' },
      ],
      hints: [
        'Use the starter\'s fake scheduler: `live()` lists timers that have neither fired nor been cancelled. Most tests should end by checking `live()`.',
        'After one info toast: `clock.live().map((t) => t.ms)` is `[5000]`. `clock.fireAll()` removes it. An error toast leaves `live()` empty, and firing everything leaves the alert up.',
        'Dismiss: click the `Dismiss` button `within` the toast, and expect no toast and `live()` of length 0.',
        'Hover: `fireEvent.mouseEnter(toastElement)` leaves nothing live, and firing does not remove it. `fireEvent.mouseLeave` gives one live 5000 ms timer again.',
        'Make each message unique (`Saved 1`, `Saved 2`…). After four toasts the screen shows 2, 3 and 4, and 3 timers are live. After `unmount()`, `live()` is empty.',
      ],
    },
    {
      id: 'test-rtl-table-sort',
      title: 'Test data that exposes a sortable table',
      kind: 'mutation',
      subjectKind: 'react',
      xp: 90,
      minTests: 8,
      why: 'Sorting and filtering bugs only show with the right data: numbers that sort differently as text, mixed case and ties. Choosing that data is a core testing skill.',
      tags: ['testing library', 'test data', 'sorting', 'accessibility'],
      mutants: [
        { slug: 'numbers-as-text', label: 'Sorts number columns as text (10 before 9)' },
        { slug: 'case-sensitive-sort', label: 'Sorts upper case before lower case' },
        { slug: 'no-toggle', label: 'A second click does not switch to descending' },
        { slug: 'no-aria-sort', label: 'Headers never get `aria-sort`' },
        { slug: 'keeps-direction', label: 'A newly clicked column inherits the previous column\'s direction' },
        { slug: 'descending-reverses-ties', label: 'Descending order reverses tied rows' },
        { slug: 'filter-case-sensitive', label: 'The filter is case-sensitive' },
        { slug: 'count-after-filter', label: 'The status counts the filtered rows as the total' },
      ],
      hints: [
        'Build the rows before the tests: ages `9, 10, 102`, names `bea` and `Bob`, and three people in team `Red` in a known order.',
        'Read a whole column: `getAllByRole(\'row\').slice(1).map((r) => within(r).getAllByRole(\'cell\')[i].textContent)`, and compare the entire list with `toEqual`.',
        'Ties: sort by Team twice. The three Red rows must be in their original order in both directions.',
        'Direction: Name, Name (descending), then Age must be ascending. Read `aria-sort` from `getByRole(\'columnheader\', { name })`, and treat `null` as `\'none\'`.',
        'Filter with `\'  RED \'`: three rows, and the status reads `Showing 3 of 5`. `purple` shows `No matching rows`.',
      ],
    },
    {
      id: 'test-rtl-queries-quiz',
      title: 'Queries, act and what to mock',
      kind: 'quiz',
      xp: 60,
      why: 'Most brittle or falsely green component tests come from a few habits: the wrong query, asserting before React has updated, and mocking the thing under test.',
      tags: ['testing library', 'test design', 'react'],
      quiz: [
        {
          q: 'Which query should you reach for first to find a "Save" button?',
          options: [
            '`container.querySelector(\'.btn-primary\')`',
            '`screen.getByTestId(\'save-button\')`',
            '`screen.getByRole(\'button\', { name: \'Save\' })`',
            '`screen.getByText(\'Save\')`',
          ],
          answer: [2],
          explain: 'A role and accessible name is how assistive technology finds the control, so the query survives restyling and also checks accessibility: an `<div onclick>` with no role fails it. `getByText` also matches non-interactive text. `getByTestId` is the fallback when nothing user-visible identifies the element, and a class name is an implementation detail.',
        },
        {
          q: 'A component loads data in an effect and then renders the list. What is the right way to wait for the first item?',
          options: [
            '`await new Promise((r) => setTimeout(r, 100))`, then `getByText`',
            '`await screen.findByRole(\'listitem\')`, or settle a controlled promise inside `await act(async () => { … })` and then query',
            '`getByRole(\'listitem\')` straight after `render`',
            'Wrap the whole test in `act()` without awaiting it',
          ],
          answer: [1],
          explain: '`findBy…` retries until the element appears (or it times out), and a promise you settle yourself inside an awaited `act` makes React finish its update before you assert. A fixed sleep is slow on a fast machine and flaky on a slow one. A synchronous `getBy` straight after render runs before the data has arrived.',
        },
        {
          q: 'How do you assert that an error message is **not** on screen?',
          options: [
            '`expect(screen.getByText(\'Error\')).toBeNull()`',
            '`expect(screen.queryByText(\'Error\')).toBeNull()`',
            '`expect(screen.findByText(\'Error\')).toBeFalsy()`',
          ],
          answer: [1],
          explain: '`getBy…` throws when nothing matches, so it can never return `null`. `queryBy…` returns `null` instead, which is what an absence check needs. `findBy…` returns a promise, and a promise is always truthy.',
        },
        {
          q: 'You are testing `<ProfilePage>`, which uses a `useProfile()` hook that calls `fetch`. What is the best thing to replace?',
          options: [
            'Mock `useProfile` so it returns a fixed profile.',
            'Nothing. Let it call the real API.',
            'The network boundary: pass a fake client (or stub `fetch`) that returns a controlled response, so the real hook and component run together.',
            'Mock `React.useState`.',
          ],
          answer: [2],
          explain: 'Mocking the hook skips the hook\'s own loading and error logic, so the test can pass while the real page is broken. Replacing only the boundary you do not control (the network) keeps the code you wrote under test. Mocking React internals couples the test to how the component is written.',
        },
        {
          q: 'Which of these are signs that a component test checks implementation details rather than behaviour? Select all that apply.',
          options: [
            'It reads the component\'s state through a ref, or asserts how many times it rendered.',
            'It asserts `document.activeElement` after closing a dialog.',
            'It fails when a `<div>` is swapped for a `<section>` with the same role and name.',
            'It asserts the `aria-invalid` attribute on a field after a failed submit.',
          ],
          answer: [0, 2],
          explain: 'Focus and ARIA attributes are behaviour: users and assistive technology depend on them. Internal state, render counts and element types are implementation: a correct refactor changes them. A good test fails when a user would notice, and only then.',
        },
        {
          q: '`getByText(\'Delete\')` throws "Found multiple elements" on a list page. What is the best fix?',
          options: [
            'Use `getAllByText(\'Delete\')[0]`.',
            'Add a unique `data-testid` to every Delete button.',
            'Scope the query to the row you mean: `within(row).getByRole(\'button\', { name: \'Delete\' })`, or give each button a distinct accessible name such as "Delete Invoice 42".',
          ],
          answer: [2],
          explain: '`[0]` silently picks whichever button renders first, so the test can delete the wrong item and still pass. Scoping with `within` (or distinct accessible names, which screen-reader users need anyway) targets the exact control a user would choose.',
        },
      ],
    },
    {
      id: 'test-rtl-boss',
      title: 'BOSS: the combobox contract',
      kind: 'mutation',
      subjectKind: 'react',
      xp: 240,
      boss: true,
      minTests: 10,
      why: 'Comboboxes are everywhere and are usually broken for keyboard and screen-reader users. Pinning down the ARIA contract in tests is how a team keeps one working.',
      tags: ['testing library', 'accessibility', 'keyboard', 'aria'],
      mutants: [
        { slug: 'no-wrap-down', label: 'ArrowDown on the last option does not wrap to the first' },
        { slug: 'no-activedescendant', label: 'The input never sets `aria-activedescendant`, so the highlight is not announced' },
        { slug: 'never-expanded', label: '`aria-expanded` is always `"false"`' },
        { slug: 'enter-picks-first', label: 'Enter with nothing highlighted chooses the first option' },
        { slug: 'case-sensitive-filter', label: 'Filtering is case-sensitive' },
        { slug: 'highlight-survives-typing', label: 'Typing after a highlight leaves an option highlighted' },
        { slug: 'escape-clears-at-once', label: 'The first Escape also clears the text' },
        { slug: 'click-skips-onselect', label: 'Clicking an option fills the input but does not call onSelect' },
        { slug: 'stays-open', label: 'The list stays open after choosing an option' },
      ],
      hints: [
        'Write `expectHighlighted(label)`: exactly one option has `aria-selected="true"` and it is `label`; `document.getElementById(input.getAttribute(\'aria-activedescendant\'))` is that same element; and `document.activeElement` is the input.',
        'Filtering: typing `\'  LAND \'` shows `Finland` and `Ireland`, `aria-expanded` is `\'true\'`, and nothing is highlighted yet. `zz` shows no listbox and a `No results` status.',
        'Wrapping: with `land`, ArrowDown twice highlights Ireland, and a third time Finland. ArrowUp from nothing highlights the last option.',
        'Enter: with nothing highlighted it changes nothing. After ArrowDown it sets the value, closes the list (`queryByRole(\'listbox\')` is null, `aria-expanded` is `\'false\'`) and calls onSelect once with the option object. Clicking an option must do the same.',
        'Typing after a highlight must clear `aria-activedescendant`. Escape once keeps the text and closes the list. Escape again clears the text.',
      ],
    },
  ],
});
