import { loadChapter } from '../../load.ts';

const here = import.meta.dirname;

export default loadChapter(here, {
  id: 'react-hooks-deep',
  title: "Hooks in Depth",
  summary: "useRef patterns, useSyncExternalStore, useId, usePrevious, useInterval, layout versus passive effects.",
  lessons: [
    {
      id: 'react-use-previous',
      title: 'usePrevious, useLatest and pure renders',
      kind: 'react',
      xp: 75,
      why: 'The snippet everyone copies writes a ref during render; it breaks under StrictMode and concurrent rendering.',
      tags: ['useRef', 'useLayoutEffect', 'StrictMode'],
      hints: [
        'A ref write belongs after commit. Read `ref.current` during render, and write it in `useEffect(() => { ref.current = value; })`.',
        '`useLatest` is `useRef(value)` plus a `useLayoutEffect` that assigns `ref.current = value` on every render. Return the ref object itself, not `.current`.',
        'For the ticker, "the previous render" is the wrong question. Keep the last price you saw *change* in state: `const [lastPrice, setLastPrice] = useState(price)`.',
        'During render: `if (price !== lastPrice) { setLastPrice(price); setTrend(price > lastPrice ? \'up\' : \'down\'); }`. React re-runs the component straight away, before the DOM is touched.',
      ],
    },
    {
      id: 'react-use-id-field',
      title: 'useId for accessible fields',
      kind: 'react',
      xp: 70,
      why: 'Every form component needs ids for labels and descriptions, and the obvious ways to make them break on reuse or on hydration.',
      tags: ['useId', 'accessibility', 'forms', 'ssr'],
      hints: [
        'Call `useId()` unconditionally at the top, then choose: `const inputId = id ?? base;`. Hooks cannot be called conditionally, so do not skip it when `id` is passed.',
        'Derive the other ids from the same base: `${base}-hint` and `${base}-error`.',
        'Build the list and fall back to `undefined`: `[hintId, errorId].filter(Boolean).join(\' \') || undefined`. React omits an attribute whose value is `undefined`; an empty string is still an attribute.',
        '`aria-invalid={error ? true : undefined}`, and spread `...inputProps` on the input *before* your own `id` and aria props so the caller cannot clobber them by accident.',
      ],
    },
    {
      id: 'react-callback-refs',
      title: 'Callback refs and merged refs',
      kind: 'react',
      xp: 85,
      why: 'Focusing an element that appears later, or giving one element two refs, is where `useRef` plus an effect quietly does nothing.',
      tags: ['refs', 'focus management', 'useCallback'],
      hints: [
        'A callback ref is just `ref={(node) => { ... }}`. React calls it with the element on attach and with `null` on detach.',
        '`useMergedRef` returns `useCallback((node) => { for (const ref of refs) ... }, refs)`: the refs array itself is the dependency list, so the same refs give the same function.',
        'For the input: `useCallback((node) => { if (node) { node.focus(); node.select(); } }, [])` passed as its `ref`. It runs exactly when the input appears.',
        'Returning focus must not happen on mount. Set a flag in a ref (`returnFocus.current = true`) in the Enter/Escape handler, and in the Edit button\'s callback ref only focus when the flag is set, then clear it.',
      ],
    },
    {
      id: 'react-imperative-handle',
      title: 'A deliberate imperative API',
      kind: 'react',
      xp: 75,
      why: 'Forwarding the raw DOM node lets every parent bypass your component\'s state; a small handle keeps it in control.',
      tags: ['forwardRef', 'useImperativeHandle', 'refs'],
      hints: [
        'Wrap the component: `export const SearchInput = forwardRef(function SearchInput(props, ref) { ... })`. Without it, React 18 drops the `ref`.',
        'Keep your own `inputRef` for the `<input>`, and give the *parent* a different object with `useImperativeHandle(ref, () => ({ focus() {...}, clear() {...} }))`.',
        'Share one `update(next)` function between typing and `clear()` so both call `setValue` and `onValueChange` the same way.',
        'If you pass a dependency list of `[]`, `clear` closes over the first render\'s `onValueChange`. Omit the list (or list `onValueChange`) so the handle is rebuilt with the latest one.',
      ],
    },
    {
      id: 'react-stale-closures',
      title: 'Debug: four stale closures',
      kind: 'react',
      xp: 90,
      why: 'Stale closures are the most common hooks bug in code review, and the dependency-array "fix" often makes a worse one.',
      tags: ['closures', 'useEffect', 'debugging', 'subscriptions'],
      hints: [
        'Updater functions receive the latest state: `setTotal((t) => t + amount)`. A handler created on the first render stays correct forever.',
        'Total and count always change together; one state object `{ total, count }` with a single updater keeps them consistent.',
        '`total > limit` is derived: compute it during render from the current props instead of inside the subscription.',
        'For "fires once when crossing": `const over = total > limit;` then `useEffect(() => { if (over) onOverLimitRef.current(total); }, [over])`.',
        'Hold `onOverLimit` in a ref updated on every render (`useLayoutEffect(() => { ref.current = onOverLimit; })`) so the subscription effect depends on `[feed]` only.',
      ],
    },
    {
      id: 'react-use-interval',
      title: 'A useInterval that works',
      kind: 'react',
      xp: 85,
      why: 'Timers in effects fail in two opposite ways depending on the dependency array; the fix is a pattern you will reuse for every subscription.',
      tags: ['timers', 'useRef', 'custom hooks'],
      hints: [
        'Two concerns, two effects. One keeps `savedCallback.current = callback` fresh on every render; the other owns the interval.',
        'The interval effect depends on `[delay]` only and calls `() => savedCallback.current()`, never `callback` directly.',
        '`if (delay === null) return;` at the top of the interval effect is how pausing works: no interval is created, and the previous one was already cleared by the cleanup.',
        'In `Countdown`, pass `paused || remaining === 0 ? null : 1000` as the delay, and call `onDone` from `useEffect(() => { if (remaining === 0) onDoneRef.current(); }, [remaining === 0])` rather than inside a state updater.',
      ],
    },
    {
      id: 'react-use-local-storage',
      title: 'useSyncExternalStore for localStorage',
      kind: 'react',
      xp: 95,
      why: 'State React does not own (storage, sockets, browser APIs) needs subscribing, not copying into useState.',
      tags: ['useSyncExternalStore', 'external state', 'localStorage'],
      hints: [
        'The snapshot is the raw string: `useSyncExternalStore(subscribe, () => localStorage.getItem(key))`. Two reads of an unchanged key are `===`.',
        'Parse outside the snapshot: `useMemo(() => parse(raw, initialRef.current), [raw])`, where `parse` returns the fallback for `null` and for a `JSON.parse` that throws.',
        'Keep a module-level `Set` of listeners. `subscribe(cb)` adds `cb` to it and to `window`\'s `storage` event, and returns a function that removes both. `setValue` and `remove` call every listener after writing.',
        'For updaters, read the stored value at call time: `const current = parse(localStorage.getItem(key), initialRef.current)`. The value from the render closure is stale by the second call.',
      ],
    },
    {
      id: 'react-effect-timing',
      title: 'Layout effects, passive effects, cleanups',
      kind: 'quiz',
      xp: 60,
      why: 'Flicker, double subscriptions and briefly-wrong data are all timing bugs; knowing the commit order fixes them in minutes.',
      tags: ['useEffect', 'useLayoutEffect', 'StrictMode'],
      hints: [
        'Effects run children first, then parents, the same as the order components finish mounting.',
        'Anything that must be right before the first paint (measuring, positioning) goes in a layout effect.',
      ],
      quiz: [
        {
          q: 'A `Parent` renders a `Child`. Both call `useEffect(() => console.log(name), [])`. What is logged on mount?',
          options: ['`Parent` then `Child`', '`Child` then `Parent`', 'The order is not defined', '`Parent` only; `Child` waits for the next commit'],
          answer: [1],
          explain: 'Effects run children before parents, in one pass after the commit. That is why a parent that updates a ref in `useEffect` is still stale when a child\'s effect reads it, and why `useLatest` updates its ref in a layout effect instead.',
        },
        {
          q: 'A tooltip measures its trigger with `getBoundingClientRect()` and sets its own position in state. Users see it flash at the top-left for one frame. The fix?',
          options: [
            'Move the measurement from `useEffect` to `useLayoutEffect`',
            'Wrap the `setState` in `requestAnimationFrame`',
            'Measure during render, in the component body',
            'Add the position to the dependency array',
          ],
          answer: [0],
          explain: 'Layout effects run after the DOM is updated but before the browser paints, and a state update made there is rendered synchronously before paint. `useEffect` runs after paint, so the first frame shows the unpositioned tooltip. Measuring during render reads the *previous* DOM, and `requestAnimationFrame` still lets one frame through.',
        },
        {
          q: 'In development, a chat component opens two WebSocket connections on mount. In production it opens one. What is the most likely cause?',
          options: [
            'A React bug in StrictMode that you should work around with a `didInit` ref',
            'The effect has no cleanup that closes the socket, and StrictMode\'s simulated unmount and remount exposes it',
            'The dependency array is missing, so the effect runs on every render',
            'Development builds render twice, and each render opens a socket',
          ],
          answer: [1],
          explain: 'StrictMode runs setup, cleanup, setup on mount precisely to surface effects that do not undo themselves. With `return () => socket.close()` you get one live connection in both modes. The same bug in production leaks a socket every time the user navigates away and back. A `didInit` ref hides the symptom and keeps the leak.',
        },
        {
          q: 'An effect subscribes to `userId`\'s presence channel with `[userId]` as its dependencies. `userId` changes from `1` to `2`. What happens, in order?',
          options: [
            'Subscribe to 2, then unsubscribe from 1',
            'Unsubscribe from 2, then subscribe to 2',
            'Unsubscribe from 1 (cleanup from the previous render), then subscribe to 2',
            'Subscribe to 2 only; the old subscription is cleaned up when the component unmounts',
          ],
          answer: [2],
          explain: 'The cleanup is the closure returned by the *previous* effect run, so it still sees `userId = 1`. React runs it, then the new effect. This is why cleanups do not need to read "the old id" from anywhere: the closure already has it.',
        },
        {
          q: 'Which belong in an effect\'s cleanup function? Select all that apply.',
          options: [
            'Removing an event listener the effect added',
            'Aborting a fetch the effect started',
            'Clearing a timer the effect set',
            'Resetting the component\'s own state to its initial values',
          ],
          answer: [0, 1, 2],
          explain: 'A cleanup undoes what the setup did to the world outside the component. Resetting the component\'s own state is pointless on unmount (the state is discarded) and on a dependency change it causes an extra render; reset during render or with a `key` instead.',
        },
        {
          q: 'A component copies a prop into state with `useEffect(() => setFullName(first + " " + last), [first, last])`. What does the user see when `last` changes?',
          options: [
            'One render with the old full name, then a second render with the new one',
            'The new full name immediately; effects run before render',
            'Nothing changes until the component remounts',
            'An infinite render loop',
          ],
          answer: [0],
          explain: 'The effect runs after the render that already painted the old value, and its `setState` triggers a second render. Compute derived values during render (`const fullName = first + " " + last`) and the extra render and the stale frame disappear.',
        },
      ],
    },
    {
      id: 'react-autosave',
      title: 'BOSS: an autosave that never loses an edit',
      kind: 'react',
      xp: 240,
      boss: true,
      why: 'Autosave is a staple feature, and every naive version loses data: out-of-order writes, stale callbacks, or the last edit dropped on close.',
      tags: ['custom hooks', 'refs', 'debounce', 'concurrency'],
      hints: [
        'Keep everything a timer or promise reads later in refs: the latest `{ value, save, delay, schedule }` (updated in a layout effect), the last saved value, whether a save is in flight, whether another was requested meanwhile, and the timer\'s cancel function.',
        'Write one stable `saveNow` with `useCallback(function saveNow() { ... }, [])`. It cancels the timer, returns early if the value equals the last saved one, sets a `queued` flag if a save is in flight, and otherwise calls `save`. Use it for both the timer and `flush`.',
        'When a save settles, clear the in-flight marker, record the saved value on success, and then: if `queued` was set and the latest value is still unsaved, call `saveNow()` again; otherwise set `\'error\'`, `\'saved\'`, or `\'pending\'` (value moved on).',
        'The debounce effect runs on `[value]`. Skip it when the value equals the last one it saw (that covers mount and StrictMode\'s re-run); otherwise cancel the old timer and `schedule(saveNow, delay)`.',
        'A separate `useEffect(() => () => { ... }, [])` handles unmount: cancel the timer, and call `latest.current.save(v)` if `v` is unsaved and not already in flight. Guard the post-settle `setState` calls with a `mounted` ref.',
      ],
    },
  ],
});
