import { loadChapter } from '../../load.ts';

const here = import.meta.dirname;

export default loadChapter(here, {
  id: 'js-collections',
  title: "Collections in Practice",
  summary: "Map and Set semantics, LRU with Map, stable sorting, Intl.Collator, dedupe and grouping by key.",
  lessons: [
    {
      id: 'js-map-set-semantics',
      title: 'Map, Set and object keys',
      kind: 'quiz',
      xp: 60,
      why: 'Choosing `{}` over `Map` decides how keys are compared, ordered and serialised, and each wrong choice is a bug that only shows up on real data.',
      tags: ['collections', 'Map', 'Set', 'code review'],
      quiz: [
        {
          q: 'What is `counts` afterwards?\n\n```js\nconst counts = {};\nfor (const id of [1, "1", 2]) counts[id] = (counts[id] ?? 0) + 1;\n```',
          options: [
            '`{ 1: 1, "1": 1, 2: 1 }` — three keys',
            'It throws: a number cannot be used as an object key',
            '`{ "1": 2, "2": 1 }` — two keys',
            '`{ "1": 1, "2": 1 }` — the second write replaces the first',
          ],
          answer: [2],
          explain: 'Property keys are strings (or symbols), so the number `1` is converted to `"1"` and both iterations update the same key. With ids from two sources — a number from one API, a string from a URL — an object silently merges them. A `Map` keeps `1` and `"1"` apart, because it compares keys with SameValueZero and does no conversion.',
        },
        {
          q: '`new Set([{ id: 1 }, { id: 1 }, NaN, NaN, 0, -0]).size` is:',
          options: ['3', '4', '5', '6'],
          answer: [1],
          explain: 'Sets (and Map keys) use SameValueZero: `NaN` equals `NaN` (unlike `===`), and `0` equals `-0`, so those four values collapse to two. The two objects are different objects, so both stay — a Set of objects deduplicates by identity, not by content. To dedupe records, key a Map by the field that identifies them.',
        },
        {
          q: 'A server caches per-user state in `const state = { sessions: new Map() }` and a health endpoint returns `JSON.stringify(state)`. What does it show for a map with 300 sessions?',
          options: [
            '`{"sessions":{"<id>":…}}` with all 300 entries',
            '`{"sessions":[["<id>",…],…]}` — an array of entries',
            'It throws `TypeError: Converting circular structure to JSON`',
            '`{"sessions":{}}`',
          ],
          answer: [3],
          explain: '`JSON.stringify` only serialises own enumerable string-keyed properties, and a Map keeps its entries in an internal slot, not in properties — so every Map (and Set) becomes `{}`, silently. Convert explicitly: `Object.fromEntries(map)` for string keys, or `[...map]` for entries, or give the containing class a `toJSON()`.',
        },
        {
          q: 'This loop runs over `new Map([["tmp1", 1], ["a", 2], ["tmp2", 3], ["b", 4]])`. Which statements are true? (select all)\n\n```js\nfor (const k of map.keys()) {\n  if (k.startsWith("tmp")) map.delete(k);\n  if (k === "a") map.set("c", 5);\n}\n```',
          options: [
            'Deleting the current key is safe, and the loop still visits `tmp2` and `b`',
            'The loop iterates over a snapshot, so `c` is not visited',
            'The key `c`, added during the loop, is visited later in the same loop',
            'Deleting during iteration throws, like Java\'s `ConcurrentModificationException`',
          ],
          answer: [0, 2],
          explain: 'Map and Set iterators are live: they walk the entries in insertion order as they are *now*. Deleting an entry (even the current one) is safe and it is simply not visited again; an entry added during iteration is visited when the iterator reaches it. That is what makes delete-while-iterating cleanup loops fine — and what makes a loop that keeps adding keys run forever. Iterate over `[...map.keys()]` when you want a snapshot.',
        },
        {
          q: 'An API returns `{ "10": {...}, "2": {...}, "b7": {...}, "a1": {...} }` in the order the server ranked them, and the UI renders `Object.values(byId)`. What order does the UI show?',
          options: [
            '`2`, `10`, `b7`, `a1`',
            '`10`, `2`, `b7`, `a1` — insertion order',
            '`10`, `2`, `a1`, `b7` — numbers by insertion, strings alphabetically',
            'Unspecified — it depends on the engine',
          ],
          answer: [0],
          explain: 'Since ES2015 the order is specified: integer-like keys ("array indices") first, in ascending numeric order, then the other string keys in insertion order. So an object keyed by numeric id is quietly sorted by id and loses the server\'s ranking. Send ranked data as an array, or build a Map, which keeps pure insertion order for every kind of key.',
        },
        {
          q: 'You need to attach metadata to DOM nodes (or request objects) you do not own, without keeping them alive after they are gone. What do you use?',
          options: [
            'A `Map` keyed by the node; entries disappear when the node leaves the document',
            'A `Map` keyed by a string id, because objects cannot be Map keys',
            'A `WeakMap` keyed by the node: once nothing else references the node, the entry can be collected',
            'A `WeakMap`, because it is faster to iterate than a `Map`',
          ],
          answer: [2],
          explain: 'A `Map` holds its keys strongly: a removed node stays in memory for as long as the map does — a classic leak in long-lived single-page apps. A `WeakMap` does not keep its keys alive, which is exactly why it cannot be iterated and has no `size`: its contents depend on the garbage collector. Objects are perfectly good `Map` keys; they are compared by identity.',
        },
        {
          q: '`const byTeam = Object.groupBy(users, (u) => u.team);` — what does `byTeam.hasOwnProperty("web")` do?',
          options: [
            'Returns `true` if any user is in the `web` team',
            'Throws a `TypeError`: the result has a null prototype, so it has no `hasOwnProperty` method',
            'Returns `false` — `groupBy` returns a Map, which has no own properties',
            'Returns `true` for any team name, because of prototype lookup',
          ],
          answer: [1],
          explain: '`Object.groupBy` returns an object created with `Object.create(null)` so that a group named `"constructor"` or `"__proto__"` is just a key. The flip side is that `Object.prototype` methods are not there. Use `Object.hasOwn(byTeam, "web")` or `"web" in byTeam` — or `Map.groupBy`, which returns a real Map.',
        },
      ],
    },
    {
      id: 'js-diff-by-id',
      title: 'Diff two lists by id',
      kind: 'js',
      xp: 80,
      why: 'Every sync, import and "save changes" screen is a diff, and the `filter` + `find` version freezes the tab at 50 000 rows while `JSON.stringify` reports rows as changed because their keys came back in another order.',
      tags: ['collections', 'Map', 'performance', 'sync'],
      hints: [
        'Index each side once: a `Map` from key to record. Building it is also the natural place to spot a duplicate key — `if (index.has(k)) throw …` before `index.set(k, record)`.',
        'A `Map` iterates in insertion order, which is array order. Walk the `next` index to find `added` and `changed`, and the `prev` index to find `removed`; each lookup in the other index is O(1).',
        'Use a `Map`, not `{}`: object keys are strings, so `1` and `"1"` collide, and a key like `"__proto__"` sets the prototype instead of adding an entry.',
        'Shallow equality: `Object.keys(a)` and `Object.keys(b)` have the same length, and every key of `a` is an own key of `b` (`Object.hasOwn`) whose value is `Object.is`-equal. `Object.is(NaN, NaN)` is true, which is what you want here.',
      ],
    },
    {
      id: 'js-lru-map',
      title: 'An LRU cache on a Map',
      kind: 'js',
      xp: 85,
      why: 'A memo `Map` with no bound is a memory leak with good intentions; an LRU bound is the default fix, and its bugs (evicting on overwrite, treating a cached `0` as a miss) only show up under real traffic.',
      tags: ['collections', 'Map', 'caching', 'LRU'],
      hints: [
        'A `Map` remembers insertion order. If "using" a key means `delete(key)` then `set(key, value)`, the map\'s first key is always the least recently used.',
        'The oldest entry is `this.#map.entries().next().value` — a `[key, value]` pair, found in O(1) without copying the keys into an array.',
        'Decide presence with `map.has(key)`, never by comparing the value to `undefined`: a cached `undefined`, `0` or `""` is a hit and must be refreshed.',
        'In `set`, move the key to the end first (delete + set), **then** check `size > max`. An overwrite leaves the size unchanged, so nothing is evicted; a new key makes it `max + 1`, so exactly one entry goes.',
      ],
    },
    {
      id: 'js-sort-by-keys',
      title: 'Multi-key sorting that stays stable',
      kind: 'js',
      xp: 80,
      why: '"Sort by status, then newest first" is on every table, and the usual comparator mutates the store, reorders ties at random, and floats the empty rows to the top when you flip the direction.',
      tags: ['collections', 'sorting', 'arrays'],
      hints: [
        'Turn each criterion into a comparator `(x, y) => number`, then combine them: run them in order and return the first non-zero result; return `0` if all tie. `items.toSorted(combined)` is stable and does not mutate.',
        'A comparator must return `0` for equal values — that is what lets the stable sort keep input order. `a < b ? -1 : a > b ? 1 : 0` works for numbers, strings, and Dates once you turn a Date into `getTime()`.',
        'Descending is `sign * compare(a, b)` with `sign = -1` — never `.reverse()`, which flips the ties and moves the missing values to the front.',
        'Handle missing values (`null`, `undefined`, `NaN`) **before** applying the sign: if both are missing return `0`; if only `a` is, return `1`; if only `b` is, return `-1`. They stay last in both directions.',
      ],
    },
    {
      id: 'js-collator-names',
      title: 'Sorting and matching names with Intl.Collator',
      kind: 'js',
      xp: 75,
      why: 'A contact list that files "Émile" after "Zack" and "Room 10" before "Room 2" looks broken to every user, and stripping accents to match names is wrong in half of Europe.',
      tags: ['collections', 'Intl', 'sorting', 'i18n'],
      hints: [
        '`new Intl.Collator(locale, options).compare` is a ready-made comparator: pass it straight to `toSorted`.',
        'For sorting, `{ numeric: true }` makes `"Room 2"` sort before `"Room 10"`. Leave `sensitivity` at its default so `"anna"` and `"Anna"` still get a consistent order.',
        'For matching, `{ sensitivity: "base" }` makes `compare(a, b) === 0` whenever the strings differ only in case or accents — and the locale decides what an accent is, which is why `Ö` and `O` match in `de` but not in `sv`.',
        'A prefix match is `compare(name.slice(0, query.length), query) === 0`. Cache the collators in a `Map` keyed by locale and options rather than creating one per call.',
      ],
    },
    {
      id: 'js-set-algebra',
      title: 'Permissions as set algebra',
      kind: 'js',
      xp: 75,
      why: 'Role checks are unions and differences; written with arrays they duplicate, go quadratic, loop forever on a role cycle, or `push` one user\'s grant into a shared role.',
      tags: ['collections', 'Set', 'authorization'],
      hints: [
        'Resolve roles with a work list and a `visited` Set: pop a name, skip it if visited, look it up (throw if missing), add its grants, push its `inherits`. The `visited` check is what ends a cycle.',
        'Add grants into a fresh `Set` you own. Never start from `role.grants` itself — pushing into it edits the role for everyone.',
        'Order matters for denies: build the full granted set (roles ∪ user grants) first, then take `.difference(new Set(user.denies ?? []))`.',
        '`missingPermissions`: a permission is satisfied by `granted.has(p)`, `granted.has("*")`, or `granted.has(resource + ":*")` where `resource` is the text before the first `:`. Collect misses into a Set (insertion order = required order) and spread it into an array.',
        '`permissionChanges` is `after.difference(before)` and `before.difference(after)`, each spread into an array and `toSorted()`.',
      ],
    },
    {
      id: 'js-tuple-key-map',
      title: 'A Map keyed by tuples',
      kind: 'js',
      xp: 90,
      why: 'Composite cache keys built with `join` or `JSON.stringify` collide on real data, and a colliding cache key serves one user\'s data to another, quickly.',
      tags: ['collections', 'Map', 'caching', 'keys'],
      hints: [
        'Skip string encoding altogether. Walk the tuple one element at a time through nested Maps: `node = node.children.get(part)`. Each Map compares its keys with SameValueZero, and objects by identity, for free.',
        'A node needs two things: `children` (a Map) and whether a key **ends** here. Store that as `entry: { key, value } | null` rather than as a value you compare to `undefined` — the value can be `undefined`.',
        'Because each key ends at its own node, `[1]` and `[1, undefined]` land on different nodes, and `[]` ends at the root. A prefix of a stored key reaches a node whose `entry` is `null`.',
        'For `size` and ordered `entries()`, keep the entry objects in an insertion-ordered `Set` too: add on first set, delete on delete, and update `entry.value` in place on overwrite. Store `[...key]`, not the caller\'s array.',
      ],
    },
    {
      id: 'js-dedupe-merge',
      title: 'Deduplicate by merging',
      kind: 'js',
      xp: 80,
      why: 'Every CSV import and CRM sync has the same person three times with different casing and different gaps; "dedupe" means merge them without losing the phone number that only row three had.',
      tags: ['collections', 'Map', 'data cleaning'],
      hints: [
        'One pass with a `Map` from normalised email to the merged contact you are building. When the key is new, create the merged object and push it to the output array right away — that fixes its position.',
        'Keep merging simple by starting every merged contact at `{ email, name: null, phone: null, company: null, tags: new Set() }` and "absorbing" each row into it: a text field is only set while it is still `null`.',
        '"Non-blank string, trimmed": `typeof v === "string" && v.trim() !== "" ? v.trim() : null`. A `Set` gives you tag union with first-seen order; convert it to an array at the end.',
        'A row with no usable email gets its own fresh merged object, pushed to the output but never stored in the Map, so nothing can merge into it.',
      ],
    },
    {
      id: 'js-indexed-store',
      title: 'BOSS: an indexed in-memory store',
      kind: 'js',
      xp: 220,
      boss: true,
      why: 'Normalised client stores, caches and test fakes all grow secondary indexes, and the bugs are always consistency bugs: a record in two buckets, a half-applied update, 799 rows left behind by a failed import.',
      tags: ['collections', 'Map', 'indexes', 'consistency'],
      hints: [
        'State: `rows` — a `Map` from id to frozen record (a Map keeps first-insertion order, and `set` on an existing key keeps its place); and one `Map(value → Set(id))` per indexed or unique field.',
        'Split every write into **validate** then **apply**. Validation reads state and may throw; apply only runs after it passed, so a throw can never leave the store half-changed.',
        '`update`: build `next = Object.freeze({ ...old, ...patch })`, check the key did not change, check unique fields against holders **other than this id**, then remove `old` from every index bucket, store `next`, and add `next` to the buckets.',
        '`insertMany`: validate the whole batch first, keeping a Set of the batch\'s keys and one Set per unique field for values the batch has already claimed. Only then insert them all. `insert(r)` can simply be `insertMany([r])[0]`.',
        'To return index buckets in insertion order, keep an insertion counter per id and sort the bucket\'s ids by it (or filter `rows.values()` by bucket membership). `query` is: candidates from an index if a where-field has one, else all rows; filter every where-field with SameValueZero; then the multi-key sort.',
      ],
    },
  ],
});
