import { loadChapter } from '../../load.ts';

const here = import.meta.dirname;

export default loadChapter(here, {
  id: 'react-state-management',
  title: "State Management Without a Library",
  summary: "Splitting context, reducer stores, selectors, URL as state, lifting and colocating.",
  lessons: [
    {
      id: 'react-where-state-lives',
      title: 'Where should this state live?',
      kind: 'quiz',
      xp: 60,
      why: 'Most state bugs and most "we need Redux" debates come from state kept in the wrong place.',
      tags: ['architecture', 'colocation', 'derived state'],
      hints: [
        'Ask first whether it can be computed from something else. Derived state is not state.',
        'Would a user expect it to survive a refresh or a shared link? Then it belongs in the URL.',
      ],
      quiz: [
        {
          q: 'An orders page shows a table plus a badge with the number of orders over £100. Where should the badge count live?',
          options: [
            'In `useState`, updated in an effect whenever `orders` changes',
            'In a context so the header can read it too',
            'Nowhere: compute `orders.filter((o) => o.total > 100).length` during render',
            'In the URL, so it survives a refresh',
          ],
          answer: [2],
          explain: 'It is derived from `orders`. Storing it adds a second source of truth and a render where the two disagree. If the calculation were expensive, `useMemo` it, but it is still derived.',
        },
        {
          q: 'Support needs to send customers a link to "orders, status = shipped, sorted by date, page 3". Where does that state belong?',
          options: [
            'In `useState` in the page component',
            'In the URL query string',
            'In `localStorage`, keyed by the user id',
            'In a global store, initialised from the server',
          ],
          answer: [1],
          explain: 'Anything that should survive refresh, Back/Forward and sharing is URL state. `localStorage` is per browser, so the customer\'s link would open with their own old filters, not the ones support meant.',
        },
        {
          q: 'A `ProductPage` fetches the product in an effect and also copies it into a global store "so the cart can read the price". What goes wrong first?',
          options: [
            'Nothing, as long as the store is updated in the same effect',
            'The two copies drift: a refetch, an edit or a second tab updates one and not the other, and the cart shows a stale price',
            'The page renders twice as often, which is only a performance problem',
            'Global stores cannot hold objects from the server',
          ],
          answer: [1],
          explain: 'Server data copied into client state becomes a cache you now have to invalidate by hand. Keep one server cache keyed by request (what query libraries do) and let both components read from it, or have the cart store only ids and quantities and look prices up.',
        },
        {
          q: 'A dropdown\'s `isOpen` flag lives in the app-level store because "one day something might need it". What is the cost?',
          options: [
            'None, as long as the store uses selectors so only the dropdown re-renders',
            'It leaks memory, because store state outlives the component',
            'None today, but it will have to be persisted to `localStorage` as well',
            'The dropdown can no longer be reused or tested without that store, two dropdowns share one flag, and the flag outlives the dropdown (it reopens already open)',
          ],
          answer: [3],
          explain: 'Colocate: state starts in the component that uses it and moves up only when a second component needs it. Selectors limit the re-renders, but not the coupling: the component now depends on a global key, instances collide, and stale state survives unmounting. Moving state up later, when a second reader appears, is a small refactor.',
        },
        {
          q: 'A `DatePicker` should work both with `value`/`onChange` from a form library and on its own. Which design is correct?',
          options: [
            'Copy `value` into internal state on mount and sync it with an effect',
            'Always keep internal state and call `onChange` so the parent can mirror it',
            'Controlled when `value` is passed (never keep a copy), uncontrolled with internal state from `defaultValue` otherwise, and call `onChange` in both modes',
            'Require `value` and `onChange` always; uncontrolled components are an anti-pattern',
          ],
          answer: [2],
          explain: 'That is the controlled/uncontrolled pattern native inputs use (`value` versus `defaultValue`). Copying the prop into state creates two sources of truth: the parent cannot veto a change, and every update renders one stale frame.',
        },
        {
          q: 'Which of these are good reasons to move state into context or a store rather than lifting it to a common parent? Select all that apply.',
          options: [
            'The common parent is many levels up and the props would pass through components that do not use them',
            'Many unrelated parts of the tree read it (the signed-in user, the theme)',
            'Two sibling components need it',
            'It is updated often, so it should be global',
          ],
          answer: [0, 1],
          explain: 'Two siblings are the textbook case for lifting to their parent. Update frequency argues the other way: frequently changing state in a context re-renders every consumer, which is why a store with selectors (or a split context) exists.',
        },
      ],
    },
    {
      id: 'react-controllable-state',
      title: 'Controlled or uncontrolled, never both',
      kind: 'react',
      xp: 85,
      why: 'Every reusable component needs to work both ways; copying props into state is the bug that ships instead.',
      tags: ['controlled components', 'custom hooks', 'component API'],
      hints: [
        'Decide per render: `const controlled = value !== undefined; const state = controlled ? value : internal;`. Never copy `value` into `useState`.',
        'Keep `useState(defaultValue)` for the uncontrolled case only; in controlled mode `setState` just calls `onChange`.',
        'For a stable `setState` that sees the latest state and `onChange`, keep them in a ref updated in a layout effect and create `setState` with `useCallback(..., [])`.',
        'So two updaters in one handler compose in uncontrolled mode, update the ref\'s state as soon as you call `setInternal(resolved)`: `latest.current = { ...latest.current, state: resolved }`.',
      ],
    },
    {
      id: 'react-split-context',
      title: 'Split context: state here, actions there',
      kind: 'react',
      xp: 80,
      why: 'One context holding state and actions re-renders every button in the app on every change.',
      tags: ['context', 'performance', 'useMemo'],
      hints: [
        'Two contexts: one whose value is the `toasts` array, one whose value is the `{ show, dismiss }` object.',
        'Create the actions once with `useMemo(() => ({ ... }), [])` or `useState(() => ({ ... }))`. For that to be correct they must never read `toasts` directly: use updater functions, `setToasts((list) => ...)`.',
        'Ids come from a ref counter (`const nextId = useRef(1)`), incremented inside `show`, so `show` can return the id synchronously.',
        'Create both contexts with `null` as the default and throw from the hook when `useContext` returns `null`.',
      ],
    },
    {
      id: 'react-store-selectors',
      title: 'A store with selectors',
      kind: 'react',
      xp: 95,
      why: 'Zustand and Redux fit in fifty lines; knowing how they avoid re-renders tells you when context is not enough.',
      tags: ['useSyncExternalStore', 'selectors', 'performance'],
      hints: [
        '`createStore` is a closure over `let state` and a `Set` of listeners. In `setState`, bail out when every key of the partial is `Object.is`-equal to the current one; otherwise replace `state` and call a *copy* of the listeners.',
        '`useStore` is `useSyncExternalStore(subscribe, getSnapshot)` where `getSnapshot` returns the selection, not the whole state.',
        'The snapshot must be stable. Keep the last `{ state, selection }` in a ref: if the state is the same object, return the cached selection; if `isEqual(cached, next)`, return the cached one too.',
        'For `shallowEqual`, handle `Object.is` first, then two arrays (length plus item-by-item `Object.is`), then two plain objects (same key count, and every key of `a` exists in `b` with an `Object.is`-equal value). Everything else is `false`.',
      ],
    },
    {
      id: 'react-url-state',
      title: 'The URL as state',
      kind: 'react',
      xp: 90,
      why: 'Filters and tabs that do not survive a refresh, a shared link or the Back button are a daily user complaint.',
      tags: ['routing', 'history API', 'useSyncExternalStore'],
      hints: [
        'Subscribe to the URL with `useSyncExternalStore(subscribe, () => window.location.search)`; the query string is a primitive, so unchanged URLs compare equal.',
        '`subscribe` listens to `popstate` (Back/Forward) and adds the callback to a module-level `Set`, because `pushState` fires no event: after writing, call every listener yourself.',
        'Build the new URL with `const url = new URL(window.location.href); url.searchParams.set(name, next)` (or `.delete(name)`) so other parameters and encoding are handled for you.',
        'Compare `url.href` with `window.location.href` before writing, and skip the write when they match. Then `history[replace ? \'replaceState\' : \'pushState\'](null, \'\', url.pathname + url.search + url.hash)`.',
      ],
    },
    {
      id: 'react-state-machine',
      title: 'A reducer as a state machine',
      kind: 'react',
      xp: 95,
      why: 'Booleans allow impossible states and late async events overwrite fresh ones; a status-driven reducer rules both out.',
      tags: ['useReducer', 'state machines', 'async'],
      hints: [
        'Switch on `action.type`, and inside each case check `state.status` first. Anything not allowed returns `state`, the same object.',
        'Build each new state from scratch with only its fields (`{ status: \'done\', attempt, file, url }`) rather than spreading the old one, so no stale `progress` or `error` survives.',
        'For `progress`, `succeed` and `fail`, also require `action.attempt === state.attempt`. That one check is what makes late events from a cancelled upload harmless.',
        'In the component, start the request in an effect keyed on `[status, attempt]` while `uploading`: create an `AbortController`, pass `attempt` into every dispatched event, and `abort()` in the cleanup.',
      ],
    },
    {
      id: 'react-immutable-updates',
      title: 'Immutable nested updates',
      kind: 'react',
      xp: 85,
      why: 'Mutating nested state is invisible to `memo`, selectors and undo; structural sharing is what makes them work.',
      tags: ['immutability', 'useReducer', 'React.memo'],
      hints: [
        'Recursion fits the path: `setIn(obj, [key, ...rest], value)` computes the new child with `setIn(obj[key] ?? {}, rest, value)` (or `value` when `rest` is empty) and copies only `obj`.',
        'Before copying, check `key in obj && Object.is(obj[key], nextChild)`: if nothing changed below, return `obj`. That is what keeps no-op updates from creating new objects all the way up.',
        'Copy arrays with `obj.slice()` and objects with `{ ...obj }`, then assign the one changed key.',
        '`toggleAll` can reuse `setIn` in a loop over the channel\'s keys: each unchanged key returns the same state, so the whole thing is a no-op when nothing changes.',
      ],
    },
    {
      id: 'react-undo-redo',
      title: 'Undo and redo',
      kind: 'react',
      xp: 85,
      why: 'Undo is the feature product asks for after launch; it is easy only if you know the past/present/future shape.',
      tags: ['useReducer', 'history', 'custom hooks'],
      hints: [
        'Hold `{ past, present, future }` in one `useReducer`, so two `set` calls in one handler each see the previous result.',
        '`set`: resolve the updater against `present`, return `state` if `Object.is` equal, otherwise `{ past: [...past, present].slice(-limit), present: next, future: [] }`.',
        '`undo` moves the last of `past` into `present` and puts the old present at the front of `future`; `redo` is the mirror image. Both return `state` when there is nothing to do.',
        '`dispatch` is stable, so create the four functions once: `const [actions] = useState(() => ({ set: (next) => dispatch({ type: \'set\', next, limit }), ... }))`.',
      ],
    },
    {
      id: 'react-board-store',
      title: 'BOSS: a Kanban store that does not stutter',
      kind: 'react',
      xp: 250,
      boss: true,
      why: 'Boards, editors and dashboards are where naive state management collapses; this is how to build one that scales without a library.',
      tags: ['state architecture', 'selectors', 'immutability', 'undo'],
      hints: [
        'Write the four edits as pure functions `(board, action) => board` that return `board` itself when nothing changes. Everything else (history, rendering) depends on that.',
        'Wrap them in a history reducer over `{ past, present, future }`: undo/redo as in the undo lesson; for an edit, `if (next === present) return state`, otherwise push and clear the future. Keep 50 entries with `.slice(-50)`.',
        'Put the state in a store object outside React (`getState`, `subscribe`, `dispatch`, `actions`), created once in the provider with `useState(() => createBoardStore(initialBoard))`. The context value is the store, which never changes.',
        '`useBoard` is the selector hook from the store lesson: `useSyncExternalStore` with a cached selection, selecting from `state.present`. `useBoardHistory` is the same with an `isEqual` that compares both flags.',
        'For `addCard`, generate the id before dispatching: `do id = \'c\' + ++counter; while (Object.hasOwn(state.present.cards, id));`, and return it.',
      ],
    },
  ],
});
