import { loadChapter } from '../../load.ts';

const here = import.meta.dirname;

export default loadChapter(here, {
  id: 'testing-strategy-2',
  title: "Test Strategy & Hygiene",
  summary: "Flakiness, the test pyramid versus trophy, contract tests, snapshots, test data builders.",
  lessons: [
    {
      id: 'test-wait-for-helper',
      title: 'Poll, don\'t sleep: a waitFor helper',
      kind: 'js',
      xp: 85,
      why: 'Fixed sleeps are the single most common source of flaky tests; a polling helper with a good failure message removes them.',
      tags: ['flaky tests', 'async', 'test helpers'],
      hints: [
        'Work out the deadline once, at the start: `const deadline = now() + timeoutMs`. Every later decision compares `now()` with it.',
        'Loop: try the check and `return await check()` if it does not throw. In the `catch`, remember the error, then decide whether to sleep or give up.',
        'After a failed check, `remaining = deadline - now()`. If `remaining <= 0`, throw. Otherwise `await sleep(Math.min(intervalMs, remaining))` and go round again. That gives the last check exactly at the deadline.',
        'The rejection is `new Error(`waitFor timed out after ${timeoutMs}ms: ${lastError.message}`, { cause: lastError })`. Passing `{ cause }` as the second argument sets `error.cause`.',
      ],
    },
    {
      id: 'test-flaky-diagnosis',
      title: 'Diagnosing flaky tests',
      kind: 'quiz',
      xp: 70,
      why: 'A mid-level engineer is expected to find the cause of a flake, not re-run CI until it goes green.',
      tags: ['flaky tests', 'debugging', 'test isolation'],
      quiz: [
        {
          q: '`users.test.js` passes when run on its own and fails in the full suite, but only when `admin.test.js` runs before it in the same worker. What is the most likely cause?',
          options: [
            'The full suite is slower, so a timeout in `users.test.js` is too tight',
            '`admin.test.js` leaves shared state behind: a row it inserted, a module-level cache it filled, or a mock it replaced and never restored',
            'The test runner has a bug in how it orders files, and pinning the order will fix it',
            '`users.test.js` has a wrong assertion that only shows up by chance',
          ],
          answer: [1],
          explain: '"Passes alone, fails after X" is the signature of **order dependence**: one test changes something shared and the next one inherits it. Reproduce it by running the two files together (`vitest run admin users`), then find the leak: a `jest.spyOn` without `mockRestore`, a singleton cache, rows that are never cleaned up. The fix is that every test sets up what it needs and tears down what it creates. Pinning the file order hides the leak until someone adds a third file.',
        },
        {
          q: 'A repository test runs `select * from orders where customer_id = $1` and asserts `expect(rows).toEqual([order1, order2])`. It fails about one run in twenty on CI and never on laptops. Which fixes are correct? (Select all that apply.)',
          options: [
            'Add `order by id` to the query, if the callers rely on the order',
            'Run CI against the same Postgres minor version as the laptops',
            'Sort the rows in the test before comparing, if order is not part of the function\'s contract',
            'Retry the test: the query planner is non-deterministic, so there is nothing else to do',
          ],
          answer: [0, 2],
          explain: 'Without `order by`, SQL returns rows in whatever order the plan produces, and that changes with table size, vacuum, parallel workers and concurrent writes, which is why CI (bigger, busier database) sees it. Decide whether order is part of the contract. If callers need it, the **code** is wrong and needs an `order by` with a unique tiebreaker. If they do not, the **test** is wrong and should compare order-insensitively. Matching versions only makes the accident rarer.',
        },
        {
          q: 'A test for `dueLabel()` passes all day and fails on CI runs between 23:00 and 00:00 UTC. The test builds its expected value from `new Date()`, and the code formats "today" in the user\'s time zone, `Europe/London`. What is the fix?',
          options: [
            'Schedule CI so it never runs in that hour',
            'Increase the test timeout; CI is slow late at night',
            'Pass a fixed clock and an explicit time zone into the code, and pin the test to chosen instants, including one late in the evening',
            'Set `TZ=UTC` on the CI runners so they match the developers\' machines',
          ],
          answer: [2],
          explain: 'The test and the code each read the real clock and each work out "today", in two different time zones. For one hour a day (in summer, when London is UTC+1) they disagree. Setting `TZ` on CI only moves the window to somebody else\'s laptop. Inject the clock, pass the zone explicitly, and write the late-evening case on purpose. A time-dependent test should fail on the day you write it, not at 23:30 three weeks later.',
        },
        {
          q: 'An API test fails about once in 200 runs with `EADDRINUSE: address already in use :::3000`. The suite runs in 4 parallel workers. What is the best fix?',
          options: [
            'Run the whole suite in a single worker',
            'Catch `EADDRINUSE` and retry `listen(3000)` after 100 ms',
            'Close the server in `afterAll` instead of `afterEach`',
            'Listen on port `0`, read the port the OS assigned from `server.address().port`, and build the test\'s URLs from it',
          ],
          answer: [3],
          explain: 'Two workers occasionally start a server at the same moment, and both ask for 3000. Port `0` asks the OS for any free port, so no two servers can collide, and the test reads the real port back. A single worker makes the suite four times slower to hide the problem, and retrying just narrows the race. Always close the server in a `finally` or `afterEach` too, but that is a separate leak.',
        },
        {
          q: 'Tests build users with a fake-data library (`faker.person.lastName()`). Once in a few hundred runs, the signup test fails with a validation error. What should you do? (Select all that apply.)',
          options: [
            'Log the random seed on every run, so a failing run can be replayed exactly',
            'Replace the random data with the same hard-coded user everywhere, so the test can never vary',
            'Find the value that failed (for example `O\'Brien`), add an explicit test for it, and fix the validation if it is wrong',
            'Mark the test as flaky and move on: random data is supposed to vary',
          ],
          answer: [0, 2],
          explain: 'This "flake" found a real bug: some legitimate last names contain an apostrophe or a space, and the validation rejects them. Random data is useful exactly because it hits cases you did not think of. It is only useful if a failure can be **reproduced**, so log (or pin) the seed. Then turn the case it found into a permanent, explicit test. Freezing all data to one value throws away the thing that found the bug.',
        },
        {
          q: 'A test sometimes fails with an assertion message that belongs to a **different** test, one that ran earlier in the file and reported as passing. What is the most likely cause?',
          options: [
            'The earlier test starts async work without awaiting or returning it, so its assertion runs after that test has already been reported as passed',
            'Two tests in the file have the same name, so the runner mixes up their results',
            'The runner runs the tests in one file in parallel by default',
            'The assertion library caches failure messages between tests',
          ],
          answer: [0],
          explain: 'A test that calls `saveUser().then(u => expect(u.id).toBe(1))` without `await` or `return` finishes synchronously and is reported green. The promise settles later, during whichever test is running then, and its failure is blamed on that one. Most runners run the tests in a file one after another, which is why the error lands on "the next test". Always `await` (or `return`) the async work, and enable a lint rule such as `@typescript-eslint/no-floating-promises` or `vitest/valid-expect` to catch it.',
        },
      ],
    },
    {
      id: 'test-due-dates-time',
      title: 'Deterministic time: clocks, midnight and time zones',
      kind: 'mutation',
      xp: 90,
      minTests: 6,
      why: 'Date logic is where tests pass on the day they are written and fail at 23:59 or in another time zone; pinning the clock is how you make them honest.',
      tags: ['time', 'test doubles', 'time zones'],
      mutants: [
        { slug: 'reads-real-clock', label: 'Reads the real clock instead of the injected one' },
        { slug: 'utc-today', label: 'Works out "today" in UTC, ignoring the user\'s time zone' },
        { slug: 'counts-24h-periods', label: 'Counts 24-hour periods from now instead of calendar days' },
        { slug: 'due-today-is-overdue', label: 'Labels a task due today as "overdue by 0 days"' },
        { slug: 'day-of-month-diff', label: 'Subtracts day-of-month numbers, which breaks across a month end' },
      ],
      hints: [
        'Write the plain cases first (today, tomorrow, in N days, overdue by 1 and by N) from a clock set in the middle of the day.',
        'Counting 24-hour periods agrees with calendar days only at midnight. Set the clock to 23:59 and ask about tomorrow and the day after.',
        'For the time zone, pick an instant where UTC and the user disagree about the date: `2031-06-30T20:00:00Z` is already 1 July in `Asia/Tokyo`. Test a zone behind UTC too, such as `America/Los_Angeles`.',
        'Due on the 1st of next month, asked on the 28th, is "due in N days" with N counted across the month end. For the real-clock bug, use a clock years from today, such as 2001 or 2099.',
      ],
    },
    {
      id: 'test-cleanup-stack',
      title: 'Teardown that cannot leak: a cleanup stack',
      kind: 'js',
      xp: 85,
      why: 'Half-finished teardown leaks ports, files and rows into the next test; that is where order-dependent flakes come from.',
      tags: ['test isolation', 'teardown', 'async'],
      hints: [
        'Store each registration as its own object (`{ fn }`) in an array. `cancel` finds that object with `indexOf` and splices it out, so the same function deferred twice is two separate entries.',
        'In `run`, loop `while (steps.length)` and `pop()` one step at a time. Anything deferred during the run is pushed on top and popped next.',
        'Wrap each `await fn()` in its own `try`/`catch` and push failures into an `errors` array. After the loop, `throw new AggregateError(errors, `${errors.length} cleanup step(s) failed`)` if there were any.',
        'In `withCleanup`, catch the body\'s error, run the cleanups with `.catch(() => {})` so their failure cannot replace it, then rethrow it. On success, `await cleanup.run()` normally and return the body\'s value.',
      ],
    },
    {
      id: 'test-data-builders',
      title: 'Test data builders: one fact per test',
      kind: 'mutation',
      xp: 90,
      minTests: 7,
      why: 'Builders turn forty-line fixtures into one readable override, and stop tests passing for the wrong reason.',
      tags: ['test data', 'builders', 'readability'],
      mutants: [
        { slug: 'first-reason-only', label: 'Reports only the first reason, not all of them' },
        { slug: 'window-closes-early', label: 'Closes the refund window at exactly 30 days instead of after' },
        { slug: 'ignores-previous-refunds', label: 'Ignores what was already refunded when checking the amount' },
        { slug: 'final-sale-any-item', label: 'Refuses when any item in the order is final sale, not just the requested one' },
        { slug: 'zero-amount-allowed', label: 'Accepts a refund of 0 cents' },
        { slug: 'blocked-ignored', label: 'Lets a blocked customer refund' },
      ],
      hints: [
        'Start with the baseline: `checkRefund(anOrder(), aRequest())` must equal `{ ok: true, reasons: [] }`. Every other test changes one thing from there.',
        'Assert the whole result with `toEqual({ ok: false, reasons: [\'final-sale\'] })`. One test must break several rules at once and check that every reason comes back, in order.',
        'Boundaries: a request at exactly 30 days after `deliveredAt` is still `ok`, one millisecond later is `window-closed`. With `refundedCents: 4000` of 5000, 1000 is fine and 1001 exceeds.',
        'For final sale, build an order whose MUG is final sale and whose TEE is not, and check that refunding the TEE is `ok`. `amountCents: 0` must be `invalid-amount`.',
      ],
    },
    {
      id: 'test-snapshot-scrubber',
      title: 'Snapshots that only change when behaviour does',
      kind: 'js',
      xp: 90,
      why: 'A snapshot full of fresh UUIDs and timestamps gets re-approved on every PR, including the one that leaks a secret.',
      tags: ['snapshots', 'determinism', 'serialisation'],
      hints: [
        'Write one recursive `walk(v)` that handles `Date`, strings, arrays, plain objects and everything else, in that order. Keep the UUID numbering in a `Map` created inside `scrub`, so it restarts on every call.',
        'Timestamps: a regex anchored at both ends, `^…$`, with optional `(\\.\\d+)?` and `(Z|[+-]\\d{2}:\\d{2})`. UUIDs: a global, case-insensitive regex used with `replace`, so it also finds them inside longer strings.',
        'Key the numbering `Map` by `uuid.toLowerCase()`, and hand out `<uuid-${map.size + 1}>` on first sight.',
        'For objects, loop over `Object.keys(v).sort()` and build the output as you go. Check `redact` **before** walking into a value: `out[key] = secret.has(key) ? \'<redacted>\' : walk(v[key])`.',
      ],
    },
    {
      id: 'test-contract-matchers',
      title: 'Consumer-driven contracts: write the matcher',
      kind: 'js',
      xp: 100,
      why: 'Contract tests catch the breaking API change that both teams\' green suites miss; knowing how the matchers work lets you write contracts that are neither brittle nor toothless.',
      tags: ['contract testing', 'APIs', 'recursion'],
      hints: [
        'Write a recursive `check(expected, actual, path, byType, problems)`. Look at the matcher tag first: `like` just recurses into `example` with `byType = true`.',
        'Name types with a helper: `null` for null, `array` for arrays, otherwise `typeof`. Compare the types first; on a mismatch push `${path}: expected ${want}, got ${got}` and return without looking inside.',
        'Objects: for each key of the contract, `Object.hasOwn(actual, key)` or push `${path}.${key}: missing`. Ignore keys that only `actual` has. Array literals: check the length, then each index.',
        '`eachLike`: not an array is a type problem; shorter than `min` pushes the "at least" message; otherwise check every item against `example` with `byType = true` and path `${path}[${i}]`. For literals, compare with `===` only when `byType` is false.',
      ],
    },
    {
      id: 'test-provider-contract',
      title: 'Provider contract tests that allow additive change',
      kind: 'mutation',
      xp: 95,
      minTests: 6,
      why: 'A provider test that pins the whole body fails on every harmless addition; one that pins nothing lets a rename break every client. The job is to pin exactly what consumers read.',
      tags: ['contract testing', 'APIs', 'serialisation'],
      mutants: [
        { slug: 'renames-total', label: 'Renames `totalCents` to `total`' },
        { slug: 'money-as-decimal-string', label: 'Sends `totalCents` as a decimal string like "129.90"' },
        { slug: 'placed-at-epoch', label: 'Sends `placedAt` as epoch milliseconds' },
        { slug: 'placed-at-no-zone', label: 'Sends `placedAt` without milliseconds or the Z' },
        { slug: 'omits-null-discount', label: 'Leaves `discountCode` out instead of sending null' },
        { slug: 'status-uppercase', label: 'Sends `status` in upper case' },
        { slug: 'empty-lines-dropped', label: 'Leaves `lines` out when the order has none' },
        { slug: 'customer-flattened', label: 'Flattens `customer` into `customerId` and `customerName`' },
      ],
      hints: [
        'Replace the whole-body `toEqual` with `toMatchObject`: it checks the keys you list and allows extra ones. Keep using `wire()` so you test the JSON the consumer receives.',
        'Types matter as much as names: check `typeof totalCents === \'number\'` and `Number.isInteger`, and `placedAt` against `/^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d{3}Z$/`.',
        'Test the awkward orders: `discountCode: null` must come back as a present key with value `null` (`Object.hasOwn`), and `lines: []` must come back as `[]`.',
        'Check each status value comes back exactly as it went in, in lower case. For lines, `toMatchObject` on the array allows extra fields per line.',
      ],
    },
    {
      id: 'test-renewals-boss',
      title: 'Boss: rebuild the renewal job\'s test suite',
      kind: 'mutation',
      xp: 240,
      boss: true,
      minTests: 8,
      why: 'Billing code is where a flaky, over-mocked suite costs real money; this is the whole chapter applied to the job that charges customers.',
      tags: ['test strategy', 'test doubles', 'time', 'builders'],
      mutants: [
        { slug: 'reads-real-clock', label: 'Reads the real clock instead of the injected one' },
        { slug: 'due-strictly-after', label: 'Does not charge a subscription exactly at its renewsAt' },
        { slug: 'charges-duplicates', label: 'Charges a subscription twice when it appears twice in the input' },
        { slug: 'throw-aborts-run', label: 'A charge that throws aborts the whole run' },
        { slug: 'key-changes-per-run', label: 'Builds the idempotency key from the current time, so a retry gets a new key' },
        { slug: 'month-end-overflows', label: 'Rolls 31 January over into March instead of clamping to February' },
        { slug: 'annual-renews-monthly', label: 'Moves annual plans on by one month' },
        { slug: 'charges-paused', label: 'Charges paused subscriptions' },
      ],
      hints: [
        'Wrap the call in a helper that runs the job with a fresh `fakeGateway()` and returns `{ renewed, failed, requests }`, with `requests` sorted by `idempotencyKey`. Then every test is two or three lines.',
        'Check the full charge request with `toEqual`, including the exact key `renew-sub_1-2031-05-10T08:00:00.000Z`. Then run the same subscription again with a later clock and check the key did not change.',
        'Boundary: clock at exactly `renewsAt` charges; one millisecond before does not. Duplicates: `[aSub(), aSub()]` makes one request. Paused and cancelled: no requests at all.',
        'Failures: `gateway.decline(...)` one customer and `gateway.explode(...)` another, and check the third still renewed and `failed` has both, sorted by id, with reason `\'error\'` for the throw.',
        'Dates: an annual plan moves to the same day next year; `2032-01-31` monthly renews on `2032-02-29`. For the clock, use `renewsAt` in 2021 and a clock in 2020: due by the real date, not by yours.',
      ],
    },
  ],
});
