import { loadChapter } from '../../load.ts';

const here = import.meta.dirname;

export default loadChapter(here, {
  id: 'react-data-fetching',
  title: "Data Fetching Patterns",
  summary: "Keyed caches, dedupe, invalidation, infinite lists, retries, suspense-style resources.",
  lessons: [
    {
      id: 'react-swr-cache',
      title: 'Stale-while-revalidate with a keyed cache',
      kind: 'react',
      xp: 85,
      why: 'Flashing a spinner for data the user saw seconds ago is the most visible cost of naive fetching.',
      tags: ['caching', 'useEffect', 'race conditions'],
      hints: [
        'Derive the initial state from the cache: `cache.has(key) ? { status: \'success\', data: cache.get(key), isFetching: true, ... } : { status: \'loading\', ... }`.',
        'Reset when the key changes *during render*, not in an effect: keep `const [shownKey, setShownKey] = useState(key)` and, when they differ, call `setShownKey(key)` and `setState(stateFor(cache, key))`. React re-renders before committing.',
        'In the fetch effect, write to the cache unconditionally (`cache.set(key, data)`), but only call `setState` if the effect is still current (a `let current = true` flipped in the cleanup).',
        'On error, use an updater: `setState((s) => s.data !== undefined ? { ...s, error, isFetching: false } : { status: \'error\', data: undefined, error, isFetching: false })`.',
      ],
    },
    {
      id: 'react-dedupe-requests',
      title: 'Deduplicating in-flight requests',
      kind: 'react',
      xp: 75,
      why: 'Forty components asking for the same three users should make three requests, not forty.',
      tags: ['performance', 'promises', 'StrictMode'],
      hints: [
        'Keep a `Map` from key to promise. If the key is present, return that promise; otherwise call `fn()`, store the promise, and return it.',
        'Remove the entry when it settles with `promise.then(clear, clear)`, and only if the map still holds *this* promise. `finally` would create an unhandled rejected promise.',
        'Wrap the call: `try { promise = Promise.resolve(fn()); } catch (e) { promise = Promise.reject(e); }` so a synchronous throw cannot leave the key stuck or escape `fetch`.',
        'In the hook, reset to loading during render when the key changes, and guard `setState` with an `active` flag from the effect cleanup, as in the previous lesson.',
      ],
    },
    {
      id: 'react-mutation-invalidate',
      title: 'Mutations, invalidation and the stale refetch',
      kind: 'react',
      xp: 95,
      why: 'Double submits, stale refetches overwriting new data, and invalidations lost on unmount are the everyday bugs of CRUD screens.',
      tags: ['mutations', 'race conditions', 'forms'],
      hints: [
        'Number requests: `const id = ++latestRequest.current;` when starting, and apply the result only if `id === latestRequest.current` when it settles.',
        'Keep `mutationFn` and the options in a ref updated in a layout effect, and create `mutate` with `useCallback(..., [])` so it is stable and always uses the latest callbacks.',
        'Call `onSuccess`/`onError` unconditionally when the promise settles, but guard `setState` with a `mounted` ref and a "latest call" id.',
        'In `TodoApp`, the invalidation is `onSuccess: () => { setTitle(\'\'); todos.refetch(); }`, and the submit button is `disabled={add.status === \'pending\'}`.',
      ],
    },
    {
      id: 'react-paginated-query',
      title: 'Pagination without the flash',
      kind: 'react',
      xp: 95,
      why: 'Tables that blank out on every page change feel broken; placeholder data and prefetching make them feel instant.',
      tags: ['pagination', 'prefetching', 'caching'],
      hints: [
        'Keep loaded pages in a `Map` in a ref (for callbacks) and mirror it into state with `setPages(new Map(cacheRef.current))` so render reads state.',
        'Track the last page actually shown: `if (current !== undefined && shownPage !== page) setShownPage(page)` during render. The placeholder is `pages.get(shownPage)`.',
        'A `load(p)` helper returns the cached value, or the in-flight promise from a second `Map`, or starts a new request. Cache every success whether or not the page is current; delete the in-flight entry on both outcomes.',
        'In the page effect: `load(page).then((data) => { if (active && data.hasMore) load(page + 1).catch(() => {}); }, (error) => { if (active) setFailure({ page, error }); })`.',
      ],
    },
    {
      id: 'react-infinite-list',
      title: 'An infinite list that does not duplicate',
      kind: 'react',
      xp: 90,
      why: 'Load-more is on every feed and table, and double requests, duplicate rows and lost pages are its standard bugs.',
      tags: ['pagination', 'refs', 'async'],
      hints: [
        'State is one render late. Keep the guard flags in refs: `busy`, `failed`, `done`, plus the next `cursor` and a `Set` of seen ids.',
        '`loadMore` returns early when `busy.current || failed.current || done.current`; otherwise it sets `busy.current = true` *before* calling `fetchPage`, which is what makes a second call in the same tick a no-op.',
        'On success, filter the page with the seen-ids `Set`, advance `cursor.current = nextCursor`, and append with an updater. On failure, leave the cursor alone, so `retry` asks for the same page.',
        'Start the first page from `useEffect(() => { loadMore(); ... }, [])` with the ref guard; StrictMode\'s second mount then finds `busy` already set.',
      ],
    },
    {
      id: 'react-retry-backoff',
      title: 'Retries with backoff, and knowing when to stop',
      kind: 'react',
      xp: 90,
      why: 'Retrying the wrong errors, or all at once, turns a blip into an outage; retrying after the user left wastes their data.',
      tags: ['resilience', 'AbortController', 'async'],
      hints: [
        'Loop `for (let retry = 0; ; retry++)` with a `try { return await request({ signal }); } catch (error) { ... }`.',
        'In the catch: if `signal?.aborted`, throw `signal.reason`; if the error is not retryable or `retry >= retries`, throw it; otherwise compute the delay, call `onRetry`, and `await sleep(delay, signal)`.',
        'Retryable means `error.status === undefined || error.status >= 500 || error.status === 429`. The delay is `baseDelay * 2 ** retry`, or `retryAfter * 1000` for a 429 that has one.',
        '`defaultSleep` wraps `setTimeout` in a promise and adds a one-time `abort` listener that clears the timer and rejects with `signal.reason`.',
        'In the component, create an `AbortController` in the effect, pass its signal, abort it in the cleanup, and ignore results when `signal.aborted`.',
      ],
    },
    {
      id: 'react-suspense-resource',
      title: 'Suspense resources and transitions',
      kind: 'react',
      xp: 100,
      why: 'Suspense moves loading states out of components; it only works with a cache, and it only feels good with transitions.',
      tags: ['Suspense', 'useTransition', 'error boundaries'],
      hints: [
        'Each cache entry records `status`, `value`, `error` and a `promise`. Make the promise always resolve (`request.then(setSuccess, setError)`), and throw *that* from `read` while pending.',
        'The first `read` for a key creates the entry; later reads reuse it. That is what keeps `loader` to one call however many times React renders.',
        'The error boundary needs `static getDerivedStateFromError`, a `reset` that calls `resource.invalidate(userId)` before clearing the error, and a `componentDidUpdate` that clears the error when `userId` changes.',
        'In `ProfileSwitcher`, `const [isPending, startTransition] = useTransition();` and `onClick={() => startTransition(() => setUserId(id))}`. Do not put `key={userId}` on the boundary: a new Suspense boundary always shows its fallback.',
      ],
    },
    {
      id: 'react-fetching-strategy',
      title: 'Fetching strategy: waterfalls, staleness, ownership',
      kind: 'quiz',
      xp: 60,
      why: 'Most slow pages are slow because of when they fetch, not how fast React renders.',
      tags: ['performance', 'caching', 'architecture'],
      hints: [
        'A waterfall is any request that could have started earlier but waits for a render or another response.',
        'Stale time decides whether a request is made; cache time decides whether there is anything to show meanwhile.',
      ],
      quiz: [
        {
          q: 'A `ProjectPage` fetches the project in an effect, then renders `<Tasks projectId>`, which fetches its tasks in its own effect. Each request takes 300 ms. What is the problem, and a good fix?',
          options: [
            'None; effects run in parallel',
            'A waterfall: tasks start only after the project arrived and rendered (about 600 ms). Start both requests together at the page level, or prefetch the tasks in the route loader',
            'The tasks request should be debounced',
            'Move the tasks fetch into `useLayoutEffect` so it starts earlier',
          ],
          answer: [1],
          explain: '`<Tasks>` does not exist until the project has loaded and rendered, so its effect cannot start sooner. The tasks only need `projectId`, which is known up front, so both requests can start together. `useLayoutEffect` still runs after the component mounts, so it changes nothing.',
        },
        {
          q: 'A query has `staleTime: 60_000`. The user opens the page, leaves, and comes back 10 seconds later. What happens?',
          options: [
            'The cached data is shown and no request is made',
            'A loading spinner, then fresh data',
            'The cached data is shown and refetched in the background',
            'Nothing is shown until the minute is up',
          ],
          answer: [0],
          explain: 'Within the stale time the data counts as fresh: served from the cache with no request. After 60 s it becomes stale: still shown immediately, and revalidated in the background. A spinner only appears when there is nothing cached at all.',
        },
        {
          q: 'The team sets `staleTime: Infinity` "to reduce server load" on a list other users edit all day. What do users see?',
          options: [
            'Always fresh data, because the cache is updated by the server',
            'Faster pages with no downside',
            'Data frozen at whenever the query first loaded, including after other users\' changes, until a manual refetch, an invalidation, or a reload',
            'An error once the stale time is exceeded',
          ],
          answer: [2],
          explain: 'Infinite stale time means "never revalidate on its own". That suits data that truly never changes (a country list), or data you invalidate precisely after your own writes. For shared, frequently edited data it quietly shows other people\'s old versions.',
        },
        {
          q: 'After `POST /todos` succeeds, which are reasonable ways to update the list? Select all that apply.',
          options: [
            'Invalidate the `[\'todos\']` queries so active ones refetch',
            'Insert the returned todo into the cached list with `setQueryData`',
            'Reload the page',
            'Push the new todo into the cached array in place (`data.push(todo)`)',
          ],
          answer: [0, 1],
          explain: 'Invalidation is the simplest correct choice; writing the response into the cache saves a round trip (often combined with an invalidation, to pick up server-side changes). Mutating the cached array in place changes nothing React can see: same reference, no re-render, and every other reader now holds a silently changed object.',
        },
        {
          q: 'Two components on one page call `useQuery([\'user\', 42], fetchUser)` at the same time. With a query cache, how many requests are made?',
          options: [
            'Two, one per component',
            'One: they share the cache entry, and the second joins the request already in flight',
            'Zero until one of them calls `refetch`',
            'One per render of either component',
          ],
          answer: [1],
          explain: 'The key identifies the query; every subscriber to the same key shares one entry and one in-flight request. That is why keys must contain every input the request depends on: `[\'user\']` for two different ids would make them share, and show, the wrong data.',
        },
        {
          q: 'Why is copying a fetched object into `useState` (or a global store) "so we can edit it" usually a mistake?',
          options: [
            'It uses twice the memory',
            'React cannot render data that came from the network',
            'Store updates are slower than cache updates',
            'The copy is a second source of truth: refetches and other tabs update the cache but not the copy, so the screen and the server drift apart. Keep server data in the cache and only the unsaved edits in local state',
          ],
          answer: [3],
          explain: 'Server data belongs to the server; the client holds a cache of it. For an edit form, initialise a draft from the cached data (or key the form by the record\'s id and version) and keep only the draft in local state, then write it back with a mutation.',
        },
      ],
    },
    {
      id: 'react-query-client',
      title: 'BOSS: build a query client',
      kind: 'react',
      xp: 260,
      boss: true,
      why: 'Knowing how TanStack Query and SWR work inside is what lets you debug them, configure them, and know when you do not need them.',
      tags: ['caching', 'useSyncExternalStore', 'invalidation', 'architecture'],
      hints: [
        'One entry per `JSON.stringify(key)`, holding `state` (`{ status, data, error, isFetching }`), `updatedAt`, `invalidated`, `requestId`, `inFlight`, the latest `fetcher`, and a `Map` of subscriber callbacks to their `staleTime`.',
        'Every state change replaces `entry.state` with a new object and calls every subscriber. Then `useSyncExternalStore(subscribe, () => entry.state)` gives each component the shared state, with no copies.',
        '`fetchEntry(entry)` increments `requestId`, remembers it, calls the fetcher, and applies the outcome only if the id is still the latest. `setQueryData` also increments `requestId`, which is how an older response in flight gets ignored.',
        'Stale means `updatedAt === null || invalidated || now() - updatedAt >= staleTime`. The mount effect calls `ensureFresh` (fetch if stale and not in flight); `invalidateQueries` and `refetch` call `fetchEntry` directly.',
        'Look the entry up by key on every render (not in state), and store `entry.fetcher = fetcher` in a layout effect. The provider adds the window `focus` listener in an effect and removes it in the cleanup.',
      ],
    },
  ],
});
