import { loadChapter } from '../../load.ts';

const here = import.meta.dirname;

export default loadChapter(here, {
  id: 'ts-generics-advanced',
  title: "Generics, Advanced",
  summary: "Inference sites, const type parameters, variance, overloads versus generics, builder types.",
  lessons: [
    {
      id: 'ts-const-type-params',
      title: 'Const type parameters',
      kind: 'typecheck',
      xp: 80,
      why: 'Helpers that turn a list of values into a union are useless if every caller must remember `as const`; a `const` type parameter makes the literals part of the signature.',
      tags: ['generics', 'const type parameters', 'literal types'],
      hints: [
        'Add the `const` modifier to the type parameter itself: `function enumOf<const T extends … >(values: T)`.',
        'Constrain with `readonly string[]`, not `string[]`: a `const` type parameter infers a readonly tuple, and a mutable constraint would reject both that and an `as const` array from elsewhere.',
        'The union of the values is `T[number]`. Use it as the predicate target (`value is T[number]`) and as `parse`\'s return type.',
        '`PermissionOf<R>` maps each resource key to its template literal, then indexes the mapped type to get the union: `{ [K in keyof R & string]: … }[keyof R & string]`, where `…` is a template literal type joining `K`, a colon and `R[K][number]`.',
        'In `definePermissions<const R extends Record<string, readonly string[]>>`, build `all` as `PermissionOf<R>[]`. The strings you build in the loop are `string` to the checker, so push each one with `as PermissionOf<R>` — it is true by construction.',
      ],
    },
    {
      id: 'ts-noinfer',
      title: 'Which argument decides the type?',
      kind: 'typecheck',
      xp: 85,
      why: 'A type parameter inferred from every argument turns a typo or a wrong fallback into a wider type instead of an error; choosing the source of truth is API design.',
      tags: ['generics', 'inference', 'NoInfer'],
      hints: [
        'In each function, find the parameter that should be allowed to *decide* the type parameter, and the one that should only be *checked* against it.',
        '`NoInfer<T>` wraps a position so TypeScript ignores it during inference: `fallback: NoInfer<T>`.',
        'For `createMachine`, it is `initial: NoInfer<S>`; for `retry`, `onGiveUp: (lastError: unknown) => NoInfer<T>`.',
        'The pre-5.4 alternative also passes: a second type parameter bounded by the first, e.g. `withDefault<T, F extends T>(value: T | undefined, fallback: F): T`.',
      ],
    },
    {
      id: 'ts-curried-generics',
      title: 'Explicit and inferred type arguments',
      kind: 'typecheck',
      xp: 90,
      why: 'Type arguments are all or nothing, so an API that needs one explicit type and infers the rest has to be split into two calls — the shape behind every typed query builder.',
      tags: ['generics', 'inference', 'api design', 'currying'],
      hints: [
        'The first call takes only the type argument that cannot be inferred and returns a function with its *own* type parameter for the rest.',
        '`selectFrom<Row>(table)` returns `async <K extends keyof Row & string>(exec: Exec, ...columns: K[]): Promise<Pick<Row, K>[]> => …`. The rows from `exec` need one `as Pick<Row, K>[]`.',
        'For `handlersFor<Events>()`, return `<K extends keyof Events>(handlers: { [P in K]: (payload: Events[P]) => void }) => …`. `K` is inferred from the object\'s keys, and each handler is contextually typed from `Events[P]`.',
        '`Object.keys` returns `string[]`, so `handles` needs `as K[]`. Give `dispatch` its own parameter bounded by the handled keys: `dispatch<E extends K>(event: E, payload: Events[E])`.',
      ],
    },
    {
      id: 'ts-overloads',
      title: 'Overloads versus generics',
      kind: 'typecheck',
      xp: 80,
      why: 'Return types that follow the arguments save every caller a null check or a cast; picking overloads for a table and generics for a relationship keeps the signatures honest.',
      tags: ['overloads', 'generics', 'api design'],
      hints: [
        '`toDate` is a small table of cases, so it wants overloads; `getSetting` is a lookup, so it wants a generic `K extends keyof Settings` returning `Settings[K]`.',
        'Overload signatures go above the implementation, and callers only ever see those. A caller with `string | null` matches neither `(input: string)` nor `(input: null)` — add a third overload that takes the union.',
        '`findById` needs a generic `T extends { id: string }` on every overload, and `items: readonly T[]` so readonly arrays are accepted.',
        'Two overloads for `findById`: first `(items, id, options: { required: true }): T`, then `(items, id, options?: { required: boolean }): T | undefined`. The implementation signature returns `T | undefined`.',
      ],
    },
    {
      id: 'ts-wrap-functions',
      title: 'Typing higher-order functions',
      kind: 'typecheck',
      xp: 90,
      why: 'Logging, retry, memoise and `once` wrappers sit on every call path; typed as `(...args: any[]) => any` they silently erase the types of everything they wrap.',
      tags: ['generics', 'variadic tuples', 'higher-order functions', 'NoInfer'],
      hints: [
        'Capture the parameters as a tuple and the result separately: `<A extends unknown[], R>(fn: (...args: A) => R): (...args: A) => R`.',
        'Avoid `F extends (...args: any[]) => any` with `Parameters<F>` and `ReturnType<F>`: it works for plain functions but resolves a generic function\'s own `T` to `unknown`, so `once(<T>(x: T) => x)(42)` is not a `number`.',
        '`partial` needs three type parameters: `<F, A extends unknown[], R>(fn: (first: F, ...rest: A) => R, first: F): (...rest: A) => R`.',
        'In `memoizeAsync`, `fn` is `(...args: A) => Promise<R>`. The key function also mentions `A`, and a key that ignores trailing optional parameters votes for a shorter tuple. Stop it voting: `key: NoInfer<(...args: A) => string>`.',
      ],
    },
    {
      id: 'ts-typed-keys',
      title: 'Typed keys and variance',
      kind: 'typecheck',
      xp: 95,
      why: 'Request context, DI containers and plugin registries hold values of different types by key; a phantom-typed key removes the cast at every read without letting a wrong write through.',
      tags: ['generics', 'variance', 'phantom types'],
      hints: [
        'Structural typing means an unused type parameter changes nothing: `Key<string>` and `Key<number>` must differ in some member that mentions `T`.',
        'A member that exists only in the type: `declare const phantom: unique symbol;` then `readonly [phantom]?: …` in the interface. `key()` can still return just `{ name }`.',
        'If that member is plain `T`, keys are covariant: a `Key<Status>` becomes assignable to `Key<string>`. Make it mention `T` as input and output: `readonly [phantom]?: (value: T) => T`.',
        'Make every `Context` method generic in the key: `get<T>(key: Key<T>): T | undefined`, `set<T>(key: Key<T>, value: T): this`, and `has<T>(key: Key<T>)`. Store values in a `Map<object, unknown>` and read them back `as T`.',
      ],
    },
    {
      id: 'ts-keys-matching',
      title: 'Keys by value type',
      kind: 'typecheck',
      xp: 85,
      why: '`key: keyof T` lets callers sort by an object or sum a string; constraining keys by their value type moves those bugs from production to the editor.',
      tags: ['generics', 'mapped types', 'constraints'],
      hints: [
        'Build a mapped type over `keyof T` whose value is the key itself when `T[K]` fits `V`, and `never` otherwise. Then index that mapped type with `[keyof T]` to get the union of survivors.',
        'Check the optional-key cases in the spec. Without a modifier, an optional key\'s entry in the mapped type is optional too, and indexing adds `undefined` to the result. Write `[K in keyof T]-?: …`.',
        'Use it in the signatures: `sortBy<T>(items: readonly T[], key: KeysMatching<T, Sortable>, direction: \'asc\' | \'desc\' = \'asc\'): T[]` and `sumBy<T>(items: readonly T[], key: KeysMatching<T, number>): number`.',
        '`indexBy` needs the key as its own type parameter so the Map can use `T[K]`: `indexBy<T, K extends KeysMatching<T, PropertyKey>>(items: readonly T[], key: K): Map<T[K], T>`. In the bodies, read values with `item[key] as number` (or `as Sortable`).',
      ],
    },
    {
      id: 'ts-variance-quiz',
      title: 'Inference and variance',
      kind: 'quiz',
      xp: 70,
      why: 'Unsound array covariance, method bivariance and return-only generics are how "fully typed" code still ships the wrong object to production.',
      tags: ['variance', 'inference', 'generics'],
      quiz: [
        {
          q: '`Dog extends Animal`. Which of these assignments compile under `--strict`?\n\n```ts\ninterface RepoA<T> { save(item: T): void }\ninterface RepoB<T> { save: (item: T) => void }\ndeclare const a: RepoA<Dog>;\ndeclare const b: RepoB<Dog>;\nconst x: RepoA<Animal> = a;  // (1)\nconst y: RepoB<Animal> = b;  // (2)\n```',
          options: [
            'Both: a repository of dogs is a repository of animals',
            'Neither: `strictFunctionTypes` rejects both',
            'Only (1)',
            'Only (2)',
          ],
          answer: [2],
          explain: '`strictFunctionTypes` checks function-typed *properties* contravariantly, so (2) fails: a `RepoB<Animal>` may be handed a `Cat`, and the dog repository cannot store one. Parameters declared with *method* syntax are deliberately exempt and checked bivariantly (so that built-ins like `Array<T>` stay usable), which lets (1) through — the unsound direction. If a type\'s callbacks are meant to be checked strictly, declare them as properties: `save: (item: T) => void`.',
        },
        {
          q: 'What happens here?\n\n```ts\nconst dogs: Dog[] = [rex];\nconst animals: Animal[] = dogs;\nanimals.push(tom); // tom: Cat\ndogs[1].bark();\n```',
          options: [
            'Line 2 is a compile error: mutable arrays are invariant',
            'Line 3 is a compile error: `animals` still refers to a `Dog[]`',
            'It compiles, and `dogs[1].bark()` throws at runtime',
            'It compiles, and `dogs[1]` is `undefined` because `push` copied the array',
          ],
          answer: [2],
          explain: 'TypeScript treats arrays as covariant even though they are mutable: `Dog[]` is assignable to `Animal[]`, and through the wider alias you can push a `Cat` into the dogs array. Nothing catches it until `bark` is not a function. The defence is at API boundaries: a function that only reads should take `readonly Animal[]` (a readonly array has no `push`, so covariance is sound), and a function that writes should take the exact element type.',
        },
        {
          q: 'Given `function same<T>(a: T, b: T): T`, what does `same(count, label)` do, where `count: number` and `label: string`?',
          options: [
            'Compiles, with `T` inferred as `string | number`',
            'Error: the `string` argument is not assignable to `number`',
            'Compiles, with `T` inferred as `unknown`',
            'Error: `T` cannot be inferred and must be written explicitly',
          ],
          answer: [1],
          explain: 'Inference collects the candidates `number` and `string` and picks one of them (here the first); it does not synthesise a union to make the call succeed, so the second argument fails against `number`. That is usually what you want — the signature says "two of the same thing". If a union is really intended, the caller says so: `same<string | number>(count, label)`. The flip side is the `NoInfer` lesson: when one argument should decide `T` alone, stop the other from being a candidate.',
        },
        {
          q: 'What is the type of `byId`, and why?\n\n```ts\nconst byId = items.reduce((acc, item) => ({ ...acc, [item.id]: item }), {});\n```',
          options: [
            '`Record<string, Item>`, inferred from the callback\'s return',
            '`{ [x: string]: Item }`, from the computed key',
            '`any`, because the seed carries no type',
            '`{}`, so `byId[someId]` is a compile error',
          ],
          answer: [3],
          explain: 'The accumulator type comes from the seed, and `{}` is the empty object type. The callback\'s return (`{ [x: string]: Item }`) is assignable to `{}`, so everything compiles until you try to read from the result. Give inference something to work with: `items.reduce<Record<string, Item>>(…, {})`, or annotate the seed `{} as Record<string, Item>` — or better, use a `Map` or a `for…of` loop with a typed `const out: Record<string, Item> = {}`.',
        },
        {
          q: 'A helper is declared `function parseJson<T>(text: string): T` and called as `const user = parseJson<User>(body)`. What is the problem?',
          options: [
            'Nothing: `T` is explicit, so the call is fully checked',
            '`T` appears only in the return type, so this is an unchecked cast with a friendlier spelling',
            'It is a compile error: `T` cannot be inferred from the arguments',
            '`T` is erased at runtime, so `user` is `any` inside the function',
          ],
          answer: [1],
          explain: 'A type parameter that appears only in the return position cannot be checked against anything; the caller chooses it, so `parseJson<User>` means exactly `JSON.parse(body) as User`, with the cast hidden in a signature that looks safe. Return `unknown` instead and make callers validate (`parseJson(body, userSchema)` where the schema\'s type drives `T`). The rule of thumb: every type parameter should appear at least twice, or in an argument.',
        },
        {
          q: 'What does the `in out` annotation do here?\n\n```ts\ninterface Key<in out T> { readonly name: string }\n```',
          options: [
            'It changes the emitted JavaScript so the key carries its type at runtime',
            'Nothing: `T` is unused, so `Key<string>` and `Key<number>` are still interchangeable',
            'It makes `Key` invariant in `T` when two `Key`s are compared, and the checker reports an error if the members contradict the declared variance',
            'It makes `T` optional at every use site',
          ],
          answer: [2],
          explain: 'Variance annotations (TS 4.7) declare how a type parameter behaves, and when the checker compares `Key<A>` with `Key<B>` it uses the annotation instead of measuring the structure — here, invariantly, so a `Key<Dog>` is not a `Key<Animal>`. They are also checked: `interface Box<out T> { set: (v: T) => void }` is an error. Types are still erased at runtime. Most code never needs them; they document intent on phantom and performance-sensitive types.',
        },
      ],
    },
    {
      id: 'ts-typed-container',
      title: 'BOSS: a typed dependency container',
      kind: 'typecheck',
      xp: 230,
      boss: true,
      why: 'Builders that accumulate state in a type parameter are how query builders, routers and DI containers stay typed end to end without a cast at every call site.',
      tags: ['generics', 'builders', 'dependency injection', 'api design'],
      hints: [
        'Give the class a type parameter for the map so far: `class Container<D>`, with `container(): Container<{}>`. `build(): D`, and `Deps<C> = C extends Container<infer D> ? D : never`.',
        '`provide<K extends string, V>(name: K, factory: (deps: D) => V): Container<D & { [P in K]: V }>` gets the basics working. Then flatten the result with `type Simplify<T> = { [K in keyof T]: T[K] } & {}`.',
        'Reject bad names by making the parameter type depend on `K`: `name: K extends keyof D ? never : K`. TypeScript still infers `K` from the argument, then the argument fails against `never`.',
        'A plain `string` name also needs rejecting: `string extends K ? never : …` is true only when `K` is the whole of `string`. Put both checks in one helper type and use it in `provide` and `value`.',
        '`override<K extends keyof D & string>(name: K, make: () => D[K]): Container<D>`. For storage, keep an array of `{ name: string; make: (deps: Record<string, unknown>) => unknown }`, cast each factory once when storing (`factory as unknown as …`), and return `resolved as D` from `build`.',
      ],
    },
  ],
});
