import { loadChapter } from '../../load.ts';

const here = import.meta.dirname;

export default loadChapter(here, {
  id: 'sql-concurrency',
  title: "Concurrency & Locking",
  summary: "Optimistic locking with versions, FOR UPDATE, SKIP LOCKED semantics, advisory locks, idempotent writes.",
  lessons: [
    {
      id: 'node-db-optimistic-locking',
      title: 'Optimistic locking with a version column',
      kind: 'node-db',
      xp: 90,
      why: 'Every edit form and every background job that rewrites a row loses someone\'s change without it, silently.',
      tags: ['optimistic locking', 'lost update', 'concurrency', 'retry'],
      hints: [
        'The version check belongs in the `UPDATE` itself: `where id = $3 and version = $4`, with `version = version + 1` in the `SET` and `returning id, title, body, version`.',
        'A read before the update cannot protect you: the other editor\'s save lands between your read and your write. Zero rows back from the conditional `UPDATE` is the only reliable signal.',
        'When the `UPDATE` returns no row, read the row once more only to explain it: missing → `DocumentNotFoundError`, present → `VersionConflictError(id, expectedVersion, row.version)`.',
        'The retry loop: `for (let attempt = 1; attempt <= maxAttempts; attempt++) { const doc = await getDocument(…); if (!doc) throw …; const change = await mutate(doc); try { return await saveDocument(conn, { id, expectedVersion: doc.version, ...change }); } catch (err) { if (!(err instanceof VersionConflictError)) throw err; last = err; } }` then `throw last`.',
      ],
    },
    {
      id: 'node-db-lock-parent-row',
      title: 'Lock the parent to protect a rule across rows',
      kind: 'node-db',
      xp: 95,
      why: 'Capacity, quotas and spending limits are sums over many rows; without a lock, two requests read the same sum and both squeeze in.',
      tags: ['select for update', 'row locks', 'invariants', 'transactions'],
      hints: [
        'The race is between your read of `bookings` and your insert. Something has to make the second request wait before it reads, and the one row both requests share is the event.',
        'Inside the transaction, first: `select capacity from events where id = $1 for update`. A second booking for the same event blocks on that statement until you commit.',
        'Only after the lock: `select coalesce(sum(seats), 0)::int as booked from bookings where event_id = $1`. Without `coalesce`, an event with no bookings sums to `null`.',
        'Keep the lock and the sum in separate statements. A subquery in the locking `SELECT` reads the snapshot taken before the statement waited for the lock.',
        'The shape: validate; `begin`; lock (no row → `EventNotFoundError`); sum; `if (seats > free) throw new SoldOutError(eventId, free)`; insert `returning id`; `commit`; and a `catch` that rolls back and rethrows.',
      ],
    },
    {
      id: 'node-db-lock-ordering',
      title: 'Deadlocks: lock in one global order',
      kind: 'node-db',
      xp: 95,
      why: '`deadlock detected` under load is almost always two code paths locking the same rows in different orders; the fix is an ordering rule, not a retry.',
      tags: ['deadlocks', 'row locks', 'lock ordering', 'transactions'],
      hints: [
        'The caller\'s line order is arbitrary. Sort a copy of the lines by `walletId` once, after validation, and let every lock follow that order.',
        'Validation is plain JavaScript: a `Set` catches a repeated wallet, `Number.isSafeInteger` catches `1.5` and `\'1\'`, and a running sum must end at exactly 0.',
        'One statement can lock every wallet in order: `select id, balance_cents from wallets where id = any($1::int[]) order by id for update`, with the ids array as `$1`. Fewer rows back than ids means a wallet is missing.',
        'Check every new balance in JavaScript before writing anything, then apply the amounts. Once the rows are locked, updating them in any order adds no new lock.',
        'Alternative: loop over the sorted lines with `update wallets set balance_cents = balance_cents + $1 where id = $2 and balance_cents + $1 >= 0 returning balance_cents`, and tell a missing wallet from a poor one when no row comes back.',
      ],
    },
    {
      id: 'node-db-serialization-retry',
      title: 'SERIALIZABLE means you must retry',
      kind: 'node-db',
      xp: 100,
      why: 'Write skew slips past every row lock; SERIALIZABLE catches it, but only code that retries 40001 turns that into correctness instead of 500s.',
      tags: ['serializable', 'write skew', 'retry', 'transactions'],
      hints: [
        'The whole attempt is the unit of retry: `begin isolation level serializable`, `work(conn)`, `commit` — all inside one `try`. Re-running only the failed statement reuses decisions made on stale reads.',
        'Put the `commit` inside the `try` too. Postgres often reports the serialization failure when you commit, not on the statement that caused it.',
        'In the `catch`: `await conn.query(\'rollback\').catch(() => {})`, then `if (![\'40001\', \'40P01\'].includes(err?.code) || attempt >= maxAttempts) throw err;`, then `await sleep(baseDelayMs * 2 ** (attempt - 1))` and loop.',
        '`goOffCall` is one call: `withSerializableRetry(conn, async (tx) => { … })`. Inside, read the doctor ids on call for the shift; not in the list → return its length; only one → throw `LastDoctorError`; else delete the row and return length - 1.',
      ],
    },
    {
      id: 'sql-gapless-counter',
      title: 'Gapless per-tenant numbers with a counter row',
      kind: 'sql',
      xp: 85,
      why: 'Sequences leave gaps by design; invoice and receipt numbers often must not, and the fix is a locked counter row whose cost you should understand.',
      tags: ['sequences', 'row locks', 'upsert', 'transactions'],
      hints: [
        'A sequence cannot give a number back on rollback. A row in a table can: an `UPDATE` inside your transaction is undone with it.',
        'Seed the counters with `insert into invoice_counters (tenant_id, last_number) select tenant_id, max(number) from invoices group by tenant_id`. `count(*)` is wrong for Globex, whose numbers start at 11.',
        'One statement creates or increments: `insert into invoice_counters as c (tenant_id, last_number) values (p_tenant, 1) on conflict (tenant_id) do update set last_number = c.last_number + 1 returning last_number`.',
        'Wrap it in `create function next_invoice_number(p_tenant text) returns integer language sql as $$ … $$;`, and write `create_invoice` as an `insert into invoices … values (p_tenant, next_invoice_number(p_tenant), p_amount_cents) returning *` with `returns invoices`.',
      ],
    },
    {
      id: 'sql-locking-judgement',
      title: 'Choosing locks, waits and isolation levels',
      kind: 'quiz',
      xp: 70,
      why: 'Most lock outages are a migration queued behind a report or a lock stronger than it needed to be, and both are decisions made in code review.',
      tags: ['locks', 'isolation', 'migrations', 'advisory locks'],
      quiz: [
        {
          q: 'A deploy runs `ALTER TABLE orders ADD COLUMN note text` (no default; instant in modern Postgres). A 10-minute analytics query is reading `orders`. Within seconds, every checkout request times out. Why?',
          options: [
            'Adding a column rewrites the whole table, and the rewrite saturates the disk',
            'The ALTER waits for an ACCESS EXCLUSIVE lock behind the report, and every new query on `orders` queues behind the waiting ALTER',
            'The report holds row locks on every order it has read so far',
            'Autovacuum cannot run during an ALTER, so the table bloats until queries slow down',
          ],
          answer: [1],
          explain: 'Lock requests are granted in order. The ALTER cannot get ACCESS EXCLUSIVE while the report holds ACCESS SHARE, so it waits — and every later SELECT, which only needs ACCESS SHARE too, queues behind the ALTER. The table is effectively down for as long as the report runs. The fix is to run DDL with `SET lock_timeout = \'2s\'` and retry the migration: failing fast is harmless, queueing is an outage. Readers never take row locks, and a nullable column without a default does not rewrite the table.',
        },
        {
          q: 'A worker locks an order with `SELECT … FROM orders WHERE id = $1 FOR UPDATE` before changing its `status`. Meanwhile, inserts into `order_events` (which has a foreign key to `orders`) for that order stall until the worker commits. What is the smallest correct fix?',
          options: [
            'Drop the foreign key on `order_events.order_id`',
            'Lock with `FOR SHARE` instead',
            'Lock with `FOR NO KEY UPDATE` instead',
            'Take no lock at all: the UPDATE is atomic on its own',
          ],
          answer: [2],
          explain: 'The foreign key check takes `FOR KEY SHARE` on the parent row, which conflicts only with `FOR UPDATE` — the lock that says "I might delete this row or change its key". `FOR NO KEY UPDATE` still excludes other writers of the row, which is what the worker needs, but lets child inserts through. It is also exactly the lock a plain UPDATE of a non-key column takes. `FOR SHARE` would let two workers both lock and then deadlock upgrading; dropping the lock reintroduces the read-then-write race.',
        },
        {
          q: 'Two transactions at READ COMMITTED run `UPDATE stock SET qty = qty - 1 WHERE sku = \'KB-1\' AND qty >= 1` at the same moment. `qty` is 1. What happens?',
          options: [
            'Both succeed and `qty` ends at -1: each read 1 from its snapshot',
            'One succeeds; the other waits for it, re-checks the WHERE against the committed row, finds `qty = 0`, and updates 0 rows',
            'One succeeds; the other fails with a serialization error (40001)',
            'Both block until one is chosen as a deadlock victim',
          ],
          answer: [1],
          explain: 'At READ COMMITTED, an UPDATE that finds its target row locked waits, and when the other transaction commits it re-evaluates its WHERE clause against the new row version. That is why a conditional single-statement write is safe without extra locks, while the same check done in application code between a SELECT and an UPDATE is not. A 40001 would be REPEATABLE READ or SERIALIZABLE behaviour.',
        },
        {
          q: 'You move a nightly reconciliation job to REPEATABLE READ so that all of its reads see one consistent snapshot. It also updates rows. What must the code now handle that it did not before?',
          options: [
            'Nothing: REPEATABLE READ only changes what reads see',
            'Phantom rows appearing in its second read of a table',
            'Deadlocks, which REPEATABLE READ makes more likely',
            'A 40001 `could not serialize access due to concurrent update` when it updates a row another transaction changed after its snapshot, which means retrying the whole transaction',
          ],
          answer: [3],
          explain: 'At REPEATABLE READ Postgres will not let you overwrite a change you could not see; instead of re-checking like READ COMMITTED, it aborts with 40001 and the only correct response is to rerun the transaction from BEGIN. Postgres\'s REPEATABLE READ does not show phantoms (it is snapshot isolation), and deadlock likelihood depends on lock order, not on the isolation level.',
        },
        {
          q: 'Which of these are good uses of `SKIP LOCKED`? Select all that apply.',
          options: [
            'Workers claiming the next jobs from a queue table, where any unclaimed job will do',
            'Checking whether seat 14C is free before selling it',
            'Handing out one of a pool of pre-generated voucher codes, where any unused code will do',
            'Computing the total of all open invoices for a report',
          ],
          answer: [0, 2],
          explain: '`SKIP LOCKED` answers "give me some rows nobody else is working on", which is right when the rows are interchangeable. It silently pretends locked rows do not exist, so it gives wrong answers to questions about specific rows ("is 14C free?" — it may be locked by a buyer who is about to roll back) and to aggregates, which would just leave locked rows out of the total.',
        },
        {
          q: 'A cron job runs on three app servers. To run it on only one, the code does `SELECT pg_try_advisory_lock(42)` on a connection from the app\'s pool, runs the job through the pool, then calls `pg_advisory_unlock(42)`. Occasionally the job stops running anywhere for days. What is the likeliest cause?',
          options: [
            'Advisory lock ids collide with row lock ids, so 42 is sometimes taken by a row',
            'The lock and the unlock went out on different pooled connections, so the unlock failed and the lock stayed held by an idle pooled connection',
            'Advisory locks expire after `idle_in_transaction_session_timeout`',
            'Two servers can both get a session-level advisory lock if they call it in the same millisecond',
          ],
          answer: [1],
          explain: 'A session-level advisory lock belongs to the connection, not to your code. Through a pool, the unlock may run on another connection (it returns false and a warning), and the original connection goes back to the pool still holding the lock — for as long as it lives. Take the lock and do the work on one checked-out client, or use `pg_try_advisory_xact_lock` inside a transaction so commit or rollback always releases it. Advisory locks have their own namespace and are exclusive; they do not expire.',
        },
      ],
    },
    {
      id: 'node-db-skip-locked-queue',
      title: 'A job queue with SKIP LOCKED, leases and fencing',
      kind: 'node-db',
      xp: 100,
      why: 'A Postgres table is the queue most teams already have; claimed twice, stuck forever or completed by a zombie worker are its three classic bugs.',
      tags: ['skip locked', 'job queue', 'leases', 'row locks'],
      hints: [
        'Claim in one statement so there is no gap between reading and writing: a CTE selects the ids with `for update skip locked`, and the `UPDATE … from next where j.id = next.id` claims exactly those.',
        'The `WHERE` of the CTE: `queue = $1 and ((status = \'queued\' and run_at <= $2) or (status = \'running\' and locked_until <= $2))`, then `order by run_at, id limit $3 for update skip locked`.',
        'Compute the lease in JavaScript: `new Date(now.getTime() + leaseMs)`, passed as a parameter. `returning j.id, j.payload, j.attempts, j.run_at`, then sort by `run_at` and `id` and map to `{ id, payload, attempts }`.',
        'Ownership lives in the `WHERE`: `update jobs set status = \'done\', locked_until = null where id = $1 and status = \'running\' and attempts = $2 returning id`; one row back means it was yours.',
        '`failJob`: decide in JavaScript — `attempts >= maxAttempts` → `\'dead\'`, else `\'queued\'` with `run_at = new Date(now.getTime() + backoffMs * 2 ** (attempts - 1))` — then one guarded `UPDATE` that also sets `last_error` and clears `locked_until`.',
      ],
    },
    {
      id: 'node-db-advisory-lock',
      title: 'Run a job on one server with an advisory lock',
      kind: 'node-db',
      xp: 90,
      why: 'The moment an app runs on two servers, every in-process scheduler runs every job twice; an advisory lock is the cheapest fix, and the easiest to leak.',
      tags: ['advisory locks', 'scheduled jobs', 'transactions', 'idempotency'],
      hints: [
        'There is no row to lock, so lock a number: `pg_try_advisory_xact_lock(hashtext($1))` with the name as `$1`. It answers true or false at once instead of waiting.',
        'The `_xact_` lock only exists inside a transaction, and is released by its `COMMIT` or `ROLLBACK`. So: `begin`, then the try-lock, then `work(conn)`, then `commit`, with a `catch` that rolls back and rethrows.',
        'Alias the result (`… as locked`) and read `rows[0].locked`. When it is `false`, roll back and return `{ ran: false }` without calling `work`.',
        'The lock prevents overlap, not repeats. Inside `work`: `select 1 from invoice_runs where day = $1` first; then `insert into invoices (subscription_id, day, amount_cents) select id, $1, price_cents from subscriptions where active returning id`, and the `invoice_runs` row with `rows.length`.',
      ],
    },
    {
      id: 'node-db-seat-hold-boss',
      title: 'Boss: seat holds that survive a ticket rush',
      kind: 'node-db',
      xp: 230,
      boss: true,
      why: 'Holds, carts and reservations are the everyday concurrency problem: all-or-nothing writes, expiring leases and idempotent checkout, under a thundering herd.',
      tags: ['row locks', 'leases', 'idempotency', 'transactions'],
      hints: [
        'Validate everything first, sort a copy of the ids, and wrap the rest in a small helper: `begin`, `await work()`, `commit`, and a `catch` that rolls back and rethrows.',
        'Hold, step 1: `select id from seats where id = any($1::int[]) and event_id = $2 order by id for update`. Ids missing from the result are the `SeatNotFoundError` list.',
        'Hold, step 2, the availability rule in the write: `update seats set held_by = $3, held_until = $4 where id = any($1::int[]) and event_id = $2 and order_id is null and (held_by is null or held_until <= $5 or held_by = $3) returning id`. Fewer rows than ids → the ones missing are unavailable.',
        'Confirm: look up `orders` by `hold_token` first and return it if found. Then `select id, event_id, held_until from seats where held_by = $1 and order_id is null order by id for update`; none, or any with `held_until <= now` → `HoldExpiredError`.',
        'Then insert the order `returning id`, and `update seats set order_id = $1, held_by = null, held_until = null where held_by = $2 and order_id is null`. `releaseHold` is one `UPDATE … returning id`; `availableSeats` is one `SELECT` with the same "free" rule as the hold.',
      ],
    },
  ],
});
