import { loadChapter } from '../../load.ts';

const here = import.meta.dirname;

export default loadChapter(here, {
  id: 'react-performance',
  title: "React Performance",
  summary: "Virtualised lists, memo pitfalls, transitions, reconciliation, measuring renders.",
  lessons: [
    {
      id: 'react-why-render',
      title: 'Why did this render?',
      kind: 'react',
      xp: 80,
      why: 'Every performance fix starts with knowing which prop changed. Guessing is how `useMemo` ends up on everything.',
      tags: ['performance', 'memo', 'hooks', 'debugging'],
      hints: [
        'Build the set of keys from both objects, then classify each key: missing on one side first, then `Object.is`, then what kind of difference it is.',
        '`Object.prototype.hasOwnProperty.call(obj, key)` tells "present with value undefined" apart from "absent". `obj[key] === undefined` does not.',
        'Shallow equality for `new-reference`: `Array.isArray` must agree, the key counts must match, and every value must be `Object.is`-equal. Check functions before objects.',
        'For the hook, keep the previous props in a `useRef` and do the comparison in a `useEffect` with **no** dependency array, so it runs after every commit. Update the ref after reporting.',
      ],
    },
    {
      id: 'react-expensive-render',
      title: 'Expensive work in the render body',
      kind: 'react',
      xp: 75,
      why: 'Typing lag in a big table is usually a parse or a formatter rebuilt on every keystroke, not React itself.',
      tags: ['performance', 'useMemo', 'useState'],
      hints: [
        'Three separate costs, three separate fixes. Find each place the grader counts: `loadSettings`, `parseCsv`, and `new Intl.NumberFormat`.',
        '`useState(loadSettings)` (the function, not its result) is a lazy initialiser: React calls it once, on mount.',
        '`useMemo(() => parseCsv(csv), [csv])` re-parses only when the string changes. Strings compare by value, so an equal new string is not a change.',
        'Build the formatter once per currency with `useMemo(() => new Intl.NumberFormat(\'en-US\', { style: \'currency\', currency }), [currency])` and call `.format` in the loop.',
      ],
    },
    {
      id: 'react-memo-comparator',
      title: 'Debug: the memo comparator that lies',
      kind: 'react',
      xp: 90,
      why: 'A custom `memo` comparator that ignores props turns a performance problem into a data-loss bug.',
      tags: ['performance', 'memo', 'useCallback', 'debugging'],
      hints: [
        'Delete the custom comparator first and make the shop correct. Then find out why the default comparison fails on every render.',
        'Two props are new on every render of `Shop`: the inline `style` object and the `onAdd` arrow. A constant object can live outside the component.',
        '`useCallback(..., [cart])` is correct but changes every time the cart does. A functional update, `setCart((current) => [...current, id])`, reads the latest cart without closing over it.',
        'With `onAdd` wrapped as `useCallback((id) => setCart((current) => [...current, id]), [])` and `style` hoisted, plain `memo(ProductCardImpl)` does the rest.',
      ],
    },
    {
      id: 'react-key-reset',
      title: 'Identity: nested components and the key reset',
      kind: 'react',
      xp: 80,
      why: 'Losing focus on every keystroke and saving one record\'s draft onto another are both the same rule about component identity.',
      tags: ['reconciliation', 'keys', 'state', 'debugging'],
      hints: [
        'React keeps state for "the same type at the same position". Ask, for each bug, which of those two things changes or fails to change.',
        'A function declared inside a component body is a new function each render, so React sees a new component type. Move `Field` to module level.',
        'The editor stays the same type at the same position when you switch contacts, so it keeps its `useState` draft. Something has to tell React it is a different editor.',
        'Render `<ContactEditor key={selected.id} … />`. A new key unmounts the old editor and mounts a fresh one that reads the new contact.',
      ],
    },
    {
      id: 'react-transition-tabs',
      title: 'Transitions: keep the old screen while the next loads',
      kind: 'react',
      xp: 85,
      why: 'Replacing content the user was reading with a spinner on every click is the most common way a Suspense app feels slower than the one it replaced.',
      tags: ['performance', 'useTransition', 'suspense'],
      hints: [
        'An urgent update that suspends shows the nearest `<Suspense>` fallback. A transition update that suspends keeps the current UI instead.',
        '`const [isPending, startTransition] = useTransition();` gives you both the wrapper and a pending flag.',
        'Wrap the state update, not the click handler: `onClick={() => startTransition(() => setActive(tab.id))}`.',
        'Put `aria-busy={isPending ? \'true\' : undefined}` on the tablist. `aria-selected` already follows `active`, which only commits when the new panel can render.',
      ],
    },
    {
      id: 'react-lazy-preload',
      title: 'Code splitting that does not wait for the click',
      kind: 'react',
      xp: 90,
      why: 'Lazy routes cut the first download, and without preloading and retry they add a spinner to every first visit and break after every deploy.',
      tags: ['performance', 'lazy', 'suspense', 'code splitting'],
      hints: [
        'Keep one variable in the closure, `let loading = null`, and a `load()` that sets it on first call and returns it every time after.',
        'Give `React.lazy` that same `load`, and expose it as `preload`. Now rendering and preloading share one promise.',
        'Retry inside the promise: `const attempt = (left) => factory().catch((e) => left > 0 ? attempt(left - 1) : Promise.reject(e));`. React.lazy never calls you again after a rejection.',
        'In `PageSwitcher`, call `p.Component.preload().catch(() => {})` from both `onMouseEnter` and `onFocus`, and give the error boundary `key={page.name}` so a new page gets a fresh boundary.',
      ],
    },
    {
      id: 'react-virtual-list',
      title: 'A virtualised list',
      kind: 'react',
      xp: 100,
      why: 'Past a few thousand rows no amount of memo helps; rendering only what is on screen is the fix every data-heavy app eventually needs.',
      tags: ['performance', 'virtualisation', 'lists'],
      hints: [
        'Work out `start` and `end` with the four formulas in the brief, then loop from `start` to `end` and render only those rows.',
        'The container\'s only child is a spacer `<div style={{ height: items.length * itemHeight }}>`; each row is `position: \'absolute\'` with `top: index * itemHeight`.',
        'Use `key={index}` where `index` is the item\'s index in `items`, not the loop counter from 0 to the window size.',
        'Clamp before computing: `const top = Math.min(scrollTop, Math.max(0, items.length * itemHeight - height));`.',
      ],
    },
    {
      id: 'react-perf-measuring',
      title: 'Measure before you memo',
      kind: 'quiz',
      xp: 60,
      why: 'Optimising the wrong thing costs a day and a pile of dependency arrays; the Profiler tells you the right thing in a minute.',
      tags: ['performance', 'profiling', 'devtools'],
      quiz: [
        {
          q: 'Users say typing in a search box on a big page lags. What do you do first?',
          options: [
            'Wrap every list item component in `memo`',
            'Debounce the input by 300 ms so it renders less often',
            'Record the interaction in the React DevTools Profiler (and the browser Performance panel) with CPU throttling on, and find out what actually takes the time',
            'Switch the input to an uncontrolled one so React is not involved',
          ],
          answer: [2],
          explain: 'Every other option is a fix for a cause you have not established. The Profiler shows which components rendered for that keystroke, how long each took, and why each rendered; the Performance panel shows whether the time is even in React (it might be layout, a third-party script, or one slow function). Throttling makes a fast laptop behave like a user\'s phone. A debounce, in particular, hides lag by making the input feel unresponsive instead.',
        },
        {
          q: 'In development your render log shows every component rendering twice, and each effect running mount, cleanup, mount. What does it mean?',
          options: [
            'Something is setting state during render and must be fixed',
            'StrictMode deliberately double-invokes renders and re-runs effects in development, to expose impure renders and missing cleanups; production renders once',
            'React 18 always renders twice so it can diff the two results',
            'The components are not memoised, so the parent renders them twice',
          ],
          answer: [1],
          explain: 'StrictMode is a development-only check. A render that is not a pure function of props and state behaves differently the second time, and an effect without a proper cleanup leaks when it is re-run, so both bugs show up locally instead of in production. Counting renders in development therefore overstates the work by exactly this factor; do not "fix" it by removing StrictMode.',
        },
        {
          q: 'The Profiler shows a 500-row list re-rendering on every keystroke in an unrelated filter box, each row reporting "The parent component rendered" with identical props. Which fixes are sound? Select all that apply.',
          options: [
            'Wrap the row in `memo`, and make sure every prop it receives is stable (a `useCallback` handler, no inline objects)',
            'Move the filter state down into a small component of its own, so the list\'s parent no longer re-renders on each keystroke',
            'Give each row `key={Math.random()}` so React treats it as fresh',
            'Have a component that does not own the changing state create the list and pass it in as `children`, so it is not re-created when that state changes',
          ],
          answer: [0, 1, 3],
          explain: 'memo with stable props skips the rows. Colocating state and "lifting content up" as children avoid the parent re-render entirely, and are often simpler than memo. A random key does the opposite of helping: every row unmounts and remounts on every render, which is far more work than re-rendering, and loses every row\'s state and focus.',
        },
        {
          q: 'Which of these `useMemo` calls pay for themselves? Select all that apply.',
          options: [
            '`useMemo(() => price * quantity, [price, quantity])`',
            '`useMemo(() => rows.filter(matches).sort(byDate), [rows, query])` over 5,000 rows, in a component that also re-renders for unrelated reasons',
            '`useMemo(() => first + \' \' + last, [first, last])`',
            '`useMemo(() => ({ user, logout }), [user, logout])` as the `value` of a context provider that many components consume',
          ],
          answer: [1, 3],
          explain: 'useMemo has a cost: a dependency comparison on every render and a closure to allocate. For arithmetic or string concatenation that cost is larger than the work saved. It pays when the work is genuinely expensive (filtering and sorting thousands of rows) or when the result\'s identity matters: a context value that is a new object on every render re-renders every consumer.',
        },
        {
          q: 'In the development build the Profiler reports a 40 ms commit. What can you conclude?',
          options: [
            'Production will take about 40 ms too, so the component must be fixed',
            'Nothing useful: Profiler timings are always inaccurate',
            'The 16 ms frame budget is exceeded, so the component must be memoised',
            'Development builds do extra work (dev-only checks and warnings), so the absolute number is inflated. Use it to compare before and after, and confirm with a production profiling build',
          ],
          answer: [3],
          explain: 'The development build runs extra validation and, under StrictMode, extra renders, so absolute timings run high. Relative comparisons (which component dominates, did the change help) are still meaningful. For absolute numbers, profile a production build with profiling enabled (`react-dom/profiling`), with CPU throttling to approximate real devices.',
        },
        {
          q: 'An interaction feels slow, but the React Profiler shows every commit under 3 ms. Where do you look next?',
          options: [
            'The browser Performance panel: long tasks in the event handler itself, forced layout or style recalculation, or a third-party script on the main thread',
            'Add `useTransition` around the state update',
            'Wrap the app root in `memo`',
            'Upgrade React, since the Profiler is clearly wrong',
          ],
          answer: [0],
          explain: 'If React\'s render and commit are fast, the time is somewhere React does not measure: a slow synchronous handler (a big JSON parse, a sort), layout thrashing from reading and writing DOM sizes in a loop, or other scripts. A transition only helps when rendering is the slow part, and there is nothing to memoise.',
        },
        {
          q: 'Which are real costs of virtualising a long list? Select all that apply.',
          options: [
            'The browser\'s find-in-page cannot find rows that are not rendered',
            'Assistive technology only sees the rendered rows, so you must supply `aria-setsize`/`aria-posinset` and solid keyboard navigation',
            'React re-renders the list more often than it would without virtualisation',
            'Restoring the scroll position after navigating back needs extra work, because the full content does not exist to scroll to',
          ],
          answer: [0, 1, 3],
          explain: 'Virtualisation trades completeness of the DOM for speed, and everything that relied on the DOM being complete (find-in-page, screen reader browsing, scroll restoration, printing) needs attention. It does re-render on scroll, but each render is tiny; the point is that it no longer lays out and diffs thousands of nodes. For a few hundred simple rows, it is often not worth it.',
        },
      ],
    },
    {
      id: 'react-slow-inbox',
      title: 'Boss: the inbox that re-renders everything',
      kind: 'react',
      xp: 220,
      boss: true,
      why: 'Real slowdowns have several causes at once, and a fix for one that breaks correctness is worse than no fix.',
      tags: ['performance', 'memo', 'context', 'useCallback'],
      hints: [
        'Start with `memo(MessageRowImpl)` and then look at each failing test: which prop, or which context, changed for the rows that re-rendered?',
        'The context value `{ density, query, setDensity }` is a new object every render. Rows only need the density: provide exactly that (a string, or an object memoised on `[density]`).',
        'Toggle with a functional update, `setSelected((current) => { const next = new Set(current); … return next; })`, inside `useCallback(…, [])`.',
        'For `onArchive`: `const ref = useRef(onArchive); useLayoutEffect(() => { ref.current = onArchive; });` then `const archive = useCallback((id) => ref.current(id), []);`. The row gets a stable function that always calls the latest prop.',
      ],
    },
  ],
});
