import { loadChapter } from '../../load.ts';

const here = import.meta.dirname;

export default loadChapter(here, {
  id: 'ts-migration',
  title: "Migrating to Strict TypeScript",
  summary: "JS to TS, turning on strict flags incrementally, auditing any, typing legacy modules.",
  lessons: [
    {
      id: 'ts-migration-strategy',
      title: 'Planning an incremental strict migration',
      kind: 'quiz',
      xp: 70,
      why: 'Big-bang migrations stall and end in blanket suppressions; knowing the incremental levers is what gets a real codebase to strict and keeps it there.',
      tags: ['migration', 'tsconfig', 'strict mode', 'tooling'],
      quiz: [
        {
          q: 'Half the codebase is still `.js`. You want the compiler to report type errors in those JavaScript files (using their JSDoc comments) **without renaming them yet**. What do you turn on?',
          options: [
            '`allowJs` on its own',
            '`isolatedModules`',
            '`allowJs` plus `checkJs` (or a `// @ts-check` comment in individual files)',
            '`skipLibCheck: false`',
          ],
          answer: [2],
          explain: '`allowJs` only lets `.js` files into the program so TypeScript files can import them; it does not report errors in them. `checkJs` (project-wide) or `// @ts-check` (per file) type-checks the JavaScript too, reading JSDoc types. That lets you tighten files before renaming them. `isolatedModules` is about single-file transpilers, and `skipLibCheck` only concerns `.d.ts` files.',
        },
        {
          q: 'After turning on a flag, 40 errors remain that the team cannot fix this sprint. Which suppression should the PR use on those lines?',
          options: [
            '`// @ts-expect-error` with a short reason or ticket reference',
            '`// @ts-ignore`, because it is the standard one',
            'A cast to `any` on the offending expression',
            '`// @ts-nocheck` at the top of each affected file',
          ],
          answer: [0],
          explain: '`@ts-expect-error` is itself an error when the line below it no longer has one, so the suppressions clean themselves up: once someone fixes the underlying problem, the compiler tells you to delete the comment. `@ts-ignore` stays silent forever and also hides any **new** error introduced on that line later. `as any` spreads `any` into everything downstream, and `@ts-nocheck` switches off the whole file.',
        },
        {
          q: '`strictNullChecks` produces 2,300 errors across the repo. Which approaches let you turn it on **incrementally** while keeping the main build green? (Select all that apply.)',
          options: [
            'A second tsconfig (e.g. `tsconfig.strict.json`) with the flag on, whose `include` lists the directories already migrated, run in CI next to the main one',
            'Setting `"strictNullChecks": true` in a comment at the top of each migrated file',
            'A per-file strictness tool such as `typescript-strict-plugin`, which checks strict mode everywhere except files carrying an ignore comment',
            'Adding `// @ts-check` to the files that have been migrated',
          ],
          answer: [0, 2],
          explain: 'Compiler flags apply to a whole program, not to individual files, so the incremental tools work at the program level: a stricter tsconfig covering a growing set of directories, or a plugin/CI script that runs the strict check and filters by file. Both let migrated code stay strict while the rest catches up, and the list of exceptions only shrinks. There is no per-file comment for `strictNullChecks`, and `// @ts-check` is only for JavaScript files.',
        },
        {
          q: 'Which strict flag do most teams turn on **first**, and why?',
          options: [
            '`strictNullChecks`, because null errors cause the most production crashes',
            '`noImplicitAny`, because untyped parameters are `any`, and every other check is blind to whatever flows through an `any`',
            '`strictPropertyInitialization`, because classes are the hardest part to migrate',
            'They are equivalent: the order does not matter',
          ],
          answer: [1],
          explain: 'While a parameter is implicitly `any`, `strictNullChecks` cannot see the `undefined` flowing through it, and `strictFunctionTypes` has no types to compare. Typing the parameters first makes the later flags find real problems rather than a subset. It is also the flag whose fixes (annotations) are most mechanical. `strictPropertyInitialization` requires `strictNullChecks` anyway.',
        },
        {
          q: 'The team renamed every file to `.ts`. The build (esbuild or Babel) is green, yet the editor shows hundreds of type errors. What is going on?',
          options: [
            'The editor uses a different TypeScript version; the build is right',
            'esbuild and Babel strip types **without checking them**, so a separate `tsc --noEmit` step has to run in CI for type errors to fail the build',
            '`skipLibCheck` is hiding the errors from the build',
            'The errors are warnings, which never fail a build',
          ],
          answer: [1],
          explain: 'Fast transpilers (esbuild, SWC, Babel, and Node\'s own type stripping) remove type annotations file by file and never run the type checker. That is why they are fast. Unless CI runs `tsc --noEmit` (or `vue-tsc`, and so on), type errors never fail anything, and the migration silently stops meaning anything.',
        },
        {
          q: 'Which number best tells you whether the migration is actually making the code **safer**?',
          options: [
            'The percentage of files with a `.ts` extension',
            'The number of interfaces and type aliases in the codebase',
            'Type coverage: the share of expressions whose type is not `any` (for example from the `type-coverage` tool), together with the count of suppression comments',
            'The number of `.d.ts` files',
          ],
          answer: [2],
          explain: 'A `.ts` file full of `any` is renamed JavaScript. Type coverage measures how much of the code the checker can actually see, and the suppression count measures how much it has been told to ignore. Both should move in one direction only, which also makes them good CI ratchets ("coverage must not drop").',
        },
      ],
    },
    {
      id: 'ts-implicit-any',
      title: 'noImplicitAny without writing any',
      kind: 'typecheck',
      xp: 80,
      why: 'Clearing implicit-any errors with `: any` makes a migration check less than before it started; generic signatures on shared utilities type every call site at once.',
      tags: ['strict mode', 'generics', 'migration', 'any'],
      hints: [
        'Start with the easy two: `formatMoney(cents: number, currency: Currency = "GBP"): string` (type `SYMBOLS` as `Record<Currency, string>` so indexing it compiles), and `sumBy<T>(items: readonly T[], amount: (item: T) => number): number`.',
        'When the result type depends on an argument, the function needs a type parameter for it. `groupBy` needs two: the item `T` and the key `K extends PropertyKey`, inferred from what `keyOf` returns.',
        '`groupBy<T, K extends PropertyKey>(items: readonly T[], keyOf: (item: T) => K): Partial<Record<K, T[]>>`, with `const groups: Partial<Record<K, T[]>> = {}` inside.',
        '`pick<T extends object, K extends keyof T>(obj: T, keys: readonly K[]): Pick<T, K>`. The empty object needs one cast: `const out = {} as Pick<T, K>`.',
        '`once<A extends unknown[], R>(fn: (...args: A) => R): (...args: A) => R`. Store the result as `{ value: R } | undefined` so a function that returns `undefined` is still only called once.',
      ],
    },
    {
      id: 'ts-strict-null-fixes',
      title: 'strictNullChecks: a decision per error',
      kind: 'ts',
      xp: 75,
      why: 'Turning on `strictNullChecks` produces hundreds of errors; clearing them with `!` keeps every bug, and deciding what "missing" means clears them for real.',
      tags: ['strict mode', 'null safety', 'migration'],
      hints: [
        'Start with `get`: look the user up once, `if (!user) throw new NotFoundError("User", id)`, then return it. Several other functions can then call `get`.',
        'For `managerName`, optional chaining does most of it: `const managerId = byId.get(id)?.managerId`, then return `undefined` if that is undefined, else `byId.get(managerId)?.name`.',
        '`emailDomain`: `lastIndexOf("@")` gives -1 when there is none; `slice(at + 1)` gives the domain.',
        '`displayNames`: map to `byId.get(id)`, then `filter((u): u is User => u !== undefined)`, then map to names. `isActive`: `user !== undefined && user.deactivatedAt == null` (the loose `==` matches both null and undefined).',
        '`initials`: `name.split(" ").filter((w) => w !== "").map((w) => w[0].toUpperCase()).join("")`, and `"?"` if that is empty.',
      ],
    },
    {
      id: 'ts-dynamic-keys',
      title: '"Element implicitly has an any type": typing dynamic keys',
      kind: 'typecheck',
      xp: 80,
      why: 'It is the single most common error when a JavaScript codebase turns on strict, and both quick fixes (`as any`, a string index signature) hide real undefined-at-runtime bugs.',
      tags: ['strict mode', 'keyof', 'mapped types', 'migration'],
      hints: [
        'Add `as const` to `STATUS_LABELS` and derive the union: `export type Status = keyof typeof STATUS_LABELS`.',
        '`isStatus(value: string): value is Status { return Object.hasOwn(STATUS_LABELS, value); }`. After the guard, `STATUS_LABELS[value]` compiles, which makes `statusLabel` a one-liner.',
        'For `countByStatus`, initialise every key: `const counts: Record<Status, number> = { open: 0, paid: 0, shipped: 0 }`. Then `counts[order.status] += 1` needs no fallback.',
        '`getField<K extends keyof Order>(order: Order, field: K): Order[K]` is the indexed-access pattern: the key type picks the value type.',
        '`SortKey` filters keys by value type: `{ [K in keyof Order]: Order[K] extends string | number ? K : never }[keyof Order]`.',
      ],
    },
    {
      id: 'ts-any-audit',
      title: 'Auditing the explicit anys',
      kind: 'typecheck',
      xp: 80,
      why: 'Strict mode only catches implicit `any`; the explicit ones left over from a migration switch off checking in every file that calls them.',
      tags: ['any', 'unknown', 'migration', 'generics'],
      hints: [
        'Replace `any` with the most specific honest type: a real interface where you know the shape, a type parameter where the caller decides it, and `unknown` where nobody knows yet.',
        '`readJson<T>(text: string, guard: Guard<T>): T`: assign `const value: unknown = JSON.parse(text)`, throw if `!guard(value)`, and after that check `value` is already a `T`.',
        '`pluck<T, K extends keyof T>(rows: readonly T[], key: K): T[K][]`.',
        '`createCache<V>()` with `const entries = new Map<string, CacheEntry<V>>()`; annotate `get` as returning `V | undefined` and `set`\'s value as `V`.',
        'In `isUser(value: unknown)`, you cannot write `value?.id` on `unknown`. Check `typeof value === "object" && value !== null` first, then `"id" in value && typeof value.id === "string"`: since TS 4.9, `in` narrows an `object` to one that has that key.',
      ],
    },
    {
      id: 'ts-legacy-port',
      title: 'Porting a JS module: the bugs the types reveal',
      kind: 'ts',
      xp: 80,
      why: 'The errors a port produces are rarely the types being fussy; they are production bugs that were always there, and a mid-level engineer is expected to recognise and fix them rather than cast them away.',
      tags: ['migration', 'coercion', 'sorting', 'data cleaning'],
      hints: [
        'Build a `Map` from customer id to name once, keyed by `String(c.id)`, so the lookup uses one key type and is not a `find` per order.',
        'Write a small `pence(value, field, orderId)` helper: `""` gives 0, `/^\\d+$/` gives `Number(value)`, anything else throws the brief\'s error.',
        'Collect unknown ids in a `Set<string>`, then return `[...set].sort()`.',
        'A comparator returns a number: `(a, b) => b.netPence - a.netPence || (a.orderId < b.orderId ? -1 : a.orderId > b.orderId ? 1 : 0)`. The `||` only reaches the tiebreak when the difference is 0.',
        'Start the total\'s `reduce` from `0`, not `""`.',
      ],
    },
    {
      id: 'ts-method-bivariance',
      title: 'The method-syntax hole in strictFunctionTypes',
      kind: 'typecheck',
      xp: 75,
      why: 'Migrated codebases are full of method-syntax interfaces, which `strictFunctionTypes` does not check, so wrong callbacks keep compiling long after strict mode is on.',
      tags: ['strict mode', 'variance', 'interfaces', 'migration'],
      hints: [
        'Only the way the members are written needs to change: `handle(event: AppEvent): void` becomes `handle: (event: AppEvent) => void`.',
        'Do the same for `validate` and for both `Repository` members: `save: (item: T) => void; all: () => T[];`.',
        'For the array hole, make the parameters `readonly AppEvent[]` and `readonly Listener[]`. A readonly array has no `push`, so `withDefaults` has to build a new one.',
        '`return [...events, { type: "tick", at: 0 }];` Its return type is a mutable `AppEvent[]` that the caller owns.',
      ],
    },
    {
      id: 'ts-migration-review',
      title: 'Reviewing "fix TS errors" pull requests',
      kind: 'quiz',
      xp: 70,
      why: 'Most migration damage is done in review, when a silenced error is approved as a fixed one; spotting the difference is a core mid-level review skill.',
      tags: ['code review', 'migration', 'type safety'],
      quiz: [
        {
          q: 'The PR changes\n\n```ts\nconst user = users.find((u) => u.id === id);\nsendEmail(user.email);\n```\n\nto `const user = users.find((u) => u.id === id)!;`. What do you say?',
          options: [
            'Approve: `!` is the idiomatic fix for `find`',
            'Ask for `as User` instead, which is more explicit',
            'Ask what should happen when the user does not exist, and handle it: throw a named not-found error or return early. The `!` keeps the crash and only moves it',
            'Ask for `user?.email` in the `sendEmail` call',
          ],
          answer: [2],
          explain: '`!` and `as User` both tell the compiler "trust me" and change nothing at runtime: a missing user still crashes, now with `Cannot read properties of undefined` one line later. `user?.email` compiles only if `sendEmail` accepts `undefined`, and quietly sends nothing. The error was asking a product question (what if there is no such user?), and the fix is to answer it.',
        },
        {
          q: 'The PR fixes an `any` with\n\n```ts\nconst config = JSON.parse(raw) as AppConfig;\n```\n\nWhat do you say?',
          options: [
            'Approve: it removes the `any`',
            'Ask for runtime validation at this boundary (a schema or a type guard), so a malformed file fails here with a clear error rather than somewhere downstream',
            'Ask for `JSON.parse<AppConfig>(raw)` instead',
            'Ask for `const config: AppConfig = JSON.parse(raw)`, which avoids the cast',
          ],
          answer: [1],
          explain: '`as AppConfig` and the annotated variable are the same unchecked claim; `JSON.parse` returns `any`, which is assignable to anything. (`JSON.parse` is not generic, so the third option does not compile.) Data from outside the process (files, env, network) is exactly where types need a runtime check, because the compiler has never seen it.',
        },
        {
          q: 'The PR turns\n\n```ts\nconst LABELS = { open: "Open", paid: "Paid" };\nreturn LABELS[status]; // status: string\n```\n\ninto `const LABELS: { [key: string]: string } = { … }`. What do you say?',
          options: [
            'Ask for `Record<Status, string>` with `Status` a union (or derived with `keyof typeof`), plus a guard where a raw string comes in: the index signature says every string has a label, so `LABELS["refunded"]` is typed `string` but is `undefined`',
            'Approve: an index signature is the standard way to type a lookup table',
            'Ask for `LABELS[status as keyof typeof LABELS]` instead',
            'Ask for `Map<string, string>` so the lookup is faster',
          ],
          answer: [0],
          explain: 'An index signature trades the error for a lie: every string key "exists". The cast in option 3 makes the same claim about `status`. Typing the keys as the real union moves the check to where the string enters (an `isStatus` guard), and a missing label for a new status becomes a compile error in the table itself.',
        },
        {
          q: 'In a React component the PR changes `catch (e) { setError(e.message) }` (an error under `useUnknownInCatchVariables`) to `catch (e: any) { setError(e.message) }`. What do you say?',
          options: [
            'Approve: `any` is fine in a catch clause, since anything can be thrown',
            'Ask for `(e as Error).message`, which is at least typed',
            'Ask for `setError(String(e))`',
            'Ask for a shared helper that normalises `unknown` (an `Error`\'s message, a thrown string, a fallback for anything else), because a thrown non-Error makes `e.message` undefined and the UI shows a blank error',
          ],
          answer: [3],
          explain: 'Libraries do throw strings, plain objects and `undefined`. `any` and `as Error` both compile and both render `undefined`. `String(e)` never crashes but shows "Error: …" prefixes and "[object Object]". A tiny `errorMessage(e: unknown)` helper, written once and tested, is the fix every catch block can share.',
        },
        {
          q: 'The PR adds `// @ts-ignore` above twelve lines in `checkout.ts` "to unblock the strict flag". What do you say?',
          options: [
            'Approve: suppressions are a normal part of a migration',
            'Ask for `// @ts-expect-error` with a reason on each, so every one fails the build once its error is fixed, and track the count so it only goes down',
            'Ask for `// @ts-nocheck` at the top of the file instead, which is tidier than twelve comments',
            'Block the PR: suppressions should never be used',
          ],
          answer: [1],
          explain: 'Suppressions are a legitimate migration tool, but `@ts-ignore` is the wrong one: it also hides future errors on those lines and never tells you when it has become unnecessary. `@ts-expect-error` does. `@ts-nocheck` switches off the whole checkout file, the last place you want that.',
        },
        {
          q: 'A props interface in the PR reads\n\n```ts\ninterface Props { onChange(value: string | number): void }\n```\n\nand a caller passes `onChange={(v: string) => setName(v.trim())}`. It compiles. What do you say?',
          options: [
            'Nothing: it compiles under `strict`, so it is type-safe',
            'Ask for `onChange: (value: string | number) => void`: method syntax is exempt from `strictFunctionTypes`, so a handler that only accepts strings is allowed and will call `.trim()` on a number',
            'Ask the caller to annotate `v` as `any`',
            'Ask for an overload per value type',
          ],
          answer: [1],
          explain: '`strictFunctionTypes` checks function-typed **properties** contravariantly but leaves **methods** bivariant. In property syntax the caller\'s handler is rejected, because it cannot handle a number, and that is the bug. Migrated interfaces are full of method syntax, and a lint rule (`@typescript-eslint/method-signature-style`) can enforce property style.',
        },
      ],
    },
    {
      id: 'ts-migrate-module',
      title: 'BOSS: migrate a module to strict',
      kind: 'typecheck',
      xp: 210,
      boss: true,
      why: 'A real migration is one module at a time, where every error needs a decision and the exported types become everyone else\'s contract; this is that job, end to end.',
      tags: ['migration', 'strict mode', 'unknown', 'api design'],
      hints: [
        'Start with the data: `as const` on `PRODUCTS`, `export type Sku = keyof typeof PRODUCTS`, then write the interfaces and union types from the brief and export them. Most signatures follow.',
        '`isSku(value: string): value is Sku { return Object.hasOwn(PRODUCTS, value); }` makes `PRODUCTS[line.sku]` compile in `lineTotal` without a cast.',
        '`findCoupon` returns `Coupon | undefined` (type `COUPONS` as `readonly Coupon[]`); `applyCoupon` then has to handle the miss: `if (!coupon || subtotalCents < coupon.minCents) return subtotalCents`.',
        'In `parseCart`, `let data: unknown` inside a `try` around `JSON.parse`. Narrow with `typeof data === "object" && data !== null && "lines" in data && Array.isArray(data.lines)`, then validate each element in a small `toLine(value: unknown): CartLine | undefined`.',
        'Keep listeners in a `Set<CartListener>`, and return `() => { listeners.delete(listener); }` from `onCartChange`. In `checkout`, `if (!cart.ok) return cart;` passes a failed parse straight through, and the `catch` uses `error instanceof Error ? error.message : String(error)`.',
      ],
    },
  ],
});
