import { loadChapter } from '../../load.ts';

const here = import.meta.dirname;

export default loadChapter(here, {
  id: 'node-resilience',
  title: "Resilience II",
  summary: "Bulkheads, retry budgets, hedged requests, timeout propagation, graceful degradation.",
  lessons: [
    {
      id: 'node-bulkhead',
      title: 'Bulkheads: bounded concurrency per dependency',
      kind: 'node',
      xp: 85,
      why: 'One slow dependency should cost you one feature, not every worker in the process; a bulkhead with a bounded queue and fast rejection is how you contain it.',
      tags: ['resilience', 'concurrency', 'promises'],
      hints: [
        'State is just `let active = 0` and `const queue = []`. `run` has three branches: slot free → execute; queue has room → wait; otherwise `return Promise.reject(new BulkheadFullError())`.',
        'Write `execute(fn)`: `active++`, then `const result = new Promise((resolve) => resolve(fn()))` — that turns a synchronous throw into a rejection — and `result.then(release, release)` so the slot is freed either way. Return `result` itself so the caller sees the original outcome.',
        'A waiter is `{ start, timer }`, where `start = () => execute(fn).then(resolve, reject)` inside the `new Promise` that `run` returned.',
        '`release` does `active--`, then `queue.shift()` (oldest first); if there is one, `timers.clearTimeout(next.timer)` and `next.start()`.',
        'The queue timeout callback must remove *its own* waiter: `const i = queue.indexOf(waiter); if (i !== -1) queue.splice(i, 1);` then reject with `QueueTimeoutError`. Only set the timer when `Number.isFinite(queueTimeoutMs)`.',
      ],
    },
    {
      id: 'node-retry-policy',
      title: 'Which failures to retry, and when',
      kind: 'node',
      xp: 90,
      why: 'Retrying the wrong request charges a card twice; retrying at the wrong time ignores the server asking for less load. The decision function is where both are prevented.',
      tags: ['resilience', 'http', 'retries', 'idempotency'],
      hints: [
        'Put the classification in data: a set of always-retryable (`ECONNREFUSED`, `429`), a set of retryable-if-safe (`ECONNRESET`, `ETIMEDOUT`, `EPIPE`, `EAI_AGAIN`, `408`, `502`, `503`, `504`). Anything else is `not-retryable`.',
        'Safe is `IDEMPOTENT.has(String(method).toUpperCase())` or a non-empty string `idempotencyKey`. Guard `method` being undefined.',
        'For `retry-after`: `/^\\d+$/` first (seconds × 1000). Only if the value matches the IMF-fixdate regex from the brief do you `Date.parse` it — `Date.parse(\'1.5\')` is a real date.',
        'Compare the server\'s delay with `maxDelayMs` and give up if it is larger; do not clamp it, which would retry before the server asked.',
        'Backoff: `const cap = Math.min(maxDelayMs, baseMs * 2 ** (attempt - 1)); return { retry: true, delayMs: Math.floor(random() * cap) }`.',
      ],
    },
    {
      id: 'node-retry-budget',
      title: 'Retry budgets: stopping retry storms',
      kind: 'node',
      xp: 90,
      why: 'Per-request retry limits multiply load exactly when a dependency is overloaded; a client-wide budget caps retries at a fraction of real traffic.',
      tags: ['resilience', 'retries', 'load', 'sliding windows'],
      hints: [
        'Keep two arrays of timestamps. Because `now()` never goes backwards, expired entries are always at the front: `while (arr.length && now() - arr[0] >= windowMs) arr.shift()`.',
        'Prune at the start of every method, so `stats()` and `tryRetry()` always see the current window.',
        '`tryRetry`: `const allowed = Math.max(minRetries, Math.floor(ratio * requests.length))`; if `retries.length >= allowed` return `false`, else push `now()` and return `true`.',
        'In `callWithBudget`, `budget.recordRequest()` once before the loop. In the catch: `const retry = attempt < maxAttempts && shouldRetry(error) && budget.tryRetry()`. The `&&` short-circuit is what keeps a hopeless request from spending budget.',
      ],
    },
    {
      id: 'node-hedged-request',
      title: 'Hedged requests for tail latency',
      kind: 'node',
      xp: 100,
      why: 'At the p99, one slow replica makes a whole page slow; a hedged second request is the standard cheap fix for idempotent reads, if it cleans up after itself.',
      tags: ['resilience', 'latency', 'AbortController', 'promises'],
      hints: [
        'Keep a `Map` from attempt number to its `AbortController` for the attempts in flight, an `errors` array indexed by `attempt - 1`, a `started` counter, a `timer` and a `settled` flag.',
        'Write one `finish(settle, value)` that sets `settled`, clears the timer, removes your abort listener, aborts every controller still in the map and calls `settle(value)`. Every exit goes through it.',
        '`launch()` bumps `started`, creates the controller, re-arms the timer (only if `started < maxAttempts`), and calls `fn` inside try/catch. Attach both handlers to the result immediately, even for attempts that will lose: that is what prevents unhandled rejections.',
        'In the failure handler: delete this attempt from the map; if the map is still non-empty, return; else `launch()` if attempts remain, otherwise `finish(reject, new AggregateError(errors, …))`.',
        'Check `signal?.aborted` before doing anything, and `signal?.addEventListener(\'abort\', onAbort, { once: true })` where `onAbort` is `() => finish(reject, signal.reason)`.',
      ],
    },
    {
      id: 'node-deadline-propagation',
      title: 'Propagating deadlines between services',
      kind: 'node',
      xp: 90,
      why: 'Without deadline propagation, every layer keeps working long after the user has given up; passing the remaining budget downstream is how a stack stops wasting work under load.',
      tags: ['resilience', 'timeouts', 'http', 'distributed systems'],
      hints: [
        '`readBudget`: `typeof raw === \'string\' && /^\\d+$/.test(raw)` or return the default; then `Math.min(Number(raw), maxMs)`. A repeated header arrives as an array, which the `typeof` check rejects.',
        '`createDeadline` computes `expiresAt` once, up front; `remaining` is `Math.max(0, expiresAt - now())` and everything else is built on it.',
        '`child(capMs)` is just `createDeadline(Math.min(remaining(), capMs), { now })`.',
        'In the server: build the deadline first; if `remaining() < minBudgetMs` return 504 before calling anything; wrap only `lookupPrice` in try/catch for the 502; check `deadline.expired()` after it returns.',
      ],
    },
    {
      id: 'node-load-shedding',
      title: 'Load shedding with priorities',
      kind: 'node',
      xp: 90,
      why: 'Under overload, refusing some requests quickly is what lets the rest succeed; priorities and exempt health checks keep the refusal from cascading.',
      tags: ['resilience', 'http', 'overload', 'middleware'],
      hints: [
        'The admission rule is one line: `inFlight < (critical ? maxInFlight : maxInFlight - criticalReserve)`, with `critical = req.headers[\'x-priority\'] === \'critical\'`.',
        'Check `exempt.includes(req.url.split(\'?\')[0])` first and call the handler straight away for those — no counting.',
        'Count down in `res.once(\'close\', …)` guarded by a `released` flag, not in a `finally` after the handler: the client may disconnect while the handler is still awaiting something, and the handler may return before the response is done.',
        'Shed with `res.writeHead(503, { \'content-type\': \'application/json\', \'retry-after\': String(retryAfterSec) })` and increment `shed` — and return before calling the handler.',
      ],
    },
    {
      id: 'node-graceful-degradation',
      title: 'Graceful degradation with stale fallbacks',
      kind: 'node',
      xp: 90,
      why: 'Most pages have one required dependency and several nice-to-haves; timeouts, last-good fallbacks and an explicit `degraded` list keep a partial outage from becoming a full one.',
      tags: ['resilience', 'fallbacks', 'timeouts', 'caching'],
      hints: [
        'Write `withTimeout(name, productId, controller)` returning a promise that **never rejects**: it resolves `{ ok: true, value }` or `{ ok: false }`, from whichever of the call and the timer comes first.',
        'Inside it, use one `settle(result)` guarded by a `done` flag that also clears the timer. The timer callback aborts the controller and settles `{ ok: false }`.',
        'Start both optional calls **before** awaiting the catalog, so all three run at once. Wrap only `await catalog(...)` in try/catch; in the catch, abort both controllers and rethrow.',
        'After the catalog, `await Promise.all` of the two wrapped calls, then turn each result into a value: success → remember and use it; failure → last good value with `:stale`, or `[]` with `:empty`.',
        'For the bounded cache use a `Map` per dependency: on store, `delete` then `set` (moves it to the end), then if `size > staleEntries` delete `keys().next().value`.',
      ],
    },
    {
      id: 'node-resilience-quiz',
      title: 'Choosing the right resilience tool',
      kind: 'quiz',
      xp: 70,
      why: 'Every resilience pattern has a failure mode of its own; picking the one that fits the outage in front of you is the judgement a design review tests.',
      tags: ['resilience', 'architecture', 'operations'],
      quiz: [
        {
          q: 'The mobile app times out after 5 s. It calls the gateway (timeout to the orders service: 10 s), which calls orders (timeout to Postgres: 30 s). What is wrong?',
          options: [
            'Nothing: longer inner timeouts give slow queries a chance to finish',
            'The timeouts should all be equal so nothing gives up early',
            'Inner timeouts are longer than outer ones, so under load every layer keeps working for up to 30 s on requests whose caller left after 5',
            'Only the database timeout matters; the others can be removed',
          ],
          answer: [2],
          explain: 'Each layer should give up no later than its caller does, ideally by using the remaining budget passed down with the request. Otherwise a slow database fills the orders service with work nobody is waiting for, which slows everything else behind it. Equal timeouts still waste work, because each layer has already spent part of the budget before calling the next.',
        },
        {
          q: 'Three services call each other in a chain, and each retries failed calls up to 3 times. The bottom service starts rejecting everything. How much traffic can it receive, relative to normal?',
          options: ['3×', '9×', '27×', 'Unchanged: failed calls return quickly'],
          answer: [2],
          explain: 'Each layer multiplies: 3 × 3 × 3. That is why retries belong at **one** layer (usually the one closest to the failing dependency), capped by a retry budget, with the others failing fast. "Failed calls return quickly" is only true until the retries arrive.',
        },
        {
          q: 'The recommendations service gets slow (8 s per call, no errors). Within minutes, checkout — which does not use recommendations — is timing out too. Which pattern addresses the root cause?',
          options: [
            'A bulkhead (with a short timeout) around recommendations, so it can hold only a few workers',
            'A retry policy on recommendations calls',
            'A circuit breaker that opens on errors from recommendations',
            'A cache in front of checkout',
          ],
          answer: [0],
          explain: 'Slow is worse than down: nothing errors, so an error-counting breaker never opens (unless timeouts count as failures), and retries add more slow calls. The problem is that one dependency can take every worker; a bulkhead caps how many it may hold and rejects the rest instantly, so checkout keeps its capacity.',
        },
        {
          q: 'Which calls are reasonable to hedge (send a second copy after a delay, keep the first answer)? (Select all that apply.)',
          options: [
            '`GET /search?q=lamp` to a replicated search cluster',
            '`POST /payments` to the payment provider',
            'A cache lookup by key in a replicated cache',
            '`POST /emails` that sends a welcome email',
          ],
          answer: [0, 2],
          explain: 'Hedging sends the request twice by design, so it is only for idempotent reads, and it only helps when replicas fail slow *independently*. A duplicated payment or email is a real-world side effect. (Even for reads, keep the hedge delay near the p95 so the extra load stays around 5%.)',
        },
        {
          q: 'At peak your service is at 100% CPU with a growing queue. Why is answering some requests with an immediate 503 better than queueing them all?',
          options: [
            'A 503 is cheaper for the load balancer to route',
            'Queued requests wait past their callers\' timeouts, so the server ends up doing full work for requests nobody reads; shedding keeps latency low for the requests it accepts',
            'HTTP requires 503 above a certain load',
            'Queueing loses requests when the process restarts',
          ],
          answer: [1],
          explain: 'Throughput does not rise past saturation, but latency does, until every response arrives after its caller has given up — 100% work, 0% useful. A fast rejection with `Retry-After` costs almost nothing and tells well-behaved clients to back off, so the accepted requests stay fast.',
        },
        {
          q: 'Recommendations have silently returned `[]` from their fallback for three days; nobody noticed because the page still rendered. What should the fallback have done differently?',
          options: [
            'Thrown an error instead, so the page fails',
            'Retried until it succeeded',
            'Cached the empty list for longer',
            'Recorded the degradation — a `degraded` field, a metric, a log line — so dashboards and alerts show it',
          ],
          answer: [3],
          explain: 'Graceful degradation is a trade: availability now, in exchange for knowing you are degraded. A fallback that is not counted turns a visible outage into an invisible one. Failing the page would undo the benefit, and retrying forever is the retry storm again.',
        },
      ],
    },
    {
      id: 'node-resilience-boss',
      title: 'BOSS: a gateway that bends instead of breaking',
      kind: 'node',
      xp: 250,
      boss: true,
      testTimeoutMs: 15000,
      why: 'Deadlines, bulkheads, retry policies, budgets and stale fallbacks only work in combination; wiring them into one request path is what a resilient service actually looks like.',
      tags: ['resilience', 'http', 'retries', 'timeouts'],
      hints: [
        'Build the request path top to bottom as the brief numbers it: route → deadline (504) → bulkhead (503) → live lookup → answer. Keep `active` and the stale `Map` at the top of `createGateway`, not per request.',
        'Write `attemptOnce(sku, remaining)` that returns a small result object — `ok`, `missing`, `retryable` (with an optional `retryAfterMs`) or `failed` — using an `AbortController` with `setTimeout(() => controller.abort(), remaining)`, cleared in a `finally`. Always read the body, even for errors.',
        'In its catch, `controller.signal.aborted` tells your own deadline apart from a network error: the first is `failed`, the second `retryable`. Parse the 200 body in its own try/catch so a bad body is not mistaken for a network error.',
        'The retry loop: `recordRequest()` once; after a retryable result, compute the delay, check `attempt < maxAttempts`, then `delay + minBudgetMs <= deadline.remaining()`, then `tryRetry()` — in that order, so the budget is only spent on retries that will really happen.',
        'Take the bulkhead slot just before the lookup and give it back in a `finally`. Then answer: live (and remember) → stale → `504` if `remaining() === 0` → `502`.',
      ],
    },
  ],
});
