import { loadChapter } from '../../load.ts';

const here = import.meta.dirname;

export default loadChapter(here, {
  id: 'testing-doubles',
  title: 'Doubles, async, integration',
  summary: 'Inject what you do not control, control time instead of waiting for it, test an API through real HTTP, and test components the way a user uses them.',
  lessons: [
    {
      id: 'test-doubles',
      title: 'Stubs, fakes, spies, and when not to mock',
      kind: 'mutation',
      xp: 90,
      minTests: 5,
      why: 'Over-mocked tests break on every refactor and still miss real bugs. Injecting a small honest fake gives you tests that break only when behaviour changes.',
      tags: ['test doubles', 'dependency injection', 'clocks'],
      mutants: [
        { slug: 'sends-twice', label: 'Reminds twice when the same invoice appears twice in the input' },
        { slug: 'ignores-paid', label: 'Reminds invoices that are already paid' },
        { slug: 'off-by-one-day', label: 'Treats an invoice as overdue on its due date' },
        { slug: 'wrong-recipient', label: 'Sends every reminder to the first invoice\'s customer' },
        { slug: 'uses-real-date', label: 'Reads the real clock instead of the injected one' },
      ],
      hints: [
        'Build the fake mailer as a plain object that pushes every message into an array. Then assert on the array\'s contents, not on the order of the calls.',
        'Because order is not promised, index the sent messages by `invoiceId` (or sort them) before comparing. Two invoices for *different* customers expose the wrong-recipient bug.',
        'The boundary: with the clock on `2024-03-10`, an invoice due `2024-03-10` gets no email and one due `2024-03-09` is 1 day overdue.',
        'For the real-clock bug, set the stub clock *before* the due date (e.g. clock `2020-06-01`, due `2020-06-15`) and assert nothing is sent. The real clock is years later and would send it.',
      ],
    },
    {
      id: 'test-async-deterministic',
      title: 'Testing async code without sleeping',
      kind: 'mutation',
      xp: 100,
      minTests: 6,
      testTimeoutMs: 400,
      why: 'Tests that sleep are slow on a good day and flaky on a bad one. Controlling time is how you test retries, debouncing and timeouts deterministically.',
      tags: ['async', 'fake timers', 'retry', 'debounce', 'flaky tests'],
      mutants: [
        { slug: 'no-await', label: 'retry returns fn() without awaiting it, so a rejection is never retried' },
        { slug: 'extra-attempt', label: 'retry makes one attempt too many (treats attempts as retries)' },
        { slug: 'sleeps-after-last', label: 'retry sleeps again after the final failed attempt' },
        { slug: 'debounce-leading-edge', label: 'debounce fires on the first call of a burst instead of after it goes quiet' },
      ],
      hints: [
        'For `retry`, pass `sleep: async (ms) => { delays.push(ms); }`. It records the backoff and resolves at once, so no real time passes.',
        'Write a `fn` that rejects N times and then resolves, and records each call. The `no-await` bug fails "fails once, then succeeds": it rejects when it should retry.',
        'Assert both the calls to `fn` (e.g. `[1, 2, 3]` when every attempt fails with `attempts: 3`) and the recorded delays (`[100, 200]`, not `[100, 200, 400]`).',
        'For `debounce`, use the starter\'s `fakeTimers()`: call twice, `advance(ms - 1)`, and assert `fn` has **not** run yet. Then `advance(1)` and assert it ran once with the last arguments.',
      ],
    },
    {
      id: 'test-http-integration',
      title: 'Integration-testing an endpoint',
      kind: 'mutation',
      subjectKind: 'node',
      xp: 110,
      minTests: 7,
      why: 'Most API bugs sit in the wiring: status codes, auth on one route, error envelopes. Only a request through a real server exercises the wiring.',
      tags: ['integration tests', 'http', 'auth', 'pagination'],
      mutants: [
        { slug: '201-becomes-200', label: 'POST /notes answers 200 instead of 201' },
        { slug: 'leaks-error-message', label: 'A 500 sends the internal error message to the client' },
        { slug: 'auth-missing-on-delete', label: 'DELETE /notes/:id works without a token' },
        { slug: 'validation-500', label: 'Validation failures come back as 500 instead of 400' },
        { slug: 'total-after-paging', label: 'total counts the page instead of every match' },
        { slug: 'patch-clears-tags', label: 'PATCH without tags wipes the note\'s tags' },
      ],
      hints: [
        'Use the starter\'s `withApi` for every test: a fresh server per test means ids start at `\'1\'` and no state leaks between tests.',
        'Auth: in one test, loop over every method and path (`GET /notes`, `POST /notes`, `GET`/`PATCH`/`DELETE /notes/1`) with a wrong token and expect `401` for each. Then check with a valid token that nothing was deleted or changed.',
        'The 500 path: `withApi(fn, { now: () => { throw new Error("db-primary refused") } })`, then POST a valid note. Assert status `500`, code `INTERNAL`, and that the response text does not contain `db-primary`.',
        'Paging: create 5 notes, request `?limit=2&offset=1`, and expect `total` to be 5. PATCH: create a note with `tags: ["work"]`, patch only the `title`, and expect the tags to be unchanged.',
      ],
    },
    {
      id: 'test-rtl-behaviour',
      title: 'BOSS: test components by behaviour',
      kind: 'mutation',
      subjectKind: 'react',
      xp: 220,
      boss: true,
      minTests: 8,
      why: 'Tests that query the way users and assistive technology do survive redesigns and still catch broken rollbacks, double submits and focus traps.',
      tags: ['testing library', 'accessibility', 'optimistic ui', 'focus management'],
      mutants: [
        { slug: 'no-rollback', label: 'LikeButton keeps the optimistic count and label after a failed save' },
        { slug: 'double-fire', label: 'LikeButton lets a second click fire another save while one is in flight' },
        { slug: 'focus-not-restored', label: 'Modal leaves focus on the page body when it closes' },
        { slug: 'escape-ignored', label: 'Modal ignores the Escape key' },
        { slug: 'error-never-clears', label: 'LikeButton\'s error alert never goes away' },
      ],
      hints: [
        'Make `save` return a promise you settle by hand (the starter\'s `deferred()`), and record each call. Now you can check the in-flight state and then `await act(async () => { d.reject(new Error("x")); })`.',
        'Double fire: click, then click again while the save is pending. `save` must have been called once, and the button must be `.disabled`.',
        'Error clearing takes two saves: fail the first (the alert appears), click again, resolve the second, then `expect(screen.queryByRole("alert")).toBeNull()`.',
        'Focus: render a wrapper with `const [open, setOpen] = React.useState(false)`, a trigger button and the Modal. Call `trigger.focus()`, click it, close with `fireEvent.keyDown(document.body, { key: "Escape" })`, and assert `document.activeElement === trigger`.',
        'Find the dialog with `getByRole("dialog", { name: "Settings" })`, not by `h2` or class. The rewrite uses `<section>` and `<h3>`.',
      ],
    },
  ],
});
