import { loadChapter } from '../../load.ts';

const here = import.meta.dirname;

export default loadChapter(here, {
  id: 'node-background-work',
  title: "Background Work",
  summary: "In-process job queues with retries, schedulers, outbox-lite, dead letters, concurrency control.",
  lessons: [
    {
      id: 'node-job-queue-retries',
      title: 'A job queue whose retries do not block the line',
      kind: 'node',
      xp: 90,
      why: 'Every app moves slow work (emails, webhooks, exports) out of the request. A worker that sleeps through its backoff inside a slot turns one bad job into a stalled queue.',
      tags: ['jobs', 'retries', 'concurrency', 'timers'],
      hints: [
        'Keep a `jobs` map (id → mutable record), a `ready` array of queued ids, and counters `running` and `waiting`. One `pump()` starts jobs while `running < concurrency && ready.length > 0`.',
        'Start a handler with `new Promise((resolve) => resolve(handler(payload, meta)))` so a synchronous throw becomes a rejection. In `.finally`, decrement `running` and call `pump()` again.',
        'On failure with attempts left: set the state to `\'waiting\'`, `waiting++`, and `timers.setTimeout(() => { waiting--; job.state = \'queued\'; ready.push(job.id); pump(); }, backoff(job.attempts))`. The slot is freed by the `finally` above, not by the timer.',
        'Idle means `ready.length === 0 && running === 0 && waiting === 0`. Keep an array of `onIdle` resolvers and flush it at the end of every `pump()` when idle.',
        '`get` returns `{ ...job }`, and `enqueue` checks `Object.hasOwn(handlers, type)` — `\'toString\' in handlers` is true for every object.',
      ],
    },
    {
      id: 'node-dead-letter',
      title: 'Poison messages and dead-letter queues',
      kind: 'node',
      xp: 90,
      why: 'One message that can never succeed will be retried forever unless the consumer moves it aside — and moving it aside wrongly loses exactly the message you needed to inspect.',
      tags: ['queues', 'retries', 'errors', 'reliability'],
      hints: [
        'Write one `handle(message)` that resolves to `\'acked\'`, `\'deadLettered\'` or `\'released\'`, and run `Promise.allSettled(messages.map(handle))` — `allSettled` is what keeps one failing broker call from rejecting the whole poll.',
        'Parse first, in its own `try`: a parse error goes straight to the DLQ with reason `\'unparseable\'`, and the handler never sees the message.',
        'After a handler failure, check in order: `isPermanent(error)` → `\'permanent\'`; `receiveCount >= maxReceives` → `\'max-receives\'`; else `release(id, backoff(receiveCount))`. Use the message\'s `receiveCount`, never a counter of your own.',
        'Dead-lettering is `try { await dlq.send(entry) } catch { await queue.release(id, backoff(receiveCount)); return \'released\' }` followed by `await queue.ack(id)`. The ack comes **after** the DLQ write succeeded.',
      ],
    },
    {
      id: 'node-interval-scheduler',
      title: 'An interval scheduler that neither overlaps nor drifts',
      kind: 'node',
      xp: 90,
      why: '`setInterval` overlaps slow runs, `setTimeout`-after-finish drifts, and an uncaught error ends the loop. Every service has a periodic task that needs these three fixed.',
      tags: ['scheduling', 'timers', 'async', 'reliability'],
      hints: [
        'Store `start = now()` for each task. Tick *k* is due at `start + k * intervalMs`; compute every due time from that grid, never from when a run finished.',
        'After each tick, the next index is `Math.max(k + 1, Math.floor((now() - start) / intervalMs) + 1)` — the first grid point strictly after now. That is what turns a long sleep into one run instead of a burst.',
        'Keep `inFlight` per task: the run\'s promise, set to `null` in `.finally`. A tick that finds it set increments `skipped` and just schedules the next tick.',
        'Start a run with `new Promise((resolve) => resolve(task()))` and attach `.catch((e) => { failures++; onError(name, e); })` before `.finally` — then a failure neither escapes nor stops the schedule.',
        '`stop()`: set a `stopped` flag, `timers.clearTimeout` every pending handle, then `await Promise.all(tasks.map((t) => t.inFlight))` (awaiting `null` is fine).',
      ],
    },
    {
      id: 'node-keyed-serial',
      title: 'Ordered per key, parallel across keys',
      kind: 'node',
      xp: 90,
      why: 'Webhooks, per-account ledgers and per-document edits must be processed in order for the same key but in parallel overall. The naive queue either races or blocks everyone behind one busy key.',
      tags: ['concurrency', 'ordering', 'queues', 'memory leaks'],
      hints: [
        'Three pieces of state: `pending` (array of `{ key, task, resolve, reject }` in submission order), `busy` (a `Set` of keys with a task running), and `running`.',
        'In `pump()`, walk `pending` from the front: skip an item whose key is in `busy`; otherwise `splice` it out and start it. Stop when `running === concurrency`. Skipping, rather than stopping at the first busy key, is the whole lesson.',
        'Starting a task: `running++`, `busy.add(key)`, then `new Promise((r) => r(task())).then(resolve, reject).finally(() => { running--; busy.delete(key); …; pump(); })`.',
        'For `activeKeys`, keep a `Map` of key → number of tasks running or pending: increment in `run`, decrement when a task settles, and `delete` the key when it reaches 0.',
      ],
    },
    {
      id: 'node-job-leases',
      title: 'Leases, heartbeats and zombie workers',
      kind: 'node',
      xp: 95,
      why: 'A worker that dies mid-job must not strand the job, and a worker that was only paused must not complete work someone else has taken over. Leases with tokens handle both.',
      tags: ['jobs', 'distributed systems', 'time', 'concurrency'],
      hints: [
        'Store per job: `done`, `attempt`, `availableAt` (for release delays), and `lease` — `null` or `{ token, owner, expiresAt }`. A lease is active while `now() < lease.expiresAt`.',
        '`claim` iterates the jobs map in insertion order (which is id order) and takes the first that is not done, has no active lease, and has `now() >= availableAt`.',
        'Generate tokens with `randomUUID()` from `node:crypto` (or a global counter). A token derived from the job id alone is the same for every claim, which is exactly what lets a zombie through.',
        'Write one `holder(id, token)` that returns the job or throws `new LeaseLostError(id)` when the job is unknown, done, its lease is not active, or `lease.token !== token`. `heartbeat`, `complete` and `release` all start with it.',
        '`get` derives `state` and `owner` from the lease at the current time: an expired lease shows `\'available\'` and `owner: null` even though the stale lease object is still stored.',
      ],
    },
    {
      id: 'node-db-outbox',
      title: 'The transactional outbox',
      kind: 'node-db',
      xp: 95,
      why: 'Writing to the database and publishing to a broker are two writes that cannot share a transaction. The outbox is the standard way to never lose, or invent, an event.',
      tags: ['transactions', 'events', 'postgres', 'reliability'],
      hints: [
        '`placeOrder` is the familiar shape: `begin`, `try { …; commit }`, `catch (e) { rollback; throw e }`. The outbox insert goes inside the `try`, after the order insert.',
        'Get the order id with `insert … returning id`, then pass the payload as `JSON.stringify({ orderId, customer, totalCents })` into `$2::jsonb`.',
        'The relay selects with `where published_at is null order by id limit $1` and loops with `for … of` and `await` — events are published one at a time, in order.',
        'After each successful `publish`, run `update outbox set published_at = now() where id = $1` immediately. In the `catch`, `update outbox set attempts = attempts + 1, last_error = $2 where id = $1` and `return` — no transaction around the loop.',
      ],
    },
    {
      id: 'node-db-job-lock',
      title: 'Run a scheduled job once across replicas',
      kind: 'node-db',
      xp: 90,
      why: 'Scaling to three replicas runs every in-process cron job three times. A lease row taken with one atomic statement is the fix that uses the database you already have.',
      tags: ['postgres', 'locking', 'scheduling', 'concurrency'],
      hints: [
        'Compute the expiry in JavaScript: `new Date(now.getTime() + ttlMs)`, and pass both it and `now` as parameters.',
        'The statement is `insert into job_locks (name, owner, locked_until) values ($1, $2, $3) on conflict (name) do update set owner = excluded.owner, locked_until = excluded.locked_until where … returning owner`.',
        'The `where` on the `do update` decides whether you may take an existing row: `job_locks.locked_until <= $4 or job_locks.owner = excluded.owner`. When it is false, nothing is updated and `returning` yields no row — so `rows.length === 1` is your answer.',
        '`release` is `delete … where name = $1 and owner = $2 returning name`. In `runExclusive`, put the `release` in a `finally` around `await fn()`.',
      ],
    },
    {
      id: 'node-background-judgement',
      title: 'Background job design calls',
      kind: 'quiz',
      xp: 60,
      why: 'Queue semantics, job payloads and transaction boundaries decide whether background work is boring or haunted. These are the calls reviewers expect you to get right.',
      tags: ['jobs', 'queues', 'reliability'],
      hints: [
        'Assume every message can be delivered twice and every process can die between any two lines.',
        'Ask what the worker sees when it runs: the world at enqueue time, or the world now?',
      ],
      quiz: [
        {
          q: 'Your queue promises **at-least-once** delivery. What does that require of the "send receipt email" handler?',
          options: [
            'Nothing: at-least-once means each message is processed exactly once in practice.',
            'It should acknowledge the message before sending, so a crash cannot cause a resend.',
            'It must be idempotent: record that receipt N was sent (keyed by a stable id) and skip it when the message arrives again.',
            'It should use a longer visibility timeout so duplicates cannot happen.',
          ],
          answer: [2],
          explain: 'At-least-once means duplicates **will** happen: a worker crashes after sending but before acking, a lease expires during a GC pause, a network blip loses the ack. The handler must make the second delivery harmless — a unique constraint on `(receipt_id)` in a `sent_emails` table, or an idempotency key passed to the email provider. Acking first converts duplicates into **lost** emails (at-most-once). A longer timeout makes duplicates rarer, never impossible.',
        },
        {
          q: 'A job calls a partner API, which answers `400 Bad Request: "vat_number is invalid"`. What should the worker do?',
          options: [
            'Retry with exponential backoff up to the maximum attempts, then dead-letter it.',
            'Treat it as permanent: dead-letter it (or mark it failed) at once, with the error, and alert whoever owns the data.',
            'Retry forever with a long backoff; the partner may fix it eventually.',
            'Ack it and log a warning.',
          ],
          answer: [1],
          explain: 'A 400 says the request itself is wrong: sending the same payload again will fail the same way, and each retry burns a worker slot and partner rate limit. Classify errors: timeouts, 429s and 5xx are transient (retry with backoff); 4xx validation errors are permanent. Acking and logging hides the failure in a log nobody reads — dead-lettering keeps the message and the reason where someone can fix the data and replay it.',
        },
        {
          q: 'You enqueue `sendInvoice`. What should the job payload contain?',
          options: [
            'The whole invoice object, so the worker does not need to query the database.',
            'The rendered PDF, base64-encoded, so the job is self-contained.',
            'The invoice id (plus anything that must be frozen at enqueue time), and the worker loads the current invoice when it runs.',
            'The SQL query the worker should run to find the invoice.',
          ],
          answer: [2],
          explain: 'A job may run seconds or hours later, possibly after retries. A full snapshot goes stale (the invoice was voided in the meantime, and the worker emails it anyway), bloats the queue, and copies personal data into another system with its own retention. Pass the id and re-read, and let the worker check current state ("voided? skip"). The exception is data that must be as-of enqueue time — then include exactly that, deliberately.',
        },
        {
          q: 'Inside the database transaction that creates a user, the code does `await queue.add(\'welcome-email\', { userId })` and then commits. What can go wrong? Select all that apply.',
          options: [
            'The worker picks up the job before the commit is visible and cannot find the user.',
            'The transaction rolls back after the enqueue, and a welcome email is sent for a user who does not exist.',
            'Nothing: the enqueue happens inside the transaction, so it is rolled back with it.',
            'The process dies between the commit and returning, and the email is sent twice.',
          ],
          answer: [0, 1],
          explain: 'The queue (Redis, SQS, …) is not part of your database transaction, so the enqueue is visible immediately and is **not** undone by a rollback. Workers are fast: they often run before the commit lands. Enqueue after commit (and accept a small chance of losing the job if the process dies in between), or use a transactional outbox so the job and the user are written atomically. The last option describes a different problem, not one this code creates.',
        },
        {
          q: 'The worker process receives `SIGTERM` for a deploy, with a 30-second grace period. It has three jobs running. What is the best behaviour?',
          options: [
            'Exit immediately; the leases will expire and other workers will retry the jobs.',
            'Stop claiming new jobs, give running jobs most of the grace period to finish, then abort and release whatever is left so it is retried promptly.',
            'Keep claiming and running jobs until the platform kills the process.',
            'Ignore `SIGTERM`: jobs must never be interrupted.',
          ],
          answer: [1],
          explain: 'Exiting at once is survivable with leases, but every running job waits out its full lease before anyone retries it, and half-done side effects are more likely. Claiming more work during shutdown guarantees interrupted jobs. The clean sequence is drain-then-release: stop taking work, let in-flight jobs finish within the grace period, and explicitly hand back (release) the stragglers so they are retried immediately. Ignoring the signal just gets you `SIGKILL`.',
        },
        {
          q: 'A job that expires unpaid carts runs every hour on each of three replicas. Which of these make it run once per hour? Select all that apply.',
          options: [
            'A lock row taken with one atomic `insert … on conflict … do update … where locked_until <= now` before running.',
            'A random 0–60 s delay before each replica starts the job.',
            'Running the scheduler in a single dedicated process (or the platform\'s cron) instead of in every web replica.',
            'Checking `select count(*) from job_runs where started_at > now() - interval \'1 hour\'` and skipping if it is non-zero.',
          ],
          answer: [0, 2],
          explain: 'An atomic lock (or a Postgres advisory lock) makes "check and take" one step, so only one replica wins. Moving scheduling out of the replicas removes the problem entirely. A random delay only makes collisions rarer. The `count(*)` check is check-then-act: two replicas can both read zero before either inserts its run — the race the lock exists to prevent.',
        },
      ],
    },
    {
      id: 'node-worker-boss',
      title: 'BOSS: a production job worker',
      kind: 'node',
      xp: 240,
      boss: true,
      why: 'Claiming, concurrency, heartbeats, retries, dead letters and graceful shutdown all live in one loop in every real worker. The bugs are in how they interact.',
      tags: ['jobs', 'concurrency', 'timers', 'shutdown', 'reliability'],
      hints: [
        'Keep a `Set` of runs this worker still owns. "Owned" is the single question every late event asks: a heartbeat failure, a grace timeout and a handler settling all check `runs.has(r)` first, and giving a job up is `runs.delete(r)` plus clearing its heartbeat timer.',
        'Write `fill()` as a loop guarded by a `filling` flag: `while (!stopping && runs.size < concurrency) { const job = await claimOne(); if (!job) { schedulePoll(); return; } run(job); }`. Call it from `start`, the poll timer, and whenever a slot frees.',
        '`schedulePoll` does nothing if a poll timer is already pending or you are stopping. `claimOne` wraps `store.claim` in `try/catch` (a failure is `null`) and, if `stopping` became true while it waited, releases the job with `delayMs: 0` and returns `null`.',
        'Per job: an `AbortController`, and a heartbeat `timers.setTimeout` that calls `store.heartbeat` and reschedules itself only if the job is still owned. If the heartbeat throws: disown, `controller.abort()`, and free the slot.',
        'Settle a handler through `new Promise((r) => r(handler(…))).then(onOk, onErr)`: both handlers first `if (!owned) return`, then disown and call `complete` / `bury` / `release` through a `quietly` wrapper that swallows store errors. Then free the slot.',
        '`stop`: set `stopping`, clear the poll timer, `await` any claim in flight, and if runs remain, race "drained" (a callback the slot-freeing code calls when `runs.size === 0`) against a `graceMs` timer that disowns, aborts and releases the leftovers.',
      ],
    },
  ],
});
