import { loadChapter } from '../../load.ts';

const here = import.meta.dirname;

export default loadChapter(here, {
  id: 'testing-integration',
  title: "Integration Tests",
  summary: "HTTP handlers, services with fakes, contract-style checks — you write the tests.",
  lessons: [
    {
      id: 'test-int-http-edges',
      title: 'The HTTP edges: 405, 413, 415 and bad JSON',
      kind: 'mutation',
      subjectKind: 'node',
      xp: 85,
      minTests: 7,
      why: 'Clients, caches and retry libraries act on status codes. A parse error sent as `500` gets retried forever, and a strict content-type check locks out real clients.',
      tags: ['integration tests', 'http', 'status codes'],
      mutants: [
        { slug: 'charset-rejected', label: 'Rejects `application/json; charset=utf-8` with 415' },
        { slug: 'accepts-text-plain', label: 'Accepts a JSON body sent as `text/plain`' },
        { slug: 'malformed-json-500', label: 'Malformed JSON comes back as 500 instead of 400' },
        { slug: 'no-size-limit', label: 'Accepts bodies over 1024 bytes' },
        { slug: 'no-location', label: '201 has no Location header' },
        { slug: 'no-allow-header', label: '405 has no Allow header' },
        { slug: 'item-method-404', label: 'An unsupported method on `/bookmarks/:id` answers 404 instead of 405' },
      ],
      hints: [
        'Walk the contract table and the numbered POST checks, and write one test per row. Each row has its own status code.',
        'Send content types on purpose: `{ json, headers: { \'content-type\': \'application/json; charset=utf-8\' } }` must be 201, and `{ body: JSON.stringify(...), headers: { \'content-type\': \'text/plain\' } }` must be 415.',
        'The size limit: `{ json: { url: \'https://example.com\', note: \'x\'.repeat(solution.MAX_BODY_BYTES + 1) } }` is valid JSON and must still be 413.',
        'Compare `Allow` as a set: `headers.get(\'allow\').split(\',\').map((m) => m.trim()).sort()`. Check it on `/bookmarks` and on `/bookmarks/1` with a method neither supports, such as `PATCH`.',
        'Follow the Location header: `expect(created.headers.get(\'location\')).toBe(\'/bookmarks/\' + created.body.id)`, then GET it.',
      ],
    },
    {
      id: 'test-int-conditional-get',
      title: 'ETags and 304s, end to end',
      kind: 'mutation',
      subjectKind: 'node',
      xp: 85,
      minTests: 6,
      why: 'A wrong ETag either serves stale data from every cache or saves no bandwidth at all. Only a request sequence through a real server shows which.',
      tags: ['integration tests', 'http caching', 'etag'],
      mutants: [
        { slug: 'etag-not-updated', label: 'A PUT changes the article but not its ETag' },
        { slug: 'ignores-list', label: 'An If-None-Match list never matches' },
        { slug: 'strong-compare', label: '`W/"x"` does not match `"x"`' },
        { slug: 'any-header-304', label: 'Answers 304 to any If-None-Match, even a stale tag' },
        { slug: 'no-etag-on-304', label: 'A 304 has no ETag header' },
        { slug: 'no-cache-control', label: 'Sends no Cache-Control header' },
      ],
      hints: [
        'Never hardcode a tag. GET the article, read `headers.get(\'etag\')`, then send it back in `If-None-Match`.',
        'Pair every 304 test with a 200 test: a made-up tag such as `\'"some-old-version"\'` must get the full article.',
        'Lists and weak tags: `\'"nope", \' + etag` must be 304, and so must `\'W/\' + etag`.',
        'The sequence test: GET (keep the tag), PUT a change, then revalidate with the old tag. It must be 200 with the new content, and the tag from the PUT response must be 304.',
        'Check the headers on the 304 too: `etag` equals the current tag, and `cache-control` split on commas contains `no-cache`.',
      ],
    },
    {
      id: 'test-int-idempotency',
      title: 'Proving a payment endpoint is safe to retry',
      kind: 'mutation',
      subjectKind: 'node',
      xp: 95,
      minTests: 7,
      why: 'Clients retry on timeouts. Without a test of every retry path, a lost response turns into a double charge.',
      tags: ['integration tests', 'idempotency', 'payments', 'concurrency'],
      mutants: [
        { slug: 'charges-twice', label: 'A retry after a success charges the customer again' },
        { slug: 'body-not-compared', label: 'The same key with a different amount replays the old payment instead of answering 422' },
        { slug: 'replay-status-200', label: 'A replay answers 200 instead of the stored 201' },
        { slug: 'failure-cached', label: 'After a failed charge the key is stuck: retries replay the 502 and never reach the provider' },
        { slug: 'no-in-flight-guard', label: 'Two simultaneous requests with the same key both charge' },
        { slug: 'missing-key-allowed', label: 'A payment with no Idempotency-Key goes through' },
        { slug: 'key-order-matters', label: 'The same body with its keys in another order counts as a different request' },
      ],
      hints: [
        'Write a fake `charge` that pushes every call into an array. Almost every test should end with `expect(calls).toHaveLength(n)`.',
        'Replay: pay twice with key `k1` and the same body. The second answer is `201`, its body `toEqual`s the first one, and `calls` has length 1.',
        'Failure: make the fake throw on its first call only. The first request is `502` `PAYMENT_FAILED`, the retry with the same key is `201`, and `calls` has length 2.',
        'Also send the same body with its keys reordered (`{ amountCents, customerId }`): it is the same request. A changed `amountCents` is `422`.',
        'Concurrency: let the first call return a promise you settle later, and resolve a `started` deferred inside it. `const first = pay(...)`, `await started.promise`, then `await pay(...)` again and expect `409`. Make any later call settle at once so a buggy server fails fast instead of hanging.',
      ],
    },
    {
      id: 'test-int-rate-limit',
      title: 'Testing a rate limiter with a fake clock',
      kind: 'mutation',
      subjectKind: 'node',
      xp: 85,
      minTests: 6,
      why: 'Rate limiters fail at window edges, across keys and in their headers. You can only see those failures when the test controls time.',
      tags: ['integration tests', 'rate limiting', 'fake clock'],
      mutants: [
        { slug: 'one-extra-request', label: 'Allows one request more than the limit' },
        { slug: 'shared-bucket', label: 'All API keys share one counter' },
        { slug: 'window-never-resets', label: 'The window never resets' },
        { slug: 'reset-late', label: 'Still limits at the exact millisecond the window ends' },
        { slug: 'retry-after-ms', label: 'Retry-After is in milliseconds, not seconds' },
        { slug: 'remaining-off-by-one', label: 'RateLimit-Remaining is one too high' },
        { slug: 'no-key-served', label: 'A request without an API key is served instead of 401' },
      ],
      hints: [
        'Build a clock you move by hand: `let t = 0; const now = () => t;`. Pass it as `now`, and set `t` between requests. Nothing sleeps.',
        'Use a small limit (2 or 3) and assert the whole sequence: statuses `[200, 200, 200]` then `429`, and `ratelimit-remaining` `[\'2\', \'1\', \'0\']`.',
        'Boundary: first request at `t = 0` with `windowMs: 10000`. At `9999` it is still 429; at exactly `10000` it is 200 again.',
        'Retry-After: `limit: 1`, first request at `0`, then at `18500` the answer is `\'42\'` (41.5 s rounded up). Milliseconds would give `41500`.',
        'Exhaust key `noisy`, then key `quiet` must still get 200. And `/search` with no key is 401.',
      ],
    },
    {
      id: 'test-int-webhook',
      title: 'Testing a webhook receiver',
      kind: 'mutation',
      subjectKind: 'node',
      xp: 90,
      minTests: 7,
      why: 'Webhook receivers break on the provider\'s rules: raw-byte signatures, signed timestamps, duplicate deliveries and retries. A test that checks only the happy path misses all of them.',
      tags: ['integration tests', 'webhooks', 'hmac', 'security'],
      mutants: [
        { slug: 'reserialised-body', label: 'Verifies the signature against re-serialised JSON, so pretty-printed payloads are rejected' },
        { slug: 'timestamp-unsigned', label: 'The signature does not cover the timestamp, so an old signature works with a fresh `t`' },
        { slug: 'no-staleness-check', label: 'Accepts signatures of any age' },
        { slug: 'future-accepted', label: 'Accepts timestamps far in the future' },
        { slug: 'no-dedupe', label: 'Handles a duplicate delivery twice' },
        { slug: 'marks-before-handling', label: 'Marks an event handled before the handler runs, so the retry after a failure is skipped' },
        { slug: 'handler-error-200', label: 'Answers 200 when the handler throws, so the provider never retries' },
      ],
      hints: [
        'Record every event `onEvent` receives (the starter does). Most tests should assert on that list as well as on the status.',
        'Sign a pretty-printed body as sent: `const pretty = JSON.stringify(event, null, 2); post(pretty, sign(pretty))` must be 200.',
        'Replay attack: `sign(raw, NOW_S - 3600)` gives an old `v1`. Send it as `` `t=${NOW_S},v1=${v1}` `` and expect 401.',
        'Timestamps: `NOW_S - 300` and `NOW_S + 300` are accepted; `NOW_S - 301` and `NOW_S + 301` are `STALE_SIGNATURE`.',
        'Retries: make `onEvent` throw once. The first post is 500 `HANDLER_FAILED`, the same post again is 200, and the handler ran twice. Two successful deliveries of the same id run it once.',
      ],
    },
    {
      id: 'test-int-upstream-stub',
      title: 'A stub server for the API you call',
      kind: 'mutation',
      subjectKind: 'node',
      xp: 90,
      minTests: 7,
      why: 'A mocked `fetch` only answers what you imagined. A stub server sends real statuses and headers, and records what your client actually sent.',
      tags: ['integration tests', 'stub server', 'retries', 'http client'],
      mutants: [
        { slug: 'retries-client-errors', label: 'Retries 4xx errors such as 401' },
        { slug: 'no-retry-on-5xx', label: 'Gives up on the first 503 instead of retrying' },
        { slug: 'ignores-retry-after', label: 'Ignores Retry-After on a 429 and uses the normal backoff' },
        { slug: 'sleeps-after-last', label: 'Sleeps once more after the final failed attempt' },
        { slug: 'no-bearer', label: 'Sends the API key without the `Bearer ` prefix' },
        { slug: '404-throws', label: 'Throws on 404 instead of resolving to null' },
        { slug: 'trusts-body', label: 'Returns `rate` even when it is not a number' },
      ],
      hints: [
        'Make the stub scriptable: `respond(n)` gets the request number, so `(n) => (n < 3 ? { status: 503 } : { status: 200, body: { rate: 1.1 } })` fails twice, then succeeds.',
        'Pass `sleep: async (ms) => { sleeps.push(ms); }`. For `503, 503, 200` expect 3 requests and `sleeps` equal to `[100, 200]`.',
        'Giving up: a stub that always answers 500 with `maxAttempts: 3` gives 3 requests, sleeps `[100, 200]` (not three sleeps), and an error with `status: 500` and `retryable: true`.',
        'Final answers: a 401 is one request and `retryable: false`; a 404 resolves to `null`; a 429 with `retry-after: 30` sleeps `30000`.',
        'Check what was sent: `requests[0].url.searchParams.get(\'from\')`, `requests[0].headers.authorization === \'Bearer key-123\'`. And a `200` with `{ rate: \'0.91\' }` must reject.',
      ],
    },
    {
      id: 'test-int-csv-export',
      title: 'Testing a CSV export byte by byte',
      kind: 'mutation',
      subjectKind: 'node',
      xp: 85,
      minTests: 7,
      why: 'Exports feed spreadsheets and finance systems. Quoting, date ranges, money formats and formula injection are where they break, and a "200 and non-empty" test sees none of it.',
      tags: ['integration tests', 'csv', 'file export', 'security'],
      mutants: [
        { slug: 'no-quoting', label: 'Does not quote fields that contain commas, quotes or newlines' },
        { slug: 'quotes-not-doubled', label: 'Quotes a field but does not double the quotes inside it' },
        { slug: 'last-day-excluded', label: 'Leaves out orders placed on the `to` date' },
        { slug: 'cents-not-padded', label: 'Writes 5 cents as `0.5` and 1205 as `12.5`' },
        { slug: 'negative-rounded-down', label: 'Writes a refund of -250 as `-3.50`' },
        { slug: 'formula-injection', label: 'Lets a customer name starting with `=` through as a live formula' },
        { slug: 'lf-line-endings', label: 'Ends lines with `\\n` instead of `\\r\\n`' },
        { slug: 'inverted-range-ok', label: 'Answers 200 with an empty export when `from` is after `to`' },
      ],
      hints: [
        'Choose data that hits each rule: an order on `2024-01-31` late in the day, customers `Smith, Jones & Co`, `The "Best" Shop` and `=SUM(A1)`, and totals `5`, `1205` and `-250`.',
        'One exact-bytes test catches the line endings: a single order and `expect(text).toBe(\'id,customer,total,placedAt\\r\\no1,Alice,10.00,2024-01-10T09:00:00Z\\r\\n\')`.',
        'For the tricky cells, look for the exact encoded text: `a,"Smith, Jones & Co",1.00,` and `"The ""Best"" Shop"`. Or write a small CSV reader and check each row has four fields.',
        'Headers: compare `content-type.split(\';\')[0]` with `text/csv`, and match the filename with a regex that allows optional quotes: `/filename="?orders-2024-01-01-to-2024-01-31\\.csv"?/`.',
        'Range errors: no query, only `from`, `2024-1-1`, and `from=2024-02-01&to=2024-01-01` are all 400 `BAD_RANGE`.',
      ],
    },
    {
      id: 'test-int-judgement',
      title: 'What to make real, what to fake',
      kind: 'quiz',
      xp: 60,
      why: 'Integration suites become slow, flaky or useless through a handful of design choices. Recognising those choices in review saves weeks.',
      tags: ['integration tests', 'test design', 'flaky tests'],
      quiz: [
        {
          q: 'You are integration-testing a checkout endpoint. Which of these should the test run **for real**? Select all that apply.',
          options: [
            'The HTTP server, routing and middleware',
            'JSON parsing and validation of the request body',
            'The payment provider\'s live sandbox API',
            'The system clock',
          ],
          answer: [0, 1],
          explain: 'An integration test exists to exercise your own wiring: routing, middleware order, parsing, validation, serialisation. Replace things you do not own or cannot control, such as a third-party API (use a stub server or an injected fake) and time (inject a clock). A live sandbox makes the suite slow, rate-limited and flaky whenever the provider has a bad day.',
        },
        {
          q: 'Two test files each start the API with `server.listen(3000)`. Locally they pass, and in CI one fails with `EADDRINUSE`. What is the fix?',
          options: [
            'Run the test files one at a time in CI.',
            'Use ports 3000 and 3001, one per file.',
            'Retry the failing file.',
            'Listen on port `0` and read the real port from `server.address().port`.',
          ],
          answer: [3],
          explain: 'Port `0` asks the operating system for any free port, so parallel files, parallel CI jobs and a developer\'s running dev server never collide. Hardcoded ports, including one per file, break as soon as something else is running.',
        },
        {
          q: 'A suite shares one in-memory store across all its tests. `lists 2 orders` passes alone but fails when the whole file runs. What is the most likely cause, and the right fix?',
          options: [
            'The test runner is flaky. Mark the test as retryable.',
            'An earlier test left an order behind. Give each test fresh state (a new app per test, or a reset in `beforeEach`), so no test depends on another test\'s leftovers.',
            'The order of `it` blocks is random. Put the tests in alphabetical order.',
          ],
          answer: [1],
          explain: 'Order-dependent tests are a symptom of shared mutable state. Build the state each test needs inside that test (or reset it before each one). Then any test can run alone, in any order, or in parallel, and a failure points at a real bug.',
        },
        {
          q: 'A test starts a server, makes a request, and an `expect` fails before `server.close()` runs. What happens?',
          options: [
            'Nothing. The server is garbage-collected when the test ends.',
            'Only that test fails.',
            'The server keeps the process alive: later tests may hit port or state conflicts, and the runner can hang at the end. Close it in a `finally`.',
          ],
          answer: [2],
          explain: 'A listening server is an open handle, and nothing garbage-collects it. Cleanup that runs only on the happy path leaks exactly when you are already debugging a failure. `try { … } finally { await close() }`, or a helper that does it for you, makes cleanup unconditional.',
        },
        {
          q: 'Which bug can an integration test through real HTTP catch that a unit test of the handler (with `req` and `res` mocked) usually cannot?',
          options: [
            'A wrong discount calculation inside the handler.',
            'The auth middleware is registered after the route, so the route runs without it.',
            'An off-by-one in a pure pagination helper.',
            'A typo in an error message string.',
          ],
          answer: [1],
          explain: 'Middleware order, route registration, body parsing, status codes and headers only exist when a request goes through the real stack. Pure calculations are cheaper and clearer to test as units. Test each kind of bug where it is cheapest to catch.',
        },
        {
          q: 'An endpoint returns `{ id, createdAt, total, items }`. Which assertion is the most robust?',
          options: [
            '`expect(body).toEqual({ id: \'1\', createdAt: \'2024-05-01T10:00:00.000Z\', total: 1200, items })` with the real clock',
            '`expect(JSON.stringify(body)).toBe(expectedJson)`',
            '`expect(body).toMatchObject({ total: 1200, items })`, with the clock injected if `createdAt` matters, and `id` read from the response',
            '`expect(body).toBeDefined()`',
          ],
          answer: [2],
          explain: 'Assert the fields that carry the behaviour, and control or read back the ones that vary. A whole-body `toEqual` with the real clock fails every run, and a string comparison also breaks when keys are reordered. `toBeDefined` passes for any body at all.',
        },
      ],
    },
    {
      id: 'test-int-boss',
      title: 'BOSS: users, ownership and lost updates',
      kind: 'mutation',
      subjectKind: 'node',
      xp: 240,
      boss: true,
      minTests: 10,
      why: 'Authorization leaks and lost updates are invisible to a single user making one request. Only multi-user, multi-step tests find them before an attacker or a busy support team does.',
      tags: ['integration tests', 'authorization', 'optimistic concurrency', 'etag'],
      mutants: [
        { slug: 'other-owner-403', label: 'Another customer\'s order answers 403 instead of 404, which confirms it exists' },
        { slug: 'other-owner-readable', label: 'A customer can read another customer\'s order' },
        { slug: 'list-not-filtered', label: 'GET /orders shows a customer everyone\'s orders' },
        { slug: 'if-match-optional', label: 'A PATCH without If-Match is applied instead of answering 428' },
        { slug: 'if-match-not-compared', label: 'A PATCH with a stale If-Match is applied instead of answering 412' },
        { slug: 'patch-keeps-version', label: 'A PATCH does not change the ETag, so a second writer with the old ETag overwrites the first' },
        { slug: 'patch-cancelled', label: 'A cancelled order can still be patched' },
        { slug: 'customer-can-delete', label: 'The owner can delete their order (only admins may)' },
        { slug: 'admin-blind', label: 'Admins cannot see other people\'s orders' },
      ],
      hints: [
        'Every rule has a "who else?" test: Bob reading Alice\'s order, the admin reading it, Alice trying an admin-only DELETE. Write a small `place(as, user)` helper that creates an order and returns its `id` and `etag`.',
        'Visibility: Bob\'s `GET /orders/<alice\'s id>` must be `404` with the same code as `GET /orders/999`. And each user\'s `GET /orders` list must contain exactly their own ids, while the admin\'s contains both.',
        'Conditional writes: a PATCH with no `If-Match` is `428`, and the order is unchanged. A PATCH with the current ETag is `200` with a different ETag.',
        'The lost update: take the ETag from creation, PATCH once with it (200), then PATCH again with the **same old** ETag. It must be `412`, and a GET must still show the first writer\'s items.',
        'Cancel, then PATCH with the ETag the cancel returned: `409` `CONFLICT`. DELETE: the owner gets `403` and the order still exists; the admin gets `204`, and after that the order is `404`.',
      ],
    },
  ],
});
