import { loadChapter } from '../../load.ts';

const here = import.meta.dirname;

export default loadChapter(here, {
  id: 'sql-from-code-2',
  title: "Postgres from Code II",
  summary: "A migrations runner, repositories, batched inserts, transaction helpers, a safe query builder.",
  lessons: [
    {
      id: 'node-db-migrations-runner',
      title: 'A migrations runner you can trust',
      kind: 'node-db',
      xp: 95,
      why: 'Every deploy runs one; knowing how bookkeeping, ordering, checksums and transactions fit together is how you debug the day it misbehaves.',
      tags: ['migrations', 'transactions', 'ddl', 'checksums'],
      hints: [
        'Sort a copy: `[...migrations].sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0))`. Read the applied rows once into a `Map` of id → checksum.',
        'Check every checksum before applying anything: an edited, already-applied migration must stop the whole run, even the pending ones.',
        'The bookkeeping insert belongs inside the migration\'s transaction: `begin`, `conn.exec(m.sql)`, `insert into schema_migrations (id, checksum) values ($1, $2)`, `commit`.',
        'In the `catch`: `await conn.query(\'rollback\').catch(() => {})`, then `throw new MigrationFailedError(m.id, err)`. The throw ends the loop, so nothing later runs.',
      ],
    },
    {
      id: 'node-db-repository-patch',
      title: 'A repository with real PATCH semantics',
      kind: 'node-db',
      xp: 85,
      why: 'Partial updates that wipe fields, clients patching columns they should not, snake_case leaking into the UI: all fixed in the one module that maps rows to objects.',
      tags: ['repository', 'patch', 'dynamic sql', 'mapping'],
      hints: [
        'Write the mapping once: `const toUser = (row) => ({ id: row.id, email: row.email, displayName: row.display_name, … })`, and use it in every method.',
        'An allowlist maps property to column: `const PATCHABLE = { email: \'email\', displayName: \'display_name\', bio: \'bio\' }`. Check keys with `Object.hasOwn(PATCHABLE, key)`: `in` also accepts `toString` and `constructor`.',
        'Collect `[column, value]` pairs for the keys whose value is not `undefined`. If there are none, `return this.findById(id)`.',
        'Number the placeholders from the pairs: pair `i` becomes the text `display_name = $2` for `i = 1`, and so on. Push the id onto the params last and end with `where id = $N`, where N is `params.length`. Add `updated_at = now()` to the list and `returning` the columns.',
      ],
    },
    {
      id: 'node-db-batch-insert',
      title: 'Bulk inserts: batches, unnest and one transaction',
      kind: 'node-db',
      xp: 90,
      why: 'Imports and backfills that insert row by row spend their time on round trips, and the VALUES-list fix breaks at 65,535 parameters on the busiest day.',
      tags: ['batching', 'bulk insert', 'unnest', 'transactions'],
      testTimeoutMs: 20000,
      hints: [
        'Loop over chunks: `for (let start = 0; start < events.length; start += batchSize) { const chunk = events.slice(start, start + batchSize); … }`, all between one `begin` and one `commit`.',
        'One array per column: `[chunk.map((e) => e.externalId), chunk.map((e) => e.kind), chunk.map((e) => e.occurredAt.toISOString()), chunk.map((e) => JSON.stringify(e.payload))]`.',
        'The statement: `insert into events (external_id, kind, occurred_at, payload) select * from unnest($1::text[], $2::text[], $3::timestamptz[], $4::jsonb[]) returning id, external_id`.',
        'Put each returned row into a `Map` of `external_id` → `id`, and finish with `events.map((e) => map.get(e.externalId))`. Roll back and rethrow in the `catch`.',
      ],
    },
    {
      id: 'node-db-nested-transactions',
      title: 'Nested transactions are savepoints',
      kind: 'node-db',
      xp: 95,
      why: 'Composable services call each other inside transactions; without savepoints an inner COMMIT ends the outer one early and a caught error poisons the rest.',
      tags: ['transactions', 'savepoints', 'error handling', 'composition'],
      hints: [
        'Keep `const depthOf = new WeakMap()` at module level. Read `const depth = depthOf.get(conn) ?? 0` on entry; depth 0 means outermost.',
        'Outermost uses `begin` / `commit` / `rollback`; nested uses `savepoint sp_${depth}` / `release savepoint sp_${depth}` / `rollback to savepoint sp_${depth}`.',
        'Set `depthOf.set(conn, depth + 1)` after opening, and put `depthOf.set(conn, depth)` in a `finally`, so an error cannot leave the connection looking nested.',
        'In the nested `catch`: send `rollback to savepoint sp_N` for this level\'s name, then `release savepoint sp_N`, then `throw err`. The caller can now catch the error and keep using the transaction.',
      ],
    },
    {
      id: 'node-db-filter-builder',
      title: 'A safe WHERE builder for list endpoints',
      kind: 'node-db',
      xp: 95,
      why: 'Every list endpoint turns query-string filters into SQL; placeholder drift, `= NULL` and wildcard leaks are the bugs that ship when it is done by hand.',
      tags: ['dynamic sql', 'parameters', 'null', 'validation'],
      hints: [
        'Make a table: `const FILTERS = { status(v) { … }, assigneeId(v) { … }, … }`. Each entry validates its value and returns the condition. Look keys up with `Object.hasOwn(FILTERS, key)`.',
        'Number placeholders from the parameter array: push the value first, then use `$${params.length}` in the condition. Skipped filters then never leave a gap.',
        '`null` needs a condition with no parameter: `assignee_id is null`. A status list is one parameter: `status = any($1::text[])`, and a single status can be wrapped into a one-element list.',
        'Literal, case-insensitive search without LIKE: `strpos(lower(title), lower($n)) > 0`. Tags: `tags @> $n::text[]`.',
        'In `listTickets`, validate `limit`, push it last, and end the query with `order by created_at desc, id desc limit $N` where N is `params.length`. Map `assignee_id` and `created_at` to camelCase.',
      ],
    },
    {
      id: 'node-db-error-mapping',
      title: 'Let constraints decide, then translate their errors',
      kind: 'node-db',
      xp: 80,
      why: 'Check-then-insert races under load; the constraint is the real check, and mapping its error by name is how a duplicate becomes a 409 instead of a 500.',
      tags: ['error handling', 'constraints', 'race conditions', 'sqlstate'],
      hints: [
        'Read `err.code` and `err.constraint`. The message is for humans and changes between Postgres versions and languages.',
        'A nested table reads well: `const BY_CODE = { \'23505\': { users_email_lower_key: () => new ConflictError(\'email\'), … }, \'23503\': { … }, \'23514\': { … } }`.',
        'Look up with `Object.hasOwn` at both levels, so a constraint named `constructor` is not found. Unknown → `return err`.',
        'Set `mapped.cause = err` (or pass `{ cause: err }` to the constructor). In the services: `try { … } catch (err) { throw translateDbError(err); }` around the insert.',
      ],
    },
    {
      id: 'node-db-batched-backfill',
      title: 'Backfill a big table in small transactions',
      kind: 'node-db',
      xp: 90,
      why: 'Every new column on a large table needs a backfill, and the one-statement version locks, bloats and lags replicas; batched, resumable loops are the standard fix.',
      tags: ['backfill', 'batching', 'keyset', 'migrations'],
      hints: [
        'No `BEGIN`: a single statement already runs in its own transaction and commits when it finishes. That is exactly the unit you want per batch.',
        'Pick the batch in a subquery: `update customers set email_normalized = lower(btrim(email)) where id in (select id from customers where id > $1 and email_normalized is null order by id limit $2) returning id`.',
        'Keep the cursor in JavaScript: after each batch, `afterId` becomes the largest returned id. An empty result means you are done.',
        'Count `rows.length` into `updated`, and call `await sleep(pauseMs)` at the top of every iteration except the first, only when `pauseMs > 0`.',
      ],
    },
    {
      id: 'node-db-pooling-judgement',
      title: 'Connection pools: the failures that are not queries',
      kind: 'quiz',
      xp: 70,
      why: 'Pool exhaustion, split transactions and idle-in-transaction sessions cause as many outages as slow queries, and they are all decided in application code.',
      tags: ['connection pool', 'transactions', 'pgbouncer', 'timeouts'],
      quiz: [
        {
          q: 'A transfer function does `await pool.query(\'BEGIN\')`, two `await pool.query(\'UPDATE …\')` calls, and `await pool.query(\'COMMIT\')`. It passes every test. What happens in production?',
          options: [
            'It works: the pool keeps a connection per request for its whole duration',
            'Each call may run on a different connection, so the updates can run outside the transaction, and a BEGIN may be left open on a connection that goes back to the pool',
            'Postgres rejects the second UPDATE because the BEGIN came from a different client',
            'It works but is slow, because each statement waits for a free connection',
          ],
          answer: [1],
          explain: '`pool.query` borrows a connection for one statement. Under load, BEGIN, the UPDATEs and COMMIT land on whatever connections are idle; the UPDATEs autocommit on their own, and a stray BEGIN leaves some other request\'s statements inside a transaction nobody commits. Tests pass because a quiet pool hands out the same connection each time. Use `const client = await pool.connect()` for every statement of the transaction, and `client.release()` in a `finally`.',
        },
        {
          q: 'After a deploy, the API slowly stops responding: requests hang, then fail with "timeout exceeded when trying to connect". `pg_stat_activity` shows only 10 connections from the app, all `idle`. What is the likeliest cause?',
          options: [
            'The database has hit `max_connections`',
            'A slow query is holding locks',
            'The pool\'s `max` is too small for the traffic',
            'A code path checks out a client with `pool.connect()` and does not release it when it throws, so the pool leaks one client per error until none are left',
          ],
          answer: [3],
          explain: 'Idle connections on the server and waiting callers in the app means the app\'s pool believes every client is in use: they were checked out and never released. The classic path is an early `return` or a `throw` between `connect()` and `release()`. Always release in `finally`, or use a helper that owns checkout and release (like the transaction helpers in this chapter). The server is nowhere near its limit, and a bigger pool would only delay the same failure.',
        },
        {
          q: 'You run 40 instances of the API, each with a pool of `max: 20`. Postgres has `max_connections = 200` on an 8-core server. Which statements are true? Select all that apply.',
          options: [
            'At peak the instances can ask for 800 connections, and requests start failing with "too many clients already" well before that',
            'Raising `max_connections` to 1000 is the right fix, because more connections means more throughput',
            'Much smaller pools (say 5 per instance), or a PgBouncer in front of the database, would likely serve the same traffic faster',
            'Pool size does not matter as long as each request releases its client',
          ],
          answer: [0, 2],
          explain: 'Pool sizes add up across instances, and autoscaling multiplies them. Each Postgres connection is a process; past a few times the core count, extra active connections contend for CPU, locks and memory and total throughput falls. The usual fix is fewer, busier connections: small per-instance pools, or a pooler like PgBouncer multiplexing many app connections onto a few server connections. Releasing clients promptly is necessary but does not change the arithmetic.',
        },
        {
          q: '`pg_stat_activity` shows several sessions in state `idle in transaction` for minutes, and other requests are waiting on their row locks. What is the most likely cause in the application?',
          options: [
            'Code that opens a transaction and then awaits something slow — an HTTP call, a queue publish, a file upload — before committing',
            'Autovacuum running on the same tables',
            'The pool keeping idle connections open between requests',
            'A missing index making the transaction\'s queries slow',
          ],
          answer: [0],
          explain: '"Idle in transaction" means the session is doing nothing *inside* an open transaction: the database is waiting for the application. Every lock the transaction took is held while your code waits for a payment API. Do slow I/O before BEGIN or after COMMIT, and set `idle_in_transaction_session_timeout` so a forgotten transaction is killed instead of blocking everyone. Plain idle pooled connections hold no locks; a slow query shows as `active`.',
        },
        {
          q: 'You put PgBouncer in transaction mode in front of the database. Which of these application patterns stop working reliably? Select all that apply.',
          options: [
            '`SET search_path = tenant_42` once per connection, then unqualified queries in later transactions',
            'A session-level `pg_advisory_lock` taken in one transaction and released in a later one',
            'A plain `BEGIN … COMMIT` block with several statements',
            '`LISTEN new_orders` on a connection that then waits for notifications',
          ],
          answer: [0, 1, 3],
          explain: 'In transaction mode, each transaction may run on a different server connection, so anything stored in a session — `SET` (use `SET LOCAL` inside the transaction), session advisory locks (use the `_xact_` variants), `LISTEN` (use a direct connection), temporary tables across transactions — may be on a connection you no longer have. A normal transaction is exactly the unit PgBouncer lends out, so it is fine.',
        },
        {
          q: 'A monthly report query sometimes runs for ten minutes, and while it runs the API\'s p99 latency triples. Which change fixes the cause rather than the symptom?',
          options: [
            'Double the API\'s pool size so there are connections left for normal requests',
            'Run reports under a separate database role (and pool, ideally against a read replica) whose `statement_timeout` and resources are set for reports, and give the API role a short `statement_timeout`',
            'Add `LIMIT 1000` to the report',
            'Retry API requests that take more than a second',
          ],
          answer: [1],
          explain: 'The report competes with the API for connections, CPU and I/O. Separating workloads by role and pool (and moving analytics to a replica) stops one from starving the other, and a per-role `statement_timeout` (`ALTER ROLE api SET statement_timeout = \'5s\'`) makes a runaway API query fail fast instead of piling up. A bigger pool adds contention; retries add load; a LIMIT changes the report\'s answer.',
        },
      ],
    },
    {
      id: 'node-db-order-service-boss',
      title: 'Boss: an order service that scales with the order',
      kind: 'node-db',
      xp: 220,
      boss: true,
      why: 'Checkout is where transactions, batching, error mapping and idempotency all meet, and where getting any one wrong costs money.',
      tags: ['transactions', 'batching', 'error handling', 'idempotency'],
      hints: [
        'Write one private helper for the transaction (`begin`, `await work()`, `commit`; `rollback` and rethrow in the `catch`) and one that reads an order with its lines (a join to `products` for the sku, ordered by `line_no`) and maps it.',
        'Inside the transaction: replay first (`select id from orders where idempotency_key = $1`), then `select id, sku, price_cents, stock from products where sku = any($1::text[]) order by id for update`, into a `Map` by sku.',
        'Decide both errors in JavaScript from that map: skus missing from it, then lines whose `qty` exceeds `stock`. Sort each list before throwing.',
        'Wrap only the orders insert in `try { … } catch (err) { if (err.code === \'23503\' && err.constraint === \'orders_customer_id_fkey\') throw new NotFoundError(\'customer\', { cause: err }); throw err; }`.',
        'Batch with arrays: `insert into order_lines (…) select $1, x.line_no, x.product_id, x.qty, x.price from unnest($2::int[], $3::int[], $4::int[], $5::int[]) as x(line_no, product_id, qty, price)`, and `update products p set stock = p.stock - x.qty from unnest($1::int[], $2::int[]) as x(product_id, qty) where p.id = x.product_id`. Cancel restocks only if `update orders set status = \'cancelled\' where id = $1 and status = \'placed\'` changed a row.',
      ],
    },
  ],
});
