import { loadChapter } from '../../load.ts';

const here = import.meta.dirname;

export default loadChapter(here, {
  id: 'node-input-security',
  title: "Defending the Input Boundary",
  summary: "Path traversal, SSRF allowlists, upload validation, header injection, per-user limits.",
  lessons: [
    {
      id: 'sec-path-traversal',
      title: 'Serving files without path traversal',
      kind: 'node',
      xp: 85,
      why: 'Any endpoint that maps a request to a file path is one encoded `../` away from serving your secrets; decode-once, resolve and `path.relative` is the check that holds.',
      tags: ['security', 'filesystem', 'http'],
      hints: [
        'Order matters: `decodeURIComponent` once (inside try/catch), reject `\\0`, then `path.resolve(root, decoded)`. Checking for `..` before decoding misses `%2e%2e%2f`.',
        'Do not compare strings with `startsWith(root)`: `/srv/files-private` starts with `/srv/files`. Ask `path.relative(root, full)` instead.',
        'Inside means: `rel !== \'\'`, `rel !== \'..\'`, `!rel.startsWith(\'..\' + path.sep)` and `!path.isAbsolute(rel)`. Testing `rel.startsWith(\'..\')` alone wrongly rejects a file called `..notes.txt`.',
        'In the server, slice the raw `req.url` (before `?`) after `/files/` — do not build a `URL` and use `pathname`, which would already have normalised the dots away and hidden the attack from your own check.',
        'For symlinks: `stat` for "is it a file", then compare `await fs.promises.realpath(full)` with `await fs.promises.realpath(root)` using the same inside-test. Stream with `pipeline(fs.createReadStream(real), res)`.',
      ],
    },
    {
      id: 'sec-open-redirect',
      title: 'Redirects that cannot be pointed elsewhere',
      kind: 'node',
      xp: 80,
      why: '`?next=` and `?returnTo=` are on every login page, and an open redirect there turns your trusted domain into the first hop of a phishing link.',
      tags: ['security', 'urls', 'http', 'phishing'],
      hints: [
        'Start with the cheap rejections: not a string, longer than 2048, or `/[\\x00-\\x1f\\x7f]/.test(next)`. That regex is what catches the tab trick.',
        'For relative paths, check `next[1] !== \'/\' && next[1] !== \'\\\\\'` before parsing — both mean "another host" to a browser.',
        'Parse relative ones with `new URL(next, \'http://base.invalid\')` and require `url.origin === \'http://base.invalid\'`; then return `url.pathname + url.search + url.hash`, not `next`.',
        'For absolute ones, wrap `new URL(next)` in try/catch, then check `url.protocol`, `url.username === \'\' && url.password === \'\'`, and `allowedOrigins.includes(url.origin)` — an exact comparison of the parsed origin, never `startsWith` on the string.',
      ],
    },
    {
      id: 'sec-content-disposition',
      title: 'File names in headers: Content-Disposition done right',
      kind: 'node',
      xp: 80,
      why: 'Every download endpoint puts a user-chosen file name into a response header; quoting, CR/LF and non-ASCII names are where it breaks.',
      tags: ['security', 'http', 'headers', 'unicode'],
      hints: [
        'Clean first: `name.slice(Math.max(name.lastIndexOf(\'/\'), name.lastIndexOf(\'\\\\\')) + 1)`, then `.replace(/[\\x00-\\x1f\\x7f]/g, \'\')`, `.trim()`, the `\'download\'` fallback, and `.toWellFormed()`.',
        'Build the fallback with `for (const ch of cleaned)` — that iterates code points, so `📄` is one character. Keep `ch` only if its code point is 0x20–0x7e and it is not `"`, `\\` or `%`.',
        'Add `filename*` only when `fallback !== cleaned`. `encodeURIComponent` leaves `\'`, `(`, `)` and `*` unencoded; follow it with `.replace(/[\'()*]/g, (c) => \'%\' + c.charCodeAt(0).toString(16).toUpperCase())`.',
        'In the server, look the id up in the `Map` and send `writeHead(200, { \'content-type\': file.type, \'content-disposition\': contentDisposition(file.name), \'x-content-type-options\': \'nosniff\' })`.',
      ],
    },
    {
      id: 'sec-html-escaping',
      title: 'Escape on output: a safe html`` template',
      kind: 'node',
      xp: 85,
      why: 'Server-rendered HTML — emails, admin pages, error pages — has no React to escape for you; a tagged template makes escaping the default and raw HTML the exception you can grep for.',
      tags: ['security', 'xss', 'templates', 'urls'],
      hints: [
        'A tag receives `(strings, ...values)` with `strings.length === values.length + 1`. Start from `strings[0]` and append `render(values[i]) + strings[i + 1]` for each value.',
        'Write `render(value)` with the rules in order: `instanceof SafeHtml` → `value.value`; `Array.isArray` → `value.map(render).join(\'\')`; `null`/`undefined`/`false` → `\'\'`; otherwise escape `String(value)`. Check for `false` explicitly — `!value` would also drop `0`.',
        'Escape with one regex and a lookup: `text.replace(/[&<>"\']/g, (c) => MAP[c])`. A single pass cannot double-escape, so the `&` ordering problem disappears.',
        '`safeUrl`: inside try/catch, `new URL(url, \'http://base.invalid\').protocol` must be in `[\'http:\', \'https:\', \'mailto:\']`. The parser strips the tab in `java\\tscript:` and lowercases the scheme for you; a regex would not.',
      ],
    },
    {
      id: 'sec-ssrf-guard',
      title: 'Fetching user-supplied URLs without SSRF',
      kind: 'node',
      xp: 100,
      why: 'Webhooks, link previews and imports make your server fetch URLs a user chose; without an address check, that is a request from inside your network to your cloud metadata service.',
      tags: ['security', 'ssrf', 'networking', 'dns'],
      hints: [
        'Use `net.BlockList`: create one at module level, `addSubnet(network, prefix, \'ipv4\' | \'ipv6\')` for each row of the table, and in `isPublicAddress` return `!blocked.check(ip, version === 4 ? \'ipv4\' : \'ipv6\')` after `net.isIP(ip)` says it is an address.',
        'Always take the host from the parsed `URL`: `url.hostname` is already normalised (`0x7f.1` → `127.0.0.1`). For IPv6 it keeps the brackets, so strip them before `net.isIP`.',
        'The effective port is `url.port === \'\' ? (https ? 443 : 80) : Number(url.port)` — `URL` hides the default port, so `https://x:443/` has `port === \'\'`.',
        'Resolve only non-literal hosts, inside try/catch; treat a rejection or an empty array as `dns-failed`. Then `addresses.every((a) => isPublicAddress(a.address))` — checking only the first answer lets a name with one public and one private address through.',
      ],
    },
    {
      id: 'sec-upload-validation',
      title: 'Validating uploads by their bytes',
      kind: 'node',
      xp: 90,
      why: 'Upload endpoints are where stored XSS and web shells get in; size caps, magic-byte sniffing and random storage names are the standard defence.',
      tags: ['security', 'uploads', 'binary data', 'validation'],
      hints: [
        'Describe the formats as data — `{ type, exts, magic }` — and write one `startsWithAt(bytes, offset, expected)` helper. WEBP needs two checks (offset 0 and offset 8); GIF has two alternatives.',
        'Follow the order: `bytes instanceof Uint8Array && bytes.length > 0`, then size, then sniff and `allowed.includes(format.type)`.',
        'Normalise the declared type with `split(\';\')[0].trim().toLowerCase()`, and let `\'\'` and `application/octet-stream` through as "unknown".',
        'The extension comes from the cleaned display name via `lastIndexOf(\'.\')`, so `shell.php.png` is `png` (fine — you store it as `<random>.png` anyway) and `photo.png.exe` is `exe`.',
        '`storageName` is `crypto.randomBytes(16).toString(\'hex\') + \'.\' + format.exts[0]` — the canonical extension from the bytes, never the user\'s.',
      ],
    },
    {
      id: 'sec-user-limits',
      title: 'Per-user concurrency and quotas',
      kind: 'node',
      xp: 90,
      why: 'Global rate limits do not stop one account hogging workers or storage; per-user slots and quotas need reservations and release-once semantics to be correct under concurrency.',
      tags: ['security', 'concurrency', 'quotas', 'resource limits'],
      hints: [
        'Keep one record per user: `{ inFlight, reserved, day, used }`. A helper `usedToday(s)` compares `s.day` with today\'s `new Date(now()).toISOString().slice(0, 10)` and resets `used` when they differ.',
        'The quota check is `usedToday(s) + s.reserved + bytes > bytesPerDay`. Leaving out `reserved` is exactly the concurrent-overshoot bug.',
        'Return a closure from `acquire` with its own `let released = false`, and capture the acquisition\'s `day` in it too. The first call flips the flag; later calls return `false` immediately.',
        'In `release`, always give back the slot and the reservation; add to `used` only if `ok` and — after rolling over — `s.day` is still the day the acquisition was made.',
      ],
    },
    {
      id: 'sec-input-quiz',
      title: 'Judgement calls at the input boundary',
      kind: 'quiz',
      xp: 70,
      why: 'Validation versus escaping, what CORS actually protects and why fetch must not follow redirects blindly are reasoning a reviewer expects from you, not a library.',
      tags: ['security', 'validation', 'http'],
      quiz: [
        {
          q: 'A comment field is shown on a web page, included in a CSV export and sent in a plain-text email. Where should you defend against XSS?',
          options: [
            'Strip `<` and `>` from the comment when it is submitted, so it is safe everywhere',
            'Escape for HTML when rendering the page; the CSV and email each get their own output encoding',
            'Store it base64-encoded and decode it only in the browser',
            'Reject any comment containing `<script`',
          ],
          answer: [1],
          explain: 'Escaping depends on the output context, which is unknown at input time: stripping `<` mangles legitimate text ("3 < 5") and still misses attribute or URL contexts, and the CSV needs formula-injection handling (`=HYPERLINK(...)`) that HTML escaping does not provide. Denylisting `<script` misses `<img onerror>`. Validate input for *shape* (length, type); encode on *output* for the context.',
        },
        {
          q: 'Your API sets strict CORS: only `https://app.example.com` may read responses. What does that protect against?',
          options: [
            'Cross-site request forgery: other sites can no longer POST to the API',
            'Server-side request forgery from your own backend',
            'Other origins\' JavaScript reading responses in a user\'s browser — nothing else',
            'Attackers calling the API with `curl`',
          ],
          answer: [2],
          explain: 'CORS is a browser rule about *reading* cross-origin responses. A cross-site form POST is still sent (with cookies, subject to SameSite) — the attacker just cannot read the result, which CSRF does not need. `curl` and servers ignore CORS entirely. CSRF needs SameSite cookies, tokens or Origin checks; SSRF needs outbound controls.',
        },
        {
          q: 'Your webhook sender validates the URL with an SSRF guard, then calls `fetch(url)`. What is still wrong?',
          options: [
            'Nothing, the URL was validated',
            '`fetch` does not support HTTPS in Node',
            'The request should use POST instead of GET',
            '`fetch` follows redirects by default, so a public URL that answers `302 Location: http://169.254.169.254/` is fetched anyway',
          ],
          answer: [3],
          explain: 'Each redirect hop is a new URL the user effectively controls. Use `redirect: \'manual\'` and run every `Location` through the same check (with a hop limit), and connect to the address the check approved so DNS cannot change its answer in between. Some teams route all user-URL fetches through an egress proxy that enforces this centrally.',
        },
        {
          q: 'A signup form validates emails with `/^([a-zA-Z0-9]+)*@example\\.com$/`. Under load testing, one request pins the CPU for 30 seconds. Why, and what is the fix?',
          options: [
            'Nested quantifiers backtrack exponentially on a near-miss like `aaaa…a!`; cap the input length first and use a regex without nested repetition (or a linear engine such as RE2)',
            'The regex is compiled on every request; hoist it to module scope',
            'JavaScript regexes are slow; use `indexOf` instead',
            'The email is too long for Postgres; add a column length',
          ],
          answer: [0],
          explain: 'This is ReDoS. `(x+)*` gives the engine exponentially many ways to split the input, and on a string that almost matches it tries them all — on the one thread that serves every other request. A length cap (emails are at most 254 characters) bounds the damage; rewriting to `^[a-zA-Z0-9]+@…` removes it. Compilation cost is trivial by comparison.',
        },
        {
          q: 'Which of these are allowlists — the approach that fails safe when something new appears? (Select all that apply.)',
          options: [
            'Accepting uploads only when their bytes are PNG, JPEG or PDF',
            'Rejecting file names that end in `.exe`, `.php` or `.js`',
            'Allowing redirect targets only to origins in a configured list',
            'Blocking outbound requests to `localhost` and `127.0.0.1`',
          ],
          answer: [0, 2],
          explain: 'An allowlist names what is permitted, so an unforeseen input (`.phtml`, `.svg`, `[::1]`, `0x7f.1`) is rejected by default. Denylists name what is forbidden and silently permit everything nobody thought of. SSRF protection is the one place you are forced into a denylist of address *ranges* — which is why it has to be applied to resolved addresses, not host strings.',
        },
        {
          q: 'A handler does `const { role, ...profile } = await req.json(); await db.users.update(id, req.body)`. The code review flags it. What is the underlying bug?',
          options: [
            'Mass assignment: the whole client object reaches the database, so a client can set `role`, `isAdmin` or `ownerId`',
            'The destructuring is slower than reading the fields one by one',
            'It should use PATCH semantics instead of PUT',
            '`req.json()` is not available in Node',
          ],
          answer: [0],
          explain: 'Destructuring `role` out does nothing when the original object is what gets written. Build the update from an explicit list of editable fields, validated, and set server-owned fields (`ownerId`, `role`) from the server\'s own state. The same rule applies to ORMs that accept a whole object.',
        },
      ],
    },
    {
      id: 'sec-attachments-boss',
      title: 'BOSS: an attachments service that holds the line',
      kind: 'node',
      xp: 240,
      boss: true,
      why: 'File upload and download is where every input-boundary defence — size, type, name, per-user limits, ownership and safe serving — has to work at once, in one request path.',
      tags: ['security', 'uploads', 'http', 'resource limits'],
      hints: [
        'Structure it as `route(req, res)` wrapped in one try/catch, with an `HttpError(status, code)` class for every rejection. Match the two path shapes first (404 otherwise), then authenticate, then dispatch on method.',
        'For uploads, do all the header checks (411, 413, 400, 429, quota) **before** touching the body. Returning without reading is what makes `too-large` answer instantly.',
        'Keep a per-user `{ stored, reserved, inFlight }`. Reserve (`inFlight++`, `reserved += length`) right before reading the body, and undo both in a `finally` around read-validate-store: that one block covers success, 415s and a client that disconnects mid-upload (the `for await` over `req` rejects).',
        'Reuse the earlier lessons nearly verbatim: the magic-byte table (PNG, JPEG, PDF), the display-name cleaner, and `contentDisposition`. Validation failures are `HttpError(415, code)`, except an empty body (400).',
        'For `GET`/`DELETE /attachments/<id>`, one helper `ownFile(id, userId)` that throws 404 for both unknown and not-yours. `DELETE` also subtracts the size from `stored`.',
      ],
    },
  ],
});
