import { loadChapter } from '../../load.ts';

const here = import.meta.dirname;

export default loadChapter(here, {
  id: 'node-http-advanced',
  title: "HTTP, Advanced",
  summary: "Content negotiation, ETags and conditional requests, Range, compression, CORS, Cache-Control.",
  lessons: [
    {
      id: 'node-content-negotiation',
      title: 'Content negotiation with Accept and q-values',
      kind: 'node',
      xp: 80,
      why: 'One endpoint serving JSON and CSV is routine. Getting q=0, wildcards and Vary wrong serves the wrong format, or caches one format for everyone.',
      tags: ['http', 'headers', 'caching'],
      testTimeoutMs: 20000,
      hints: [
        'Parse first, decide second: turn the header into a list of `{ type, subtype, q }` and only then look at `available`.',
        'Split on `,`, then each part on `;`, trimming everything. The first piece is the range; among the rest, the one whose key is `q` sets the quality. Lower-case the range.',
        'For each available type, walk all ranges and remember the one with the highest **specificity** (exact 3, `type/*` 2, `*/*` 1) — not the highest q. That range\'s q is the type\'s quality.',
        'Keep the best candidate with a strict `q > bestQ`, starting from `bestQ = 0`: that both excludes q=0 and lets the earlier type win ties.',
        'In the handler, set `vary: \'Accept\'` on the 200s and the 406 alike, and pass `req.headers.accept` straight to `negotiate`.',
      ],
    },
    {
      id: 'node-last-modified',
      title: 'Last-Modified and If-Modified-Since, by the RFC',
      kind: 'node',
      xp: 80,
      why: 'Date-based revalidation silently never fires when timestamps have milliseconds, and mixing it with ETags wrongly serves stale data. Both show up in every API with caching.',
      tags: ['http', 'caching', 'conditional requests'],
      testTimeoutMs: 20000,
      hints: [
        'Compute the validators once: `etag` from a hash of the body wrapped in double quotes, `last-modified` from `doc.updatedAt.toUTCString()`. Send them on both 200 and 304.',
        'Branch on `If-None-Match` **presence**, not on whether it matched: when the header exists, its answer is final.',
        'For the date: `const since = Date.parse(header)`; ignore it if `Number.isNaN(since)` or `since > now()`.',
        'Truncate before comparing: `Math.floor(updatedAt.getTime() / 1000) * 1000 <= since` means "not modified".',
        'For `HEAD`, write the same status and headers and call `res.end()` without the body.',
      ],
    },
    {
      id: 'node-range-requests',
      title: 'Range requests: 206, 416 and If-Range',
      kind: 'node',
      xp: 85,
      why: 'Media, large downloads and PDF viewers depend on byte ranges. Off-by-one ends and ignoring If-Range produce corrupt resumed downloads that nobody can reproduce.',
      tags: ['http', 'files', 'headers'],
      testTimeoutMs: 20000,
      hints: [
        'Match the part after `bytes=` against one strict pattern, `/^(\\d*)-(\\d*)$/`. Anything that fails it — including a comma — is `null`.',
        'Handle the suffix form (`-N`, empty start) separately: it means the **last** N bytes, `start = max(0, size - N)`.',
        'For `a-b` and `a-`: a present end smaller than the start is `null`; then `start >= size` is `\'unsatisfiable\'`; then clamp the end with `Math.min(end, size - 1)`. Treat a missing end as `Infinity` so the checks stay in that order.',
        'Ranges are inclusive: send `content.subarray(start, end + 1)` and `content-length: end - start + 1`.',
        'For `If-Range`, compare the raw header string to your ETag with `===`; if it is present and different, pretend there was no `Range` header.',
      ],
    },
    {
      id: 'node-compression',
      title: 'Response compression and the Vary header',
      kind: 'node',
      xp: 85,
      why: 'Compression is a big, cheap win — until a CDN serves gzip to a client that cannot read it, or an overwritten Vary breaks CORS caching.',
      tags: ['http', 'zlib', 'caching'],
      testTimeoutMs: 20000,
      hints: [
        'In `pickEncoding`, build a `Map` from coding to q first. Then `quality(c) = map.get(c) ?? map.get(\'*\') ?? 0` — an explicit `q=0` stays 0 and is not replaced by `*`.',
        'Return `identity` when both are `<= 0`, else `br >= gz ? \'br\' : \'gzip\'`.',
        'Measure the body in bytes: turn a string into `Buffer.from(body)` first and use `.length` for both the threshold and `content-length`.',
        'For `Vary`, read `res.getHeader(\'vary\')`, split it on commas, and only append `, Accept-Encoding` when no lower-cased entry already equals `accept-encoding`.',
        'After compressing, set `content-encoding` and set `content-length` from the **compressed** buffer, then `res.writeHead(status)` and `res.end(data)`.',
      ],
    },
    {
      id: 'node-content-disposition',
      title: 'Download file names that survive real users',
      kind: 'node',
      xp: 70,
      why: 'Every app with exports or uploads sets Content-Disposition from a user-controlled name. Non-ASCII names garble, and unchecked control characters crash the request or inject headers.',
      tags: ['http', 'headers', 'security'],
      testTimeoutMs: 20000,
      hints: [
        'Clean first: `String(filename).split(/[/\\\\]/).pop()`, then remove `[\\u0000-\\u001f\\u007f]` with a regex, then `trim()`, then default to `download`.',
        'Iterate with `[...name]`, not `name.split(\'\')` or indexes: spread walks code points, so an emoji is one character.',
        'One predicate does double duty: "printable ASCII and not `"`, `\\` or `%`" decides both whether you need `filename*` and which characters become `_` in the fallback.',
        '`encodeURIComponent(name).replace(/[\'()*]/g, (c) => \'%\' + c.charCodeAt(0).toString(16).toUpperCase())` gives the RFC 8187 encoding.',
      ],
    },
    {
      id: 'node-trust-proxy',
      title: 'Client IP and protocol behind proxies',
      kind: 'node',
      xp: 85,
      why: 'Rate limits, audit logs, geo rules and secure-cookie decisions all depend on the client IP and scheme. Reading X-Forwarded-For naively lets any client choose its own IP.',
      tags: ['http', 'security', 'proxies'],
      testTimeoutMs: 20000,
      hints: [
        'Build a `net.BlockList` once in `createClientInfo`: `addAddress(ip)` for plain entries, `addSubnet(network, Number(prefix))` for `a.b.c.d/n`. `list.check(ip)` then answers "is this one of ours?".',
        'Only IPv4 can be trusted here: guard with `net.isIPv4(ip) && list.check(ip)`. Normalise first — strip a leading `::ffff:` when what follows is IPv4.',
        'Walk from the right: `for (let i = hops.length - 1; i >= 0 && isTrusted(ip); i--) { … ip = hops[i]; }`, starting with `ip` = the socket address. The loop stops by itself at the first untrusted address.',
        'Inside the loop, `break` before assigning when `net.isIP(hops[i]) === 0`, so garbage never becomes the answer.',
        'Protocol: only when the socket peer is trusted, take `proto.split(\',\')[0].trim().toLowerCase()` and accept it if it is `http` or `https`; otherwise fall back to `req.socket.encrypted`.',
      ],
    },
    {
      id: 'node-safe-redirects',
      title: 'Redirects without open redirects',
      kind: 'node',
      xp: 80,
      why: 'Post-login `next` parameters and URL canonicalisation are in every web app, and both are classic open-redirect bugs that phishing campaigns rely on.',
      tags: ['http', 'security', 'redirects'],
      testTimeoutMs: 20000,
      hints: [
        'Do not try to list every dangerous pattern. Let the WHATWG parser decide: `new URL(value, \'http://app.internal\')`, then compare `url.origin`.',
        'Check for control characters before parsing: `/[\\u0000-\\u001f\\u007f]/.test(value)`. The parser strips tabs and newlines, which is exactly what makes them dangerous.',
        'Return `url.pathname + url.search + url.hash` — the resolved form, with dot segments already normalised.',
        'For the login `next`, read it with `new URLSearchParams(query).get(\'next\')` so it is decoded once, then pass it through `safeNext`.',
        'Canonical path: `\'/\' + path.replace(/\\/+$/, \'\').replace(/^\\/+/, \'\')`, then add the original query. `301` for `GET`/`HEAD`, `308` otherwise.',
      ],
    },
    {
      id: 'node-http-advanced-quiz',
      title: 'HTTP behind real infrastructure',
      kind: 'quiz',
      xp: 60,
      why: 'Load balancers, CDNs and browser caches act on your headers literally. Knowing what they do with them separates a service that works in staging from one that works in production.',
      tags: ['http', 'caching', 'infrastructure'],
      quiz: [
        {
          q: 'A Node service behind an AWS ALB (idle timeout 60 s) returns occasional `502 Bad Gateway` errors under light, bursty traffic, with nothing in the app logs. What is the likely cause and fix?',
          options: [
            'The app is too slow; add more instances.',
            'Node closes idle keep-alive connections after `server.keepAliveTimeout` (5 s by default) while the ALB still considers them open and sends the next request into a closing socket. Set `keepAliveTimeout` above the ALB\'s idle timeout (e.g. 65 s) and `headersTimeout` above that.',
            'The ALB does not support keep-alive; disable it with `Connection: close` on every response.',
            'Raise `server.requestTimeout` to 0 so requests never time out.',
          ],
          answer: [1],
          explain: 'An idle connection must be closed by the **load balancer** first, never by the backend. If Node closes it first, there is a window where the ALB reuses a socket Node is tearing down, and the ALB reports 502 without the request ever reaching your handler — hence empty logs. The rule: backend keep-alive timeout > proxy idle timeout. Disabling keep-alive "works" at a large cost in connection setup.',
        },
        {
          q: '`GET /api/me` returns the logged-in user\'s profile and sends `Cache-Control: public, max-age=60` "to take load off the database". A CDN sits in front. What happens?',
          options: [
            'Nothing bad: the CDN keys its cache on the cookie automatically.',
            'Only the browser caches it, since CDNs never cache API responses.',
            'The CDN may cache one user\'s profile and serve it to other users for a minute. Per-user responses need `private` (browser only) or `no-store`.',
            'The response is not cached because it has a `Set-Cookie` header.',
          ],
          answer: [2],
          explain: '`public` explicitly allows shared caches to store the response, and most CDNs do not include cookies in the cache key unless told to. This exact mistake has leaked account pages at real companies. Use `private, max-age=60` if the browser may reuse it, or `no-store` for sensitive data. (Some CDNs skip responses with `Set-Cookie` by default; relying on that is not a policy.)',
        },
        {
          q: 'Which statements about `Cache-Control: no-cache` are true? Select all that apply.',
          options: [
            'The response may be stored, but must be revalidated with the server before every use.',
            'It forbids storing the response anywhere, including on disk.',
            'With an `ETag`, revalidation usually costs a `304 Not Modified` with no body.',
            'It is the usual choice for an SPA\'s `index.html`, so a deploy is picked up immediately.',
          ],
          answer: [0, 2, 3],
          explain: '`no-cache` means "store it, but ask me first"; `no-store` is the one that forbids storing. Paired with a validator, `no-cache` gives always-fresh HTML at the cost of a small conditional request, while the fingerprinted bundles it references are cached for a year.',
        },
        {
          q: 'After a connection reset, which requests may a proxy, a client library or a retry middleware re-send automatically without risking a duplicate side effect? Select all that apply.',
          options: [
            '`GET /orders/42`',
            '`POST /orders` (create an order)',
            '`PUT /orders/42` with the full new representation',
            '`DELETE /orders/42`',
            '`PATCH /orders/42` with `{ "op": "increment", "field": "quantity" }`',
          ],
          answer: [0, 2, 3],
          explain: '`GET`, `HEAD`, `PUT` and `DELETE` are **idempotent** by definition: doing them twice has the same effect as once, so they are safe to retry (a repeated `DELETE` may return 404, but nothing extra is deleted). `POST` creates a new resource each time, and a relative `PATCH` like "increment" is not idempotent either. Retrying those safely needs an idempotency key.',
        },
        {
          q: 'An API sends `Cache-Control: max-age=60, stale-while-revalidate=300`. A browser that honours it requests the resource 2 minutes after it was cached. What happens?',
          options: [
            'The cached copy is stale, so the browser blocks on a fresh request.',
            'The browser uses the stale copy immediately and refreshes it in the background; the next request gets the new one.',
            'The browser uses the cached copy without contacting the server for up to 360 seconds.',
            'The server must answer `304` within 300 ms or the cached copy is used.',
          ],
          answer: [1],
          explain: 'For 60 s the response is fresh. From 60 s to 360 s it is stale but may be **served while revalidating**: the user gets an instant (slightly old) answer and the cache refreshes behind the scenes. After 360 s the cache must wait for the server. It is a good fit for data where a minute of staleness is fine and latency matters.',
        },
        {
          q: 'A server compresses responses on the fly and sends the same strong ETag, `"abc123"`, for the gzip and the uncompressed body. Why is that a problem?',
          options: [
            'It is not: the ETag describes the resource, not the bytes.',
            'Clients reject strong ETags on compressed responses.',
            'A strong ETag promises byte-identical content, and ranges and cache validation rely on that: a cache could combine a byte range of the gzip representation with one of the plain one. Use a different ETag per encoding (e.g. `"abc123-gzip"`) or a weak ETag.',
            'ETags must be numeric when `Content-Encoding` is present.',
          ],
          answer: [2],
          explain: 'A strong validator means "these exact bytes". Two different byte sequences sharing one makes `Range` and `If-Range` unsafe and confuses caches. nginx weakens the ETag (`W/"abc123"`) when it gzips; Apache appends `-gzip`. Weak ETags remain fine for `If-None-Match` revalidation, which uses weak comparison.',
        },
      ],
    },
    {
      id: 'node-static-server-boss',
      title: 'Boss: a static file server that gets HTTP right',
      kind: 'node',
      xp: 240,
      boss: true,
      why: 'Serving files from disk touches path safety, validators, ranges, compression and streaming at once — the whole of practical HTTP in one handler.',
      tags: ['http', 'files', 'streams', 'security'],
      testTimeoutMs: 20000,
      hints: [
        'Work in the order of the brief: method, path, file lookup, headers, then the four-way decision (304, range, gzip, plain). Each step returns early.',
        'Path: `decodeURIComponent` in a try/catch (400), reject `\\0` (400), split on `/[/\\\\]+/`, `path.resolve(root, ...parts)`, then `path.relative(root, target)` must not be `..` or start with `..` + `path.sep`.',
        '`stat` the target; if it is a directory, `stat` its `index.html`. Catch `ENOENT`/`ENOTDIR` as 404 and require `isFile()`.',
        'Reuse your earlier lessons: the `If-None-Match`/`If-Modified-Since` precedence from Last-Modified, `parseRange` and `If-Range` from Range requests, and the `gzip`/`*`/`q=0` lookup from Compression.',
        'Stream with `await pipeline(createReadStream(file, { start, end }), res)` or `pipeline(createReadStream(file), createGzip(), res)` in a try/catch that destroys `res`. For `HEAD` and `304`/`416`, `writeHead` then `res.end()` with no stream at all.',
      ],
    },
  ],
});
