import { loadChapter } from '../../load.ts';

const here = import.meta.dirname;

export default loadChapter(here, {
  id: 'web-performance',
  title: "Web Performance",
  summary: "Core Web Vitals, bundles and code splitting, images, caching strategy, measuring before optimising.",
  lessons: [
    {
      id: 'web-vitals-quiz',
      title: 'Core Web Vitals: symptom to metric to fix',
      kind: 'quiz',
      xp: 60,
      why: 'Performance work starts with naming the problem correctly; optimising the wrong metric is the most common way to waste a sprint.',
      tags: ['web-vitals', 'lcp', 'inp', 'cls'],
      quiz: [
        {
          q: 'Users say the "Add to cart" button sometimes moves just as they tap it, and they buy the wrong size. Which metric captures this, and what is the usual cause?',
          options: [
            'INP; a slow click handler',
            'CLS; content inserted above it without reserved space — a late banner, an ad, an image without `width`/`height`',
            'LCP; the button renders late',
            'TTFB; the server is slow',
          ],
          answer: [1],
          explain: 'A layout shift is content moving without the user causing it. Reserve space: `width`/`height` (or `aspect-ratio`) on media, a fixed-height slot for ads and banners, and insert late content below the viewport or in response to input. Shifts within 500 ms of the user\'s own input are excluded, so an accordion opening on click is fine.',
        },
        {
          q: 'Which changes can improve **INP**? Select all that apply.',
          options: [
            'Splitting a 300 ms click handler so the visual update happens first and the analytics call is deferred (e.g. after `await scheduler.yield()`)',
            'Rendering 5 000 table rows with virtualisation instead of all at once',
            'Adding `loading="lazy"` to below-the-fold images',
            'Breaking up a long hydration task that runs while the user is already clicking',
          ],
          answer: [0, 1, 3],
          explain: 'INP is input delay + processing time + presentation delay. A busy main thread (hydration, long tasks) causes input delay; heavy handlers cause processing time; huge DOM updates cause presentation delay. Lazy-loading images saves bandwidth and helps LCP of other content, but does nothing for how fast a click is answered.',
        },
        {
          q: 'Lighthouse gives the product page LCP 1.8 s, but field data (CrUX) says 3.9 s at p75. What is the most useful conclusion?',
          options: [
            'The field data is wrong; Lighthouse runs in a controlled environment',
            'Average the two: the real LCP is about 2.85 s',
            'LCP is not measurable in the lab',
            'The lab run does not represent your users — slower devices and networks, cold caches, other entry points, cookie banners — so optimise for the field number and use the lab to reproduce it',
          ],
          answer: [3],
          explain: 'Lab data is one device on one network with a cold cache and no consent banner or personalisation. Field data is what users experience and what search ranking uses. Throttle the lab run (CPU 4×, slow 4G), test the pages users actually land on, and look at the field LCP element — it is often a different element than in the lab.',
        },
        {
          q: 'The LCP element is a hero image. Which of these typically make LCP **worse**? Select all that apply.',
          options: [
            '`loading="lazy"` on the hero',
            'Setting the hero as a CSS `background-image` in a stylesheet',
            '`<link rel="preload" as="image" fetchpriority="high">` for it',
            'Rendering the hero only after a client-side data fetch in a `useEffect`',
          ],
          answer: [0, 1, 3],
          explain: 'LCP suffers when the browser discovers the image late. Lazy-loading waits for layout; a CSS background is only found once the CSS is downloaded and applied; a client-side fetch waits for JavaScript, hydration and an API call. A preload with high priority does the opposite: the preload scanner requests it while the HTML is still arriving.',
        },
        {
          q: 'What does a CLS of 0.25 actually mean?',
          options: [
            'A quarter of the page\'s elements moved',
            'The page moved for 250 ms in total',
            'The worst burst of shifts (a session window of at most 5 s) adds up to 0.25, where each shift scores the fraction of the viewport affected times the distance moved',
            'The sum of every layout shift during the whole visit',
          ],
          answer: [2],
          explain: 'Each shift scores impact fraction × distance fraction. Shifts are grouped into windows (gaps under 1 s, at most 5 s long) and CLS is the largest window. That change (2021) stopped long-lived pages such as infinite feeds from accumulating huge scores just by being open. 0.25 is the "poor" threshold.',
        },
        {
          q: 'A team reports "our average LCP is 1.9 s, so we pass". Why might they still fail Core Web Vitals?',
          options: [
            'Core Web Vitals are assessed at the 75th percentile of page views, and a long tail of slow devices can put p75 far above the mean',
            'Averages are fine; the threshold is 2.5 s',
            'Only the median counts',
            'LCP must be under 1 s to pass',
          ],
          answer: [0],
          explain: 'Performance distributions have long tails: a fast majority on good connections hides a quarter of users on slow phones. The assessment uses p75 per metric, and a page passes only if all three are good at p75. Always look at percentiles, and segment by device type.',
        },
      ],
    },
    {
      id: 'web-cls-windows',
      title: 'Computing CLS the way Chrome does',
      kind: 'js',
      xp: 80,
      why: 'Lab and field CLS disagree all the time; knowing how session windows and input exclusion work is how you find the shift that actually hurts.',
      tags: ['cls', 'web-vitals', 'rum'],
      hints: [
        'Start with `entries.filter((e) => !e.hadRecentInput).sort((a, b) => a.startTime - b.startTime)`. `filter` returns a new array, so sorting it does not touch the input.',
        'Keep the current window as `{ first, last, value, shifts }`. A shift joins it when `shift.startTime - last.startTime < 1000` **and** `shift.startTime - first.startTime < 5000`.',
        'Collect every window, then take the one with the largest `value` using a strict `>`, so the earlier window wins a tie.',
        'For `largestTarget`, scan the worst window\'s shifts with a strict `>` too; the first of equal shifts stays.',
      ],
    },
    {
      id: 'web-preload-planner',
      title: 'Resource hints that help instead of hurt',
      kind: 'js',
      xp: 85,
      why: 'A missing `crossorigin` on a font preload downloads the font twice; preconnecting to ten origins starves the ones that matter.',
      tags: ['preload', 'preconnect', 'fonts', 'lcp'],
      hints: [
        'Filter to critical resources first. Then build connections and preloads as two separate lists and return `[...connections, ...preloads]`.',
        'A resource is CORS when it is a font, a fetch, or a module script. The key for a connection is the pair: `` `${cors}|${origin}` ``. Keep a `Set` of seen keys and an array of pairs in first-seen order.',
        'The first 4 pairs are preconnects (with `crossorigin: \'anonymous\'` for CORS pairs). For the rest, emit `dns-prefetch` only for origins that have neither a preconnect nor a dns-prefetch yet.',
        'Write one `preloadFor(resource)` with a `switch` on `type` that returns a hint or `null`, adding optional keys (`type`, `imagesrcset`, `imagesizes`) only when they apply.',
        'Fonts: `new URL(url).pathname.endsWith(\'.woff2\')` — check the pathname, so a `?v=2` query does not hide the extension.',
      ],
    },
    {
      id: 'web-responsive-images',
      title: 'srcset, sizes and the attributes that stop layout shift',
      kind: 'js',
      xp: 80,
      why: 'Images are most of the bytes on most pages; one helper that gets srcset, sizes, dimensions and loading right fixes every image at once.',
      tags: ['images', 'lcp', 'cls', 'srcset'],
      hints: [
        'Validate first: `typeof alt !== \'string\'` and `Number.isInteger(w) && w > 0` for every width.',
        '`[...new Set(widths)].filter((w) => w <= intrinsic.width).sort((a, b) => a - b)` — without a comparator, `sort()` compares strings and puts 1200 before 400.',
        'Build each candidate with `const url = new URL(src); url.searchParams.set(\'w\', String(w)); url.href`.',
        'Sort a **copy** of the slots by `minViewport` descending, map each to `(min-width: Npx) width`, then append the fallback. Convert numbers with a small `css(width)` helper that adds `px`.',
        'Spread the loading attributes conditionally: `...(priority ? { loading: \'eager\', fetchpriority: \'high\' } : { loading: \'lazy\', decoding: \'async\' })`.',
      ],
    },
    {
      id: 'web-bundle-quiz',
      title: 'Bundles, code splitting and tree shaking',
      kind: 'quiz',
      xp: 60,
      why: 'JavaScript is the most expensive byte a page loads, and most bloat comes from a handful of patterns you can spot in review.',
      tags: ['bundles', 'code-splitting', 'tree-shaking'],
      quiz: [
        {
          q: 'The home page bundle contains the admin area\'s charting library. The admin routes are only visited by staff. What is the right fix?',
          options: [
            'Load the admin routes with `React.lazy(() => import(\'./admin/AdminRoutes\'))` (a dynamic `import()`), so the charts land in a separate chunk loaded on demand',
            'Minify more aggressively',
            'Move the charting library to a CDN `<script>` tag in `index.html`',
            'Add the library to `optimizeDeps.exclude`',
          ],
          answer: [0],
          explain: 'A dynamic `import()` is a split point: the bundler puts everything reachable only through it into its own chunk. A CDN script tag still downloads and executes on every page. Route-level splitting is the highest-value split; then split large, rarely used widgets (editors, charts, maps) the same way.',
        },
        {
          q: '`import { formatPrice } from \'@shop/utils\'` pulls in the whole package (dates, validation, a PDF generator). Which of these can cause that? Select all that apply.',
          options: [
            'The package is published as CommonJS',
            'Its `index.js` barrel file re-exports modules that run code at import time (side effects), and `package.json` does not declare `"sideEffects": false`',
            'The import uses named instead of default imports',
            'Tree shaking only runs in development builds',
          ],
          answer: [0, 1],
          explain: 'Tree shaking needs static ES module syntax, and the bundler may only drop a module if it can assume importing it has no side effects. CommonJS `require`/`module.exports` is dynamic; a barrel file whose modules touch globals at import time must be kept unless `"sideEffects": false` (or a list) says otherwise. Named imports are exactly what tree shaking works with, and it runs in production builds.',
        },
        {
          q: 'After a dependency upgrade the bundle grew by 70 KB. The analyzer shows `lodash` **and** `lodash-es`, and two copies of `date-fns`. What is the likely cause and fix?',
          options: [
            'The bundler is broken; downgrade it',
            'Gzip does not work on duplicated code',
            'Nothing: duplicates are removed at runtime',
            'Different dependencies require different builds or incompatible versions of the same library; align versions (or dedupe/override in the package manager) and import from one entry point',
          ],
          answer: [3],
          explain: 'Package managers install a separate copy whenever version ranges do not overlap, and `lodash` (CommonJS) and `lodash-es` are different packages to a bundler. `npm ls <pkg>` shows who needs what; `overrides`/`resolutions` or upgrading the laggard dependency collapses them. Duplicates are not deduplicated by gzip across chunks, and both copies execute.',
        },
        {
          q: 'Your main chunk has a content hash (`main.3f9a1c2b.js`) and a long `max-age`. After a one-line change to a rarely used utility, every user re-downloads the whole 400 KB vendor code too. Why?',
          options: [
            'Content hashes are random on every build',
            '`immutable` must be removed from `Cache-Control`',
            'Vendor code and app code are in the same chunk, so any app change changes the hash of the file containing the vendor code; a separate vendor chunk (manual chunks) that changes rarely keeps its cache',
            'The CDN does not cache JavaScript',
          ],
          answer: [2],
          explain: 'A content hash changes when **any** byte in the file changes. Splitting stable dependencies from frequently changing app code means a deploy invalidates only the small app chunk. Do not overdo it: dozens of tiny chunks cost more requests and worse compression; a few coarse, stable groups work best.',
        },
        {
          q: 'Which statement about "our bundle is 180 KB" is most accurate?',
          options: [
            'Only the gzipped transfer size matters for performance',
            'The transfer size (gzip/brotli) drives download time, but parse, compile and execution time depend on the uncompressed size and the device — 180 KB compressed can be 700 KB of JavaScript to run on a slow phone',
            'Uncompressed size does not matter because browsers cache compiled code',
            'Bundle size affects only LCP, never INP',
          ],
          answer: [1],
          explain: 'Compression ratios for JS are often 3–5×. Download is governed by transfer size, CPU cost by the uncompressed code, and that CPU cost lands on the main thread — delaying hydration, interactivity and input handling (INP). Code caching helps repeat visits, not the first one.',
        },
      ],
    },
    {
      id: 'web-perf-budget',
      title: 'A performance budget check over the Vite manifest',
      kind: 'js',
      xp: 95,
      why: 'Budgets only hold when CI enforces them, and only mean something when they measure the JavaScript a user downloads before the page works.',
      tags: ['bundles', 'budgets', 'ci', 'graphs'],
      hints: [
        'Write `staticClosure(manifest, entryKey)`: a stack (or recursion) plus a `seen` Set, following only `imports`. The `seen` check before expanding a key is what makes cycles safe.',
        'Map the closure keys to chunks, then collect `new Set(chunks.map((c) => c.file))` and `new Set(chunks.flatMap((c) => c.css ?? []))` — Sets, because two keys can share a file.',
        'One helper for sizes that throws `new Error(\'No size for \' + file)` unless `Object.hasOwn(sizes, file)`. `sizes[file] ?? 0` would silently accept a missing file, and `if (!sizes[file])` rejects a legitimate `0`.',
        'Check each budget only when `budgets.x !== undefined`, and compare with `>`.',
        'For chunk violations, dedupe every manifest `file` with a Set, sort it, then check each size against `budgets.chunk`.',
      ],
    },
    {
      id: 'web-long-task-chunker',
      title: 'Breaking up long tasks by time, not by count',
      kind: 'js',
      xp: 90,
      why: 'Long tasks are what make a page feel frozen and what INP measures; yielding on a time budget is the standard fix.',
      tags: ['inp', 'long-tasks', 'scheduling', 'async'],
      hints: [
        'Start with `signal?.throwIfAborted()`: it throws `signal.reason`, which rejects the async function with exactly that value.',
        'Keep `let sliceStart = now()` and check **before** each item: `if (index > 0 && now() - sliceStart >= budgetMs)`.',
        'Inside that check: `await yieldToMain()`, then `signal?.throwIfAborted()`, then `sliceStart = now()` — after the yield, so time spent by other work does not count against the new slice.',
        'Do not catch anything: an error from `fn` inside an `async` function already rejects the returned promise and stops the loop.',
      ],
    },
    {
      id: 'web-vitals-reporter',
      title: 'A field-data reporter that does not lose its data',
      kind: 'js',
      xp: 85,
      why: 'Real-user monitoring is how you know performance in production, and the naive reporter loses most mobile sessions.',
      tags: ['rum', 'web-vitals', 'beacon', 'sampling'],
      hints: [
        'Decide sampling in the factory: `const sampled = random() < sampleRate`. Every public function returns early when it is `false`.',
        'Keep a `Map` of id → latest metric (a `Map` remembers first-insertion order even when you `set` an existing key) and a `Set` of pending ids.',
        'In `record`, round first, then compare with the stored metric: same value and rating → return without marking it pending.',
        'In `flush`, build the list from the map\'s keys filtered by the pending set, clear the set, then `if (!transport.beacon(endpoint, body)) transport.fetch(endpoint, { … keepalive: true … })`.',
        'In `attach`, keep the visibility handler in a variable (it checks `target.visibilityState === \'hidden\'`) so the returned function can remove exactly the listeners you added.',
      ],
    },
    {
      id: 'web-lcp-boss',
      title: 'BOSS: diagnosing a slow LCP from field timings',
      kind: 'js',
      xp: 220,
      boss: true,
      why: 'Turning raw timing entries into "the hero is a CSS background, discovered 950 ms late" is what separates guessing from fixing.',
      tags: ['lcp', 'web-vitals', 'diagnostics', 'rum'],
      hints: [
        'Find the image first: when `lcp.url` is non-empty, keep the matching resource with the smallest `startTime`. No match → treat it as text.',
        'Compute the four raw phases, and one more value: `readyAt`, the earliest moment the LCP could paint — the image\'s `responseEnd`, or TTFB for text. Render delay and the blocker check both use it.',
        'Push issues in the order of the brief, comparing the **raw** numbers with `>`. Round only when you build `phases` in the returned object.',
        'Blockers: `resources.filter((r) => r.renderBlockingStatus === \'blocking\' && r.responseEnd > readyAt)`, sorted with `b.responseEnd - a.responseEnd || a.name.localeCompare(b.name)` — or an explicit `<` comparison on names.',
        'Rating uses the rounded value: `value <= 2500` good, `<= 4000` needs-improvement, else poor.',
      ],
    },
  ],
});
