import { loadChapter } from '../../load.ts';

const here = import.meta.dirname;

export default loadChapter(here, {
  id: 'js-objects',
  title: "Objects, Prototypes & Protocols",
  summary: "Prototypes, classes, getters, Symbols, the iterator protocol, Proxy and Reflect, WeakMap.",
  lessons: [
    {
      id: 'js-prototypes-quiz',
      title: 'Quiz: the prototype chain at work',
      kind: 'quiz',
      xp: 60,
      why: 'Spies that never fire, shared defaults that leak and `instanceof` that lies are all the same model applied to an edge case.',
      tags: ['prototypes', 'classes'],
      quiz: [
        {
          q: 'Before creating the service, a test stubs `Api.prototype.fetchUser = vi.fn(async () => fakeUser)`. The real network call still runs. `Api` is:\n\n```js\nclass Api {\n  fetchUser = async (id) => { /* real fetch */ };\n}\n```\n\nWhy?',
          options: [
            '`fetchUser` is a class field: the constructor gives each instance its own `fetchUser`, which shadows anything on `Api.prototype`',
            'Async functions cannot be stubbed by assignment; you have to wrap the returned promise',
            'Assignments to a class\'s prototype are silently ignored in ES modules',
            'The stub has to be installed after the instance exists, because instances copy their methods when they are created',
          ],
          answer: [0],
          explain: 'Class **fields** (including arrow-function fields) are assigned to every instance when it is constructed; only **methods** (`fetchUser() {}`) live once on the prototype. An own property always wins over the prototype, so the stub is never reached. Stub the instance (`vi.spyOn(api, \'fetchUser\')`) or make it a method. Instances do not copy methods: a change to the prototype is visible to existing instances immediately.',
        },
        {
          q: 'What does `defaults` look like after this runs?\n\n```js\nconst defaults = { retries: 3, headers: { accept: \'application/json\' } };\nconst opts = Object.create(defaults);\nopts.retries = 5;\nopts.headers.authorization = \'Bearer x\';\n```',
          options: [
            '`{ retries: 3, headers: { accept: \'application/json\' } }` — `opts` only ever writes to itself',
            '`{ retries: 5, headers: { accept: \'application/json\', authorization: \'Bearer x\' } }`',
            '`{ retries: 3, headers: { accept: \'application/json\', authorization: \'Bearer x\' } }`',
            'It throws: you cannot assign through an inherited property',
          ],
          answer: [2],
          explain: 'Assigning `opts.retries` creates an **own** property on `opts` that shadows the inherited one. But `opts.headers.authorization = …` first *reads* `opts.headers`, which finds the one shared object on `defaults`, then mutates it. Every later request built from `defaults` now carries the token. Inheritance shares nested objects; copy them (`{ ...defaults, headers: { ...defaults.headers } }`).',
        },
        {
          q: 'A `Cart` class has fields `items` and `currency`, a getter `get total()` and a method `add()`. A reducer returns `{ ...cart }`. What does the copy have?',
          options: [
            '`items`, `currency`, `total` and `add` — spread copies everything reachable',
            '`items`, `currency` and `total` — getters are evaluated, methods are skipped',
            '`items` and `currency` only; it is a plain object, so `copy.total` and `copy.add` are `undefined`',
            'A `Cart` instance, because spread preserves the prototype',
          ],
          answer: [2],
          explain: 'Object spread copies **own enumerable** properties into a new plain object. The getter and the method live on `Cart.prototype`, so the copy has neither, and `copy instanceof Cart` is false. This is why class instances in Redux state break the first time a reducer spreads them. (An own getter would be evaluated once and frozen as a value.)',
        },
        {
          q: 'An error handler does `if (err instanceof ValidationError) return res.status(400)`. It works in tests, but in production validation errors come back as 500s. Which explanations are plausible? Select all that apply.',
          options: [
            'Two copies of the library are installed (a nested `node_modules`), so the error was built from a different `ValidationError` class',
            'The error crossed a realm (a worker, `vm` context or iframe) and was reconstructed there',
            '`instanceof` compares the error\'s `name` string, and a minifier renamed the class',
            'The error was serialised and parsed (a queue, `structuredClone`), which drops the custom prototype',
          ],
          answer: [0, 1, 3],
          explain: '`instanceof` asks whether *that exact* `ValidationError.prototype` object is on the chain. A second copy of the package, another realm, or a serialisation round-trip all produce an object whose chain does not contain it. It never looks at `name`. Robust checks use something that survives: a `code` property, `Symbol.for(\'mylib.ValidationError\')` as a brand, or `Array.isArray` rather than `instanceof Array` for built-ins.',
        },
        {
          q: 'A record comes from `Object.create(null)` (a dictionary from a parser). Which lookup does **not** throw?',
          options: [
            '`record.hasOwnProperty(\'id\')`',
            '`Object.hasOwn(record, \'id\')`',
            '`record.toString()`',
            '`` `${record}` ``',
          ],
          answer: [1],
          explain: 'A null-prototype object inherits nothing: no `hasOwnProperty`, no `toString`, no `Symbol.toPrimitive`, so string conversion throws `Cannot convert object to primitive value`. `Object.hasOwn(obj, key)` is a static function that works on any object, which is why linters now prefer it over `obj.hasOwnProperty(key)`.',
        },
        {
          q: 'What are `Model.count` and `User.count` afterwards?\n\n```js\nclass Model {\n  static count = 0;\n  static create() { this.count++; return new this(); }\n}\nclass User extends Model {}\n\nUser.create();\nUser.create();\nModel.create();\n```',
          options: [
            '`Model.count` is 3 and `User.count` is 3: static fields are shared by the hierarchy',
            '`Model.count` is 3 and `User.count` is `undefined`',
            'It throws: `User` has no own `count` to increment',
            '`Model.count` is 1 and `User.count` is 2',
          ],
          answer: [3],
          explain: '`User`\'s prototype is `Model`, so `this.count` inside `User.create()` first *reads* the inherited `0`, and the `++` then *writes* an own `User.count`. From then on the two counters are separate. Per-class registries and caches built on static fields split like this silently; use `Object.hasOwn(this, \'count\')` or a `WeakMap` keyed by the class when you mean one per class.',
        },
      ],
    },
    {
      id: 'js-static-this',
      title: 'Classes that survive subclassing',
      kind: 'js',
      xp: 75,
      why: 'Base models, repositories and error hierarchies all break the day someone extends them, if the base class names itself.',
      tags: ['classes', 'inheritance', 'this'],
      hints: [
        'Inside a static method, `this` is the class the method was called on. `new this(...)` builds a `User` when you call `User.fromJSON`.',
        'In the constructor, `new.target` is the class `new` was called with, even through `super()`. Compare it to `Model` to refuse direct construction, and read `new.target.fields` for the field list.',
        'Use `attrs[field] ?? null`, not `||`: `0` and `\'\'` are real values.',
        'In instance methods, `this.constructor` is the concrete class: `new this.constructor({ ...this.toJSON(), ...changes })`. For `equals`, compare `other.constructor === this.constructor` rather than `instanceof`, which would let an `Admin` equal a `User`.',
      ],
    },
    {
      id: 'js-private-brand',
      title: 'Private fields and brand checks',
      kind: 'js',
      xp: 80,
      why: 'A secret on `this._secret` ends up in a log line eventually. `#private` fields and brand checks are how you actually keep it in.',
      tags: ['classes', 'private fields', 'security'],
      hints: [
        'Declare `#id; #secret; #scopes;` in the class body and assign them in the constructor. `JSON.stringify`, spread and `Object.keys` cannot see them.',
        'Expose `id` and `scopes` as getters, and have `scopes` return a copy (`[...this.#scopes]`). Copy the array you are given in the constructor too.',
        '`util.inspect` calls the method stored under `Symbol.for(\'nodejs.util.inspect.custom\')` if one exists. Define it with a computed method name: `[Symbol.for(\'nodejs.util.inspect.custom\')]() { ... }`.',
        'The brand check is `#secret in value`, but it throws on primitives: `return typeof value === \'object\' && value !== null && #secret in value;`',
      ],
    },
    {
      id: 'js-lazy-seq',
      title: 'The iterator protocol: a lazy Seq',
      kind: 'js',
      xp: 90,
      why: 'Processing a large export, a cursor or paginated API without loading it all is the iterator protocol, and its bugs are over-reading and never closing.',
      tags: ['iterators', 'generators', 'laziness'],
      hints: [
        'Do not store an iterator in the `Seq`. Store a function that *opens* a fresh one, and call it from `[Symbol.iterator]()`.',
        'Each operator returns `new Seq(function* () { ... })` that loops `for (const value of upstream)`. A generator function is itself a "function that opens an iterator".',
        'For `take`, yield first and check the count *after* yielding: `yield value; if (++count >= n) return;`. Checking before the yield means one extra pull.',
        'A `return` (or `break`) inside `for...of` calls the upstream iterator\'s `return()`, which runs the source generator\'s `finally`. `first()` can be `for (const v of this) return v; return undefined;`.',
      ],
    },
    {
      id: 'js-weakmap-side-tables',
      title: 'WeakMap side tables',
      kind: 'js',
      xp: 70,
      why: 'Caching something about objects you do not own, without mutating them and without leaking them, comes up in every selector, renderer and request pipeline.',
      tags: ['WeakMap', 'memoization', 'memory'],
      hints: [
        'Create one `WeakMap` inside `weakMemo` (so each memo has its own) and key it by the argument itself.',
        'Only objects and functions can be `WeakMap` keys. Check `(typeof x === \'object\' && x !== null) || typeof x === \'function\'` and just call `fn(x)` otherwise.',
        'Use `cache.has(arg)`, not `cache.get(arg) !== undefined`, so an `undefined` result is cached too. Attach `has` and `forget` as properties of the returned function.',
        'For `createIdentityKeys`, keep `let next = 1` and a `WeakMap` in the closure; on a miss, `keys.set(obj, \'k\' + next++)`.',
      ],
    },
    {
      id: 'js-safe-merge',
      title: 'Deep merge without prototype pollution',
      kind: 'js',
      xp: 85,
      why: 'Prototype pollution through config and body merging is a recurring CVE; a mid-level engineer should be able to write the merge that is not vulnerable.',
      tags: ['security', 'prototypes', 'objects'],
      hints: [
        '`isPlainObject`: rule out `null` and non-objects, then check `Object.getPrototypeOf(value)` is `Object.prototype` or `null`.',
        'Iterate with `Object.keys(source)`, not `for...in`: `for...in` walks inherited keys, including anything already polluted.',
        'Skip `__proto__`, `constructor` and `prototype` inside the recursive helper, so the check runs at every depth, not just the top.',
        'Build into objects you created: when the incoming value is plain, recurse into `isPlainObject(existing) ? existing : {}`. Since every plain object in the result is your own copy, merging into it never touches a source.',
      ],
    },
    {
      id: 'js-proxy-strict-config',
      title: 'Proxy: config that fails on typos',
      kind: 'js',
      xp: 80,
      why: 'A misspelt config key that silently reads `undefined` is a production incident; a strict config turns it into a stack trace at boot.',
      tags: ['Proxy', 'Reflect', 'configuration'],
      hints: [
        'Return `new Proxy(values, { get, set, deleteProperty, defineProperty })`. Traps you do not define (`has`, `ownKeys`) forward to the target, which is what `in` and `Object.keys` need.',
        'At the top of `get`, let symbols, `then` and `toJSON` through: `if (typeof key === \'symbol\' || key === \'then\' || key === \'toJSON\') return Reflect.get(target, key, receiver);`',
        'Test existence with `key in target`, not `target[key] === undefined`, so an explicitly undefined key is still known.',
        'For a plain-object value, return `strictConfig(value, { name: `${name}.${key}` })`. The write traps just throw a `TypeError`.',
      ],
    },
    {
      id: 'js-proxy-readonly',
      title: 'Proxy: read-only views with stable identity',
      kind: 'js',
      xp: 95,
      why: 'Handing live state to code you do not trust, without copying it and without breaking memoisation, is what stores and plugin systems do.',
      tags: ['Proxy', 'WeakMap', 'immutability'],
      hints: [
        'Use a single shared handler object. In `get`, read with `Reflect.get(target, key, receiver)` and return `readonlyView(value)`, so nested plain objects come back wrapped.',
        'Cache views in a `WeakMap` (target to view) so `view.cart === view.cart`, and keep a `WeakSet` of views so `readonlyView(view)` and `isReadonlyView` can recognise them.',
        'Only wrap arrays and objects whose prototype is `Object.prototype` or `null`; return everything else as is, which keeps `Date` and `Map` methods working.',
        'Before wrapping in `get`, look at `Reflect.getOwnPropertyDescriptor(target, key)`: if it is non-configurable and non-writable, return the raw value, or the engine throws a proxy invariant `TypeError`.',
        'The `set`, `deleteProperty` and `defineProperty` traps receive `(target, key, …)`: throw `new TypeError(`Cannot set "${String(key)}"…`)`. `String(key)` handles symbol keys.',
      ],
    },
    {
      id: 'js-produce-drafts',
      title: 'BOSS: copy-on-write drafts (a mini Immer)',
      kind: 'js',
      xp: 240,
      boss: true,
      why: 'Immer and Redux Toolkit run on this. Building it pulls Proxy, WeakMap, revocation and structural sharing into one working model.',
      tags: ['Proxy', 'immutability', 'structural sharing'],
      hints: [
        'One `createDraft(base, parent)` returns `Proxy.revocable(base, handler)` and stores a record `{ base, copy: null, modified: false, parent, drafts: new Map() }` in a `WeakMap` keyed by the proxy. Collect every `revoke` and call them all in a `finally`.',
        '`get`: read from `copy ?? base`. If the value is a plain object or array and is still the *original* `base[key]`, return a child draft, cached in `drafts` by key. Otherwise return the value as is.',
        'On the first write, walk up the parents: for each one that is not yet modified, set `modified = true` and make its shallow `copy`. Then write to `copy`. In `set`, return early if `Object.is(current, value)` or the value is the draft of the current, unchanged value.',
        'Also define `has`, `ownKeys`, `deleteProperty` and `getOwnPropertyDescriptor` against `copy ?? base`. Report descriptors as `configurable: true` except where the base itself pins the key (an array\'s `length`), or the engine throws an invariant error.',
        'Finalise recursively: an unmodified draft becomes its `base`; a modified one becomes its `copy`, with every value inside replaced. If a value is a draft (found via the `WeakMap`), finalise it; if it is the original `base[key]` and that key was drafted, finalise that child; if it is a new object from the recipe, walk it and replace any drafts inside.',
      ],
    },
  ],
});
