import { loadChapter } from '../../load.ts';

const here = import.meta.dirname;

export default loadChapter(here, {
  id: 'web-http-browser',
  title: "HTTP from the Browser",
  summary: "fetch semantics, CORS and preflight, cookies across sites, caching headers, errors that are not exceptions.",
  lessons: [
    {
      id: 'web-fetch-quiz',
      title: 'What fetch resolves, rejects and sends',
      kind: 'quiz',
      xp: 60,
      why: 'Most front-end data bugs come from a wrong mental model of fetch: a 500 that "succeeded", a cookie that was never sent, a body read twice.',
      tags: ['fetch', 'http', 'cookies'],
      quiz: [
        {
          q: '`const res = await fetch(\'/api/orders\')` and the server answers `500 Internal Server Error`. What happens?',
          options: [
            'The promise rejects with a `TypeError`',
            'The promise resolves; `res.ok` is `false` and `res.status` is `500`',
            'The promise resolves; `res.ok` is `true` because a response arrived',
            'The promise rejects with an error whose `status` is `500`',
          ],
          answer: [1],
          explain: '`fetch` rejects only when no HTTP response could be obtained. Any status code — 404, 500, 503 — resolves, and `ok` is simply `status >= 200 && status < 300`. Code that does `await (await fetch(url)).json()` without checking `ok` renders an error payload as if it were data.',
        },
        {
          q: 'Which of these make the `fetch` promise **reject**? Select all that apply.',
          options: [
            'The API host does not resolve in DNS',
            'A cross-origin response has no `Access-Control-Allow-Origin` header',
            'The request\'s `AbortController` is aborted',
            'The server answers `401 Unauthorized`',
            'The server answers `302` to a login page, which answers `200`',
          ],
          answer: [0, 1, 2],
          explain: 'Network failures and CORS failures both reject with a `TypeError` (the browser deliberately does not tell the page which one it was — look in DevTools). An abort rejects with an `AbortError`. A 401 resolves. A redirect is followed automatically and you get the final `200` page, with `res.redirected === true` and `res.url` set to the login URL.',
        },
        {
          q: 'The page at `https://app.shop.com` calls `fetch(\'https://api.shop.com/me\')`. The user is logged in to the API with a cookie, but the API answers 401. What is the most likely cause?',
          options: [
            'The cookie is `HttpOnly`, so `fetch` cannot send it',
            '`fetch` sends cookies only for same-origin requests by default; it needs `credentials: \'include\'`, and the API must answer with `Access-Control-Allow-Credentials: true` and a specific origin',
            'Cookies are never sent on cross-origin requests; the API must use a bearer token',
            'The API needs `Access-Control-Allow-Origin: *` to accept cookies',
          ],
          answer: [1],
          explain: 'The default is `credentials: \'same-origin\'`, and two subdomains are different origins. `HttpOnly` only hides the cookie from JavaScript; the browser still attaches it. With `include`, the server must reply with the exact origin (never `*`) and `Access-Control-Allow-Credentials: true`, or the browser hides the response.',
        },
        {
          q: 'A teammate "fixes" a CORS error by adding `mode: \'no-cors\'` to the `fetch`. What happens now?',
          options: [
            'The browser skips the CORS check and the page can read the JSON',
            'The request is not sent at all',
            'The request is sent, and the page gets an opaque response: `status` is `0`, the headers are empty and the body cannot be read',
            'The browser sends a preflight first and then allows the response',
          ],
          answer: [2],
          explain: '`no-cors` means "I do not need to read the response". It is for fire-and-forget requests and for caching third-party resources in a service worker. The error disappears from the console, the data never arrives, and `await res.json()` fails on an empty body. The fix is on the server, in its CORS headers.',
        },
        {
          q: 'What does this log? `const data = await res.json(); console.log(await res.text());`',
          options: [
            'The raw JSON text',
            'An empty string, because the stream is at its end',
            'Nothing: the second call rejects with a `TypeError` because the body has already been read',
            '`undefined`',
          ],
          answer: [2],
          explain: 'A response body is a stream and can be consumed once; `res.bodyUsed` becomes `true`. The classic victim is `try { await res.json() } catch { await res.text() }` — the `catch` throws and hides the real parse error. Read once with `text()` and parse yourself, or call `res.clone()` before the first read.',
        },
        {
          q: 'You send an analytics event when the user closes the tab (in a `pagehide` handler). Which of these are reliable ways to make sure it is delivered? Select all that apply.',
          options: [
            '`navigator.sendBeacon(url, body)`',
            '`fetch(url, { method: \'POST\', body, keepalive: true })`',
            'A normal `fetch(url, { method: \'POST\', body })`, awaited',
            'A synchronous `XMLHttpRequest` in `beforeunload`',
          ],
          answer: [0, 1],
          explain: 'When the page is unloaded its pending requests are cancelled, and awaiting inside `pagehide` does not keep the page alive. `sendBeacon` and `keepalive: true` hand the request to the browser to finish after the page is gone (both have a small body limit, around 64 KB). Synchronous XHR during unload is blocked by modern browsers and freezes the tab where it is not.',
        },
      ],
    },
    {
      id: 'web-fetch-json',
      title: 'A fetch wrapper that tells failures apart',
      kind: 'js',
      xp: 80,
      why: 'Every front end has a `fetchJson`. One that treats a 404 as data, or parses an HTML fallback page as JSON, turns a clear error into a confusing one.',
      tags: ['fetch', 'errors', 'http', 'content-type'],
      hints: [
        'Build the headers with `new Headers(init.headers)`: it accepts an object, an array of pairs or another `Headers`, and `has(\'accept\')` is case-insensitive. Pass `{ ...init, headers }` on.',
        'Wrap only the `fetchImpl` call in `try/catch`. In the `catch`, `if (error?.name === \'AbortError\') throw error;` and otherwise `throw new NetworkError(url, error)`.',
        'Call `await response.text()` exactly once, then decide. `res.json()` followed by `res.text()` in a `catch` throws "Body is unusable".',
        'For the type check: `contentType.split(\';\')[0].trim().toLowerCase()`, then `=== \'application/json\' || endsWith(\'+json\')`. `includes(\'json\')` is too loose.',
        'Order: not `ok` → `HttpError` (body: `null` if empty, parsed if JSON and it parses, else text). Then `204`/`205`/empty → `null`. Then not JSON → `ContentTypeError`. Then `JSON.parse(text)`.',
      ],
    },
    {
      id: 'web-cors-middleware',
      title: 'CORS middleware that is neither open nor broken',
      kind: 'node',
      xp: 100,
      why: 'CORS bugs are either a security hole (any site reads your users\' data) or an outage (every browser request fails). Both come from a few lines of middleware.',
      tags: ['cors', 'http', 'security', 'middleware'],
      hints: [
        'Put the allowed origins in a `Set` and use `has(origin)`. `startsWith`, `includes` or an unanchored regex let `https://app.example.com.evil.io` through.',
        'Call `res.setHeader(\'Vary\', \'Origin\')` first thing, before any branch. Headers set with `setHeader` are merged into whatever the handler later passes to `writeHead`.',
        'A preflight is `req.method === \'OPTIONS\' && req.headers[\'access-control-request-method\'] !== undefined`. Answer it yourself and `return` — never call the handler for it.',
        'Parse the requested headers with `.split(\',\').map((h) => h.trim().toLowerCase()).filter(Boolean)` and check `every` against a lower-cased `Set` of `allowHeaders`.',
        'For everything else: if the origin is allowed, set `Access-Control-Allow-Origin` (the origin itself), credentials and expose headers, then `return handler(req, res)`. If it is not allowed, just call the handler.',
      ],
    },
    {
      id: 'web-request-bodies',
      title: 'Request bodies and the Content-Type that describes them',
      kind: 'js',
      xp: 75,
      why: '"The server says my payload is empty" is nearly always a body whose Content-Type is missing, wrong or hand-written.',
      tags: ['fetch', 'http', 'forms', 'content-type'],
      hints: [
        'Decide which body option was passed with `\'json\' in options`, not `if (options.json)`: `false`, `0`, `\'\'` and `null` are real JSON bodies.',
        'Start from `const headers = new Headers(options.headers)`. It accepts every shape and its `has`/`set`/`delete` are case-insensitive.',
        'Let the platform encode: build a `URLSearchParams` for `form` and a `FormData` for `multipart`, append entry by entry, and pass it as `body`. `new Request` sets the content type for both, including the multipart boundary.',
        'For `multipart`, call `headers.delete(\'content-type\')`: a hand-written `multipart/form-data` has no boundary and would win over the generated one.',
        'Method last: `(options.method ?? (kind ? \'POST\' : \'GET\')).toUpperCase()`, then `return new Request(url, { method, headers, body })` — the constructor throws the `TypeError` for a body on GET/HEAD for you.',
      ],
    },
    {
      id: 'web-cors-quiz',
      title: 'Debugging CORS errors',
      kind: 'quiz',
      xp: 60,
      why: 'CORS errors are the most common "the API is broken" report, and the quick fixes people reach for are usually security holes or no-ops.',
      tags: ['cors', 'http', 'security'],
      quiz: [
        {
          q: '`https://evil.io` has a page with an auto-submitting HTML form that POSTs `amount=500` (as `application/x-www-form-urlencoded`) to `https://bank.com/transfer`. The bank sends **no** CORS headers at all. What happens?',
          options: [
            'The browser blocks the request because `bank.com` did not allow `evil.io`',
            'The browser sends a preflight, it fails, and the POST is never sent',
            'The POST is sent with the user\'s cookies (subject to `SameSite`) and the transfer runs; CORS only stops `evil.io` from reading the response',
            'Nothing is sent because forms cannot submit to another origin',
          ],
          answer: [2],
          explain: 'A form post with a safelisted content type is a *simple* request: no preflight, the request goes out, and the server processes it. CORS governs whether script on the other origin may **read** the answer; it is not an access-control layer on your server. Protection against this is CSRF defence — `SameSite` cookies, CSRF tokens, checking `Origin` — not CORS.',
        },
        {
          q: 'Which of these cross-origin `fetch` calls are **preflighted**? Select all that apply.',
          options: [
            '`POST` with `content-type: application/json`',
            '`GET` with an `Authorization: Bearer …` header',
            '`POST` with a `URLSearchParams` body',
            '`GET` with `Accept: application/json`',
            '`PUT` with no custom headers',
          ],
          answer: [0, 1, 4],
          explain: 'A request skips the preflight only if its method is `GET`, `HEAD` or `POST`, its headers are all CORS-safelisted (`Accept`, `Accept-Language`, `Content-Language`, `Content-Type`), and its content type is one of `text/plain`, `multipart/form-data`, `application/x-www-form-urlencoded`. JSON, `Authorization` and `PUT` each trigger one. That is why a JSON API always sees `OPTIONS` requests from browsers.',
        },
        {
          q: 'The page calls `fetch(api, { credentials: \'include\' })`. The API answers with `Access-Control-Allow-Origin: *` and `Access-Control-Allow-Credentials: true`. What does the page get?',
          options: [
            'The response: `*` allows every origin, including this one',
            'A CORS error: with credentials, the browser requires the exact requesting origin, never `*`',
            'The response, but without cookies being sent',
            'The response, but with an empty body',
          ],
          answer: [1],
          explain: 'The wildcard is only honoured on uncredentialed requests. With credentials the server must echo the specific origin (after checking it against an allow-list) and add `Vary: Origin`. Echoing *any* origin back with credentials is the dangerous version: every site on the internet can then read your users\' data.',
        },
        {
          q: 'After adding auth middleware to every route, the browser app gets CORS errors on every `PUT`, while `curl` with a token works. What is the likely cause?',
          options: [
            'The auth middleware answers the `OPTIONS` preflight with `401`, because preflights never carry cookies or `Authorization`, so the real `PUT` is never sent',
            'The browser strips the `Authorization` header from `PUT` requests',
            '`curl` sends an `Origin` header and the browser does not',
            '`PUT` is not allowed cross-origin by the CORS specification',
          ],
          answer: [0],
          explain: 'A preflight is sent without credentials by design — it is asking permission to send them. If it reaches an auth check it fails, and a failed preflight shows up only as a CORS error. Answer preflights before authentication (and before routing), with a `2xx` and the `Access-Control-Allow-*` headers.',
        },
        {
          q: 'The API reflects the request\'s `Origin` into `Access-Control-Allow-Origin` for its two front ends, `app.shop.com` and `admin.shop.com`. Behind a CDN, admin users intermittently get CORS errors that go away on a hard refresh. What is missing?',
          options: [
            '`Access-Control-Max-Age`',
            '`Access-Control-Allow-Credentials: true`',
            '`Cache-Control: no-store` on every API response',
            '`Vary: Origin`, so the CDN keys its cache on the origin and does not serve the `app.shop.com` answer to `admin.shop.com`',
          ],
          answer: [3],
          explain: 'A shared cache stores one response per URL unless told which request headers change it. Without `Vary: Origin` the first origin to ask poisons the cache for the other one. Disabling caching entirely would also hide the bug, at the cost of the cache; `Vary: Origin` is the precise fix.',
        },
        {
          q: 'The front end reads `res.headers.get(\'x-total-count\')` for pagination. DevTools shows the header on the response, but the code gets `null`. Why?',
          options: [
            'Custom headers must start with `X-` to be readable, and this one does',
            'Header names are case-sensitive in `fetch`, so it must be `X-Total-Count`',
            'Cross-origin, script can only read CORS-safelisted response headers unless the server lists others in `Access-Control-Expose-Headers`',
            'The header was removed by the preflight',
          ],
          answer: [2],
          explain: 'Only `Cache-Control`, `Content-Language`, `Content-Length`, `Content-Type`, `Expires`, `Last-Modified` and `Pragma` are readable by default. `ETag`, `Location`, `X-Total-Count` and friends need `Access-Control-Expose-Headers`. `Headers.get` is case-insensitive, and DevTools shows what arrived on the wire, not what the page may read.',
        },
      ],
    },
    {
      id: 'web-samesite-quiz',
      title: 'SameSite cookies and what "site" means',
      kind: 'quiz',
      xp: 60,
      why: 'SameSite is why CSRF got rarer and why SSO callbacks, payment returns and embedded widgets suddenly log people out.',
      tags: ['cookies', 'security', 'csrf'],
      quiz: [
        {
          q: 'Which pairs are **same-site**? Select all that apply.',
          options: [
            '`https://app.shop.com` and `https://api.shop.com`',
            '`https://shop.com` and `https://shop.co.uk`',
            '`https://alice.github.io` and `https://bob.github.io`',
            '`https://shop.com` and `https://shop.com:8443`',
            '`http://shop.com` and `https://shop.com`',
          ],
          answer: [0, 3],
          explain: 'Site = scheme + registrable domain. Subdomains of one registrable domain are same-site; the port does not matter. `github.io` is on the public suffix list, so each user\'s subdomain is its own site. Browsers now compare the scheme too ("schemeful same-site"), so `http` and `https` are different sites.',
        },
        {
          q: 'The session cookie is `SameSite=Strict`. A logged-in user clicks a link in their webmail to `https://shop.com/orders/42`. What do they see?',
          options: [
            'Their order: they are logged in',
            'The logged-out page on that first load, although clicking any link inside the site shows them logged in again',
            'A browser warning about a cross-site cookie',
            'Their order, but only if the link opened in a new tab',
          ],
          answer: [1],
          explain: '`Strict` withholds the cookie on every request that starts on another site, including a top-level link click. The next navigation starts on `shop.com`, so the cookie comes back — the classic "I have to click twice" bug. `Lax` sends the cookie on top-level `GET` navigations, which is why it is the default and the usual choice for session cookies.',
        },
        {
          q: 'After checkout, the payment provider sends the user back with an auto-submitted form `POST` to `https://shop.com/checkout/return`. The session cookie is `SameSite=Lax`. What goes wrong, and what is a sound fix?',
          options: [
            'Nothing: `Lax` cookies are sent on top-level navigations',
            'The cookie is not sent on a cross-site `POST`, so the return page sees no session; carry a signed, single-use order token in the callback (or redirect to a `GET` on your own site) instead of relying on the session',
            'The cookie is not sent, and the only fix is to switch the session cookie to `SameSite=None`',
            'The provider\'s page cannot submit forms to another site',
          ],
          answer: [1],
          explain: '`Lax` allows top-level navigations with **safe** methods only; a cross-site `POST` gets no cookie. Loosening the session cookie to `None` works but re-opens CSRF on every endpoint to fix one. The robust pattern makes the callback self-authenticating: verify a signed token the provider round-trips, then set up the session on a same-site request.',
        },
        {
          q: 'A support-chat widget from `chat.io` runs in an iframe on customers\' sites and keeps its own login cookie. Which cookie attributes can work at all?',
          options: [
            '`SameSite=Lax`',
            '`SameSite=Strict; Secure`',
            '`SameSite=None` without `Secure`',
            '`SameSite=None; Secure` (ideally `Partitioned`, since many browsers block unpartitioned third-party cookies)',
          ],
          answer: [3],
          explain: 'An iframe on another site is a cross-site context, so `Lax` and `Strict` cookies are never sent to it. `None` is required, and browsers **reject** a `SameSite=None` cookie that is not `Secure`. Even then, third-party cookie blocking may drop it; `Partitioned` (CHIPS) gives the widget a separate cookie jar per embedding site, which survives that blocking.',
        },
        {
          q: 'The session cookie is `SameSite=Lax`. Which statements about CSRF are true? Select all that apply.',
          options: [
            'A cross-site form `POST` to your API will not carry the session cookie',
            'A state-changing `GET /account/delete?confirm=1` can still be triggered by a cross-site link',
            'A compromised `blog.shop.com` can still send same-site requests with the cookie to `shop.com`',
            '`Lax` makes CSRF tokens unnecessary on every endpoint of every app',
          ],
          answer: [0, 1, 2],
          explain: '`Lax` blocks the classic cross-site form post. It does not help if a `GET` changes state (top-level navigations carry the cookie), and it does nothing against a sibling subdomain, which is the same site. It is strong defence in depth, not a replacement for keeping `GET` safe and checking `Origin` or a token on sensitive writes.',
        },
        {
          q: 'A response sets `Set-Cookie: sid=abc; SameSite=None; HttpOnly` on `https://api.shop.com`. What does the browser do?',
          options: [
            'Stores it and sends it on all requests, including cross-site ones',
            'Rejects the cookie entirely: `SameSite=None` requires `Secure`',
            'Stores it as `SameSite=Lax`',
            'Stores it but never sends it, because `HttpOnly` cookies are not sent cross-site',
          ],
          answer: [1],
          explain: 'Modern browsers drop a `SameSite=None` cookie without `Secure`, and log a warning in the console — the Set-Cookie is simply ignored, so the login "does not stick". `HttpOnly` is unrelated: it hides the cookie from `document.cookie`, not from requests.',
        },
      ],
    },
    {
      id: 'web-cache-headers',
      title: 'Cache-Control, ETags and 304s for static assets',
      kind: 'node',
      xp: 90,
      why: 'Wrong caching headers either make every visit re-download the bundle or strand users on a stale index.html after a deploy.',
      tags: ['caching', 'http', 'etag', 'deploy'],
      hints: [
        'Precompute each asset once: its bytes (`Buffer.from(body)` for a string), its ETag and its `cache-control`. `Buffer.byteLength` / `bytes.length` gives bytes; `string.length` gives UTF-16 units.',
        'A strong ETag is a quoted hash: `` `"${createHash(\'sha256\').update(bytes).digest(\'base64url\')}"` ``.',
        'The fingerprint test is one anchored regex on the pathname: a `.` or `-`, then `[0-9a-f]{8,}`, then `\\.[a-z0-9]+$`. Check it before the `.html` / `/` rule.',
        'For `If-None-Match`, split on `,`, trim each tag, strip a leading `W/`, and compare with `===`. `includes` on the raw header matches tags that merely contain yours.',
        'On a match: `writeHead(304, { etag, \'cache-control\': … })` and `end()` with nothing. For `HEAD`, write the same headers as `GET` and `end()` without the body.',
      ],
    },
    {
      id: 'web-http-cache-client',
      title: 'A client-side HTTP cache that revalidates',
      kind: 'js',
      xp: 100,
      why: 'Service workers, BFFs and native apps all end up reimplementing the browser cache, and the usual version treats a 304 as an error.',
      tags: ['caching', 'etag', 'fetch', 'dedupe'],
      hints: [
        'Keep two maps: `entries` (url → `{ data, etag, freshUntil }`) and `inflight` (url → the promise of the current request).',
        'Parse `Cache-Control` into a small object: split on `,`, trim, lower-case, split each part on `=`. You need `no-store`, `no-cache` and `max-age`.',
        'Check `status === 304` before anything that looks at `ok`: a 304 is not 2xx. Take the new `freshUntil` from the 304\'s own headers.',
        'Dedupe by storing the promise, not the result: `pending = load(url).finally(() => inflight.delete(url))`. The `finally` is what makes a failure forgettable.',
        'Return `structuredClone(await pending)` from `get` (and clone the fresh-hit path too), so no caller ever holds the stored object.',
      ],
    },
    {
      id: 'web-http-boss',
      title: 'BOSS: a cross-origin API that prevents lost updates',
      kind: 'node',
      xp: 220,
      boss: true,
      why: 'Preflights, exposed headers, conditional requests and concurrent edits all meet in the first cross-origin admin API you build.',
      tags: ['cors', 'etag', 'concurrency', 'http'],
      hints: [
        'Structure: `res.setHeader(\'Vary\', \'Origin\')`, then answer preflights and return, then set the three CORS headers for an allowed origin with `setHeader` (so every later `writeHead` includes them), then route.',
        'Two comparisons: `If-None-Match` is weak (strip `W/` before comparing), `If-Match` is strong (a `W/` tag never equals the ETag). Both accept `*` and a comma-separated list.',
        'Follow the PUT order exactly: 428 when `if-match` is absent, 412 when it does not match, 415 on the media type (`split(\';\')[0].trim().toLowerCase()`), 400 on a bad body.',
        'Validation: `Number.isInteger(price) && price >= 0` and `typeof name === \'string\' && name.length > 0`. `JSON.parse(\'null\')` and `JSON.parse(\'[]\')` succeed, so check the result is an object.',
        'The race: two PUTs both pass the `If-Match` check, then both wait for their bodies. After the body is read, check `If-Match` against the current version **again**, and write synchronously right after that check.',
      ],
    },
  ],
});
