import { loadChapter } from '../../load.ts';

const here = import.meta.dirname;

export default loadChapter(here, {
  id: 'sql-performance-2',
  title: "Query Performance II",
  summary: "Index types, partial, covering and expression indexes, reading plans, statistics, pagination at scale.",
  lessons: [
    {
      id: 'sql-sargable-rewrites',
      title: 'Make the WHERE clause searchable',
      kind: 'sql',
      xp: 80,
      why: 'The most common "the index isn\'t used" ticket is a function wrapped around an indexed column, and the fix is a rewrite, not another index.',
      tags: ['indexes', 'sargable', 'explain', 'ranges'],
      hints: [
        'The index is sorted by the bare column. Anything that computes a value from the column per row — a cast, `extract`, arithmetic, `coalesce` — hides it from the index.',
        'Turn a function of the column into a range of the column: a day is `created_at >= \'2024-01-15T00:00:00Z\' and created_at < \'2024-01-16T00:00:00Z\'`, and a year works the same way. Half-open: `<` the next boundary, not `between`.',
        'Move the arithmetic to the constant: `total_cents > 5000`. Check the edge: `total_cents / 100 > 50` is integer division and would drop 5001–5099.',
        '`coalesce(status, \'new\') = \'new\'` means `status = \'new\' or status is null`. A B-tree indexes NULLs, so both halves can use `orders_status_idx`.',
      ],
    },
    {
      id: 'sql-full-text-search',
      title: 'Full-text search instead of ILIKE',
      kind: 'sql',
      xp: 90,
      why: 'Every app grows a search box; Postgres full-text search with a GIN index covers most of them before anyone needs Elasticsearch.',
      tags: ['full-text search', 'gin', 'generated columns', 'ranking'],
      hints: [
        '`ilike \'%x%\'` compares characters. Full-text search compares lexemes: `to_tsvector(\'english\', \'Deployed!\')` is `\'deploy\':1`, and so is the parsed query for "deploying".',
        'The column: `alter table articles add column search tsvector generated always as (setweight(to_tsvector(\'english\', title), \'A\') || setweight(to_tsvector(\'english\', body), \'B\')) stored;`',
        'The index: `create index articles_search_idx on articles using gin (search);` — GIN indexes each lexeme, which is what `@@` looks up.',
        '`plainto_tsquery` ignores quotes, `or` and `-`. `websearch_to_tsquery(\'english\', p_query)` understands them and never raises a syntax error.',
        'In the function: `select a.id, a.title, ts_rank(a.search, query) as rank from articles a, websearch_to_tsquery(\'english\', p_query) as query where a.published and a.search @@ query order by rank desc, a.id limit 20`.',
      ],
    },
    {
      id: 'sql-brin-time-series',
      title: 'BRIN for append-only time series',
      kind: 'sql',
      xp: 75,
      why: 'Log, event and metrics tables outgrow their B-trees; a BRIN index is a thousandth of the size, but only on a column whose order follows the table\'s.',
      tags: ['brin', 'index types', 'statistics', 'time series'],
      hints: [
        'Index syntax for another access method: `create index … on readings using brin (recorded_at) with (pages_per_range = 32);`',
        'BRIN only helps when neighbouring rows on disk have neighbouring values. `device_time` is scattered, so it gets a plain `create index readings_device_time_idx on readings (device_time);`',
        '`pg_stats` is empty until the table is analyzed. Put `analyze readings;` before the final query.',
        'The last statement: `select attname, correlation from pg_stats where tablename = \'readings\' and attname in (\'recorded_at\', \'device_time\') order by attname;`',
      ],
    },
    {
      id: 'sql-extended-statistics',
      title: 'Fix estimates for correlated columns',
      kind: 'sql',
      xp: 85,
      why: 'A plan is only as good as its row estimates; when two filters are correlated, the planner is wrong by orders of magnitude and ANALYZE alone cannot fix it.',
      tags: ['statistics', 'query planner', 'explain', 'estimates'],
      hints: [
        'The per-column statistics are fine. What the planner lacks is how the columns relate: the district determines the city, and the city determines the country.',
        'For the filter: `create statistics addresses_district_city_stats (dependencies) on district, city from addresses;`',
        'For the grouping, a different kind: `create statistics … (ndistinct) on city, country from addresses;`',
        '`CREATE STATISTICS` only declares the object. End with `analyze addresses;` so it has data.',
      ],
    },
    {
      id: 'sql-fk-index-report',
      title: 'Find the foreign keys nobody indexed',
      kind: 'sql',
      xp: 90,
      why: 'An unindexed foreign key turns every parent delete into a table scan per child table; a catalog query in CI catches it before production does.',
      tags: ['indexes', 'foreign keys', 'system catalogs'],
      hints: [
        'Start from `pg_constraint c join pg_class t on t.oid = c.conrelid join pg_namespace n on n.oid = t.relnamespace where c.contype = \'f\' and n.nspname = \'public\'`, and keep the rows for which `not exists (select 1 from pg_index i where i.indrelid = c.conrelid and …)`.',
        'The conditions on the index: `i.indpred is null` (not partial) and `i.indnkeyatts >= cardinality(c.conkey)` (enough key columns, so `INCLUDE` columns never count).',
        'Compare the first n index columns with the key\'s columns as sets: sort both. `(select array_agg(x order by x) from unnest((i.indkey::int2[])[0:cardinality(c.conkey) - 1]) as x) = (select array_agg(x order by x) from unnest(c.conkey) as x)`.',
        'For `columns`: `(select string_agg(a.attname, \', \' order by k.ord) from unnest(c.conkey) with ordinality as k(attnum, ord) join pg_attribute a on a.attrelid = c.conrelid and a.attnum = k.attnum)`. Cast the names with `::text`.',
      ],
    },
    {
      id: 'sql-deferred-join',
      title: 'Deep pages with a deferred join',
      kind: 'sql',
      xp: 85,
      why: 'OFFSET reads and discards every skipped row; when users really do jump to page 151, a deferred join keeps the discarding inside the index.',
      tags: ['pagination', 'offset', 'index-only scan', 'explain'],
      hints: [
        'Split the work: which 20 products are on the page is a question the index can answer on its own, because it holds `category_id`, `created_at` and `id`.',
        'The inner query: `select id from products where category_id = 3 order by created_at desc, id desc offset 3000 limit 20`. Selecting only `id` is what makes an Index Only Scan possible.',
        'Join it back: `from (…inner…) as page join products p on p.id = page.id`, selecting the five columns from `p`.',
        'Finish with `order by p.created_at desc, p.id desc`: the join may return the 20 rows in any order.',
      ],
    },
    {
      id: 'sql-count-estimates',
      title: 'Counts at scale: estimates and capped counts',
      kind: 'sql',
      xp: 80,
      why: 'An exact count(*) behind every "N results" label is a full scan per page view; estimates and capped counts are how large tables keep pagination fast.',
      tags: ['count', 'statistics', 'explain', 'pagination'],
      hints: [
        'The estimate is already computed for every plan. `explain (format json) select …` returns it without running the query, as `Plan Rows`.',
        'In PL/pgSQL: `declare plan json; begin execute \'explain (format json) \' || p_query into plan; return (plan -> 0 -> \'Plan\' ->> \'Plan Rows\')::bigint; end;`',
        '`select case when reltuples < 0 then null else reltuples::bigint end from pg_class where oid = p_table` — a `regclass` compares directly with `pg_class.oid`.',
        'The capped count: `select count(*) into n from (select 1 from events where account_id = p_account limit 1001) as capped;` then `if n <= 1000 then return query select n, true; else return query select estimated_count(format(\'select * from events where account_id = %s\', p_account)), false; end if;`',
      ],
    },
    {
      id: 'sql-plan-reading',
      title: 'Reading EXPLAIN ANALYZE like a mid-level engineer',
      kind: 'quiz',
      xp: 70,
      why: 'A slow query ticket is solved by reading the plan; knowing which number to trust first saves the hour spent adding indexes that were never the problem.',
      tags: ['explain', 'query planner', 'statistics', 'performance'],
      quiz: [
        {
          q: 'After last night\'s bulk import into `order_lines`, a report went from 200 ms to 90 s. The plan has `Nested Loop (rows=12) (actual rows=48000 loops=1)` over `Seq Scan on order_lines (rows=12) (actual rows=48000 loops=1)` and an inner `Index Scan on products (actual rows=1 loops=48000)`. What do you try first?',
          options: [
            'Add an index on `order_lines` so the sequential scan goes away',
            'Raise `work_mem` so the join can be done in memory',
            '`ANALYZE order_lines`: the planner expected 12 rows and chose a nested loop for 12; statistics predate the import',
            'Rewrite the join as a CTE so the planner cannot reorder it',
          ],
          answer: [2],
          explain: 'Estimate 12, actual 48,000: the plan is built for a different table. A nested loop is the right join for 12 outer rows and a poor one for 48,000. Bulk loads outrun autovacuum\'s analyze; running ANALYZE after a large import (or in the import job itself) lets the planner pick a hash join. An index would not fix the estimate, and work_mem only matters once the planner chooses a hash or sort.',
        },
        {
          q: 'A node reads `Index Scan using order_lines_order_id_idx on order_lines (actual time=0.009..0.015 rows=2 loops=40000)`. About how much time did this node take in total?',
          options: [
            '0.015 ms',
            'About 600 ms',
            'About 40 s',
            'It cannot be known without BUFFERS',
          ],
          answer: [1],
          explain: '`actual time` is per loop, and this node ran 40,000 times: 0.015 ms × 40,000 ≈ 600 ms. Each lookup is fast; there are just a lot of them. This is how an N+1 looks inside one query, and the fix is usually a different join strategy or fewer outer rows, not a faster index.',
        },
        {
          q: '`Seq Scan on events (cost=… rows=40) (actual rows=38 loops=1)  Filter: (session_id = \'…\')  Rows Removed by Filter: 5999962`. What does it tell you?',
          options: [
            'The estimate is badly wrong, so the table needs ANALYZE',
            'The table is bloated and needs VACUUM FULL',
            'Nothing is wrong: sequential scans are the fastest way to read a table',
            'The query reads 6 million rows to return 38; an index on `session_id` would turn it into a lookup',
          ],
          answer: [3],
          explain: 'The estimate (40) matches the actual (38), so statistics are fine. The waste is in `Rows Removed by Filter`: six million rows read and discarded. That is the signature of a missing index on a selective filter. A sequential scan is the right choice when you want most of a table, not 38 rows of it.',
        },
        {
          q: 'A nightly export has `Sort (actual rows=4000000) Sort Key: created_at  Sort Method: external merge  Disk: 612000kB`. Which changes would remove the disk sort? Select all that apply.',
          options: [
            'Raise `work_mem` for this job\'s session (`SET work_mem = \'1GB\'`) so the sort fits in memory',
            'An index on `created_at`, so rows can be read already in order',
            'Raise `shared_buffers`',
            'Run `VACUUM ANALYZE` on the table first',
          ],
          answer: [0, 1],
          explain: 'The sort spilled because it needed more than `work_mem`. Raising it for one session is safe; raising it globally is not, because every sort and hash in every connection may use that much. An index in the sort order lets the plan skip the sort entirely. `shared_buffers` is the page cache, not sort memory, and statistics do not change how much there is to sort.',
        },
        {
          q: 'In the plan for a slow dashboard query you see `Seq Scan on countries (actual rows=48 loops=1)` feeding a hash join. What should you do about it?',
          options: [
            'Nothing: reading a 48-row table sequentially is the cheapest way to build the hash',
            'Add an index on the join column of `countries`',
            'Force an index scan with `enable_seqscan = off`',
            'Cache `countries` in the application instead',
          ],
          answer: [0],
          explain: 'A small table fits in a page or two; a sequential scan reads them once, which beats any index. "Seq Scan" is not a smell by itself; look for large `rows`, large `Rows Removed by Filter`, or a big gap between estimate and actual. `enable_seqscan = off` is a diagnostic switch, never a fix.',
        },
        {
          q: '`select * from tasks where status = $1` is fast in psql with `status = \'failed\'` (0.1% of rows) but, from the app, becomes slow after the service has been up a few minutes. What is the likeliest explanation?',
          options: [
            'The app\'s connection pool is exhausted',
            'Autovacuum is running and locking the table',
            'The driver uses a prepared statement; after five executions Postgres may switch to a generic plan chosen without the value, which suits common statuses and not the rare one',
            'psql uses a different isolation level from the app',
          ],
          answer: [2],
          explain: 'Parameterised queries are usually prepared. For the first five executions Postgres plans with the actual value; then, if a generic plan looks no worse on average, it keeps that one for every value. For skewed columns that average is wrong for the rare values. Confirm with `EXPLAIN (ANALYZE) EXECUTE …` or auto_explain; fixes include `plan_cache_mode = force_custom_plan` for that query\'s session, or a partial index for the rare status.',
        },
      ],
    },
    {
      id: 'sql-index-workload-boss',
      title: 'Boss: an index set for a real workload',
      kind: 'sql',
      xp: 220,
      boss: true,
      why: 'Indexing is a budget: every index speeds some reads and slows every write, and the job is to serve the whole workload with the fewest.',
      tags: ['indexes', 'partial indexes', 'expression indexes', 'explain'],
      hints: [
        'Start by dropping: `tickets_status_idx` narrows nothing, `tickets_subject_idx` indexes a column nobody searches raw, and `tickets_tenant_idx` is a prefix of anything that starts with `tenant_id`.',
        'W1 and W5 can share one index: `(tenant_id, status, created_at desc, id desc)`. Equality columns first, then the sort columns in the `ORDER BY`\'s direction.',
        'W2 cannot put `status` in the key without breaking the order (the `IN` makes two sorted runs). Keep it out of the key with a partial index: `(assignee_id, priority desc, created_at, id) where status in (\'open\', \'pending\')`.',
        'W3 needs the expression itself in the key: `(tenant_id, lower(subject))`. W4 is a partial index: `(updated_at) where status = \'pending\'`.',
      ],
    },
  ],
});
