import { loadChapter } from '../../load.ts';

const here = import.meta.dirname;

export default loadChapter(here, {
  id: 'js-functional',
  title: "Functional Tools That Earn Their Keep",
  summary: "Reducers, currying where it helps, lenses, immutable updates, composition in real code.",
  lessons: [
    {
      id: 'js-predicate-builders',
      title: 'Currying that helps: predicate builders',
      kind: 'js',
      xp: 70,
      why: 'Every list screen has filters, and building them from small tested parts beats one lambda that grows a clause per feature.',
      tags: ['currying', 'composition', 'filtering'],
      hints: [
        'Every builder returns a function. `prop` splits the path once and returns `(item) => keys.reduce((v, k) => (v == null ? undefined : v[k]), item)`.',
        'For the curried `propEq`, take `(path, ...rest)` and check `rest.length`: zero means "return `(value) => predicate`". Checking `value === undefined` breaks `propEq(\'deletedAt\', undefined)`.',
        'For `includesText`, normalise the query first (`String(q ?? \'\').trim().toLowerCase()`); if it is empty, return `() => true`.',
        '`fromQuery` pushes conditions into an array and returns `allOf(...conditions)`. For the bounds, reject blank strings *before* `Number()`, then keep only `Number.isFinite` values. For `status`, `split(\',\')` and `anyOf(...values.map(propEq(\'status\')))`.',
      ],
    },
    {
      id: 'js-lenses',
      title: 'Lenses: composable focus on nested state',
      kind: 'js',
      xp: 85,
      why: 'Updating "the title of todo 42" in several places is a lens; composing them keeps nested immutable updates short and shared-structure safe.',
      tags: ['lenses', 'immutability', 'composition'],
      hints: [
        '`prop(key)`: `get` is `whole == null ? undefined : whole[key]`. `set` first checks the no-op rule (`Object.hasOwn` and `Object.is`), then copies one level: `[]`/`{}` for a missing whole, `slice()` for an array, spread for an object.',
        '`find(pred)`: use `findIndex`; return the same array when the index is `-1` or the element is already the value, otherwise `slice()` and replace.',
        '`compose` set works inside out: to set through lenses `i..n`, get the current inner value with `lenses[i].get(whole)`, set the rest into it recursively, then `lenses[i].set(thatResult, whole)`. The no-op rule then propagates up by itself.',
        '`over(l, fn, ...rest)`: build `run = (whole) => l.set(fn(l.get(whole)), whole)` and return `rest.length ? run(rest[0]) : run`. Same shape for `view` and `set`.',
      ],
    },
    {
      id: 'js-reducer-combine',
      title: 'Reducers that return the same state',
      kind: 'js',
      xp: 80,
      why: 'Reference equality is how React and Redux skip work; a root reducer that always returns a new object re-renders the whole app.',
      tags: ['reducers', 'immutability', 'redux'],
      hints: [
        'In `createReducer`, check `Object.hasOwn(handlers, action.type)` before calling; otherwise return `state`. Throw if the handler returned `undefined`.',
        'In `combineReducers`, build `next` by calling every slice reducer and track `changed` whenever a slice is `!==` its previous value. Return `changed ? next : state`.',
        'Extra keys in `state` that have no reducer also count as a change: start with `changed = Object.keys(state).some((k) => !Object.hasOwn(reducers, k))`.',
        'For `createAction`, create a function and attach `type`, `toString = () => type` and `match`. The `toString` is what makes `{ [todoAdded]: handler }` produce the right key.',
      ],
    },
    {
      id: 'js-higher-order-reducers',
      title: 'Higher-order reducers: stale responses and per-key state',
      kind: 'js',
      xp: 85,
      why: 'Loading state per request and per row is in every app, and the stale-response race is one of the most common async UI bugs.',
      tags: ['reducers', 'composition', 'race conditions'],
      hints: [
        'Each function returns `(state, action) => …`. `withReset` is a single conditional; `filterActions` returns `state` when it is defined and the predicate says no.',
        'In `requestStatus`, `pending` always wins and stores `action.meta.requestId`. For `fulfilled`/`rejected`, return `state` unless `state.requestId !== null && action.meta?.requestId === state.requestId`.',
        'In `keyedBy`, read the previous slice with `Object.hasOwn(state, key) ? state[key] : undefined`, so a key like `constructor` does not start from a function.',
        'If the slice reducer returns the same slice, return `state`; otherwise `{ ...state, [key]: next }`. A brand-new key always changes (from `undefined` to the initial state).',
      ],
    },
    {
      id: 'js-entity-adapter',
      title: 'Normalised state: an entity adapter',
      kind: 'js',
      xp: 90,
      why: 'Lists of API records become `ids` + `entities` in any app with a cache; getting the sharing and ordering right is what keeps it fast.',
      tags: ['normalisation', 'immutability', 'state management'],
      hints: [
        'Write one internal `change(state, edit)`: make working copies (`ids.slice()`, `{ ...entities }`), let `edit` mutate them and return whether anything changed. If nothing did, return `state`.',
        'Inside `change`, after editing: if there is a `sortComparer`, sort a copy of the ids by it (`Array#sort` is stable). Then reuse `state.ids` if the new list is element-for-element the same.',
        'Implement per-item steps (`insert`, `merge`, `remove`) that each return a boolean, and build every `…Many` as `change(state, (d) => items.reduce((changed, item) => step(d, item) || changed, false))`. The `…One` versions wrap one item in an array.',
        '`merge` is a no-op when every key of `changes` is already an own key with an `Object.is`-equal value. If `selectId(updated)` differs from the old id, delete the old key and put the new id at the old position in `ids`. Use `Object.hasOwn` for every existence check.',
      ],
    },
    {
      id: 'js-tree-transforms',
      title: 'Recursive transforms on trees',
      kind: 'js',
      xp: 85,
      why: 'Menus, category pickers, file trees and threads need search, breadcrumbs, flattening and deep updates that do not re-render everything.',
      tags: ['recursion', 'trees', 'immutability'],
      hints: [
        '`filterTree`: for each node, filter its children first (when it has a `children` array). Keep the node if it matches or the filtered children are non-empty.',
        'Track whether anything changed: a dropped node, or children that came back as a different array. Keep `node` itself when its children array came back identical, and return the original `nodes` array when nothing changed at this level.',
        '`findPath` returns `[node]` on a match, or `[node, ...below]` when a recursive call on the children returns a non-empty path. `flatten` is a recursive `walk(forest, depth, parentId)` that only descends when `isExpanded(node)`.',
        'For `updateNode`, have a helper return `{ forest, found }` so you can stop at the first match even when `fn` changed nothing. Copy the array only when the replacement node differs: `copy = forest.slice(); copy[i] = replacement`.',
      ],
    },
    {
      id: 'js-state-diff',
      title: 'Diff and patch immutable state',
      kind: 'js',
      xp: 90,
      why: 'Audit logs, undo, and syncing over a socket all need "what changed", and structural sharing makes computing it cheap.',
      tags: ['immutability', 'diffing', 'recursion'],
      hints: [
        'Have `diff` create the `ops` array and call a recursive `walk(prev, next, path, ops)`. The first line of `walk` is `if (Object.is(prev, next)) return;`, before anything reads a property.',
        'Plain objects: loop over `Object.keys(next)` (add or recurse), then `Object.keys(prev)` for removals. Arrays: recurse over the common length, add the extra `next` indexes, then remove the extra `prev` indexes from the highest down.',
        'Before falling through to `replace`, return early for two `Date`s with the same `getTime()`.',
        '`applyPatch` reduces over the ops. For one op, recurse down the path copying one container per level (`slice()` or spread); at the last key, `splice` for array add/remove, `delete` for object remove, assignment otherwise. A path of `[]` just returns `op.value`.',
      ],
    },
    {
      id: 'js-fp-quiz',
      title: 'Quiz: when functional style pays, and when it costs',
      kind: 'quiz',
      xp: 60,
      why: 'Code review is where functional habits either prevent bugs or add them; knowing which is which is the mid-level skill.',
      tags: ['functional', 'performance', 'code review'],
      quiz: [
        {
          q: 'Building a lookup of 50,000 users takes several seconds:\n\n```js\nconst byId = users.reduce((acc, u) => ({ ...acc, [u.id]: u }), {});\n```\n\nWhat is the problem and the fix?',
          options: [
            '`reduce` is inherently slower than a loop; rewrite it with `for...of` and keep the spread',
            'Each step copies the whole accumulator, so it is O(n²). Mutating the accumulator you created (`acc[u.id] = u; return acc;`) or `Object.fromEntries(users.map((u) => [u.id, u]))` is O(n) and still pure from the outside',
            'Computed property keys deoptimise the object; use a `Map` with the same spread',
            'The accumulator should be frozen so the engine can optimise it',
          ],
          answer: [1],
          explain: 'Immutability matters for values **other code can see**. The accumulator is created inside this expression and nobody else holds it, so mutating it is invisible from outside: the function stays pure. Spreading it on every step copies 1, 2, 3 … n keys, which is quadratic. The loop is not the problem, and a `Map` rebuilt with spread has the same cost.',
        },
        {
          q: 'What does `[\'10\', \'10\', \'10\'].map(parseInt)` return?',
          options: [
            '`[10, 10, 10]`',
            '`[\'10\', \'10\', \'10\']`',
            '`[10, NaN, 2]`',
            'It throws, because `parseInt` expects one argument',
          ],
          answer: [2],
          explain: '`map` calls its callback with `(value, index, array)`, and `parseInt` takes `(string, radix)`: the calls are `parseInt(\'10\', 0)` (radix 0 means "guess": 10), `parseInt(\'10\', 1)` (invalid radix: `NaN`) and `parseInt(\'10\', 2)` (binary: 2). Passing a function reference point-free is only safe when you know its full signature: write `.map((s) => parseInt(s, 10))` or `.map(Number)`.',
        },
        {
          q: 'A selector is `const selectByDate = (state) => state.todos.sort(byDueDate);`. Which statements are true? Select all that apply.',
          options: [
            'It reorders the array inside the store, so every other reader now sees the sorted order too',
            'It returns the same array reference it was given, so a memoised component compares equal and may not re-render even though the order changed',
            'It is fine, because `sort` is stable since ES2019',
            '`state.todos.toSorted(byDueDate)` (or `[...state.todos].sort(byDueDate)`) fixes it',
          ],
          answer: [0, 1, 3],
          explain: '`Array#sort` sorts **in place** and returns the same array. In a selector that means mutating store state (other readers and devtools see it change without an action) and handing out a reference that is `===` to the previous one, which is exactly what memoisation treats as "nothing changed". Stability is about the order of equal elements, not about mutation. `toSorted` (ES2023) returns a new array.',
        },
        {
          q: 'Which of these functions are pure (same inputs, same output, no side effects)? Select all that apply.',
          options: [
            '`(cart) => cart.items.reduce((sum, i) => sum + i.price * i.qty, 0)`',
            '`(order) => ({ ...order, placedAt: Date.now() })`',
            '`(list, item) => { list.push(item); return list; }`',
            '`(cents, rate) => Math.round(cents * rate)`',
          ],
          answer: [0, 3],
          explain: 'The totals and the rounding depend only on their arguments and change nothing. `Date.now()` is an input the caller does not pass (the same order gives a different result a millisecond later), so inject `now` as a parameter if you want it testable. `push` mutates the caller\'s array: a side effect, even though it returns something.',
        },
        {
          q: 'In a codebase that is not otherwise written in a functional style, which curried helper is the clearest win?',
          options: [
            'Currying every utility so it can be used point-free, e.g. `add(1)(2)(3)`',
            'A curried `fetchJson(baseUrl)(token)(path)` that is always called once with all three arguments',
            'Rewriting a readable loop as `pipe(map(prop(\'price\')), filter(gt(0)), sum)`',
            '`const byStatus = (status) => (order) => order.status === status;` used as `orders.filter(byStatus(\'paid\'))`',
          ],
          answer: [3],
          explain: 'Currying pays when a function is **configured in one place and applied in another**, typically as a callback: a predicate for `filter`, an updater for `setState`, middleware. When every call site passes all the arguments at once, currying only adds parentheses, and a point-free chain the team cannot read is a maintenance cost, not a style win.',
        },
        {
          q: 'To "be safe", a reducer returns `structuredClone({ ...state, filter: action.payload })`. After this change, typing in the filter box is sluggish and every list row re-renders on each keystroke. Why?',
          options: [
            'Deep cloning gives every object in the state a new identity, so every memoised selector and `React.memo` row sees a change, even in data that did not change',
            '`structuredClone` is asynchronous, so the state is out of date for one render',
            '`structuredClone` drops the `filter` key',
            'The reducer is now impure',
          ],
          answer: [0],
          explain: 'Reference equality is how the whole stack skips work: `useSelector`, `useMemo`, `React.memo` and `useSyncExternalStore` all ask "is this the same object?". Structural sharing (copy only what changed) keeps the untouched parts identical; a deep clone makes everything new, so nothing can be skipped. `structuredClone` is synchronous, and the reducer is still pure; it is just expensive and defeats memoisation.',
        },
      ],
    },
    {
      id: 'js-store-middleware',
      title: 'BOSS: a Redux-style store with middleware',
      kind: 'js',
      xp: 230,
      boss: true,
      why: 'The store, middleware and thunk pattern underlies Redux, and building it explains the currying, the reducer rules and the dispatch chain you use every day.',
      tags: ['reducers', 'middleware', 'currying'],
      hints: [
        'Keep `state`, a `reducing` flag and a `Set` of listeners in the closure. `getState`, `subscribe` and the base dispatch all start by throwing if `reducing` is true.',
        'The base dispatch validates the action, sets `reducing = true`, calls the reducer inside `try { … } finally { reducing = false; }`, and only notifies when the new state is `!==` the old one.',
        'For the notification round, iterate over a copy (`[...listeners]`) and call each one only if `listeners.has(it)` is still true. Store a wrapper per `subscribe` call so the same function can be subscribed twice.',
        'Middleware: start with `let dispatch = () => { throw new Error(\'…middleware…\') }`, give each middleware `api = { getState, dispatch: (a) => dispatch(a) }`, build `chain = middleware.map((mw) => mw(api))`, then `dispatch = chain.reduceRight((next, link) => link(next), baseDispatch)`. The arrow in `api.dispatch` is what makes it reach the finished chain later.',
        '`thunk` is one line: `(api) => (next) => (action) => typeof action === \'function\' ? action(api.dispatch, api.getState) : next(action)`.',
      ],
    },
  ],
});
