import { loadChapter } from '../../load.ts';

const here = import.meta.dirname;

export default loadChapter(here, {
  id: 'design-patterns',
  title: "Patterns That Show Up at Work",
  summary: "Strategy, observer, adapter, command with undo, state machines, dependency injection.",
  lessons: [
    {
      id: 'design-strategy-shipping',
      title: 'Strategy: shipping options without the if-chain',
      kind: 'js',
      xp: 75,
      why: 'Parallel `if (method === ...)` chains are where "add one more option" bugs come from; a strategy object keeps each option\'s rules in one place.',
      tags: ['strategy', 'open-closed', 'polymorphism'],
      hints: [
        'Each built-in is a plain object literal with the four members. No classes needed.',
        'For express, compute `extraGrams = Math.max(0, weightGrams - 2000)` and charge `150 * Math.ceil(extraGrams / 1000)` on top of 999.',
        'In `quotes`, `filter` by `isAvailable` **before** you `map` to `costCents` — a strategy may throw when priced for an order it cannot serve.',
        '`Array.prototype.sort` is stable, so sorting by `a.costCents - b.costCents` keeps equal costs in their original order. Build a `Map` from id to strategy up front; that is also where you detect duplicates.',
      ],
    },
    {
      id: 'design-observer-store',
      title: 'Observer: a store widgets can subscribe to',
      kind: 'js',
      xp: 90,
      why: 'Every state library is an observer with opinions about identity, selectors and batching; those opinions decide whether your UI re-renders once or fifty times.',
      tags: ['observer', 'state', 'subscriptions'],
      hints: [
        'Keep listeners in a `Set` of small wrapper objects `{ call(next, prev) }`. `subscribe` and `select` both add a wrapper, so they share one ordered list.',
        'For a partial, only build a new object if `Object.keys(partial).some((k) => !Object.is(state[k], partial[k]))`. Then one `notify(prev)` that returns early when `Object.is(prev, state)` covers every "no change" case.',
        'In `notify`, loop over `[...listeners]` (a snapshot, so late subscribers wait) but call an entry only if `listeners.has(entry)` is still true (so a just-removed one is skipped).',
        'A `select` wrapper remembers `last = selector(state)` in a closure. On each call: compute `next = selector(state)`; if `equals(last, next)` return; otherwise swap and call `listener(next, previous)`.',
        'For `batch`, keep a depth counter and the state at depth 0. `setState` skips `notify` while depth > 0; the outermost `batch` calls `notify(stateBeforeBatch)` in a `finally`, which also covers the throwing case.',
      ],
    },
    {
      id: 'design-adapter-payments',
      title: 'Adapter: two payment SDKs, one interface',
      kind: 'js',
      xp: 85,
      why: 'Migrations, vendor swaps and test fakes all depend on your code talking to an interface you own rather than to a third-party SDK\'s quirks.',
      tags: ['adapter', 'integration', 'money', 'errors'],
      hints: [
        'Write two small pure helpers first: `centsToDecimal(1999) === \'19.99\'` and `decimalToCents(\'19.99\') === 1999`. Every other part of the legacy adapter is plumbing around them.',
        'For `centsToDecimal`, split into `Math.trunc(cents / 100)` and `String(cents % 100).padStart(2, \'0\')`. For the reverse, a regex like `/^(\\d+)(?:\\.(\\d{1,2}))?$/` and `padEnd(2, \'0\')` on the fraction avoids floats entirely.',
        'Promisify the callback: `await new Promise((resolve, reject) => legacy.makePayment(req, (err, res) => err ? reject(wrap(err)) : resolve(res)))`.',
        'Validate `Number.isInteger(amountCents) && amountCents > 0` as the first line of each `async charge` — a `throw` there becomes the rejected promise the caller sees, and the SDK is never called.',
        'For modern, wrap only the SDK call in `try/catch`: `retryable: status == null || status >= 500`, and `super(message, { cause })` sets `cause`.',
      ],
    },
    {
      id: 'design-command-undo',
      title: 'Command: undo, redo and merged keystrokes',
      kind: 'js',
      xp: 95,
      why: 'Undo is only cheap if every change is already a command object; the redo-after-edit and delete-restores-at-the-end bugs are the ones reviewers look for.',
      tags: ['command', 'undo', 'state'],
      hints: [
        'Two arrays: `done` (undo stack) and `undone` (redo stack). `undo` pops from one, calls `undo()`, pushes to the other; `redo` is the mirror image but calls `execute()`.',
        'In `execute`, call `command.execute()` **first**. If it throws, you have not touched either stack yet, which is exactly the required behaviour.',
        'Keep one boolean, e.g. `topIsFresh`, set to `true` by `execute` and `false` by `undo`/`redo`. Only try `top.merge(command)` when it is `true`.',
        '`removeTodo` keeps `index` and `removed` in its closure, assigned inside `execute()`; `undo()` does `list.splice(index, 0, removed)`.',
        'Give renames the original text as a parameter: `rename(list, id, text, from)`. Its `merge(next)` returns `rename(list, id, next.text, from)` when `next` renames the same id — the new command keeps the first `from` and the last `text`.',
      ],
    },
    {
      id: 'design-di-password-reset',
      title: 'Dependency injection: a reset flow you can test in milliseconds',
      kind: 'js',
      xp: 85,
      why: 'Code that reads the clock, randomness or the network directly can only be tested slowly or not at all; passing them in is the cheapest testability win there is.',
      tags: ['dependency-injection', 'testability', 'security', 'time'],
      hints: [
        'Destructure the deps with defaults in the parameter list: `createPasswordResetService({ users, mailer, hashPassword, clock = Date.now, generateToken = defaultToken })`.',
        'Every place the starter says `Date.now()` becomes `clock()`, and `randomUUID()` becomes `generateToken()`. Do not call `clock()` once and keep the number.',
        'For "no enumeration", an unknown email simply `return`s — no throw, no email. To supersede, loop over the `Map` and delete every entry whose `userId` matches before storing the new token.',
        'In `resetPassword`, order matters: token check (`!record || clock() >= record.expiresAt`), then password length, then `await users.updatePassword(...)`, and only then `tokens.delete(token)`.',
      ],
    },
    {
      id: 'design-ticket-state-machine',
      title: 'An explicit state machine instead of four booleans',
      kind: 'js',
      xp: 85,
      why: 'Workflow entities (orders, tickets, payments) grow flags until impossible combinations reach production; a transition table makes illegal moves unrepresentable and loud.',
      tags: ['state-machine', 'workflow', 'guards'],
      hints: [
        'Write the table as data: `const machine = { open: { ASSIGN: fn, CLOSE: fn }, assigned: { … }, … }`, where each `fn(ticket, event)` returns the next ticket.',
        'Every handler starts with `{ ...t, … }` so untouched fields carry over and the input is never mutated.',
        'Let a guarded handler return `null` when the guard fails. Then one `next(ticket, event)` returns a ticket or `null`, `transition` throws on `null`, and `can` is `next(ticket, event) !== null` — they cannot disagree.',
        'Look the handler up with `Object.hasOwn(machine[ticket.status], event.type)` so `\'toString\'` is not treated as a legal event.',
      ],
    },
    {
      id: 'design-typed-transitions',
      title: 'A transition table the compiler enforces',
      kind: 'typecheck',
      xp: 90,
      why: 'Moving "is this event legal here?" into the type system turns a class of runtime bugs in UI connection and workflow code into red squiggles.',
      tags: ['state-machine', 'typescript', 'discriminated-unions'],
      hints: [
        '`Status` is `ConnState[\'status\']` and `EventType` is `ConnEvent[\'type\']`. `StateOf<S>` is `Extract<ConnState, { status: S }>`.',
        'Write `Transitions` literally: `{ disconnected: { CONNECT: \'connecting\' }; connecting: { OPENED: \'connected\'; … }; … }`.',
        '`EventFor<S>` is `Extract<ConnEvent, { type: keyof Transitions[S] }>`. Because it does not wrap `S` in a conditional, `keyof` sees the union and keeps only common keys.',
        '`NextStatus<S, T>` is `T extends keyof Transitions[S] ? Transitions[S][T] : never`; wrap the hit in `Extract<…, Status>` so it satisfies `StateOf`\'s constraint.',
        'Signature: `send<S extends ConnState, E extends EventFor<S[\'status\']>>(state: S, event: E): StateOf<NextStatus<S[\'status\'], E[\'type\']>>`, and end the body with `return next as StateOf<…>`.',
      ],
    },
    {
      id: 'design-patterns-judgement',
      title: 'When a pattern helps, and when it is ceremony',
      kind: 'quiz',
      xp: 60,
      why: 'Reviewers push back on missing abstractions and on premature ones equally; knowing which is which is most of design judgement.',
      tags: ['patterns', 'judgement', 'code-review'],
      quiz: [
        {
          q: 'Tax is computed in one function with an `if/else` over three countries. It has changed twice in two years. A colleague\'s PR replaces it with a `TaxStrategy` interface, three strategy classes, a registry and a factory. What is the best review comment?',
          options: [
            'Approve: patterns prevent future bugs, and it is cheaper to add them now than later.',
            'Ask to keep the `if/else` for now; extract strategies when the same branching appears in a second place or the branches grow their own rules.',
            'Ask to move the tax rates into a database table instead, so no code change is ever needed.',
            'Ask for an abstract base class instead of an interface, so shared logic has a home.',
          ],
          answer: [1],
          explain: 'A strategy pays off when there are **parallel** branchings on the same key (price here, availability there) or when each branch has grown real logic. One stable three-way `if` has neither problem; the PR adds indirection a reader must follow and a registry that can be misconfigured. "Extract when it hurts" is cheap here because the `if` is in one place. Moving rules to a database is a different trade-off (runtime changes without review) and not obviously better.',
        },
        {
          q: 'A React app subscribes components to a hand-written store with `store.subscribe(listener)` in `useEffect`. Memory grows with every page navigation and old pages\' listeners still log on updates. What is the most likely cause?',
          options: [
            'The store keeps listeners in a `Set`, which never shrinks.',
            'The components call `setState` with new objects instead of mutating.',
            'The effect does not return the unsubscribe function, so unmounted components stay subscribed.',
            'The selectors return new arrays every time, so listeners fire too often.',
          ],
          answer: [2],
          explain: 'The lapsed-listener problem is the classic observer leak: the subject holds a reference to every observer, so an observer that never unsubscribes is never collected — along with everything its closure captured. In React, the effect must `return unsubscribe`. Selector identity (option 4) causes extra renders, not leaks.',
        },
        {
          q: 'Which of these are good reasons to put an adapter in front of something? (Select all that apply.)',
          options: [
            'A third-party SDK with callbacks and decimal-string amounts, used from a dozen places.',
            'Giving tests a fake that implements the same small interface as production.',
            'Your own team\'s `pricing.js`, "in case we change it later".',
            'Converting a vendor\'s error shape into your own error types at the boundary.',
          ],
          answer: [0, 1, 3],
          explain: 'Adapters earn their keep at boundaries you do not control: they keep a vendor\'s quirks (and its eventual replacement) to one file, give you a seam for fakes, and translate foreign errors into ones your code can branch on. Wrapping your own module just adds a layer; if it changes, you can change it.',
        },
        {
          q: 'Product asks for "undo" on *Send newsletter to 40,000 subscribers*, alongside undo for editing the draft. What is the right design?',
          options: [
            'A command whose `undo()` sends a follow-up retraction email.',
            'Keep sending as a normal command in the same history; `undo()` can just mark it as unsent in the database.',
            'Refuse: undo is only for text editors.',
            'Treat sending as irreversible: delay the actual send (an "Undo send" window, or a scheduled send the user can cancel) and keep it out of the edit history.',
          ],
          answer: [3],
          explain: 'The command pattern only gives you undo when the effect is reversible. An email cannot be unsent; a "compensating" retraction is a different, visible action. The honest design delays the irreversible side effect so that cancelling is still possible, and keeps it off the undo stack so `Ctrl+Z` in the editor never pretends to recall mail. Marking it "unsent" in the database lies to the user.',
        },
        {
          q: 'You are making a `ReportService` testable. Which of these should become injected dependencies? (Select all that apply.)',
          options: [
            'The clock it uses to decide which month is "last month".',
            'The HTTP client it uses to fetch exchange rates.',
            'A pure `formatCurrency(cents, currency)` helper from your own utils.',
            'The ID generator it uses to name the exported file.',
          ],
          answer: [0, 1, 3],
          explain: 'Inject what is **non-deterministic or slow or external**: time, randomness/ids, network, email, the database. Those are what make tests flaky or slow and what you want to control. A pure, fast, deterministic helper gives the same answer in a test as in production — injecting it only adds parameters. Over-injection makes constructors long and hides the real seams.',
        },
        {
          q: 'An order has `status: \'pending\' | \'paid\' | \'shipped\'` and someone adds `isRefunded: boolean` for a new feature. What is the real problem?',
          options: [
            'Booleans are slower to query than strings.',
            'It makes impossible combinations representable (`pending` and refunded), and every place that reads `status` now has to remember the flag too.',
            'Nothing, as long as a code comment documents which combinations are valid.',
            'It should have been a number of refunds rather than a boolean.',
          ],
          answer: [1],
          explain: 'Every independent flag doubles the state space; most of the new combinations are nonsense, and nothing prevents them. Refunds are a lifecycle step, so they belong in the transition table (`paid → refunded`, maybe `partially_refunded`) where illegal moves are rejected in one place. A comment does not stop the bad write.',
        },
      ],
    },
    {
      id: 'design-notifier-boss',
      title: 'BOSS: a notifier that respects its users',
      kind: 'js',
      xp: 220,
      boss: true,
      why: 'Notifications are where strategy, injected time and observers meet real users: double sends, 3am texts and silent outages are all design bugs.',
      tags: ['strategy', 'observer', 'dependency-injection', 'idempotency'],
      hints: [
        'Build the pieces first: a `Map` of channels by id (throw on a duplicate), a `Map` of event type to a `Set` of listeners, and an `emit` that calls each listener inside its own `try/catch`.',
        'In `notify`, `await getPreferences(user.id)` first and spread it over the defaults: `{ ...DEFAULT_PREFERENCES, ...(await getPreferences(user.id)) }` works for `null` too. Then the checks, in the order the table gives.',
        'Quiet hours: `const hour = new Date(clock()).getUTCHours()`. If `start < end` it is quiet when `hour >= start && hour < end`; if `start > end` the range wraps, so it is quiet when `hour >= start || hour < end`.',
        'Deduplication needs two records: `lastSentAt` (a `Map` from `userId + key` to a time, written only on success) and an `inFlight` `Set`. Check both and add to `inFlight` with no `await` in between, then remove it in a `finally` around the routing loop.',
        'Routing: `for (const id of prefs.channels)`, skip unknown or unsupported channels, `attempted.push(id)`, then `try { await channel.send(user, message) } catch (error) { emit(\'failed\', …); continue; }`. `await` inside `try` turns a synchronous throw into a caught failure too.',
      ],
    },
  ],
});
