import { loadChapter } from '../../load.ts';

const here = import.meta.dirname;

export default loadChapter(here, {
  id: 'node-observability',
  title: "Observability",
  summary: "Counters and histograms, health checks, trace context propagation, request logs, error reporting.",
  lessons: [
    {
      id: 'node-metrics-registry',
      title: 'Counters, gauges and the cardinality trap',
      kind: 'node',
      xp: 85,
      why: 'Every service exposes metrics, and one unbounded label can take down the monitoring system. Knowing the exposition format and capping series is table stakes.',
      tags: ['observability', 'metrics', 'prometheus'],
      hints: [
        'Per metric keep a `Map` from a series key to `{ values, value }`, in insertion order (which gives you "first-seen" order for free). Registration pushes a `render()` function onto a registry-level array.',
        'Build the key from the values in `labelNames` order with `JSON.stringify(values)` — joining with `,` makes `{a:\'x,y\',b:\'z\'}` and `{a:\'x\',b:\'y,z\'}` the same series.',
        'Check labels with `Object.keys(labels).length === labelNames.length && labelNames.every((l) => Object.hasOwn(labels, l))`.',
        'The cap only applies when creating a series: `if (!series.has(key) && series.size >= maxSeries) { dropped++; return; }`.',
        'Escape label values with three `replace` calls, the backslash first, then `"`, then newlines — escaping the backslash last would double the backslashes you just added.',
      ],
    },
    {
      id: 'node-histogram',
      title: 'Histograms and why the average lies',
      kind: 'node',
      xp: 90,
      why: 'Latency SLOs are about p95 and p99, not the mean. Histograms are how services record them cheaply, and how dashboards estimate them.',
      tags: ['observability', 'metrics', 'latency', 'percentiles'],
      hints: [
        'Store per-bucket counts (non-cumulative) with one extra slot for `+Inf`: `counts[bounds.findIndex((le) => value <= le)]`, or the last slot when `findIndex` is -1. Make them cumulative only when you read them.',
        'Validate buckets with `every((b, i) => Number.isFinite(b) && (i === 0 || b > buckets[i - 1]))` — this catches unsorted, repeated and non-numeric bounds at once.',
        '`startTimer` captures `start = now()` and returns a closure with its own `seconds = null`; the first call computes `(now() - start) / 1000`, observes it and stores it.',
        'For `quantile`: `rank = q * count`; find the first cumulative bucket with `count >= rank`; if it is `+Inf`, return the last finite bound. Otherwise `lower = i === 0 ? 0 : bounds[i - 1]`, `below = i === 0 ? 0 : cum[i - 1].count`, and interpolate with `(rank - below) / (cum[i].count - below)`.',
      ],
    },
    {
      id: 'node-request-metrics',
      title: 'Request metrics with bounded labels',
      kind: 'node',
      xp: 95,
      why: 'RED metrics (rate, errors, duration) per route are the first dashboard of every service. Labelling them by raw URL is the classic way to take down Prometheus.',
      tags: ['observability', 'metrics', 'http', 'cardinality'],
      hints: [
        'Compile each template once: split on `/`, and at request time compare segment by segment — `:name` captures, anything else must be equal, and the segment counts must match.',
        'Decide the labels before calling the handler: `method = METHODS.has(req.method) ? req.method : \'other\'`, `route = matched ? template : \'unmatched\'`.',
        'Record inside `res.on(\'finish\', …)`, reading `res.statusCode` and `now()` there. Increment the in-flight gauge when the request arrives and decrement it in the same `finish` listener.',
        'Keep two maps keyed by `JSON.stringify([method, route, status])` and `JSON.stringify([method, route])`. For the histogram, increment every bucket with `seconds <= le` — that is what makes them cumulative.',
        'Handle `GET /metrics` before any of this so scrapes are not counted.',
      ],
    },
    {
      id: 'node-health-checks',
      title: 'Liveness, readiness and honest probes',
      kind: 'node',
      xp: 90,
      why: 'A liveness probe that checks the database restarts every pod during a database blip. Getting the two probes right is what keeps a small incident small.',
      tags: ['observability', 'kubernetes', 'timeouts', 'resilience'],
      hints: [
        '`/livez` is one line: it answers ok without touching `checks`. Everything interesting is in `/readyz`.',
        'Wrap each check in a promise that never rejects: create an `AbortController`, start `timers.setTimeout` that resolves `{ status: \'fail\', error: \'timeout\' }` and aborts, run `new Promise((r) => r(check(signal)))`, and let whichever settles first win via a `settled` flag. Clear the timer on the way out.',
        'Run them with `Promise.all(checks.map(runCheck))` so they start together. Then fold the outcomes: a failed critical check makes it `fail`; a failed non-critical one makes an `ok` into `degraded`.',
        'Share and cache with two variables: `inflight` (the promise of the running evaluation) and `cached = { result, finishedAt }`. Serve the cache while `now() - finishedAt < cacheMs`; otherwise reuse `inflight` or start one.',
        'Check `draining` first on every `/readyz`, before looking at the cache.',
      ],
    },
    {
      id: 'node-trace-context',
      title: 'W3C trace context across services',
      kind: 'node',
      xp: 90,
      why: 'A trace id that survives every hop is what turns three services\' logs into one story. Parsing it strictly and keeping it per request is where implementations go wrong.',
      tags: ['observability', 'tracing', 'async_hooks', 'http'],
      hints: [
        'One regex does most of the parsing: `/^([0-9a-f]{2})-([0-9a-f]{32})-([0-9a-f]{16})-([0-9a-f]{2})(-.*)?$/` (no `i` flag). Then reject version `ff`, a trailing part when the version is `00`, and all-zero ids with `/^0+$/`.',
        'Make one `AsyncLocalStorage` per tracing instance. `middleware` builds the context, sets `x-trace-id`, and returns `storage.run(ctx, () => handler(req, res))`.',
        'For a continued trace, `parentSpanId` is the incoming parent-id and `spanId` is new; `sampled` is `(flags & 1) === 1`. Only a new trace calls `sample()`.',
        '`outgoingHeaders` formats the stored context with **its own** `spanId`: the next service\'s parent is you. Add `tracestate` only if you kept one.',
      ],
    },
    {
      id: 'node-spans',
      title: 'Spans: a tiny tracer',
      kind: 'node',
      xp: 95,
      why: 'Every tracing SDK is this core: active spans, parent/child links, error status and export. Knowing it makes instrumentation and trace-reading far less mysterious.',
      tags: ['observability', 'tracing', 'async_hooks', 'errors'],
      hints: [
        'Make `startActiveSpan` an `async` function: it then always returns a promise, and a synchronous throw from `fn` becomes a rejection you can catch with `try/catch` around `await`.',
        'Read the parent from `storage.getStore()` **before** creating the new span, then run `fn` inside `storage.run({ traceId, spanId }, () => fn(span))` — concurrent siblings each get their own store.',
        'Keep an `ended` flag. `setAttribute` and `addEvent` check it; `end(status)` sets it, fills `endTime`, `durationMs` and `status`, and calls `exporter.export` inside a `try/catch`.',
        'In the `catch`: `span.addEvent(\'exception\', { \'exception.type\': error.name, \'exception.message\': error.message })`, then `end(\'error\')`, then `throw error` — the same object.',
      ],
    },
    {
      id: 'node-error-reporting',
      title: 'Error reporting without noise, leaks or crashes',
      kind: 'node',
      xp: 95,
      why: 'An error tracker full of 404s, split by user id, leaking passwords and out of quota by 9 a.m. is worse than none. These are the rules that make one useful.',
      tags: ['observability', 'errors', 'security', 'rate limiting'],
      hints: [
        'Fingerprint with two `replace` calls in order: first `/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/gi` → `<uuid>`, then `/\\d+/g` → `<n>`. The other order would chop the UUID\'s digits first.',
        'Keep per fingerprint `{ start, sent, suppressed }`. If there is none or `now() - start >= windowMs`, start a new window (carrying `suppressed` over). If `sent >= maxPerWindow`, increment `suppressed` and return false; otherwise send with the current `suppressed` and reset it to 0.',
        'Scrub recursively: arrays map; plain objects copy key by key, replacing the value when `needles.some((n) => key.toLowerCase().includes(n))`. Building new objects is also what leaves the caller\'s untouched.',
        'Call `transport` inside `try/catch`, and if it returned a promise, attach `.then(undefined, () => {})` so a rejection is handled.',
        'In `wrapHandler`, decide `clientError = Number.isInteger(error?.status) && status >= 400 && status <= 499` first; only report when it is false.',
      ],
    },
    {
      id: 'node-slo-burn-rate',
      title: 'SLOs, error budgets and burn-rate alerts',
      kind: 'node',
      xp: 85,
      why: 'Threshold alerts page for blips and miss slow leaks. Burn-rate alerting on an SLO is how modern on-call decides what is worth waking up for.',
      tags: ['observability', 'slo', 'alerting', 'operations'],
      hints: [
        'Write one `errorRatio(w)` that sums `total` and `errors` over buckets with `now - w <= start < now` and divides once at the end, returning 0 when the total is 0.',
        '`budget = 1 - objective`; every burn rate is `errorRatio(w) / budget`. The windows are 5, 30, 60 and 360 minutes.',
        'The alert needs both windows: `page` when `1h >= 14.4 && 5m >= 14.4`, else `ticket` when `6h >= 6 && 30m >= 6`.',
      ],
    },
    {
      id: 'node-observability-boss',
      title: 'BOSS: an observable service',
      kind: 'node',
      xp: 230,
      boss: true,
      why: 'Traces, metrics, probes and error reports only help on call if they agree with each other on every request. This is the wiring every production service needs.',
      tags: ['observability', 'tracing', 'metrics', 'health checks', 'errors'],
      hints: [
        'Handle the three infrastructure endpoints first, in the top-level handler, by `GET` and pathname. Everything else goes through one `serve(req, res)` that traces, routes, handles errors and records metrics.',
        'In `serve`: build the trace context, set `x-trace-id`, match the route (setting `req.params`), attach `res.on(\'finish\', …)` for the metrics, then run the handler inside `storage.run(ctx, async () => { … })`.',
        'The catch block decides once: a 4xx `status` is answered with its own envelope and not reported; anything else is reported (through a wrapper that swallows sync and async failures) and answered with the generic 500.',
        'Reuse your readiness code from the health lesson without the cache: `Promise.all(checks.map(runCheck))`, each with its own timer and `AbortController`, then fold into `ok` / `degraded` / `fail`.',
        'The metrics are two maps keyed by `JSON.stringify([...labels])`, with cumulative buckets `0.1, 0.5, 1` — exactly the request-metrics lesson with different buckets.',
      ],
    },
  ],
});
