import { loadChapter } from '../../load.ts';

const here = import.meta.dirname;

export default loadChapter(here, {
  id: 'node-fs-cli',
  title: "Files & CLIs",
  summary: "fs/promises, path safety, argument parsing, directory walks, atomic writes, exit codes.",
  lessons: [
    {
      id: 'node-fs-read-config',
      title: 'Loading a config file without hiding errors',
      kind: 'node',
      xp: 75,
      why: 'A catch-all around a config read is how production ends up running on defaults after a typo. Handle the one error you expect and surface the rest.',
      tags: ['fs', 'error handling', 'config'],
      testTimeoutMs: 20000,
      hints: [
        'Call `readFile(filePath, \'utf8\')` inside a `try`, and look at `error.code` in the `catch`. Only `\'ENOENT\'` means "use the defaults".',
        'In the `catch`, anything that is not `ENOENT` is rethrown as is: `throw error`. `EISDIR` is what you get when the path names a directory.',
        'Parse in a **separate** try/catch, so a `SyntaxError` becomes `new ConfigError(\'invalid JSON in \' + filePath, { cause })` and an fs error never does.',
        'The BOM is the single character `\\uFEFF`: `if (text.charCodeAt(0) === 0xfeff) text = text.slice(1)`.',
        'Plain object check: `parsed !== null && typeof parsed === \'object\' && !Array.isArray(parsed)`. Return `{ ...defaults, ...parsed }` — a new object either way.',
      ],
    },
    {
      id: 'node-fs-atomic-write',
      title: 'Atomic writes: temp file, then rename',
      kind: 'node',
      xp: 90,
      why: 'Overwriting a state file in place leaves it half-written after a crash. Write-then-rename is the standard fix, and it shows up in every CLI and service that persists anything.',
      tags: ['fs', 'durability', 'concurrency'],
      testTimeoutMs: 20000,
      hints: [
        'Build the temp path in the target\'s own directory: `path.join(path.dirname(filePath), \'.\' + path.basename(filePath) + \'.\' + randomBytes(6).toString(\'hex\') + \'.tmp\')`.',
        '`await writeFile(tmp, data)` accepts strings, Buffers and async iterables alike; then `await rename(tmp, filePath)`.',
        'Wrap both steps in `try`; in the `catch`, `await rm(tmp, { force: true })` (force: no error if it was never created) and then `throw error` — the original one.',
        'For durability, open the temp file yourself: `const h = await open(tmp, \'wx\'); await h.writeFile(data); await h.sync(); await h.close();` — and close the handle in the catch too.',
      ],
    },
    {
      id: 'node-fs-walk',
      title: 'Walking a directory tree safely',
      kind: 'node',
      xp: 85,
      why: 'Every build script, linter and migration tool walks a tree. Doing it without looping on links or crawling node_modules is a routine expectation.',
      tags: ['fs', 'async generators', 'paths'],
      testTimeoutMs: 20000,
      hints: [
        'Write an inner `async function* visit(dir, rel)` and start it with `yield* visit(root, \'\')`. `rel` is the path so far, joined with `/` by you, not by `path.join`.',
        '`await readdir(dir, { withFileTypes: true })` gives `Dirent`s: `entry.name`, `entry.isFile()`, `entry.isDirectory()`, `entry.isSymbolicLink()` — no extra `stat` needed.',
        'Check the ignore list and `isSymbolicLink()` before anything else, then `if (entry.isDirectory()) yield* visit(path.join(dir, entry.name), childRel)`.',
        'For extensions, lower-case both sides once: `new Set(extensions.map((e) => e.toLowerCase()))` and `path.extname(entry.name).toLowerCase()`. Apply it to files only.',
      ],
    },
    {
      id: 'node-cli-args',
      title: 'Parsing CLI arguments strictly',
      kind: 'node',
      xp: 80,
      why: 'Internal tools and cron scripts are CLIs. One that guesses at a mistyped flag does the dangerous thing silently; one that rejects it costs a re-run.',
      tags: ['cli', 'validation', 'parsing'],
      hints: [
        '`parseArgs({ args: argv, options, allowPositionals: true, strict: true })` throws on unknown options and missing values. Catch that and return `{ ok: false, error: error.message }` — its message already names the option.',
        'Declare `limit` as `type: \'string\'` and validate it yourself. `/^[1-9]\\d*$/.test(text)` accepts exactly the positive whole numbers, with no spaces, signs, decimals or exponents.',
        'Do not give `tag` a `default: []`: `parseArgs` returns that same array on every call. Use `values.tag ?? []` instead.',
        'A real date round-trips: `new Date(text + \'T00:00:00Z\').toISOString().slice(0, 10) === text`. `2024-02-30` becomes `2024-03-01`, so it fails.',
        'Return early for `help` before the positional check, then check `positionals.length !== 1` last, with a message that contains the word `output`.',
      ],
    },
    {
      id: 'node-cli-exit-codes',
      title: 'Exit codes, stdout and stderr',
      kind: 'node',
      xp: 80,
      why: 'CI, cron and shell pipelines judge your tool by its exit code and stdout alone. Errors on stdout or a 0 after a failure break every script built on top of it.',
      tags: ['cli', 'streams', 'error handling'],
      testTimeoutMs: 20000,
      hints: [
        'Validate `argv` completely before touching any file: a usage error must leave stdout empty and resolve `2`.',
        'Loop over the files with a `try`/`catch` **inside** the loop. In the `catch`, set a `failed` flag and write to `io.stderr`; do not `return`.',
        'Map the reason with a small table: `({ ENOENT: \'no such file\', EISDIR: \'is a directory\' })[error.code] ?? error.message`.',
        'Count with `for await (const chunk of stream)`, counting `0x0a` bytes, and remember the last byte seen: if the input was non-empty and did not end in `\\n`, add one.',
      ],
    },
    {
      id: 'node-fs-lockfile',
      title: 'A lock file that survives crashes and races',
      kind: 'node',
      xp: 90,
      why: 'Overlapping cron runs and double-started workers corrupt shared files. An exclusive-create lock with stale takeover is the standard single-machine guard.',
      tags: ['fs', 'concurrency', 'cli'],
      testTimeoutMs: 20000,
      hints: [
        'Checking whether the file exists and then writing it is two steps, and another caller fits between them. Let the file system do both at once.',
        '`const handle = await open(lockPath, \'wx\')` throws an error with `code === \'EEXIST\'` when the file exists. Write the JSON through the handle and close it in a `finally`.',
        'On `EEXIST`, read the file and `stat` it. `JSON.parse` in its own try/catch: if it fails or `createdAt` is not a number, use `stat.mtimeMs` and a `null` holder.',
        'Stale means `now() - since > staleMs`. Then `await rm(lockPath, { force: true })` and call your exclusive-create helper a second time; if it returns "exists" again, throw `LockedError`.',
        'Keep the token in a closure. `release` reads the file, parses it, and only `rm`s when `parsed.token === token`; an `ENOENT` or a parse failure means "not ours, nothing to do".',
      ],
    },
    {
      id: 'node-fs-sync-plan',
      title: 'Plan, then apply: a dry run that cannot lie',
      kind: 'node',
      xp: 85,
      why: 'Deploy, backup and migration scripts need a trustworthy --dry-run. Computing a plan separately from executing it is how you get one.',
      tags: ['fs', 'cli', 'paths'],
      testTimeoutMs: 20000,
      hints: [
        'Build one helper that lists every regular file under a directory as a `Map` from relative path to absolute path, then call it for both sides.',
        'Build the relative path yourself: `rel ? rel + \'/\' + entry.name : entry.name`. `path.join` and `path.relative` use `\\` on Windows.',
        'For the destination, catch `ENOENT` and use an empty `Map`; do not catch it for the source.',
        'Equal content: compare `stat().size` first, and only when equal compare `(await readFile(a)).equals(await readFile(b))`.',
        'Sort with `(a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0)`. In `applySync`, `await mkdir(path.dirname(target), { recursive: true })` before each `copyFile`.',
      ],
    },
    {
      id: 'node-fs-cli-quiz',
      title: 'Files, paths and processes: the OS is literal',
      kind: 'quiz',
      xp: 60,
      why: 'Scripts that work at your desk and fail under cron, in a pipe or on the build server all fail for the same handful of OS-level reasons.',
      tags: ['fs', 'cli', 'paths'],
      quiz: [
        {
          q: 'An ES module at `src/jobs/report.js` does `await readFile(\'./template.html\', \'utf8\')`. It works with `node src/jobs/report.js` from the repo root, where `template.html` sits, and fails under cron with `ENOENT`. What is the robust fix?',
          options: [
            'Use `path.join(__dirname, \'template.html\')`.',
            'Resolve against the module: `new URL(\'./template.html\', import.meta.url)` (or `path.join(import.meta.dirname, \'template.html\')`), and keep the template next to the module.',
            'Call `process.chdir(\'/app\')` at the top of the script.',
            'Use `readFileSync`, which resolves relative to the calling file.',
          ],
          answer: [1],
          explain: 'Relative paths in `fs` resolve against `process.cwd()` — wherever the process was started — not against the file that contains the call. Cron starts jobs in the home directory. `__dirname` does not exist in ES modules (it throws a `ReferenceError`); `import.meta.url` / `import.meta.dirname` are the ESM equivalents. `chdir` to a hardcoded path just moves the assumption, and sync vs async has nothing to do with resolution.',
        },
        {
          q: 'A CLI prints 50,000 result lines with `process.stdout.write` and then calls `process.exit(0)`. Run in a terminal it looks fine; piped into `wc -l` it sometimes reports far fewer lines. Why, and what is the fix?',
          options: [
            '`wc` reads slowly; add `--buffer-size` to the pipe.',
            'Output must go through `console.log`, which is synchronous everywhere.',
            'Writes to a pipe can be asynchronous; `process.exit()` ends the process without waiting for queued output. Set `process.exitCode = 0` and let the event loop drain.',
            'stdout needs `setEncoding(\'utf8\')` before large writes.',
          ],
          answer: [2],
          explain: 'In Node, stdout is synchronous for files and (on POSIX) TTYs, but asynchronous for pipes — so the data you "wrote" may still be queued when `process.exit()` tears the process down. `console.log` uses the same stream, so it does not help. Setting `process.exitCode` and returning lets Node flush everything and exit with that code.',
        },
        {
          q: 'Which of these are race conditions (time-of-check to time-of-use) that should be rewritten as a single operation plus error handling? Select all that apply.',
          options: [
            '`if (!existsSync(lock)) writeFileSync(lock, pid)` to take a lock.',
            '`if (existsSync(file)) data = await readFile(file)` to read an optional file.',
            '`await mkdir(dir, { recursive: true })` before writing into `dir`.',
            '`const s = await stat(f); if (s.size < limit) data = await readFile(f)` to cap memory use on a file other processes append to.',
          ],
          answer: [0, 1, 3],
          explain: 'Each of the three checks can be invalidated before the action: another process creates the lock (use `open(lock, \'wx\')` and handle `EEXIST`), deletes the file (just `readFile` and handle `ENOENT`), or appends to it after the `stat` (read through a stream and stop at the limit). `mkdir` with `recursive: true` is already a single idempotent operation — it succeeds whether or not the directory exists.',
        },
        {
          q: 'A deploy script writes the new config to `path.join(os.tmpdir(), \'config.json\')` and then `rename`s it onto `/srv/app/config.json`. It works on a laptop and fails on the server with `EXDEV`. What happened?',
          options: [
            '`/tmp` is a different file system (often tmpfs) from `/srv`. `rename` is only atomic, and only possible, within one file system; write the temp file in the target\'s own directory instead.',
            'The server\'s Node is too old to support `rename`; use `copyFile` then `unlink`.',
            '`EXDEV` means the target is locked by the running app; stop it first.',
            'The temp name collides with another deploy; add a random suffix.',
          ],
          answer: [0],
          explain: '`EXDEV` is "cross-device link": `rename(2)` cannot move a file between file systems. Falling back to copy-then-delete works but loses atomicity — a reader can see a half-copied file. Writing `.config.json.<random>.tmp` next to the target keeps both on the same file system, which is why the atomic-write pattern puts the temp file there. A random suffix is also good practice, but it does not fix `EXDEV`.',
        },
        {
          q: 'A long-running CLI registers `process.on(\'SIGINT\', () => cleanupTempFiles())` so Ctrl-C removes its temp files. What goes wrong?',
          options: [
            'Nothing: Node runs the handler and then exits as usual.',
            'The handler runs on a separate thread and cannot touch the file system.',
            'SIGINT cannot be caught in Node; use `process.on(\'exit\')` instead.',
            'Adding a SIGINT listener replaces Node\'s default "exit on Ctrl-C", so the process keeps running. The handler must finish the cleanup and then exit itself, conventionally with code 130 (128 + signal 2).',
          ],
          answer: [3],
          explain: 'Once any listener exists for a signal, Node stops applying the default behaviour. The usual shape is `process.once(\'SIGINT\', async () => { await cleanup(); process.exitCode = 130; /* stop work so the loop drains */ })`. `exit` listeners must be synchronous, so they cannot await asynchronous cleanup. Signal handlers run on the main thread like any other event.',
        },
        {
          q: 'An API endpoint serves a 2 KB JSON file with `JSON.parse(readFileSync(\'data/countries.json\', \'utf8\'))` on every request. What is the best change?',
          options: [
            'Switch to `await readFile` inside the handler; async is always correct in a server.',
            'Read and parse it once at startup (sync is fine there) and reuse the object; a synchronous read in a handler blocks every other request while the disk answers.',
            'Keep it: 2 KB is small, so a sync read has no cost.',
            'Move the file into `/tmp` so it is cached in memory by the OS.',
          ],
          answer: [1],
          explain: 'Sync fs calls block the one thread that serves every request; on a cold cache or a network disk "2 KB" can take milliseconds, times every request. Async reads avoid the blocking but still re-read and re-parse the same data per request. Data that does not change while the process runs should be loaded once, and at startup a synchronous read is simple and harmless.',
        },
      ],
    },
    {
      id: 'node-dupes-boss',
      title: 'Boss: find-dupes, a complete CLI',
      kind: 'node',
      xp: 220,
      boss: true,
      why: 'Internal tooling is a mid-level job: a CLI that walks real directories, reports cleanly to humans and scripts, and fails in a way CI can see.',
      tags: ['cli', 'fs', 'hashing', 'exit codes'],
      testTimeoutMs: 20000,
      hints: [
        'Structure it in three phases: parse `argv` (return 2 early), collect files into a `Map` from size to files, then hash and print. Each phase is easy to test on its own.',
        'Parse by hand or with `parseArgs`, but validate `--min-size` with `/^\\d+$/` — `Number(\'\')` is `0` and `Number(\'1e3\')` is `1000`.',
        'Walk with `readdir(dir, { withFileTypes: true })`, skipping `node_modules`/`.git` by name and anything that is not `isDirectory()` or `isFile()`. Build the display path as `` `${display}/${entry.name}` ``.',
        'Keep a `Set` of `path.resolve(abs)` to count each file once. `stat` the argument first: `ENOENT` → "no such directory", `!isDirectory()` → "not a directory"; set a `failed` flag and `continue`.',
        'Hash only sizes with 2+ files: `createHash(\'sha256\')` fed by `for await (const chunk of createReadStream(file))`. Group by digest, keep groups of 2+, sort paths, then `groups.sort((a, b) => b.size - a.size || (a.paths[0] < b.paths[0] ? -1 : 1))`.',
      ],
    },
  ],
});
